### ISSUE TITLE
🔥 La remontée d'information sur les accès territoires ne fonctionne plus

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1000]
Contexte : staging

Le dispatching par territoire ne fonctionne plus. Peu importe avec quel compte territoire on se connecte on ne voit plus de trajet. 
![image](https://user-images.githubusercontent.com/15428433/91729658-2e787980-eba5-11ea-83bd-3e29d007e78c.png)

**Comment by margot-sanchez** [comment]
Fonctionne à nouveau sur chiffres clefs mais pas liste détaillée 
![image](https://user-images.githubusercontent.com/15428433/91990083-952a9e00-ed31-11ea-9bcf-b39f4c9d8638.png)

**Comment by margot-sanchez** [comment]
Hum. Je me suis créée un compte Lyon + Caluire + Villeurbanne et je n'ai aucun résultat.
![image](https://user-images.githubusercontent.com/15428433/92582715-93ad2880-f291-11ea-9fe0-45bd8d72d32f.png)

Or sur mon interface super admin on trouve bien des trajets.
![image](https://user-images.githubusercontent.com/15428433/92582797-afb0ca00-f291-11ea-94d4-7d7a260d1c49.png)

**Comment by margot-sanchez** [comment]
⚠️ cela marrche quand le territoire est AOM est-ce que cela a lien ?

**Comment by margot-sanchez** [comment]
@nmrgt prend. C'est un problème de trigger !

**Comment by jonathanfallon** [comment]
TODO : vérifier les triggers et si ça ne marche pas, appeler la fonction PG directement

**Comment by margot-sanchez** [comment]
A tester quand je pourrai créer des territoires nouveaux. Sinon cela marche pour les AOM

**Comment by margot-sanchez** [comment]
05/10/2020 
Etape 1 : création d'un nouveau territoire + un utilisateur
Etape 2 : se connecter avec ce compte
Chiffres clefs 👍 
Liste détaillée 👍
