### ISSUE TITLE
Gestion des noms de campagne identique

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1007]
# Comportement actuel 
En tant que superadmin je peux rechercher des campagnes. Etant donné que nous proposons des noms génériques, il est possible d'avoir deux noms de campagne identique à deux endroits différents. Comme se fait la gestion de ces noms identiques ? Que devrions-nous mettre pour différencier ?

![image](https://user-images.githubusercontent.com/15428433/91991104-ca83bb80-ed32-11ea-83fc-5ce356c48a87.png)

# Comportement attendu
Ajout du shortname

**Comment by margot-sanchez** [comment]
Quand le problème arrivera sur la prod on y reflechira à nouveau

**Comment by jonathanfallon** [comment]
Ajouter le _shortname_ du territoire dans le nom de la campagne pour les super-admins.
Faire une migration de la liste remplie par Margot avant.

**Comment by margot-sanchez** [comment]
MAJ : le problème commence à arriver

**Comment by margot-sanchez** [comment]
A prendre en compte dans le chantier territoire refonte
