### ISSUE TITLE
Affichage des stats par graphe -définition d'une plage

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#101]
C'est totalement illisible de lire ça 
![image](https://user-images.githubusercontent.com/15428433/56276269-8d4d6800-6102-11e9-9285-7ec9ae295564.png)

Proposition affichage des 2 ou 3 derniers mois et possibilité de faire bouger un curseur.

**Comment by samueleyre** [comment]
Déjà corrigé sur le serveur de dev

**Comment by margot-sanchez** [comment]
Effectivement 👍
![image](https://user-images.githubusercontent.com/15428433/56659050-7e375e80-669c-11e9-9d2f-25e7a5819535.png)
