### ISSUE TITLE
Incohérence actualisation des résultats sur liste détaillée ?

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1016]
Contexte : staging

Je suis super admin, je ne réalise aucune action, de base les filtres sont automatiquement appliqués sur la dernière année. J'ai 130 trajets.
![image](https://user-images.githubusercontent.com/15428433/92578103-b89e9d00-f28b-11ea-94b3-ef6599874806.png)

Par curiosité, je clique sur affiner les résultats sans changer le filtre automatique sur la dernière année et j'ai 134 trajets.
![image](https://user-images.githubusercontent.com/15428433/92578400-1501bc80-f28c-11ea-8c29-d0ab9d7e3ee3.png)

Or cela ne devrait rien changer ? A noter qu'il y a des trajets le 9 septembre 2019. L'application du filtre commence à 00H00 alors que le filtre automatique est à l'heure à laquelle est faite la requête ?

**Comment by margot-sanchez** [comment]
Par défaut pas appliqué des deux côtés @gillesboisson

**Comment by jonathanfallon** [comment]
Mettre à jour les chiffres clé pour que ce soit synchro avec la liste détaillée

**Comment by gillesboisson** [comment]
commit 232c5e95

**Comment by margot-sanchez** [comment]
Etape 1 : pas de filtre (application automatique dernière année) chiffres clefs 2 364 479 trajets
![image](https://user-images.githubusercontent.com/15428433/93776473-da046f00-fc23-11ea-9311-f05b10d59fdf.png)
Etape 2 : pas de filtre (application automatique dernière année) liste détaillée 2 363 657 trajets
![image](https://user-images.githubusercontent.com/15428433/93776579-fc968800-fc23-11ea-9914-3f5a1caa3e4a.png)

Etape 3 : application du filtre date (sans le modifier) chiffres clefs 2 364 479 trajets
Etape 4 : application du filtre date (sans le modifier) liste détaillée 2 36 3658 trajets

**Comment by margot-sanchez** [comment]
C'est toujours incohérent non ?

**Comment by margot-sanchez** [comment]
Je suis bête vous aviez raison 🌵
