### ISSUE TITLE
Suppression d'un territoire 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1018]
Je suis un super admin et je réalise des tests de création de territoire à la volée. Finalement je souhaite supprimer ce territoire, or cette fonctionnalité n'est pas possible. 

Permettre la suppression de territoire, avec demande de confirmation de l'action.

**Comment by jonathanfallon** [comment]
Utiliser le même process que pour les opérateurs.
La suppression des utilisateurs du territoire est automatique.

:warning: faire un **soft-delete** pour ne pas casser les relations avec les trajets existants sur ce territoire.

**Comment by jonathanfallon** [comment]
Besoin de faire une étude des impacts car ça touche tout l'arbre de dépendance des territoires et les breadcrumbs.

**Comment by margot-sanchez** [comment]
A dégager à la main ou mettre à jour le même territoire test.
