### ISSUE TITLE
Bug filtre territoire

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1019]
Contexte : demo

Je suis connectée avec Amiens Métropole et je voudrais filtrer sur mes "enfants" par exemple Amiens mais cela ne me le propose plus.

**Comment by margot-sanchez** [comment]
Le filtre territoire est revenu mais ne fonctionne pas.

**Comment by gillesboisson** [comment]
tu peux dire ce que tu as fait @margot-sanchez en demo avec user admin j'ai bien des trajets, avec Lyon

**Comment by jonathanfallon** [comment]
Attendu : les territoires doivent appartenir à Amiens Métropole

![Screenshot from 2020-09-24 14-20-27](https://user-images.githubusercontent.com/1656255/94144174-1aa4f800-fe71-11ea-9e77-bde6bf5ef48b.png)

**Comment by margot-sanchez** [comment]
Lorsque je recherche sur Amiens rien ne se passe et je continue de voir des trajets en dehors d'Amiens.
![image](https://user-images.githubusercontent.com/15428433/94452127-7e039280-01af-11eb-8941-7318dff3e72e.png)

**Comment by jonathanfallon** [comment]
Filtre du dropdown :+1: 
Filtrage des résultats list et stats :+1: 
Remise à 0 du dropdown quand on efface le champ :-1: 
Réinitialisation des filtres -> effet sur le dropdown ?

**Comment by margot-sanchez** [comment]
Etape 1 : création d'un territoire via "parents" + un utilisateur
Etape 2 : se connecter 162k trajets
Etape 3 : filtrer sur privas 500 résultats
