### ISSUE TITLE
Impossible de créer un territoire avec les codes INSEE

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1032]
Contexte : demo

Je suis super admin et je veux créer un territoire avec des codes INSEE, mais cela ne fonctionne pas

![image](https://user-images.githubusercontent.com/15428433/94126611-1f10e700-fe58-11ea-9e7b-b0d9785e1854.png)

**Comment by jonathanfallon** [comment]
Très probablement un soucis de validation en front. Pas d'erreurs dans la console et pas de requête envoyée au backend à ce moment là.

**Comment by margot-sanchez** [comment]
Cela ne marche toujours pas.

![image](https://user-images.githubusercontent.com/15428433/94673276-c8ebea00-0316-11eb-8a44-df3b287725f0.png)

**Comment by jonathanfallon** [comment]
@jonathanfallon 
OK pour la création de territoire.
Formulaire à mettre à jour avec les modifs apportées sur la création d'opérateur.
Vérifier le schema (update)

**Comment by margot-sanchez** [comment]
Demo 05/10/2020 
Ok la création par code INSEE est possible.
