### ISSUE TITLE
Remise à plat de l'infra V1

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#1035]
Voir spécifications : https://hackmd.io/KC9dsXlYSg-UC9svlOpZkg

To Do : 
Etape 1 : Binôme @jonathanfallon & @nmrgt (maître) (mais inclure @gillesboisson )
Etape 2 : tester sur dev 

❓ conteneurisation ou pas ? 
Réponse : **OUI**

❓ Scaleway ou OVH
Réponse : 🤑 chez OVH --> **Scaleway** (car les scripts sont déjà faits)

❓ Sentry lequel utiliser ?
Celui de data.gouv (beta?) n'est plus maintenu. Voir si on utilise notre propre sentry.
![image](https://user-images.githubusercontent.com/15428433/98920071-f01a0780-24cf-11eb-8524-0e881d9d4bd5.png)

**Comment by margot-sanchez** [comment]
Le dev tourne, le premier batch est fait.
