### ISSUE TITLE
Bouton [Nouvelle Campagne] grisé

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1048]
![Screenshot from 2020-09-29 16-12-17](https://user-images.githubusercontent.com/1656255/94569988-9f778380-026e-11eb-92f5-114bc0584805.png)

Je suis la Métropole d'Amiens, Je peux créer une nouvelle campagne (bouton orange au dessus des stats) mais pas utiliser le bouton dans la section _Vos campagnes en cours_

Attendu : pouvoir créer des campagnes aux 2 endroits.

**Comment by gillesboisson** [comment]
j'ai restesté sur la branche demo ok chez moi @jonathanfallon

**Comment by margot-sanchez** [comment]
👍
