### ISSUE TITLE
Supprimer les applications lors de la suppression d'un opérateur

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1062]
Supprimer toutes les applications liées à l'opérateur supprimé

**Comment by margot-sanchez** [comment]
Etape 1) création d'un opérateur Boulangerie Paul 👍 
Etape 2) création d'un utilisateur Margot Paul 
Etape 3) création d'une application Choucroute
Etape 4) Supprimer l'opérateur Boulangerie Paul

@jonathanfallon vérifier sir Choucroute est toujours en base

**Comment by jonathanfallon** [comment]
- Boulangerie Paul --> soft deleted :+1: 
- Utilisateur Margot Paul --> supprimé :+1: 
- Application Choucroute --> non supprimée :-1:

**Comment by jonathanfallon** [comment]
Après tests... ça marche
