### ISSUE TITLE
Automatiser l'upload des données ouvertes

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1063]
https://doc.data.gouv.fr/api/reference/#/datasets/create_dataset

**Comment by Datayama38** [comment]
refaire les exports pour avoir des champs homogènes (ex :certains mois pas de trip_id ou pas de journey_id ou encore position des champs lat et long inversés)

**Comment by Datayama38** [comment]
La colonne journey_end_town est absente dans le fichier 2020-09-vf
A partir de 2020-08-vf les colonnes journey_start_postcode et journey_end_postcode ont été renommées en journey_start_postalcode et journey_end_postal_code

**Comment by nmrgt** [comment]
J'ai l'impression que grosso modo il y a une action d'export opendata et cette action pousse vers un s3. Il reste donc à faire :
1. Paramétrer la durée de vie de ce fichier dans le s3 pour qu'il n'expire pas (ce qui est le cas aujourd'hui puisqu'utilisé par les autres exports)
2. Il faut pousser une référence à ce dataset sur datagouv (https://doc.data.gouv.fr/api/reference/#/datasets/create_dataset)
3. Et mettre ca dans un cron

Deux observations : 
1. S'il y a des évolutions du jeu de données il faut les spécifier et les implémenter
2. Actuellement il n'y a pas d'enregistrement CNAME sur le s3, ca vaudrait le coup d'en faire pour pouvoir avoir une jolie url

**Comment by P3rceval** [comment]
Simplification pour le jeu de données : 

- garder datetime, supprimer date et time
- supprimer département et on garde le code postal

**Comment by P3rceval** [comment]
Ajout : 
- distance en mètre (exposée, sinon calculée)

EPCI à rajouter après chantier territoire

**Comment by P3rceval** [comment]
Duplicate of https://github.com/betagouv/preuve-covoiturage/labels/Open%20Data%20Automation
