### ISSUE TITLE
Non affectation des AOMs... 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#107]
1) je fais une recherche filtrer sur l'AOM de Marseille Aix Provence
![image](https://user-images.githubusercontent.com/15428433/56366248-f7453a80-61f2-11e9-940d-a66cbda47fda.png)
Je n'ai pas de trajet à 17H00 le 25/02
2) Quand je ne fais pas de recherche et que j'ai accès à l'ensemble de la base, je vois clairement un trajet sur l'AOM de Marseille à 17H00 le 25/02
![image](https://user-images.githubusercontent.com/15428433/56366461-7cc8ea80-61f3-11e9-874c-63098b7c5c4f.png)

En faisant mes petites recherches, j'ai exporté le CSV et je vois que le problème vient du fait que cela ne l'a pas automatiquement mis dans l'AOM de Marseille, la colonne AOM reste vide
![image](https://user-images.githubusercontent.com/15428433/56366431-6c187480-61f3-11e9-9102-e62ef3319cec.png)

**Comment by margot-sanchez** [comment]
Margot continue son enquête cela fait pareil sur d'autres villes avec des arrondissements
![image](https://user-images.githubusercontent.com/15428433/56366635-dd582780-61f3-11e9-8e31-f38bbff1ff4d.png)
Le problème vient des codes avec numéro d'arrondissement

**Comment by margot-sanchez** [comment]
🔍🕵 @jonathanfallon  mon enquête est ici.

**Comment by jonathanfallon** [comment]
TODO : 
Ajouter les codes INSEE des arrondissements dans les listes des AOM pour les villes qui en comprennent : 
- Paris
- Lyon
- Marseille

Ajouter des migrations pour la mise à jour dans les bases existantes
