### ISSUE TITLE
Mise en "page" des exceptions trajets

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1102]
Contexte : prod 

Je suis administrateur d'un territoire. Je souhaite paramétrer des exceptions sur les trajets. Lorsque cela est long, faire un retour à la ligne car c'est illisible sinon.
![image](https://user-images.githubusercontent.com/15428433/98530788-b226a480-227f-11eb-8c38-1be1122d74c0.png)

**Comment by margot-sanchez** [comment]
Ticket expliqué en direct à Gilles.

**Comment by margot-sanchez** [comment]
Cela va sauter avec territory list. (en lieu et place de start insee et end insee)

**Comment by jonathanfallon** [comment]
@margot-sanchez toujours d'actualité ?

**Comment by P3rceval** [comment]
Le rendu final : 
![exclusions](https://user-images.githubusercontent.com/6213517/130645950-a20247f5-c26e-47ed-a1d1-d0d6016fffb8.png)
