### ISSUE TITLE
Bug - non chargement lors de la mise à jour d'une campagne

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1104]
Contexte : prod

Je suis un territoire. Je fais une campagne que j'enregistre. Finalement je fais une modification et j'enregistre. La page charge sans s'afficher.
![image](https://user-images.githubusercontent.com/15428433/98533579-71308f00-2283-11eb-81fc-a7ba11fcad9d.png)

Pourtant lorsque je clique sur campagne et retourne dans mes brouillons l'enregistrement a fonctionné.

**Comment by margot-sanchez** [comment]
Ticket expliqué en direct à Gilles.

**Comment by gillesboisson** [comment]
@margot-sanchez je suis entrain de retenter de déclencher le bug, on avait testé sur les restrictions. Le souci qu'il semble y avoir c'est un mic mac entre les restrictions sur la durée de la campagne qui sont en faite les même que les champs limite de trajets, limite de montant.

**Comment by margot-sanchez** [comment]
Testé sur prod le 18/11/2020. J'ai toujours le même bug.

**Comment by margot-sanchez** [comment]
Note : bug désormais uniquement lorsque l'on modifie une restriction.

Lorsque l'on change la date, la distance, conducteur / passager, le montant total, etc cela ne bug désormais plus.

**Comment by margot-sanchez** [comment]
Testé sur prod le 23/11/2020, en modifiant, date, distance, conducteur/passager 🆗 
Sur la modification des plafonds, au début cela n'a pas marché mais j'ai fait refresh et depuis cela marche tout le temps... donc je pense que c'était que de mon côté.

**Comment by margot-sanchez** [comment]
Testé sur la prod le 25/01/2021

Le bug est toujours présent lorsque l'on touche aux filtres de la première étape "opérateurs" "distance". Et quand je touche à plusieurs filtres à la fois aussi.

**Comment by margot-sanchez** [comment]
Testé sur le staging le 02/02/2021, le bug est bien là

**Comment by margot-sanchez** [comment]
@jonathanfallon il n'y a pas de requête qui part au back

**Comment by margot-sanchez** [comment]
Testé sur le staging le 19/02/2021 avec un compte découverte 👎 
![Uploading image.png…]()

**Comment by margot-sanchez** [comment]
Testé sur dev le 19/02/2021 avec un compte découverte 👍
