### ISSUE TITLE
Page Chargement Loader - voiture qui roule

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#111]
@margot-sanchez dessiner une voiture qui roule pour les temps de chargement.

**Comment by margot-sanchez** [comment]
Faire sauter la voiture (SVG haut) pour donner une impression que la voiture avance.
![image](https://user-images.githubusercontent.com/15428433/62878136-c8fee400-bd28-11e9-839d-02a669123489.png)


SVG disponibles ici : https://drive.google.com/drive/folders/1RN53ds8b8-ySW5Q8vXaefdXgJO4ycR7G

**Comment by vincentlaine** [comment]
Trop de détails pour un petit loader.

A voir avec @margot-sanchez si on laisse le loader de base d'Angular ou on met quelque chose d'un peu plus custom (roue qui roule ?).

Il faut quelque chose de rond qui indique visuellement bien que quelque chose est entrain de tourner en background.

**Comment by vincentlaine** [comment]
A déplacer au prochain sprint, pas urgent.

**Comment by nmrgt** [comment]
Mettre cette image en splashscreen
