### ISSUE TITLE
Design page erreur 404

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#112]
@margot-sanchez  design d'une page erreur 404

**Comment by nmrgt** [comment]
avec une voie sans issue :)

**Comment by margot-sanchez** [comment]
![image](https://user-images.githubusercontent.com/15428433/62877901-52fa7d00-bd28-11e9-8018-b28724f6048f.png)

SVG disponibles ici : https://drive.google.com/drive/folders/1RN53ds8b8-ySW5Q8vXaefdXgJO4ycR7G

**Comment by margot-sanchez** [comment]
Cf la route #16
