### ISSUE TITLE
Nouvelles statistiques par AOM sur les résultats d'incitations

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#113]
1.8 Incitations financières
Unité : € distribués

Il s’agit de la somme des contreparties financières distribuées par une AOM à des covoitureurs répondants aux critères de politiques d’incitation. Cet indicateur est propre à une AOM et ne prend pas en compte les incitations distribuées par d’autres organismes incitateurs.

1.9 Incitations non financières
Unité : points distribués

Il s’agit de la somme des points équivalents à des contreparties non financières distribués par une AOM à des covoitureurs répondants aux critères de politiques d’incitation. Cet indicateur est propre à une AOM et ne prend pas en compte les incitations distribuées par d’autres organismes incitateurs.

**Comment by margot-sanchez** [comment]
Statistiques d'usage des covoitureurs (demandées par collectivités) : 

- Sexe
- Age

Problème 
Ces données ne sont actuellement pas collectées + les opérateurs ne les collectent pas.

Stratégie 
On ne fait rien pour l'instant.

**Comment by P3rceval** [comment]
Won't do
