### ISSUE TITLE
Erreur simulation 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1139]
### Sujet

La simulation de campagne à destination des collectivités connait quelques bugs étranges.

### Environnement

Environnement : production
Navigateur : Chrome
Utilisateur : super admin et admin collectivité
https://app.covoiturage.beta.gouv.fr/campaign/draft/125

### Etapes pour reproduire

1. _Je clique sur une campagne et arrive sur le simulateur. 
2.  _Je regarde la campagne de Metz Métropole en brouillon
3. _Je modifie 1 mois, 2 mois, 3 mois

### Comportement attendu

1. _Je clique sur modifier le nombre de mois > modification du nombre de trajet
2.  Je devrais voir à minima une 100 de trajets (voir preuves ci dessous qu'il y a bien des trajets éligibles) et des incitations cohérentes mais là j'ai une incitation de 77€ pour 1 seul trajet
![image](https://user-images.githubusercontent.com/15428433/102499066-068d2300-407b-11eb-8154-2d6315b04fa6.png)

**Comment by margot-sanchez** [comment]
![image](https://user-images.githubusercontent.com/15428433/102512324-31cb3e80-408a-11eb-91c7-1371752e7c0a.png)
Incohérence 66 trajets pour 1300€ ? Il faut à nouveau diviser /100.

**Comment by nmrgt** [comment]
Après investigation, j'ai détecté un problème sur l'interfaçage front/back sur les paramètres de campagne.
```json
[
   [
      {
         "slug":"progressive_distance_range_meta",
         "parameters":{
            "min":2000,
            "max":20000
         }
      },
      {
         "slug":"cost_based_amount_setter"
      },
      {
         "slug":"passenger_only_filter"
      }
   ],
   [
      {
         "slug":"progressive_distance_range_meta",
         "parameters":{
            "min":2000,
            "max":20000
         }
      },
      {
         "slug":"driver_only_filter"
      },
      {
         "slug":"fixed_amount_setter",
         "parameters":200
      },
      {
         "slug":"per_passenger_modifier"
      },
      {
         "slug":"per_seat_modifier"
      }
   ],
   [
      {
         "slug":"progressive_distance_range_meta",
         "parameters":{
            "min":20000,
            "max":40000
         }
      },
      {
         "slug":"cost_based_amount_setter"
      },
      {
         "slug":"passenger_only_filter"
      },
      {
         "slug":"per_km_modifier"
      }
   ],
   [
      {
         "slug":"progressive_distance_range_meta",
         "parameters":{
            "min":20000,
            "max":40000
         }
      },
      {
         "slug":"driver_only_filter"
      },
      {
         "slug":"fixed_amount_setter",
         "parameters":10
      },
      {
         "slug":"per_passenger_modifier"
      },
      {
         "slug":"per_km_modifier"
      },
      {
         "slug":"per_seat_modifier"
      }
   ],
   [
      {
         "slug":"progressive_distance_range_meta",
         "parameters":{
            "min":40000,
            "max":150000
         }
      },
      {
         "slug":"driver_only_filter"
      },
      {
         "slug":"fixed_amount_setter",
         "parameters":10
      },
      {
         "slug":"per_passenger_modifier"
      },
      {
         "slug":"per_km_modifier"
      },
      {
         "slug":"per_seat_modifier"
      }
   ]
]
```

Ici, pour le passager: 
- la règle 1 donne le montant du trajet de 2 à 20 km;
- la règle 3 donne le montant du trajet x le nombre de km de 20 à 40km.

pour le conducteur : 
- la règle 2 donne 2€ par passager et par siège réservé entre 2 et 20km ;
- la règle 4 donne 0.10 € par passager, par siège et par km.

Au niveau du passager, il y a 2 soucis : 
- on multiplie le cout par le nombre de km ;
- on donne 2x le cout si le trajet est > 20km ;

Concernant le nombre de trajet (1 puis 66), je penche pour un problème de synchronisation des données du formulaire au niveau de la simulation (la campagne en db est sur 1 journée ce qui pourrait expliquer les 1 trajet).

cc @gillesboisson
