### ISSUE TITLE
Lien mort page "stats" sur covoiturage.beta.gouv.fr 

### ISSUE THREAD

**Issue by lauriebequet** [betagouv/preuve-covoiturage#1143]
### Sujet

Lien mort lorsque je clique sur le lien "stats" dans le header https://covoiturage.beta.gouv.fr/ 

### Environnement
Environnement (dev, prod...) : prod
Navigateur : chrome
Utilisateur : all
URL : https://covoiturage.beta.gouv.fr/ > https://app.covoiturage.beta.gouv.fr/stats

### Etapes pour reproduire

1. _Je clique sur : https://covoiturage.beta.gouv.fr/ 
2. _Je clique sur "stats" dans le header 

_Ajouter des captures d'écran si nécessaire (Impr. écran et Ctrl-V directement ici)_
_Préciser les valeurs utilisées dans les formulaires_
_Répéter la procédure avec la Console ouverte (F12) et copier-coller le contenu ou faire une capture d'écran_

### Comportement attendu

1. _Je clique sur la rubrique "stats" 
2. _La page "stats" s'ouvre

### Comportement actuel

1. _Je clique sur "stats" dans le header https://covoiturage.beta.gouv.fr/ 
2. .Une page erreur 404 s'ouvre Not Found The requested URL was not found on this server.

**Comment by jonathanfallon** [comment]
Problème d'hébergement résolu.
