### ISSUE TITLE
Dates de fin de campagne +1 jour

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1144]
### Sujet

Les dates de fin de campagne ont automatiquement pris un jour.

### Environnement

Environnement (dev, prod...) : prod
Navigateur : chrome
Utilisateur : super admin + admin territoire

### Etapes pour reproduire

1. _Je clique sur campagne
2. _Je fais afficher la liste des campagnes

### Comportement attendu

Les dates de fin étaient le 31 décembre 20XX

### Comportement actuel

Les dates de fin ont automatiquement prix une journée et sont désormais au 1 janvier de l'année +1. 

![image](https://user-images.githubusercontent.com/15428433/103553924-6fafcb80-4eae-11eb-8b46-1307fcd7503a.png)

A voir si lié au chantier fuseau horaire de @jonathanfallon . 
Attention le 1 janvier est non compris dans les dates de la campagne.

**Comment by margot-sanchez** [comment]
Mise à jour. 
Lorsque je modifie une campagne, chaque fois cela change les dates en ajoutant une journée. Exemple au départ j'avais mis 31 aout et j'ai fait plusieurs fois une modification. 
![image](https://user-images.githubusercontent.com/15428433/103876429-ed085580-50d3-11eb-9dde-89275f0e2194.png)
![image](https://user-images.githubusercontent.com/15428433/103881772-314b2400-50db-11eb-9152-f4fc13f69fe7.png)

**Comment by nmrgt** [comment]
Hum, je pense que c'est du backend. Je m'en occupe.

**Comment by margot-sanchez** [comment]
@nmrgt bug reproduit ce jour sur la prod.

**Comment by margot-sanchez** [comment]
A tester sur dev par @margot-sanchez :)

**Comment by margot-sanchez** [comment]
Sur app-dev : le bug est toujours là.

**Comment by margot-sanchez** [comment]
Testé le 21/01/2021 sur app-dev 👍 
J'ai fait deux fois des modifications sur une campagne et cela n'a pas ajouté de jour.
