### ISSUE TITLE
Disparition du favicon

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1145]
### Sujet

Le favicon sur staging a disparu

### Environnement

Environnement : de gauche à droite (prod, staging, dev)
Navigateur : chrome
Utilisateur : peu importe

![image](https://user-images.githubusercontent.com/15428433/103563538-39c61380-4ebd-11eb-9e5d-dc8cdaae6532.png)

### Etapes pour reproduire

Ouvrir les environnements dans un navigateur.

**Comment by jonathanfallon** [comment]
Pas reproduit sur :
- https://app.covoiturage.beta.gouv.fr
- https://app-staging.covoiturage.beta.gouv.fr
- https://app-dev.covoiturage.beta.gouv.fr

Sûrement dû au problème sur l'hébergement de lundi dernier.
@margot-sanchez tu as encore le bug ?
