### ISSUE TITLE
Open Data - Mettre un lien vers data.gouv sur la page stats

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#115]
Les administrations sont dans l’obligation de diffuser les informations publiques qu’elles produisent ou reçoivent. L’ouverture de ces données est soumise à un cadre précis, la diffusion de ces données ne devant porter atteinte ni à la protection de la vie privée, ni au secret des affaires. Ainsi, nous veillerons à traiter l’ensemble des informations avant leur publication. Dès lors, seront ouvertes des données relatives à l’usage de la plateforme, aux trajets effectués, le cas échéant après avoir fait l’objet d’un traitement permettant une publication conforme (anonymisation, agrégation, etc.).

Lien data.gouv https://www.data.gouv.fr/fr/datasets/trajets-realises-en-covoiturage-registre-de-preuve-de-covoiturage/

**Comment by margot-sanchez** [comment]
Mettre un filtre d'accès par territoire sur la plage statistiques. 
Reflexion : 
Possibilité de changer l'échelle du territoire. Par exemple le GPSEO est dans l'AOM IDF M et l'échelle de IDF M n'est pas intéressante pour eux.

**Comment by jonathanfallon** [comment]
On met un lien vers data.gouv.fr ?

**Comment by jonathanfallon** [comment]
Automatiser l'upload de données.
https://doc.data.gouv.fr/api/reference/#/datasets/create_dataset

**Comment by margot-sanchez** [comment]
Voir maquette : https://www.figma.com/file/J8LeDKQBeHTHGhm4Ys7Q0X/Chantier-Statistiques?node-id=0%3A1

![Uploading image.png…]()

**Comment by jonathanfallon** [comment]
Automatisation déplacée dans #1063 
Lien ajouté.
