### ISSUE TITLE
Doc demandes d'infos trajets

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1152]
Réponse type pour les personnes demandant des informations / export de leurs trajets sur une période.

- expliciter le fonctionnement avec les opérateurs
- expliciter la notion d'identité et protection des données

**Comment by margot-sanchez** [comment]
On a mis ça de côté. Je pense que ce n'est pas prioritaire mais il est indispensable de le faire avant la fin de l'année 2021 et espérer un transfert du produit.
