### ISSUE TITLE
Attestation.covoiturage.beta.gouv.fr bug

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1154]
### Sujet

A chaque rechargement de page le site plante en 404. 

### Environnement

Environnement : prod
Navigateur : chrome
URL : https://attestation.covoiturage.beta.gouv.fr/salarie-secteur-public

### Etapes pour reproduire

1. _Je clique sur https://attestation.covoiturage.beta.gouv.fr
2. _Je fais actualiser la page

![image](https://user-images.githubusercontent.com/15428433/103877452-65bbe180-50d5-11eb-919a-474883725684.png)

### Comportement attendu

1. _Que cela marche :) 

### Comportement actuel

1. _Cela ne marche pas.

**Comment by jonathanfallon** [comment]
Fix du `.htaccess` et mise à jour du monitoring uptime qui ne détectait pas le problème...
