### ISSUE TITLE
Amélioration texte export

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1169]
### Sujet

Lors de la confirmation de l'action d'export, en tant qu'utilisateur je souhaite 
1) être informé du fait que l'export sera réalisé par mail.
2) être informé du filtrage réalisé sur la date + opérateur

### Environnement

Utilisateur : profil en droit d'exporter
URL : https://app.covoiturage.beta.gouv.fr/trip/export

### Etapes pour reproduire / vérifier la bonne implémentation de l'amélioration

1. _Je clique sur trajets
2. _Je clique sur export
3. _ Je sélectionne une date et plusieurs opérateurs
4. _ Je clique sur exporter les trajets

![image](https://user-images.githubusercontent.com/15428433/104215869-ab600d80-5439-11eb-81fa-8d9eaa993d83.png)

### Comportement attendu

_Merci de confirmer l'export suivant : 
Date : du 11 décembre 2020 au 11 janvier 2021 
Opérateur(s) : MegaCovoit, Maxicovoit

Les données sont au format CSV et sont compressées dans un fichier ZIP qui vous parviendra par mail._

Annuler / Confirmer

**Comment by jonathanfallon** [comment]
TODO : Ajouter des messages d'erreur...

![image](https://user-images.githubusercontent.com/1656255/105337457-b99cef00-5bda-11eb-9cad-fbeb873f8b94.png)

**Comment by margot-sanchez** [comment]
Testé sur app-dev le 21/01/2020 👍 
![image](https://user-images.githubusercontent.com/15428433/105341918-f5868300-5bdf-11eb-9a60-5833ffc59af9.png)
@jonathanfallon possible de l'avoir en français ?

**Comment by jonathanfallon** [comment]
Jawohl !

**Comment by jonathanfallon** [comment]
TODO backend : restreindre la plage d'export maximale ou découper si possible.

**Comment by margot-sanchez** [comment]
Testé sur app-dev le 25/01/2021 👍 
@jonathanfallon tu peux me faire un nouveau ticket pour ton histoire de restreindre la plage d'export ? J'ai pas envie de fermer celui-là et perdre l'information.
