### ISSUE TITLE
Impossible mise à jour numéro SIRET IDFM

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1170]
### Sujet

Le numéro de SIRET IDFM est celui de la Mairie de Paris et non celui d'IDFM. Lorsque je souhaite mettre à jour, j'ai une erreur. 

### Environnement

Environnement : prod
Navigateur : chrome
Utilisateur : super admin
URL : https://app.covoiturage.beta.gouv.fr/admin/all-territories

### Etapes pour reproduire

1. _Je clique sur Administration
2. _ Je clique sur Territoire
3. _Je clique sur Ile de France Mobilités et éditer.
4. _Je modifie le SIRET 

SIRET actuel celui de la Mairie de Paris
![image](https://user-images.githubusercontent.com/15428433/104427682-d9516900-5583-11eb-8920-db5114e043a1.png)
Le SIRET d'après le KBIS est : 28750007800020

### Comportement attendu

1. _Je rentre 28750007800020 et les différentes cases adresse, code postal, etc devraient se remplir seules.

### Comportement actuel

1. _Je rentre 28750007800020 et j'ai une erreur 500 "[{"id":1610527578384,"error":{"code":-32000,"message":"Server error","data":"Cannot read property 'status' of undefined"},"jsonrpc":"2.0"}]"

Note : https://entreprise.data.gouv.fr/ semble ne pas répondre le 13.01.2020 à 9H50

**Comment by nmrgt** [comment]
J'ai fait un petit commit pour avoir un meilleur message d'erreur mais clairement la coupure du service entreprise.data.gouv.fr est la cause de ce message d'erreur.
