### ISSUE TITLE
Ajout d'un lien fiche campagne vers "trajets" préfiltrés

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1174]
### Sujet

Je suis un membre du Registre ou un Territoire, lorsque je vais sur une fiche de campagne (en cours ou terminées), je souhaiterais avoir un lien me permettant d'accéder aux Chiffres Clefs / Liste détaillée, directement filtré sur la campagne. 

### Environnement

Environnement : prod
Navigateur : chrome
Utilisateur : Registre et Territoire
URL : https://app.covoiturage.beta.gouv.fr/campaign/draft/249

### Etapes pour reproduire / vérifier la bonne implémentation de l'amélioration

1. _Je clique sur Campagnes, je clique sur une campagne en cours (ou terminées)
2. _Par exemple Pays de la Loire

![image](https://user-images.githubusercontent.com/15428433/104475629-9c0acc80-55bf-11eb-8e54-ff5b0ba2e772.png)

### Comportement attendu

1. _Je souhaiterais avoir un lien "voir toutes les statistiques" qui amènerait directement sur la page Chiffres clefs avec le filtre appliqué sur la campagne. 

### Comportement actuel

1. _Il n'y a pas de lien effectué.

**Comment by margot-sanchez** [comment]
Note : les filtres ne passent pas dans l'URL.

**Comment by jonathanfallon** [comment]
Tu mets le doigt sur la conception du module de filtres... soit on repense le module, soit on fait un patch (sale).
Je n'ai pas de solution rapide et élégante pour ce ticket.
