### ISSUE TITLE
Ajout bouton création compte

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1177]
### Sujet

En tant que futur utilisateur je reçois un mail m'invitant à confirmer la création de mon compte et choisir un mot de passe. Je souhaite que dans ce mail se trouve un bouton cliquable pour réaliser cette action. 

### Etapes pour reproduire / vérifier la bonne implémentation de l'amélioration

1. _Je clique sur "ajouter un nouvel utilisateur" dans l'interface administration.
2. _Le nouvel utilisateur va recevoir un mail.
![image](https://user-images.githubusercontent.com/15428433/104559913-66a8c200-5645-11eb-9de9-8d1120ea8410.png)

### Comportement attendu

1. _Un bouton "confirmer mon compte"

### Comportement actuel

1. _Je un lien non esthétique

**Comment by margot-sanchez** [comment]
Testé le 21/01/2021 sur app-dev 👎 
![Uploading image.png…]()

**Comment by margot-sanchez** [comment]
Testé le 25/01/2021 sur app-dev 👎

**Comment by jonathanfallon** [comment]
- [x] Confirmation de changement d'email
- [x] Changement de l'email
- [x] Export des trajets
- [x] Mot de passe oublié
- [x] Invitation

**Comment by margot-sanchez** [comment]
Testé le 26/01/01 sur app-dev 
 - [ ] Confirmation de changement d'email
 - [ ] Changement de l'email
 - [ ] Export des trajets
 - [ ] Mot de passe oublié
 - [ ] Invitation
