### ISSUE TITLE
Simulation sur un dataset défini (territoire pour validation)

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1182]
### Sujet

Je suis une AOM et je souhaite vérifier que la campagne que je vais voter correspond bien à mes attentes. Par exemple : avec un trajet de 10 km on obtient 1€, 12 km, 1,2€, etc.
On considère uniquement les trajets éligibles, on ne cherche pas à valider l'étape 2 du moteur de recherche. On se focalise uniquement sur le calcul de la rétribution.

- [ ]  Front
- [x]  Back

To Do :

On fait des variations avec à minima 1 trajet / variation
On génère des trajets
On envoie un CSV au front pour pouvoir le charger.

Voir : https://docs.google.com/spreadsheets/d/19gMPicnyHnvOcX_RQhfasVUhUcd7_B_5EfKYnj-ewWw/edit#gid=0

Spécifications : 
A faire au moment du paramétrage

**Comment by margot-sanchez** [comment]
Etat des lieux 28/01/2021 - docteur nous a fait une consultation sur le sujet

**Comment by P3rceval** [comment]
Consultation UX à refaire
