### ISSUE TITLE
Des données affichées sur les mauvais mois

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1193]
### Sujet

Sur l'interface dans la liste détaillée on ne retrouve pas de données après le 25 novembre 2020. Cependant sur le graphique on ne voit des données qu'en janvier 2021.

### Environnement

Environnement : app-dev & app.dev
Navigateur : chrome
Utilisateur : super admin
URL : https://app.dev.covoiturage.beta.gouv.fr/trip/stats

### Etapes pour reproduire

1. _Je clique sur liste détaillée, j'observe des trajets maximum jusqu'au 25 novembre 2020
2. _Je clique sur chiffres clefs, j'observe des données uniquement en janvier 2021

![image](https://user-images.githubusercontent.com/15428433/105830651-0b23f000-5fc6-11eb-9737-f1d0f890e812.png)
![image](https://user-images.githubusercontent.com/15428433/105830728-27279180-5fc6-11eb-9324-6281febc528a.png)

### Comportement attendu

1. _Je clique sur liste détaillée, j'observe des trajets maximum jusqu'au 25 novembre 2020
2. Je clique sur chiffres clefs, j'observe des données sur octobre et novembre 2020 et aucune donnée en décembre 2020 ou janvier 2021

Note : je pense qu'il y a une année de décalage, ce sont les données de janvier 2020 car quand je filtre cela met bien à jour. 

Note : c'est que les mois

**Comment by margot-sanchez** [comment]
Testé le 28/01/2021 sur app-dev et app.dev 👎

**Comment by margot-sanchez** [comment]
⚠️ 02/02/2021, ce ticket est aussi en staging car une mise en staging a été faite.

**Comment by nmrgt** [comment]
Vérifier le casting du mois dans le trip provider

**Comment by jonathanfallon** [comment]
A tester avec la branche de `feat/stats` pour voir si ça fonctionne correctement.

**Comment by jonathanfallon** [comment]
Il y a un soucis sur le nom du mois qui doit être '2020-01' et non '1'

![image](https://user-images.githubusercontent.com/1656255/106766483-31870280-663a-11eb-9c84-661c712e2427.png)

**Comment by nmrgt** [comment]
C'est fixé dans le back, le problème persiste en front.

**Comment by jonathanfallon** [comment]
Tout ça c'est fixé dans le chantier stats, soit on le merge assez rapidement et on l'améliore, soit on patch mais ça veut dire faire 2x le travail.

**Comment by margot-sanchez** [comment]
Jamais on ne fait une mise en production avec des données affichées pas le bon mois.

**Comment by margot-sanchez** [comment]
🙏 Testé sur staging le 16/02/2021 👍 
![image](https://user-images.githubusercontent.com/15428433/108037461-f1f8e700-7039-11eb-912a-a07034110160.png)
