### ISSUE TITLE
Ajout information pays si étranger

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1194]
### Sujet

En tant qu'utilisateur du Registre lorsque je vais dans la liste détaillée, je souhaite comprendre facilement que lorsque le nom de la ville n'est pas indiqué c'est qu'il s'agit d'une destination à l'étranger.

### Environnement

URL : https://app-dev.covoiturage.beta.gouv.fr/trip/list

### Etapes pour reproduire / vérifier la bonne implémentation de l'amélioration

1. _Je clique sur liste détaillée 

![image](https://user-images.githubusercontent.com/15428433/105831849-876b0300-5fc7-11eb-9e54-37e28c9bfb5c.png)

### Comportement attendu

1. _Une information simple à comprendre. Peut être mettre des drapeaux du pays ? 

### Comportement actuel

1. _Je clique sur liste détaillée et je pense qu'il y a un bug car la colonne départ ou arrivée est vide.

**Comment by jonathanfallon** [comment]
Affichage de la ville ou du pays si celle-ci est manquante.

**Comment by margot-sanchez** [comment]
Testé le 25/02/2021 sur app.dev 👍 
![image](https://user-images.githubusercontent.com/15428433/109196811-7a932800-779c-11eb-824f-ee2bf444ef03.png)
