### ISSUE TITLE
Définition campagne - pouvoir sélectionner des dates dans le passé

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#12]
Dans la définition d'une campagne il n'est pas possible de pouvoir sélectionner une date de début d'application dans le passé. 
Est-ce un choix technique volontaire, car cela engendrerait de la complexité ? @nmrgt ?
Sinon alors, il est selon moi envisageable qu'une AOM ait un peu de retard et lance une campagne avec quelques jours de retard.

**Comment by jonathanfallon** [comment]
Préciser dans le doc qu'une campagne ne peut être configurée dans le passé.
