### ISSUE TITLE
Modification de la licence

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#120]
Suite à une discussion avec @bzg, il semblerait que la license AGPL3.0 n'est pas adaptée à notre projet et peut s'avérer bloquante pour les contributeurs éventuels qui se verraient dans l'obligation de reverser leurs contributions de manière obligatoire.

Il me conseille de la changer pour une licence Apache 2.0 qui est plus permissive et protège contre un tiers qui souhaiterait déposer un brevet sur base de notre code. La dernière option plus permissive, est l'utilisation d'une licence MIT.

Les licences :
https://choosealicense.com/licenses/agpl-3.0/
https://choosealicense.com/licenses/apache-2.0/
https://choosealicense.com/licenses/mit/

Une issue de @bzg sur le sujet (sur le site de beta.gouv.fr)
https://github.com/betagouv/beta.gouv.fr/issues/2477

Plus d'infos : https://opensource.guide/legal/

Le processus de changement de licence implique la validation de cette décision par tous les contributeurs. Je vous invite à valider ou invalider par commentaires ci-dessous, merci.

@margot-sanchez @nmrgt @samueleyre

**Comment by margot-sanchez** [comment]
J'avoue ne pas avoir une experte des licences, mais les arguments mis en avant sont cohérents. 

J'avais justement une crainte d'un Etat qui a récemment mentionné le registre de preuve de covoiturage français et a dit "il est open source dont on pourra le copier dans notre Etat". Je me demandais qu'elles étaient les obligations de ce dernier à contribuer derrière ? S'il avait le droit de le prendre et de le commercialiser en son nom sans nous mentionner ou nous informer ? 

Il nous faut une licence qui permet à d'autres de contribuer sans imposer trop de choses mais quand même garder une mention de la source (juste l'information que quelqu'un nous utilise quoi) et éviter que quelqu'un dépose un brevet et le commercialise de manière exclusive. 

On peut m'expliquer les avantages/intérêts du "trademark use" ?

**Comment by samueleyre** [comment]
L'apache 2.0 me parait bien adaptée.

**Comment by IshanB** [comment]
ok

**Comment by ThomasMenant** [comment]
La licence Apache semble tout à fait suffisante.

Notamment si nous souhaitons que "chacun" puisse contribuer/réutiliser le code, tout en garantissant la mention des travaux menés par l'équipe. 

Autrement, le "trademark use" est une cession de droits permettant la réutilisation du "nom commercial du projet", par exemple, la licence ne donne pas le droit de réutiliser directement le super-bô logo du Registre (ou son nom, si on en avait fait une marque).  
[This License does not grant permission to use the trade names, trademarks, service marks, or product names of the Licensor, except as required for reasonable and customary use in describing the origin of the Work and reproducing the content of the NOTICE file.]

Troll on : 
Après, vu que c'est @bzg qui propose, je peux vous bâtir un argumentaire juridique qui permettrait de conserver l'AGPL ;)

**Comment by bzg** [comment]
Merci @jonathanfallon d'avoir lancé le sujet et à tous pour les retours.

Il n'y a pas de pratique bien établie au sein de l'administration qui aiderait à se raccrocher à des exemples pour choisir de limiter ou non les réutilisations, mais l'idée reste que les licences permissives peuvent être utilisées sans justification, alors que les autres en demandent.

D'ailleurs, @ThomasMenant, pour ce cas ou pour un autre, je suis très preneur d'un argumentaire juridique pour imposer des licences homologuées non permissives :)  Ce serait intéressant d'avoir plusieurs argumentaires pour voir si on peut aller au-delà du cas par cas et dégager une approche générale.
