### ISSUE TITLE
Restreindre la plage d'export maximale ou découper si possible.

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1201]
### Sujet

Restreindre la plage d'export maximale ou découper si possible.

### Environnement

Utilisateur : celles et ceux pouvant exporter

### Etapes pour reproduire / vérifier la bonne implémentation de l'amélioration

1. _Je clique sur exporter

### Comportement attendu

1. _Une plage restreinte en back

### Comportement actuel

1. _En changeant dans la requête je peux facilement "hacker" le truc

**Comment by nmrgt** [comment]
@margot-sanchez ok mais quelle est la limite à mettre ?

**Comment by margot-sanchez** [comment]
@nmrgt j'allais te dire regarde les specs sur le hackmd export et en fait, tu as raison ce n'est pas écrit dedans. De mémoire on avait dit : 
- nativement cela propose le dernier mois.
- l'utilisateur peut aller jusqu'à deux ans dans le passé comme sur les filtres.

**Comment by jonathanfallon** [comment]
Réouvert pour passer dans les tests.

**Comment by margot-sanchez** [comment]
@jonathanfallon il faut qu'on ait une discussion sur ce ticket. Apparemment la patate chaude est chez toi maintenant sur le débat 2 ans / 1 an. Sachant qu'en back la limite est à 2 ans. Pour moi idéalement il faudrait 2 années.
