### ISSUE TITLE
Alignement des environnements de dev

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#1204]
- [x] 1. app.dev n'a pas les attestations
- [x] 2. problème d'export sur app.dev
- [x] 3. très étrange celui là. Sur app.dev il n'y avait plus de modèles dans le moteur d'incitation jusqu'à il y a une heure. Là ils sont revenus mais par contre le haut de l'écran disparait quand on est sur les modèles (fermé car impossible à reproduire)
- [x] 4. sur app.dev il est impossible de passer à l'étape suivante lors de la création d'une campagne d'incitation

**Comment by nmrgt** [comment]
@jonathanfallon ya pas une histoire de feature flag pour le 1 ?

**Comment by margot-sanchez** [comment]
Pour compléter sur app-dev les attestations sont présentes mais ne fonctionnent pas : Cannot GET /v2/certificates/pdf/b6acc951-126f-4c6d-b312-6ad0e76f2e0e

**Comment by nmrgt** [comment]
@jonathanfallon pour les attestations, le problème vient de ce fichier `dashboard/src/app/modules/administration/administration-layout/administration-layout.component.ts` qui n'utilise pas le service ConfigService(dashboard/src/app/core/services/config.service.ts) et qui par conséquent ne supporte pas le surchargement des variables d'environnement.

**Comment by jonathanfallon** [comment]
1 et 4 testés sur app.dev et app-dev :heavy_check_mark:

**Comment by nmrgt** [comment]
Ok, je met le ticket en review.

Margot, on peut le fermer ?

**Comment by margot-sanchez** [comment]
@nmrgt

**Comment by margot-sanchez** [comment]
Note : d'ailleurs c'est super chelou le nouveau truc que vous avez mis pour le J-5 dans ce cas là il faut faire ça aussi sur la date de début non ?

**Comment by margot-sanchez** [comment]
Les exports ne marchent toujours pas sur app.dev le 15/02/2021

**Comment by jonathanfallon** [comment]
Soucis de gestion de la date quand on la modifie et aussi de la limite max pour la date de fin qui n'était pas synchro avec le back.

**Comment by margot-sanchez** [comment]
Testé sur staging le 16/02/2021 avec un compte super admin 👎
