### ISSUE TITLE
Amélioration > Les trajets > Classe

### ISSUE THREAD

**Issue by lauriebequet** [betagouv/preuve-covoiturage#1206]
### Sujet

**https://app.covoiturage.beta.gouv.fr > Les trajets > Classe**

Ajouter une info bulle au survol (hover) sur le mot “classe” afin de rappeler de quoi il s'agit. Le territoire peut avoir oublié ou ne plus se rappeler des subtilités de la signification des classes de preuve de covoiturage :

- classe A = l’opérateur certifie la mise en relation avec intention de covoiturer
- classe B = l’opérateur certifie la mise en relation et le trajet d’un occupant du véhicule
- classe C = l’opérateur certifie la mise en relation, les trajets des occupants du véhicule et une identité distincte des occupants

### Environnement

Environnement (dev, prod...) : prod
Navigateur : chrome
Utilisateur : territoires

**Comment by margot-sanchez** [comment]
⚠️ voir si le texte n'est pas trop long.

**Comment by margot-sanchez** [comment]
Testé le 5/05/2021 sur dev 👍
