### ISSUE TITLE
Pas de template campagne 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1220]
### Sujet

Je suis un territoire et je me connecte pour créer une campagne d'incitation. J'ai une erreur dès la première étape, pas de template.

### Environnement

Environnement : staging
Navigateur : chrome
Utilisateur : admin territoire
URL : https://app-staging.covoiturage.beta.gouv.fr/campaign/create

### Etapes pour reproduire

1. _Je clique sur "brouillon d'une nouvelle campagne"

![image](https://user-images.githubusercontent.com/15428433/106630559-384f4000-657c-11eb-81c5-62d99efcf4fd.png)

**Comment by nmrgt** [comment]
Je n'arrive pas à reproduire avec un admin territoire sur le staging.

@margot-sanchez si tu n'as pas plus de détail, je propose de fermer le ticket.

**Comment by margot-sanchez** [comment]
Testé le 08/02/2021 sur staging 👎 -1

J'ai toujours le même bug @nmrgt

**Comment by margot-sanchez** [comment]
Note : lorsque je vais créer un nouveau compte et que je fais la manipulation alors là cela marche. Mais pas sur les anciens comptes. 
![image](https://user-images.githubusercontent.com/15428433/107255771-f2412300-6a38-11eb-93f0-0cea9d4fa5be.png)

**Comment by margot-sanchez** [comment]
MAJ : le compte découverte (demo) n'a pas les autorisations. Sur prod pourtant cela fonctionne.
```
[,…]
0: {id: 1612856900284, error: {data: "Invalid permissions", code: -32503, message: "Forbidden Error"},…}
error: {data: "Invalid permissions", code: -32503, message: "Forbidden Error"}
id: 1612856900284
jsonrpc: "2.0"
```

**Comment by margot-sanchez** [comment]
Testé le 15/02/2021 sur staging (erreur 403) 👎

**Comment by jonathanfallon** [comment]
Permissions fixées sur `dev` et `staging`
:warning: pour tester, il faut se déconnecter et se reconnecter pour que les nouvelles permissions soit mises à jour.
Testé pour `territory.admin` et `territory.demo`

**Comment by margot-sanchez** [comment]
Testé le 19/02/2021 sur staging en territoire démo 👍 +1
Testé le 19/02/2021 sur staging en territoire admin 👍 +1
