### ISSUE TITLE
Simulation sur derniers mois - plage (repassage sur des mois glissants)

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1223]
### Sujet

Passage de la simulation sur des mois glissants à J-5.

Je suis le 16 avril 2021, la simulation sur 3 mois doit être faite sur une période du 11 janvier au 11 avril*. 

Ajout d'une * avec un message "la collecte des trajets des 5 dernières journées n'est pas finalisée". Si vous avez un meilleur message hésitez pas

### Environnement

Environnement : prod
Navigateur : chrome
Utilisateur : territoire

### Etapes pour reproduire

1. _Je réalise une simulation 

[image](https://user-images.githubusercontent.com/15428433/106641230-448cca80-6587-11eb-9315-8bff20dcf16a.png)

**Comment by margot-sanchez** [comment]
Note : c'est dû aux 5 jours de délais. A tester le 6 février. 
Faire un message d'explication à mettre sur le front.

**Comment by jonathanfallon** [comment]
Je pense qu'une place glissante fait plus de sens, en gardant 5 jours de délai.
Je ne vois pas l'intérêt de se baser sur le découpage des stats. Les campagnes peuvent commencer quand elle veulent.

**Comment by margot-sanchez** [comment]
Gilles m'avait convaincu du contraire. Ses arguments, en indiquant 1,2,3 mois c'est une plage de mois et vu que le nombre de jours change en fonction des mois, il est plus simple de dire c'est du 1 décembre 20XX au 31 février 20XX plutôt que de faire une plage glissante. Pour moi c'était assez facile à comprendre que cela se calculait sur un mois finalisé, mais le décalage des 5 jours m'a perturbé. Faut qu'on en discute.

**Comment by margot-sanchez** [comment]
Ok je suis désormais convaincu du contraire. Il faut passer sur des mois glissants.

**Comment by margot-sanchez** [comment]
Le ticket a été modifié et spécifié ⏫

**Comment by margot-sanchez** [comment]
Testé le 10/05/2021 sur dev. Attention ne peut être testé complétement car on a pas de données de moins de 3 mois.
