### ISSUE TITLE
Réouverture des anciens comptes lors du passage en staging

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1224]
### Sujet

C'est très étrange en faisant la mise en staging vous avez réactivé tout les anciens comptes que j'avais supprimé et cela les a mis en administrateur registre ! J'ai supprimé manuellement mais c'est étrange. Par exemple les comptes de Samuel, Stacy étaient de retours alors que je suis certaine de les avoir supprimé. Des comptes AOM étaient également dans la liste des admin RPC. 

### Environnement

Environnement : staging
Navigateur : chrome
Utilisateur : super admin

Note : impossible à reproduire vu que j'ai supprimé les comptes directement.

**Comment by nmrgt** [comment]
vérifier seeding

lien avec #1220 ?

**Comment by nmrgt** [comment]
Désolé, je n'ai pas réussi ni à reproduire, ni à trouver les utilisateurs en question. Si jamais tu as plus de détail, n'hésite pas à compléter. Sinon, je propose de fermer le ticket

**Comment by margot-sanchez** [comment]
Impossible à vérifier vu que j'ai tout supprimé. A vérifier à la prochaine mise en staging.
