### ISSUE TITLE
Le module de sélection de la visibilité 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1228]
### Sujet

Je suis un admin opérateur, le module de sélection de la visibilité bug complet. Il n'y a même plus les territoires. 

### Environnement

Environnement : staging 
Navigateur : chrome
Utilisateur : admin opérateur
URL : https://app-staging.covoiturage.beta.gouv.fr/admin/visibility

### Etapes pour reproduire

1. _Je clique sur Visibilité

![image](https://user-images.githubusercontent.com/15428433/106903256-154a9a80-66fa-11eb-8faf-c8c7c60b6d90.png)

### Comportement attendu

1. _La liste des territoires

**Comment by jonathanfallon** [comment]
DB territoires fixée
