### ISSUE TITLE
Le Pole Métropolitain du Genevois n'est pas disponible sur la liste des territoires

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1229]
### Sujet

Dans la sélection de la visibilité des territoires par un opérateur, les territoires manuellement faits n'apparaissent pas. 

### Environnement

Environnement : prod
Navigateur : chrome
Utilisateur : admin opérateur 
URL : https://app.covoiturage.beta.gouv.fr/admin/visibility

### Etapes pour reproduire

1. _Je clique sur "visibilité

![image](https://user-images.githubusercontent.com/15428433/106902133-c3554500-66f8-11eb-8e0a-9d8641c816bd.png)

### Comportement attendu

1. _L'ensemble des territoires de la table du territoires doivent apparaitre

### Comportement actuel

1. _Le Pole Métropolitain du Genevois n'apparait pas. 

Note : impossible à tester sur staging puisque le staging bug voir ticket #1228

**Comment by jonathanfallon** [comment]
Madame est servie

![image](https://user-images.githubusercontent.com/1656255/108376463-51eeb980-7203-11eb-958b-b1b9ee16a287.png)

On enlève les enfants j'imagine ?

**Comment by jonathanfallon** [comment]
On a ça qui est apparu aussi :
![image](https://user-images.githubusercontent.com/1656255/108376865-b7db4100-7203-11eb-8a4e-503eeb3d4673.png)

**Comment by margot-sanchez** [comment]
Testé sur le staging le 19/02/2021 👎 
![image](https://user-images.githubusercontent.com/15428433/108493965-448b0b00-72a7-11eb-9085-20802d17b809.png)
Testé sur la prod le 19/02/2021 👎 
Testé sur la dev le 19/02/2021 👍 
![image](https://user-images.githubusercontent.com/15428433/108514103-bb360180-72c3-11eb-89d8-863d64a24f3b.png)

Je souhaite garder les enfants AOm ou partenaires tout de même.
