### ISSUE TITLE
Décochage automatique de "tous les territoires"

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1230]
### Sujet

Je suis admin d'un opérateur et je sélectionne l'ensemble des territoires dans la visibilité. Chaque fois que je coche et j'enregistre la coche est effacée. 

### Environnement

Environnement : prod
Navigateur : chrome
Utilisateur : admin opérateur
URL : https://app.covoiturage.beta.gouv.fr/admin/visibility

### Etapes pour reproduire

1. _Je clique sur Visibilité et je coche la case "tous les territoires"
2. _J'enregistre et j'actualise

![image](https://user-images.githubusercontent.com/15428433/106901696-5e99ea80-66f8-11eb-858e-c26ee6bb6157.png)

### Comportement attendu

1. _La case reste cochée
2. 
### Comportement actuel

1. La case est décochée.

Note : ceci ne peut pas être testé sur staging car cela bug voir ticket #1228

**Comment by jonathanfallon** [comment]
A tester en `staging`
