### ISSUE TITLE
Désolidariser "partenaire" et "AOM"

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1234]
### Sujet

Lorsque je suis super admin et que je dois mettre à jour une fiche territoire, les cases AOM et partenaires sont solidaires. Il est impossible de cocher AOM sans cocher partenaires. 
Ceci fait que toutes les AOM sont cochées comme partenaire de fait. 

Raisons techniques ? Voir comment améliorer ça. 

### Environnement

Utilisateur : super admin
URL : https://app-staging.covoiturage.beta.gouv.fr/admin/all-territories

![image](https://user-images.githubusercontent.com/15428433/107248480-a0959a00-6a32-11eb-9ed2-167ad7a2290e.png)

**Comment by margot-sanchez** [comment]
Renommer le champ activable en as mobilty competence aka AOM ? 
To Do se mettre d'accord sur le nommage.

**Comment by margot-sanchez** [comment]
Pour la visibilité des territoires c'est soit partenaire soit AOM.

**Comment by jonathanfallon** [comment]
Cas d'usage relevés :

1. Une région est AOM d'office
2. Une EPCI peut prendre la compétence mobilité
3. Un territoire non AOM est partenaire du RPC

Pour renommer les champs je propose :

| old front | old back | new front | new back |
|---|---|---| --- |
| AOM | `activable` | Compétence mobilité | `is_aom` |
| Partenaire | `active` | Partenaire | `is_partner` |

**Comment by jonathanfallon** [comment]
1ca1fa35 fix le comportement dans le front.
TODO : faire la modif de nom de champ dans le back et dans le front

**Comment by margot-sanchez** [comment]
Impossible à tester en fonction [de ce ticket ](https://github.com/betagouv/preuve-covoiturage/issues/1278)

**Comment by margot-sanchez** [comment]
Testé le 15/03/2021 sur app.dev 👍 
Cela fonctionne mais cela n'a pas fait le lien avec la visibilité.

Exemple : j'avais créé il y a quelques jours (>24H00) le territoire de Teslandouille 
![image](https://user-images.githubusercontent.com/15428433/111131546-a4a86080-8578-11eb-9b79-eb101b34a8d6.png)
Les deux cas sont cochées. Cela devrait donc forcement apparaitre dans la visibilité. Or en tant qu'opérateur je ne vois pas ce territoire. 
![image](https://user-images.githubusercontent.com/15428433/111131664-c3a6f280-8578-11eb-8844-027c6974bb70.png)

**Comment by margot-sanchez** [comment]
Le 16/04/2021. Ce problème de non liaison avec la visibilité est toujours d'actualités.

**Comment by jonathanfallon** [comment]
Après ajout d'un territoire, je ne récupère pas les infos dans le territoryTree.

![image](https://user-images.githubusercontent.com/1656255/117102589-eb485900-ad78-11eb-99ac-d7ee940a03a0.png)

`territory:list` donne :

![image](https://user-images.githubusercontent.com/1656255/117102629-01561980-ad79-11eb-997f-a78498774678.png)

**Comment by margot-sanchez** [comment]
Techniquement ce ticket est à fermer. 
Action faire une liste des territoires sans familles.
