### ISSUE TITLE
Suspension de compte si territoire supprimé

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1235]
### Sujet

En mettant à jour la table des territoires, le territoire fictif de Testland a disparu. 
Pour le besoin des tests, Testland avait été fait en ajoutant des codes INSEE et des régions au hasard. Il s'agissait du compte test de staging. Or le territoire a disparu de la liste et le compte utilisateur n'a donc plus de territoire attaché. 

### Environnement

Environnement : staging
Navigateur : chrome
Utilisateur : super admin
URL : https://app-staging.covoiturage.beta.gouv.fr/admin/all-users

### Etapes pour reproduire

1. _Je clique sur  Utilisateurs & accès ou sur territoires et je recherche Testland

![image](https://user-images.githubusercontent.com/15428433/107249049-3cbfa100-6a33-11eb-847c-55de6598536b.png)

**Comment by nmrgt** [comment]
Le problème est l'absence de contrainte sur les utilisateurs. A faire : ajoute d'une contrainte + cascade delete (ou soft delete) à partir de territoire.

**Comment by jonathanfallon** [comment]
NON !
Un territoire ne peut pas être supprimé dans l'interface.
Ne pas ajouter de contraintes qui auraient des effets de bord trop complexes à gérer.
Le bug vient du flashage des tables de territoire sur le staging.

**Comment by margot-sanchez** [comment]
Je vois plusieurs cas : 
:one: Des territoires fusionnent entre eux, alors on garde les territoires (on décoche AOM) et on fait un nouveau territoire AOM :heavy_check_mark: 
:two: Un territoire absorbe une commune, ou des communes à proximité. Alors on modifie le territoire pour le mettre à jour. :heavy_check_mark: 
:three: Une AOM disparait pour laisser sa compétence à la Région. Alors on va décocher AOM dans la liste des territoires. :heavy_check_mark:
