### ISSUE TITLE
Augmenter le rate limit

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1238]
### Sujet
Le rate limit est trop restrictif (surtout quand on est en phase de recette). Attention ceci est uniquement valable pour une grosse utilisation de l'application. 

Par exemple : 
_Je suis super admin, je fais plusieurs tests,  je vais dans mon interface admin et je clique sur territoire. L'app se met chaque fois à planter pendant 30 sec. Je dois faire actualiser à quasi chaque fois. 

A investiguer

**Comment by nmrgt** [comment]
Peut-être du à un rate limit trop restrictif.

**Comment by jonathanfallon** [comment]
rate limiter augmenté, à tester.

**Comment by margot-sanchez** [comment]
Testé le 19/02/2021 sur staging, j'ai vraiment fait plein de tests et cela n'a jamais bug. Je suppose donc que le rate limit a été augmenté.
