### ISSUE TITLE
Changer les . par des , dans les exports

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1241]
### Sujet

_Je télécharge un export, j'ouvre mon tableur dans un logiciel, les numéros avec des décimales ne sont pas reconnus comme des chiffres car ils comportent un point et non une virgule

### Environnement

Environnement : prod
Utilisateur : ceux pouvant faire un export

### Etapes pour reproduire / vérifier la bonne implémentation de l'amélioration

1. _Je réalise un export

### Comportement attendu

1. _J'ouvre le tableur je peux trier par distance / cout du plus petit au plus grand

### Comportement actuel

1. _Je ne peux pas trier et doit manuellement changer de . à ,

**Comment by nmrgt** [comment]
le fix en question a pas été mergé donc c'est logique ça ne fonctionne pas. 

Désolé je l'avais mis en test un peu tôt, on a retardé le merge pour la mise en prod.

**Comment by margot-sanchez** [comment]
Testé le 15/03/2021 sur app 👎

**Comment by jonathanfallon** [comment]
le fix est dans la PR #1279

**Comment by margot-sanchez** [comment]
Testé le 15 avril 2021 sur la prod 👍
