### ISSUE TITLE
UI Duplication de campagnes

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1244]
Pas de wrapper du formulaire de duplication.

Bouton désactivé tant que le bug n'est pas résolu :
`dashboard/src/app/modules/campaign/pages/campaign-active-view/campaign-active-view.component.html`

**Comment by margot-sanchez** [comment]
Faire un master ticket campagne.

**Comment by jonathanfallon** [comment]
Le bouton est maintenant dans la liste des campagnes quand on est connecté comme Territory Admin

**Comment by margot-sanchez** [comment]
Testé le 05/03/2021 sur app.dev 👍
