### ISSUE TITLE
Attestation cannot get

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1252]
### Sujet

Les attestations en pdf ne marchent plus. 

### Environnement

Environnement : dev + staging
Navigateur :  crhome
Utilisateur : super admin
URL : https://app.dev.covoiturage.beta.gouv.fr/admin/certificates

### Etapes pour reproduire

Je clique sur l'attestation en format PDF. 

@jonathanfallon pour les attestations, le problème vient de ce fichier dashboard/src/app/modules/administration/administration-layout/administration-layout.component.ts qui n'utilise pas le service ConfigService(dashboard/src/app/core/services/config.service.ts) et qui par conséquent ne supporte pas le surchargement des variables d'environnement.

### Comportement attendu

L'attestation

### Comportement actuel

Cannot GET /v2/certificates/pdf/de1580a6-28a4-45e4-8fef-99049b0ceeac

**Comment by jonathanfallon** [comment]
7d031fef668ad409b8abec0f8cc87afd8881c753

**Comment by margot-sanchez** [comment]
✔️ sur staging le 15/10/2021

**Comment by jonathanfallon** [comment]
Le hotfix n'a pas été :cherries:-picked sur `dev`.
