### ISSUE TITLE
Les simulations ne fonctionnent plus

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1253]
### Sujet

Je suis un territoire et je réalise une campagne dans l'outil. A la fin j'ai une erreur 500 sur la simulation.

### Environnement

Environnement : staging
Navigateur : chrome
Utilisateur : territoire (besançon)
URL : https://app-staging.covoiturage.beta.gouv.fr/campaign/draft/273

### Etapes pour reproduire

1. _Je clique sur la campagne et je l'édite

![image](https://user-images.githubusercontent.com/15428433/107975575-989ca380-6fb8-11eb-98a6-0302bcdf83f1.png)

`[{"id":1613408826108,"error":{"code":-32000,"message":"Server error","data":"relation \"policy.trips\" does not exist"},"jsonrpc":"2.0"}]`

**Comment by jonathanfallon** [comment]
Problème de flashing de base. Résolu.
