### ISSUE TITLE
Blocage de la date de fin sur les filtres de trajets

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1254]
### Environnement

Environnement `dev`
Navigateur : Brave
Utilisateur : `territory.admin`
URL : https://app.dev.covoiturage.beta.gouv.fr/trip/stats

### Etapes pour reproduire

1. ouvrir les filtres
2. mettre une date de fin dans le **futur** (ex 17 février)

-> Erreur 400 : `End should be before Tue Feb 16 2021`

## TODO

fix dans le front pour donner une date max de fin comme dans le formulaire d'export

**Comment by margot-sanchez** [comment]
Testé sur app.dev le 16/02/2021 👍 
![image](https://user-images.githubusercontent.com/15428433/108094608-483c4900-707f-11eb-97ed-04e65e0eee77.png)
