### ISSUE TITLE
Amélioration UX moteur de recherche territoire - stats

### ISSUE THREAD

**Issue by lauriebequet** [betagouv/preuve-covoiturage#1259]
### Sujet

En mode admin RPC : amélioration du moteur de recherche "territoires" sur https://app.covoiturage.beta.gouv.fr/trip/stats 

- [ ] Quand je cherche un territoire, ce serait pratique qu'on puisse voir tout le nom du territoire. Comme tu peux le voir sur la capture ci-dessous, il est tronqué et impossible de voir de quel territoire il s'agit. En gros sur ce moteur il faut taper précisément le territoire pour l'ajouter.

![Capture d’écran 2021-02-18 à 11 20 25](https://user-images.githubusercontent.com/76481140/108343538-5bb0f680-71dc-11eb-82c9-c49b98473fc4.png

### Environnement

Environnement :prod
Navigateur : chrome
Utilisateur : admin rpc 
URL : https://app.covoiturage.beta.gouv.fr/trip/stats

**Comment by margot-sanchez** [comment]
Propositions de solutions : 
1) on invite les gens à taper le nom de la commune principale, en générale personne ne tape Communauté d'Agglomération d'Arlysère, mais tape directement Arlysrère
2) on ajoute la possibilité de filtrer sur le shortname 
3) autre
