### ISSUE TITLE
Suppression de la branche + environnement staging

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1264]
- [x] déploiement de la branche `production` sur la pré-production
- [x] suppression de la branche de staging
- [x] mise à jour des scripts de CI
- [ ] test d'explication auprès des opérateurs

**Comment by nmrgt** [comment]
> Bonjour à tous,
> 
> Nous allons désactiver l'environnement de staging tel qu'il était déployé jusqu'à présent.
> Afin de vous permettre d'accéder à un environnement dédié à vos tests, nous avons mis en place un environnement d>
> Nous vous invitons donc à mettre à jour les adresses de l'API de test et remplacer :
> https://api-staging.covoiturage.beta.gouv.fr par https://api.demo.covoiturage.beta.gouv.fr
>
> Si vous avez des difficultés, n'hésitez pas à nous solliciter.
> Bonne journée,

**Comment by jonathanfallon** [comment]
Envoyé. https://app.mailjet.com/stats/campaigns/7654836692/overview

**Comment by nmrgt** [comment]
Cool !

Je ferme :)
