### ISSUE TITLE
Autocompletion des noms de communes avec possibilité d'en mettre plusieurs

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#127]
#20 

On peut rechercher par nom de commune encore faut-il l'écrire parfaitement en fonction de ce qui est écrit dans la base. Propositions d'améliorations : 
- [x] Autocompletion des noms de commune
- [x] Pouvoir rechercher sans les accents, exemple je n'arrive pas à rechercher É pour Écully 
- [x] Pouvoir recherche en minuscule pour pouvoir recherche ecully par exemple
- [x] Pouvoir mettre plusieurs commune dans la liste genre ecully et lyon
- [ ] Côté AOM liste des noms de commune compris sur le territoire ( Filtre par AOM ) 

Possibilité d'utiliser l'API géo + liste des communes de l'AOM.

**Comment by jonathanfallon** [comment]
ça implique du backend donc on va attendre d'avoir la version TypeScript pour faire l'implémentation

**Comment by margot-sanchez** [comment]
A vérifier par @samueleyre au retour de @jonathanfallon.
Fait sur le nouveau Front en attente pour voir ce qui bug sur le back (exemple : quand on recherche Lyon, cela affiche Grenoble).

**Comment by jonathanfallon** [comment]
Migration Postgres en cours --> mise en place des outils nécessaires pour faire de la recherche FULLTEXT sur le champs des noms de villes.
Voir les subtilités de recherche (cf. Tristram) comme le fait de chercher sur le nom de l'AOM, etc...

**Comment by jonathanfallon** [comment]
Voir #202

**Comment by nmrgt** [comment]
Est-ce qu'on peut pas côté front transformer une ville en code insee ? :)

**Comment by samueleyre** [comment]
> Est-ce qu'on peut pas côté front transformer une ville en code insee ou en code postal ? :)

Yep :)

**Comment by nmrgt** [comment]
Faut voir avec @jonathanfallon sur l'implémentation côté back pour la correspondance code insee/ville

**Comment by margot-sanchez** [comment]
On ferme. On fait un ticket #614 spécialement pour le dernier point.
