### ISSUE TITLE
Amélioration filtre territoires

### ISSUE THREAD

**Issue by lauriebequet** [betagouv/preuve-covoiturage#1271]
### Sujet

_ amélioration filtre territoires https://app.covoiturage.beta.gouv.fr/trip/stats en mode admin.
Quand j'ajoute beaucoup de territoires dans le filtre, le bouton "appliquer" disparait = > cela est problématique (voir capture d'écran)
<img width="1084" alt="Capture d’écran 2021-03-01 à 12 32 18" src="https://user-images.githubusercontent.com/76481140/109491972-8fb4d300-7a8a-11eb-99b2-1eaf8b6ead9e.png">

### Environnement

Environnement (dev, prod...) : app.covoiturage
Navigateur : chrome
Utilisateur : admin
URL : https://app.covoiturage.beta.gouv.fr/trip/stats

**Comment by margot-sanchez** [comment]
Propositions de solutions : 
1) on invite les utilisateurs à mettre directement l'EPCI au lieu de rentrer individuellement les communes. Ceci est sous réserve d'avoir l'EPCI en base
2) déplacer le composant de filtre, réorganiser pour permettre d'avoir une liste plus longue (ceci réglerait la #1259 )
3) autres ?

**Comment by jonathanfallon** [comment]
J'ai tendance à penser que c'est une mauvaise idée de proposer une liste trop longue. Il faut utiliser les différents niveaux géographiques disponibles : commune < EPCI < département < région pour faire la sélection et non mettre une liste infinie de communes.
On doit refaire une passe UX sur ces composants et sûrement repenser l'usage pour le simplifier. Ce genre de filtrage aussi détaillé doit se faire à partir d'un export des données dans un outils dédié.
