### ISSUE TITLE
Impossible de modifier mes données en tant qu'AOM 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#128]
Le bouton modifier ne fonctionne pas. 
![image](https://user-images.githubusercontent.com/15428433/56597776-77084600-65f3-11e9-9686-17cae97e913e.png)

**Comment by samueleyre** [comment]
C'est corrigé dans la pull request [122](https://github.com/betagouv/preuve-covoiturage/pull/122)

**Comment by margot-sanchez** [comment]
👍
