### ISSUE TITLE
Export date en anglais

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1282]
### Sujet

L'export est désormais de nouveau en anglais concernant les dates. Ce problème avait été réglé mais il est de nouveau là. 
![image](https://user-images.githubusercontent.com/15428433/110518561-88d23400-810c-11eb-8ad3-743a066776be.png)

### Environnement

Environnement : dev
Navigateur : chrome
Utilisateur : chaque utilisateur pouvant réaliser un export.

**Comment by jonathanfallon** [comment]
Problème de versions de dépendances. Résolu par un update complet de Angular + nettoyage des dépendances et mise à jour.

**Comment by margot-sanchez** [comment]
Testé le 15/03/2021 sur app.dev 👍
