### ISSUE TITLE
🔥 Journey id qui disparait - export

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1283]
### Sujet

Sur la prod, l'export n'indique plus l'ensemble des journey id.
![image](https://user-images.githubusercontent.com/15428433/110521541-2713c900-8110-11eb-9a04-f9dc083efbb8.png)

### Environnement

Environnement : prod
Navigateur : chrome
Utilisateur : utilisateur pouvant réaliser un export

**Comment by margot-sanchez** [comment]
Retour de ce bug sur la dev le 27/05/2021. Export réalisé depuis un compte super admin.
![image](https://user-images.githubusercontent.com/15428433/119781762-ade47080-becb-11eb-89fa-8bc4012e815a.png)

**Comment by P3rceval** [comment]
Une migration passée en prod et pas en dev ? (Je laisse le sujet à Nico)

**Comment by nmrgt** [comment]
Effectivement

**Comment by margot-sanchez** [comment]
Testé sur la dev le 07/06/2021 👎  avec un compte super admin

**Comment by nmrgt** [comment]
c'est fixé en dev

**Comment by margot-sanchez** [comment]
Testé le 10/06/2021 sur dev 👍
