### ISSUE TITLE
Disparition choix opérateur - export

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1289]
### Sujet

Le choix des opérateurs a disparu mystérieusement des fonctionnalités d'export.
![image](https://user-images.githubusercontent.com/15428433/111137122-b987f280-857e-11eb-8fdb-34400bae41f0.png)
 

### Environnement

Environnement : dev et prod
Navigateur : chrome
Utilisateur : utilisateur pouvant faire un export
URL : https://app.dev.covoiturage.beta.gouv.fr/trip/export et https://app.covoiturage.beta.gouv.fr/trip/export

### Etapes pour reproduire

1. _Je clique sur export

### Comportement attendu

1. _Je clique sur export j'ai une liste des opérateurs à sélectionner. 

### Comportement actuel

1. Disparition

**Comment by jonathanfallon** [comment]
Ça doit être un soucis de permissions dans le front qui n'est pas adapté au nouveau système. Je vais corriger ça

**Comment by margot-sanchez** [comment]
Testé le 16/04/2021 c'est toujours pas résolu.

**Comment by margot-sanchez** [comment]
Testé le 5/05/2021 sur dev : 
- profil super admin 👍 
- profil territoire 👍
