### ISSUE TITLE
Campagne - Pas de champs pour définir montant de l'incitation 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#129]
Je vais définir une politique basée sur la distance.
![image](https://user-images.githubusercontent.com/15428433/56602784-89d44800-65fe-11e9-9416-082287701302.png)
Mais au moment du lancement de la campagne je ne peux pas rentrer de montant et d'ailleurs je ne vois pas les paramètres.
![image](https://user-images.githubusercontent.com/15428433/56602745-7cb75900-65fe-11e9-8e9a-0ff3307a38f4.png)

**Comment by samueleyre** [comment]
parKM n'est pas un bon nom de variable. Ce sera corrigé dès que la pull-request [#122](https://github.com/betagouv/preuve-covoiturage/pull/122) est acceptée.
