### ISSUE TITLE
Améliorer le retour d'erreur en cas de non réponse de l'API entreprise

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1294]
### Sujet

Impossible mise à jour d'un territoire, erreur back 

### Environnement

Environnement : prod
Navigateur : chrome
Utilisateur : super admin
URL : https://app.covoiturage.beta.gouv.fr/admin/all-territories

### Etapes pour reproduire

1. _Je clique sur le territoire Occitanie 
2. _Je rentre la valeur 20005379100014 dans le champs SIRET et je clique sur Mise à jour. 
3. J'ai une erreur. 

![image](https://user-images.githubusercontent.com/15428433/111449429-aeb09780-870f-11eb-8c4e-400d59a61220.png)

**Comment by nmrgt** [comment]
Je viens de tester

![image](https://user-images.githubusercontent.com/17193937/111452346-b6be0680-8712-11eb-9271-193c2a4bae2d.png)

Je n'ai pas eu de problème. Je pense que l'API entreprise n'a pas répondu et c'est pourquoi tu as eu l'erreur.

**Comment by nmrgt** [comment]
c'est réparé
