### ISSUE TITLE
Rajouter la couleur bleu sur les statistiques sur l'environnement de dev. 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#13]
Sur la version staging  https://app-staging.covoiturage.beta.gouv.fr/statistics il y a la couleur bleu et c'est plus visuel selon moi.
![image](https://user-images.githubusercontent.com/15428433/55421909-b5718e80-557a-11e9-8b96-42607ee01298.png)
Sur https://pdc-dashboard-dev.scalingo.io/statistics c'est plus fade.
![image](https://user-images.githubusercontent.com/15428433/55421969-da660180-557a-11e9-9f1e-715ac52c6777.png)

**Comment by margot-sanchez** [comment]
@samueleyre deux questions : 

- Pourquoi avoir mis 2 statistiques et non plus 3 ?
- Pourquoi la taille de la police a baissé ? 

Ok pour la couleur sinon.

**Comment by samueleyre** [comment]
Le code est en commun avec les statistics spécifique à l'AOM, pour avancer vite j'ai fais quelque chose qui fonctionne sur les deux ce qui implique une nouvelle organisation de l'affichage des cartes.

**Comment by margot-sanchez** [comment]
Ok :) 
Je ferme alors et on ferra une passe design bien plus tard dessus
