### ISSUE TITLE
Volet indicateurs app.covoiturage.beta.gouv.fr/trip/stats

### ISSUE THREAD

**Issue by lauriebequet** [betagouv/preuve-covoiturage#1301]
### Sujet

Amélioration du volet indicateur du RPC = indiquer plus de données par mois quand on clique sur le mois.

Quand je clique sur le "mois" via le graphique en bâtons, j'aimerais accéder à plus de données, les mêmes que l'on a sur l'année :
- trajets réalisés / mois (déjà présent via le graphique en bâtons) ;
- km parcourus / mois ;
- essences économisées / mois ; 
- CO2 économisé / mois ; 
- nombre de covoitureurs ; 
- nombre de personne par véhicule.

Comportement attendu : 
1- Je clique sur un mois du graphique en bâtons
2- actualisation de la page avec les données sur le mois

**Comment by margot-sanchez** [comment]
Doublon tickets stats
