### ISSUE TITLE
idée amélioration plateforme en accès territoire

### ISSUE THREAD

**Issue by lauriebequet** [betagouv/preuve-covoiturage#1307]
### Sujet

Bonjour l'équipe, 

👇 Voici une idée d'amélioration produit. 👇
Afin de générer plus de connexions sur app.covoiturage.beta.gouv.fr et susciter des lancements de campagnes d'incitation => mettre en place un module "actualité / flash info" permettant à un territoire depuis son "espace / compte" de visualiser un exemple d'incitations en cours. 

_Exemple : "Le Pays de la Loire expérimente une campagne d'incitation jusqu'en xxx. Les premiers résultats sont très encourageants. En savoir plus"_

🚀 Objectifs : 
* inspirer les territoires 
* susciter l'envie de se lancer 
* montrer qu'il se passe des choses / montrer "l'exemple" 
* générer + de trafic sur https://app.covoiturage.beta.gouv.fr/ 

🎯 Cible : territoire partenaire du registre

**Comment by jonathanfallon** [comment]
Merci @lauriebequet c'est une super idée, on en discutera ensemble.

Je la déplace dans notre rubrique :bulb: idées des discussions.
