### ISSUE TITLE
Ajouter filtres par AOM et OPERATEUR pour les incentives

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#131]
* [x] operateur : filtrer par rapport à operateur
* [x] aom : filtrer par rapport à aom et retirer infos personnels ( target )

**Comment by margot-sanchez** [comment]
@samueleyre  Je ne comprends pas. C'est en tant que super admin ? Ou bien c'est un filtre dans les politiques incitatives ?
