### ISSUE TITLE
Collecte des dates d'inscription sur la plateforme/application de covoiturage

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#132]
IDF M soulève un besoin intéressant : **faire remonter dans le registre les dates d'inscriptions des utilisateurs sur une plateforme/application de covoiturage.** 

Les finalités sont doubles : 

1. Lutte contre la fraude. Une personne qui covoiturait avant la mise en place de la politique à moins de probabilité de frauder.
2. Pouvoir faire des statistiques et annonces exemple "depuis le lancement de notre opération, nous avons 1000 nouveaux inscrits et bénéficiaires par mois".

J'ai clairement dit qu'on ne pourrait jamais le mettre en oeuvre d'ici le lancement de l'expérimentation mais que la demande était intéressante. Je pense notamment que c'est super pertinent pour notre accès opendata. 

Questions : 
- [x] Est-ce intéressant d'avoir cette information ? 
- [x] A-t-on le droit de collecter cette information ? Quelles sont les règles à respecter ?
- [x] A-t-on le droit d'exposer cette information ? Quelles sont les règles à respecter ?
- [ ] Quid des opérateurs qui ne gèrent pas de manière homogène leur base client. Par exemple chez un opérateur j'ai a minima 3 comptes avec 3 dates d'inscription différentes et pourtant le même ID.

**Comment by ThomasMenant** [comment]
Hello,

Je trouve l'idée intéressante, s'agissant des questions "juridiques" :

A-t-on le droit de collecter cette information ? Quelles sont les règles à respecter ?
Rien ne nous empêche (en droit) de la collecter.
Même règle que pour le reste, s'assurer de sa confidentialité et de contrôler les accès.

A-t-on le droit d'exposer cette information ? Quelles sont les règles à respecter ?
Réponse de "normand" : 
- en droit pur : nous pourrions exposer cette info à peu près normalement, à condition que les informations communiquées n'identifient pas les personnes qui ont covoituré. Vu de ma fenêtre, une date de création de compte, un point de départ, un point d'arrivée, reste propre, notamment si on supprime l'opérateur où le compte a été créé.

- en droit appliqué au Registre (philosophie générale) : nous pourrions soit afficher cette information avec le reste (point de départ et d'arrivée), soit travailler sur une agrégation pour les AOM, par exemple avec un affichage suivant un range de dates.

**Comment by margot-sanchez** [comment]
C'est un non pour l'instant. Le ticket est archivé.
