### ISSUE TITLE
Processus de réception des trajets dans le passé

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1323]
### Sujet

Suite du ticket #1313 . Spécifier et définir le processus de réception des trajets dans le passé.  

@jonathanfallon & @nmrgt  merci de compléter le comportement actuel ci-après.

### Comportement actuel

Je suis un opérateur et je fais parvenir un trajet dont la date de réalisation est supérieure à 5 jours.
Le trajet est accepté mais catégorisé comme expiré. 
Comment se matérialise cette expiration ? 

- Campagne : le trajet n'est pas dans la moulinette
- Export : le trajet est exporté, il n'y a pas de colonne status dans l'export
- Front : le back envoi le status du trajet
- Communication : pas de retour d'api special lors de l'envoie mais status accessible via la route dédiée

### Comportement attendu

- Campagnes : le trajet ne passe pas dans la moulinette des campagnes 💹 
- Export : le trajet est à exporter --> ajouter une colonne statut
- Front : le trajet est-il visible dans le front avec un statut associé (cf : les filtres statut) 
- Communication : statut accessible via la route dédiée ✅

**Comment by nmrgt** [comment]
- campagne : le trajet n'est pas dans la moulinette
- export : le trajet est exporté, il n'y a pas de colonne status dans l'export
- front : le back envoit le status du trajet
- communication : pas de retour d'api special lors de l'envoie mais status accessible via la route dédiée

**Comment by jonathanfallon** [comment]
Je valide l'approche ci-dessus. On garde, on affiche mais on ne prend pas en compte pour le calcul des incitations.

**Comment by margot-sanchez** [comment]
Le ticket a été spécifié. Je le retire du sprint pour pouvoir finaliser le sprint actuel. On le repriorisera plus tard.
