### ISSUE TITLE
Liste des campagnes en cours

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1324]
### Sujet

Mettre les campagnes terminées en fin de liste et non avant celles en brouillon. 
![image](https://user-images.githubusercontent.com/15428433/115051749-73a3ae80-9edd-11eb-80bf-ae05bf10f320.png)

### Environnement

Environnement : prod
Super admin
URL : https://app.covoiturage.beta.gouv.fr/campaign/list

### Etapes pour reproduire / vérifier la bonne implémentation de l'amélioration

1. _Je vais sur la liste des campagnes. 

### Comportement attendu

1. _Une priorisation 1) en cours 2) en brouillon 3) terminées 
En tant que super admin je veux surtout voir ce qu'il se passe en ce moment et les campagnes en brouillon pour aller ensuite conseiller / accompagner. 

### Comportement actuel

1. _Une priorisation 1) en cours 2) terminées 3) en brouillon

**Comment by jonathanfallon** [comment]
Nouvel ordre des campagnes :

`dashboard/src/app/modules/campaign/pages/campaign-admin-list/campaign-admin-list.component.ts`
```typescript
    CampaignStatusEnum.VALIDATED,
    CampaignStatusEnum.PENDING,
    CampaignStatusEnum.DRAFT,
    CampaignStatusEnum.ENDED,
    CampaignStatusEnum.ARCHIVED,
```
