### ISSUE TITLE
Filtre par commune 

### ISSUE THREAD

**Issue by lauriebequet** [betagouv/preuve-covoiturage#1326]
### Sujet

Lorsque je suis un territoire, le filtre par commune ne fonctionne plus : après avoir cliquer sur « appliquer » = les statistiques ne changent pas. Alors que pour les autres filtres, ça fonctionne sans problème

### Environnement

Environnement : partout
Navigateur : chrome
Utilisateur : découverte, consultation, admin - territoire
URL : https://app.covoiturage.beta.gouv.fr

### Etapes pour reproduire

- https://app.covoiturage.beta.gouv.fr/
- Affiner les résultats 
- Sélection d'une ville dans le filtre 
- Appliquer
- Aucun changement

### Comportement attendu

1. _ Je sélectionne dans le filtre la commune pour voir les stats propres à cette commune
2. _ J'ai les données de cette commune dans l'onglet "chiffres clés" et "liste détaillée"

### Comportement actuel

1. _Je clique sur ... -> appliquer le filtre par commune
2. _ Pas de mise à jour des données dans chiffres clés et liste détaillée

**Comment by jonathanfallon** [comment]
Le bug vient du paramètre `territory_id`.

Cas 1 : Pas de filtre de ville
- `territory_id` n'est pas envoyé au backend. Le middleware applique l'ID du territoire connecté pour filtrer les résultats.

Cas 2 : filtre de ville
- on envoie un `territory_id: [1234]` pour limiter les résultats à ce territoire (ville) précis
- le middleware conserve la valeur de `territory_id` qui est présente malgré que `context.call.user.territory_id` soit différent. L'option `preserve: true` est passée au middleware
- `has_permission.by_scope` bloque l'accès [dans ce test ligne 46](https://github.com/betagouv/preuve-covoiturage/blob/2a9e0ffa4012246311ee6584307eb2fd1eb51cef/api/providers/middleware/src/HasPermissionByScope/HasPermissionByScopeMiddleware.ts#L46) car on a ces valeurs par exemple : `335 === [20891]`

Peut-on changer le nom du paramètre de filtre par ville pour ne pas utiliser `territory_id` et fusionner les valeurs dans l'action pour scoper correctement la recherche ?
J'ai l'impression qu'il faut dissocier l'application de la permission par groupe et le scoping par territoire.

**Comment by margot-sanchez** [comment]
Testé le 30/04/2021 👍
