### ISSUE TITLE
🔥 Affichage campagne - liste détaillée + Export

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1327]
### Sujet

Je suis un territoire, je vais sur les "trajets" et je souhaites filtrer sur une campagne, dans les résultats je m'attends à avoir :
Les trajets incités sur la campagne, c'est à dire uniquement ceux qui ont été incités en fonction des critères, donc incitation >0€ ;

### Environnement

Environnement : prod
Utilisateur : super admin + territoire
URL : https://app.covoiturage.beta.gouv.fr/trip/stats

### Comportement attendu

1. _Uniquement les trajets incités.

### Comportement actuel

1. _L'ensemble des trajets qui sont passés dans la moulinette mais pas forcement que ceux qui ont eu une incitation. Donc on peut avoir par exemple des trajets Megacovoit à 0€, alors que la campagne est que pour Maxicovoit. Cela permet ainsi de prendre conscience qu'il y a un intérêt d'élargir les critères.

**Comment by margot-sanchez** [comment]
Ceci est finalement bien un sujet de back. Il faut que cela soit valable dans les exports aussi.

**Comment by margot-sanchez** [comment]
Ticket impossible à tester sur dev.

Aucune campagne donnant lieu à des incitations (pas de nouveaux trajets sur dev).

**Comment by nmrgt** [comment]
@P3rceval on peut fermer ce ticket ?
