### ISSUE TITLE
Suppression DNS caduques 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1329]
### Sujet

Supprimer les entrées DNS
api-demo
api-staging
api-audit

Ping @jdauphant lorsque c'est réalisé.

**Comment by jonathanfallon** [comment]
api-demo et api-audit supprimés. api-staging est encore déployé chez Scalingo pour le moment.
le 404 sur le statut de Julien est lié au fait que la route / n'existe pas en GET.
