### ISSUE TITLE
Amélioration du moteur de calcul 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1333]
### Sujet

Exemples d'AOM qui ont des campagnes avec des spécificités : 

- De ne pas inciter des trajets intra à une zone (intra muros à Paris / intra muros à Nantes Métropole, Le Mans, Angers, etc.) ;
- De ne pas inciter des trajets dont le point de départ ou d'arrivée n'est pas sur votre région ; 
- De ne pas inciter les trajets de classe A ;
- Incitation en fonction du nombre de km.

Un conducteur peut tout à faire prendre plusieurs passagers et donc on a plusieurs trajets (couples passager / conducteur). Les données relatives à ces couples peuvent être différentes, un identifiant conducteur et un identifiant du voyage nous permettent de regrouper les couples dans un même véhicule. Il est tout à fait possible qu'un couple et donc son trajet ne soit pas éligible en fonction de vos critères mais que le reste des couples le soit. 

## Cas d'usage 1) Un couple conducteur 1 / passager 1 intra à une zone (non éligible) et un couple conducteur 1 / passager 2 sortant dans la zone (donc éligible). 
Exemple : un trajet passager Saint-Herblain (44) -> La Chapelle-sur-Erdre (44) et un trajet passager Saint-Herblain (44) -> Nozay (44) avec le même conducteur. 
L'incitation étant calculée au bénéfice du conducteur :
👍 **Comportement souhaité : uniquement inciter le trajet Saint-Herblain (44) -> Nozay (44)**
👎 Comportement actuel : prendre en compte le trajet Saint-Herblain (44) -> La Chapelle-sur-Erdre (44) (intra Nantes Métropole) 

## Cas d'usage 2 ) Un couple conducteur 1 / passager 1 qui sort de la Région (non éligible) et conducteur 1 / passager 2 intra à la Région (éligible)
Exemple : un trajet passager Fontainebleau -> Nemours et un trajet passager Fontainebleau -> Montargis
L'incitation étant calculée au bénéfice du conducteur
👍 **Comportement souhaité uniquement inciter le trajet Fontainebleau -> Nemours**
👎 Comportement actuel prendre en compte le trajet Fontainebleau -> Montargis

## Cas d'usage 3) Un couple conducteur 1 / passager 1 de classe A (non éligible) et conducteur 1 / passager 2 de classe B (éligible)
Ce cas est vraiment rare, nous avons eu une seule occurrence sur plus de 100 000 trajets. Doit-on :
uniquement inciter le trajet de Classe B ;
👍 **Comportement souhaité uniquement inciter le trajet de classe B**
👎 Comportement actuel : Prendre le mieux disant et donc s'il y a un classe B au milieu de A on applique l'incitation sur les deux couples

## Cas d'usage 4) Un couple couple conducteur 1 / passager 1 de 15km (éligible) et un couple conducteur 1 / passager 2 de 40km (éligible)

- Incitation totale de 1,5€+4€=5,5€ 
             - couple conducteur 1 / passager 1 : 2,25€ ;
             - couple conducteur 1 / passager 2 : 2,25€.
 - Incitation totale de 1,5€+4€=5,5€ 
             - couple conducteur 1 / passager 1 : 5,50€ ;
             - couple conducteur 1 / passager 2 : 0€.
- Incitation totale de 1,5€+4€=5,5€ 
             - couple conducteur 1 / passager 1 : 1,5€ ;
             - couple conducteur 1 / passager 2 : 4€.
- Incitation totale de 4€+4€=8€ 
             - couple conducteur 1 / passager 1 :4€ ;
             - couple conducteur 1 / passager 2 : 4€.
- Incitation totale de 4€+4€=8€ 
             - couple conducteur 1 / passager 1 :8€ ;
             - couple conducteur 1 / passager 2 : 0€.

👍 **Comportement souhaité idéalement** 
- Incitation totale de 1,5€+4€=5,5€ 
             - couple conducteur 1 / passager 1 : 1,5€ ;
             - couple conducteur 1 / passager 2 : 4€.
             
             Sinon à la limite ce scénario si trop difficile le premier       - couple conducteur 1 / passager 1 : 2,25€ ;
             - couple conducteur 1 / passager 2 : 2,25€.

**Comment by margot-sanchez** [comment]
Validé avec Pays de la Loire et IDFM

**Comment by nmrgt** [comment]
Supprimer la gestion du moteur d'incitation ?

**Comment by nmrgt** [comment]
@nicolas-viennot-beta on peut fermer ?

**Comment by nicolas-viennot-beta** [comment]
yes. je clos
