### ISSUE TITLE
🔥 Erreur affectation territoire - campagne

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1338]
### Sujet

Je suis super admin je vais dans la vision des campagnes. Je vois que Aix Marseille a fait une campagne. Je clique dessus et pourtant j'arrive sur une campagne de Nantes Métropole.

### Environnement

Environnement : dev
Navigateur : chrome
Utilisateur : super admin
URL : https://app.dev.covoiturage.beta.gouv.fr/campaign/60

### Etapes pour reproduire
Allez dans campagnes.
Cliquer sur la campagne A.
![image](https://user-images.githubusercontent.com/15428433/117141863-52810000-adaf-11eb-87de-7a2410480e6d.png)
![image](https://user-images.githubusercontent.com/15428433/117141957-747a8280-adaf-11eb-937e-ec9fa74c37a4.png)

**Comment by jonathanfallon** [comment]
ça ressemble à un bug de données sur le `dev`. Pas de soucis en local, ni en prod.
Les nouvelles campagnes créées ont le bon `territory_id`.

**Comment by margot-sanchez** [comment]
Testé sur dev le 19/05/2021 👎 
Je fais une campagne avec le compte d'IDFM et pourtant cela m'ajoute à Pierrevives (07)
![image](https://user-images.githubusercontent.com/15428433/118767252-cb875980-b87d-11eb-922d-40febae4c8fc.png)

**Comment by P3rceval** [comment]
Micro bug introduit sur ce commit assez récent 7078ae0e815c705e087e809dad44ee647ba078fd. (donc peut être pas encore en prod)

**Comment by margot-sanchez** [comment]
Testé le 26/05/2021 sur app.dev 👍
