### ISSUE TITLE
Lancement de campagne

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1340]
### Sujet

A spécifier et mettre dans le ticket sur la gestion des campagnes.

Aujourd'hui il est possible de lancer une campagne qui était dans le passé (en brouillon) et celle-ci va directement dans "passées" (en passant une demi seconde par en cours)

![image](https://user-images.githubusercontent.com/15428433/117154964-aa723380-adbc-11eb-9745-7150275c6e8d.png)
![image](https://user-images.githubusercontent.com/15428433/117155008-b3630500-adbc-11eb-8d2a-4ef2126b84a8.png)

Note : on ne sait pas l'année

**Comment by jonathanfallon** [comment]
TODO : vérifier les informations de la campagne avant de la lancer

**Comment by jonathanfallon** [comment]
- [x] Ajout d'une vérification au lancement de la campagne : la date de fin doit être dans le futur. La date de début, si elle est dépassée, est réactualisée au moment du lancement.
- [x] Ajout de messages pour l'utilisateur

### Campagne expirée (date de fin dépassée)

Utilisateur : Admin **et** Découverte

![image](https://user-images.githubusercontent.com/1656255/117173179-cc73b200-adcc-11eb-98db-2bb46723a1a0.png)

### Campagne en brouillon non expirée

Utilisateur : Admin

![image](https://user-images.githubusercontent.com/1656255/117173645-42781900-adcd-11eb-9c00-b096d1b4d0fb.png)

Utilisateur : Démo

![image](https://user-images.githubusercontent.com/1656255/117173686-4dcb4480-adcd-11eb-842d-961986ddf20b.png)

**Comment by margot-sanchez** [comment]
@jonathanfallon cela fait des trucs étranges. Cela rajoute + 1 an à la date de fin non ? 

![image](https://user-images.githubusercontent.com/15428433/117629742-c558f500-b17a-11eb-8a75-bdd10360831f.png)

**Comment by margot-sanchez** [comment]
Je ferme ce ticket parce que techniquement il est résolu. Même si cela a amené des problématiques autres j'ai l'impression genre #1371
