### ISSUE TITLE
🔥 Application des filtres date sur "trajets"

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1344]
### Sujet

Les filtres dates ne s'appliquent plus. Erreur 403. (503 en fait)

### Environnement

Environnement  : prod
Navigateur : chrome
Utilisateur : super admin
URL : https://app.covoiturage.beta.gouv.fr/trip/stats

### Etapes pour reproduire

1. _Je clique sur "affiner les résultats"
2. _Je rentre une valeur dans date de début et/ ou fin

![image](https://user-images.githubusercontent.com/15428433/118484836-f5267080-b717-11eb-829a-8bf1f508b036.png)

**Comment by nmrgt** [comment]
C'est du front : la requête ne passe pas la validation > question de date. Il faudrait griser les dates non sélectable pour des raisons métiers (5 jours de décalage)

**Comment by jonathanfallon** [comment]
C'est fixé et mergé en `dev` #1335 
Nécessite un déploiement en prod !

**Comment by margot-sanchez** [comment]
Non ce n'est pas réglé en dev. Testé le 18/05/2021 sur dev en tant que super admin.

Je mets des dates dont le delta est < 1an 👍 
Je mets des dates dont le delta est > 1 an 👎 

![image](https://user-images.githubusercontent.com/15428433/118605592-bdbad100-b7b6-11eb-8026-5d6b1569aee4.png)
La requête commence en Mai 2019 et pourtant les graphiques commencent en décembre 2019

**Comment by jonathanfallon** [comment]
OK, c'est un autre bug que celui adressé par #1335 par qui ne prend en compte que les 5 derniers jours

**Comment by margot-sanchez** [comment]
Le backend met en défaut 24 mois. Problème sur le timeout. 

- Souci 1 : timeout
- Souci 2 : que cela redirige vers une 503 (comportement de l'application)

**Comment by nmrgt** [comment]
il faudrait exclure la requete stats du middleware angular qui redirige vers la page 503 lorsque le serveur timeout

**Comment by margot-sanchez** [comment]
Testé le 27/05/2021 sur dev 👎 

Point positif je n'ai plus de 503. Point négatif je n'ai toujours pas le résultat désiré.
Exemple : je fais une requête à partir du 29 mai 2019. Cela ne fonctionne pas.
![image](https://user-images.githubusercontent.com/15428433/119844915-1ef64900-bf09-11eb-9004-f614948862c3.png)

**Comment by margot-sanchez** [comment]
Testé le 07/06/2021 sur dev 👍
