### ISSUE TITLE
🔥 Calcul du nombre de personnes par véhicule / équipage moyen

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1345]
### Sujet

Le calcul de l'équipage moyen est faux. (déplacer le +1 dans la formule).

Equipage moyen
Unité : personnes par véhicule

Il s’agit d’un indicateur représentant l’équipage moyen d’un covoiturage.
Cet indicateur tient également compte du nombre de sièges réservés par un passager.

Exemple : en considérant sur une période donnée 4 trajets (couple passager-conducteur).

Un trajet conducteur A / passager B (nombre de siège réservé = 1)
Un trajet conducteur A / passager C (nombre de siège réservé = 2)
Un trajet conducteur D / passager E (nombre de siège réservé = 1)
Un trajet conducteur D / passager F (nombre de siège réservé = 1)
L’indicateur est ((1+2)+(1+1))/2 = 2,5 passagers par véhicule d’où 3,5 personnes par véhicule

### Environnement

Environnement : prod
Navigateur : chrome

**Comment by margot-sanchez** [comment]
Testé sur la dev le 7/06/2021 👎

Sur un échantillon du 7/06/2020 au 31/07/2020 il y a 79 224 trajets (avec le seat number)  mais 21 563 trip donc 4,67 passagers / véhicule. Or la plateforme indique 
![image](https://user-images.githubusercontent.com/15428433/121018011-38678280-c79e-11eb-8a69-63396eb62a55.png)

**Comment by nmrgt** [comment]
avec le soucis de déploiement résolue et le cache vidé j'ai 2.01

**Comment by P3rceval** [comment]
Il doit manquer une sub querry pour le calcul de `average_carpoolers_by_car` Il faudrait faire un count sur la période demandée et pas au global comme actuellement :
```trunc(
          (((sum(passenger_seats)::numeric) / count(distinct trip_id))+1), 2
        )::float as average_carpoolers_by_car,```

**Comment by P3rceval** [comment]
@margot-sanchez comment obtiens-tu les 79 224 trajets ? 
Avec la BDD de dev sur la période que tu as indiqué, j'ai : 
- 21477 trajets (nombre de `trip_id` distinct)
- 43524 passagers (somme des sièges réservés par les passagers `passenger_seats`)

**Comment by nmrgt** [comment]
(ya des trajets qui étaient en double que j'ai viré suite à la résolution du ticket sur le journey-id vide)

**Comment by margot-sanchez** [comment]
Le 10/06/2021 sur dev 👍 

Du 1/07/2021 au 31/07/2021 10526 trajets (avec passenger seat) et 10 368 trip id donc 2,01 personnes / véhicule
