### ISSUE TITLE
🔥 Impossible modification d'un territoire (commune) 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1348]
### Sujet

Je suis super admin, je souhaite mettre à jour une commune pour par exemple indiquer qu'elle est partenaire, etc. J'ai beau compléter l'ensemble des champs obligatoires, le bouton mettre à jour reste grisé. 

### Environnement

Environnement  : dev
Navigateur : chrome
Utilisateur : super admin
URL : **https://app.dev.covoiturage.beta.gouv.fr/admin/all-territories**

### Etapes pour reproduire

1. _Je clique sur un territoire et je fais éditer
2. _Je rentre des valeurs ou en modifie

![image](https://user-images.githubusercontent.com/15428433/118768029-caa2f780-b87e-11eb-9921-c462c446dca2.png)
![image](https://user-images.githubusercontent.com/15428433/118768065-d7275000-b87e-11eb-92ae-73dc0748a7b3.png)

### Comportement attendu

1. _Lorsque les champs obligatoires sont complétés, possibilité d'appuyer sur le bouton mettre à jour. 

### Comportement actuel

1. _Le bouton reste grisé

**Comment by jonathanfallon** [comment]
Le soucis vient de la règle de validation qui n'est pas explicitée.
Ce module mérite une refonte qui sera abordée dans le chantier territoire (2021).
En attendant, j'ai ajouté un message d'erreur pour guider l'utilisateur.

![image](https://user-images.githubusercontent.com/1656255/119122396-c289ba00-ba2e-11eb-8752-d581e6e9db3b.png)

**Comment by margot-sanchez** [comment]
Testé le 26/05/2021 sur dev 👎 . Je clique donc sur contours géographique (sans modification) puis je fais mes modifications sur le territoire en tant qu'entreprise, mais impossible de mettre à jour. Erreur 400

![image](https://user-images.githubusercontent.com/15428433/119687269-5997ad00-be47-11eb-91c2-5f91290d48a6.png)

**Comment by margot-sanchez** [comment]
Testé le 07/06/2021 sur dev 👎

**Comment by P3rceval** [comment]
Problème de validation au niveau des schema (champ 'geo' attendu)

**Comment by nmrgt** [comment]
ok je prends

**Comment by nmrgt** [comment]
fixé sur dev

**Comment by margot-sanchez** [comment]
Testé le 10/06/2021 sur dev 👍
