### ISSUE TITLE
Remettre à jour la branche feat/stat

### ISSUE THREAD

**Issue by P3rceval** [betagouv/preuve-covoiturage#1350]
Repartir de la branch feat/stats : 

- [x] Réparer la page /stats publique
- [x] Fonctionnalité des pages de statistiques doivent être à minima iso avec l’environnement de démo
- [x] Faire un responsive correct
- [ ] Ajout de tests

**Comment by jonathanfallon** [comment]
#1373 mergée.

**Comment by margot-sanchez** [comment]
Tests réalisés le 14/06/2021 sur dev. 

- Lors de l'ajout d'un filtre les informations graphiques (bleu foncé) indiquant qu'il s'agit de trajets incités disparaissent.

**Comment by margot-sanchez** [comment]
J'adore l'effet de téléchargement <3

**Comment by margot-sanchez** [comment]
J'ai vu que tu as mis les trajets incités sur la page publique /stats. On avait pas parlé de ça mais finalement je trouve ça cool :)
