### ISSUE TITLE
Sur le dashboard, afficher une période de 14 jours par défaut lorsque la périodicité "jour" est sélectionnée

### ISSUE THREAD

**Issue by P3rceval** [betagouv/preuve-covoiturage#1362]
Sans filtres - Par défaut :

Affichage des 14 derniers jours.

Supprimer également le filtre de jour de la semaine

**Comment by P3rceval** [comment]
@margot-sanchez J'trouve ça un peu déroutant comme comportement dans ce cas : 
1. L'utilisateur arrive sur la page avec les 12 derniers mois par défaut mais il n'y a que les 5 premiers mois avec des trajets  
2. Il change la temporalité à "Jour" et on obtient "Aucun trajet n'a été réalisé sur cette période." à cause des 14 derniers jours chargés par défaut :thinking: 

J'ai pas d'idée sur comment faire comprendre à l'utilisateur qu'on l'a basculé sur 14 jours et que c'est la raison pour laquelle il ne voit rien ... 

Si c'est un besoin territoire, est-ce qu'on rajouterai pas un bouton "Voir les 14 derniers jours" plutôt ?
Qu'en penses tu ?

**Comment by margot-sanchez** [comment]
Très bonne réflexion. En fait c'est exactement ce comportement qui me saoule aujourd'hui quand on a pas de trajets on a un smiley confused indiquant qu'il n'y a pas de trajets mais en fait il y en a mais pas sur la dernière semaine. 

C'est pour ça que tu avais proposé le Zoom / Dezoom non ? 

On peut pas avoir des flèches pour revenir en arrière et naviguer ?

**Comment by margot-sanchez** [comment]
Au final j'aime bien ce que tu as fait sur dev. Je me demande si cela sert à quelque chose de faire le truc "par défaut". Si la personne veut que cela soit plus claire. Il lui suffit d'aller filtrer plus spécifiquement

**Comment by margot-sanchez** [comment]
J'ai vu que tu as mis les trajets incités sur la page publique /stats. On avait pas forcement parlé de ça mais finalement je me dis que c'est une bonne chose.

**Comment by margot-sanchez** [comment]
Solution : on laisse le soin aux personnes d'appliquer des filtres si elles veulent améliorer la lisibilité.
