### ISSUE TITLE
Message d'erreur - information -> disparition

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1367]
### Sujet

Je suis un utilisateur de la plateforme, je réalise une action et un message d'information devrait apparaitre. Celui-ci n'est plus visible (caché en haut de l'écran).
![image](https://user-images.githubusercontent.com/15428433/119686916-11788a80-be47-11eb-83e1-b6d1f13c023a.png)

D'une manière général même le spinner s'est décalé vers le haut aussi. 

### Environnement

Environnement : dev
Navigateur : chrome

**Comment by P3rceval** [comment]
Erreur due à la fonction d'optimisation d'angular pour tous les environnements où elle est activée (dev et prod). Le CSS pour toats-container devient `.toast-container{pointer-events:none;position:fixed;z-index:#999}` au lieu de `.toast-container{pointer-events:none;position:fixed;z-index:999999}`

**Comment by margot-sanchez** [comment]
Teste lé 10/06/2021 sur dev
