### ISSUE TITLE
Simulation impossible sur une ancienne campagne

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1370]
### Sujet

_Je suis un territoire. Je souhaite relancer une ancienne campagne. Je vais dans mes campagnes passées. J'ai un message m'indiquant que si je souhaite la relancer il me faut modifier les dates. Je modifie les dates et je souhaite voir la simulation. Rien ne se passe. Le spinner tourne et pas de message d'information. 

Pistes : 
- Parce que pas de data dans les 3 derniers mois ? --> dans ce cas mettre un message d'information 
- Parce que c'est un mauvais parcours d'aller dans une ancienne campagne pour en relancer une nouvelle ? --> dans ce cas bloquer ce parcours.

A étudier et spécifier pour voir si c'est un bug urgent (qui est partout) ou juste une erreur de parcours. 

### Environnement

Environnement : dev
Navigateur : chrome
Utilisateur : admin territoire
URL : https://app.dev.covoiturage.beta.gouv.fr/campaign/edit/359?section=1

### Etapes pour reproduire

1. _Je clique sur une ancienne campagne terminée
2. _Je rentre de nouvelles valeurs pour la date de début et de fin

![image](https://user-images.githubusercontent.com/15428433/119786100-1e8d8c00-bed0-11eb-940a-6f1e3aec1b92.png)

**Comment by P3rceval** [comment]
@margot-sanchez, il y a un spinner (et une erreur) parce qu'il n'y a pas de méthode de calcul de rétribution pour cette campagne. 
Pour information après quelques tests : 
- la copie d'une campagne efface bien seulement les dates et garde la partie rétribution.
- je n'arrive pas à reproduire; Je ne sais pas comment une campagne a pu se retrouver dans cet état, puisque pour arriver à la simulation il faut forcément avoir renseigné une méthode de calcul de rétribution.

Si tu n'arrives pas non plus à reproduire, je pense qu'on peut fermer ce bug...

**Comment by margot-sanchez** [comment]
J'arrive à le reproduire facilement sur l'ensemble des anciennes campagnes. Il y a bien des rêgles de calculs en front (peut-être pas en back).

**Comment by margot-sanchez** [comment]
Lié au #1371

**Comment by margot-sanchez** [comment]
Testé le 10/06/2021 sur dev 👍
