### ISSUE TITLE
🔥 Suppression de la possibilité de modifier un contour géographique

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1375]
### Sujet

_Je suis super admin, je souhaite modifier un territoire, j'ai la possibilité de le faire via les contours géographiques. 

Constats : 
- Si je sais faire ça c'est que je suis dev, donc pas d'intérêt à le faire en front 
- Une super admin lambda ne sait pas faire ça et surtout cela ouvre la possibilité de faire des erreurs.

Solution : supprimer en front c'est possibilité et s'assurer que tout est ok (par exemple la possibilité de mettre à jour une commune)

### Environnement

Environnement : partout
Utilisateur : super admin
URL : https://app.dev.covoiturage.beta.gouv.fr/admin/all-territories

### Etapes pour reproduire / vérifier la bonne implémentation de l'amélioration

1. _Je clique sur éditer un territoire dans l'interface administration. 

![image](https://user-images.githubusercontent.com/15428433/119834505-4eed1e80-bf00-11eb-9327-89e4b47fa2f6.png)

**Comment by P3rceval** [comment]
@margot-sanchez est-ce qu'on enlève bien la possibilité du contour géographique pour la création d'un territoire également ?

**Comment by margot-sanchez** [comment]
Testé le 07/06/2021 sur dev 👍
