### ISSUE TITLE
🔥 Incohérence département & code INSEE

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1387]
### Sujet

Je suis un super admin je télécharge un jeu de données issue du RPC. Je constate que les trajets en provenance ou à destination de Boulogne Billancourt et Issy les Moulineaux sont associés au département 75, la ville de Elbeuf dans le 76 est rattaché au 27.

### Environnement

Environnement : prod
Navigateur : chrome
Utilisateur : super admin

### Etapes pour reproduire

1. _Je clique sur export
2. _J'ouvre le fichier dans un tableur, je filtre sur Boulogne et Issy et constate : 
Boulogne code INSEE 92012 / code postal 75016
Issy code INSEE 92040 / code postal 75015

Idem Elbeuf code INSEE 76231 code postal 27 370

### Comportement attendu

1. _Département 92

### Comportement actuel

1. _Département 75

**Comment by margot-sanchez** [comment]
Depuis 1968 le code insee de Boulogne a géchan https://www.insee.fr/fr/metadonnees/cog/commune/COM75012-boulogne-billancourt

**Comment by nmrgt** [comment]
C'est un problème de synchronisation de données.

**Comment by margot-sanchez** [comment]
Phase 1 ) Hotfix
Phase 2) chantier territoire

**Comment by P3rceval** [comment]
Correction des trip.list via :  
--- Elbeuf (76) ---
UPDATE trip.list SET journey_start_department = '76', journey_start_postalcode = '76231' WHERE start_territory_id = 14485; 
UPDATE trip.list SET journey_end_department = '76', journey_end_postalcode = '76231' WHERE end_territory_id = 14485;

--- Boulogne-Billancourt (92) ---
UPDATE trip.list SET journey_start_department = '92', journey_start_postalcode = '92012' WHERE start_territory_id = 19783;
UPDATE trip.list SET journey_end_department = '92', journey_end_postalcode = '92012' WHERE end_territory_id = 19783;

--- Issy-les-Moulineaux (92) ---
UPDATE trip.list SET journey_start_department = '92', journey_start_postalcode = '92040' WHERE start_territory_id = 18764;
UPDATE trip.list SET journey_end_department = '92', journey_end_postalcode = '92040' WHERE end_territory_id = 18764;

Suppression de mauvais/anciens codes postaux :  
DELETE from territory.territory_codes tc where tc._id IN (select tc._id
	from territory.territory_codes tc 
	left join territory.territories tt on tc.territory_id = tt._id 
	where tc.type = 'postcode' and SUBSTRING(tt.name, length(tt.name) - 2, 2) != SUBSTRING(tc.value,1, 2))

**Comment by margot-sanchez** [comment]
Testé le 05/07/2021 sur la prod 👍
