### ISSUE TITLE
Action logger

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#139]
Logguer toutes les actions utilisateurs pour assurer la traçabilité de la modification des données.

Voir `request_id` dans #333

**Comment by nmrgt** [comment]
- 1 an

**Comment by nmrgt** [comment]
voir #333

**Comment by nmrgt** [comment]
En attente de réponse de la part de DINSIC
@jonathanfallon

**Comment by nmrgt** [comment]
Utiliser le request_id généré par l'hébergeur (reverse-proxy) dans les metadonnées du channel pour suivre les requêtes entre les services et les logs.
