### ISSUE TITLE
Impossible sélection de plusieurs communes - moteur campagne

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1399]
### Sujet

_Je suis un territoire je souhaite lancer une campagne d'incitation en indiquant des trajets donnant lieu à des incitations. Je rentre un nom de commune mais ensuite la liste n'apparait plus.
![image](https://user-images.githubusercontent.com/15428433/122061347-b48d4600-cdee-11eb-8988-6303615beb29.png)

### Environnement

Environnement : dev -> prod
Navigateur : chrome
Utilisateur : territoire

### Etapes pour reproduire

1. _Je clique sur modifier une campagne en cours
2. Je rentrer une première commune puis je tente d'en rentrer une seconde

### Comportement attendu

1. Pouvoir rentrer plusieurs communes (idéalement même le com com)

**Comment by margot-sanchez** [comment]
J'ai ouvert à nouveau car c'est le ou la PO qui ferme les tickets. #dictature

**Comment by margot-sanchez** [comment]
Testé le 29/06/2021 sur dev 👎

**Comment by P3rceval** [comment]
Désolé, c'était pas déployé. (A cause du workflow github qui avait passé l'issue de In Progress à done ...)

**Comment by margot-sanchez** [comment]
Testé le 05/07/2021 sur dev 👍 
![image](https://user-images.githubusercontent.com/15428433/124484197-719a0f00-ddab-11eb-8426-3e48ea129e0a.png)
