### ISSUE TITLE
Connexion - majuscule / minuscule

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1405]
### Sujet

En tant que super admin, lors de la création d'un compte, je fais simplement un copier/coller du mail. Cependant, afin de simplifier la lecture des emails, il arrive que des personnes mettent des majuscules dans le mail. Exemple : thomas.ROMAIN@mail.com. Sauf qu'au moment de se connecter ils utilisent bien le mail standard thomas.romain@mail.com et cela ne fonctionne pas. 
Lors de la connexion au compte, un utilisateur doit pouvoir utiliser thomas.ROMAIN@mail.com comme thomas.romain ou ThOmas.Romain.

### Environnement

Environnement : prod
Utilisateur : tous
URL : https://app.covoiturage.beta.gouv.fr/login

### Etapes pour reproduire / vérifier la bonne implémentation de l'amélioration

1. _Je réalise une connexion avec des majuscules aléatoirement

### Comportement attendu

1. _Agnostique des majuscules / minuscules

### Comportement actuel

1. _Obligé de mettre ISO à ce qui a été configuré

**Comment by jonathanfallon** [comment]
Dans la spec c'est du _case-sensitive_ mais dans la pratique c'est _case insensitive_ ce qui est plus pratique au quotidien...
https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive?answertab=votes#tab-top

**Comment by P3rceval** [comment]
Pose également problème lors du reset de mot de passe : 
Si l'utilisateur s'est enregistré avec des majuscules, le reset de mdp ne marchera pas si l'utilisateur met tout en majuscules.
