### ISSUE TITLE
Ne pas inclure les trajets frauduleux dans les exports

### ISSUE THREAD

**Issue by P3rceval** [betagouv/preuve-covoiturage#1412]
Blocked by [1410](https://github.com/betagouv/preuve-covoiturage/projects/3#card-63581263)
- [ ] Ne pas inclure les trajets détectés comme incohérents dans les exports de données

**Comment by margot-sanchez** [comment]
Impossible à tester - les emails transactionnels ne partent plus. #1433

**Comment by nmrgt** [comment]
@nicolas-viennot-beta on peut fermer ?

**Comment by nicolas-viennot-beta** [comment]
oui good. je clos
