### ISSUE TITLE
Paramétrage S3 pour la durée de vie des exports open data et CNAME

### ISSUE THREAD

**Issue by P3rceval** [betagouv/preuve-covoiturage#1413]
- [ ] Utiliser le s3 public pour les export opendata
- [ ] Enregistrer un CNAME pour le S3 public & export

**Comment by nmrgt** [comment]
Problème de certificat ssl en dev. A corriger avant de fermer le ticket

**Comment by nmrgt** [comment]
C'est une limitation de l'hébergeur cf https://www.scaleway.com/en/docs/tutorials/s3-customize-url-cname/

**Comment by nmrgt** [comment]
après échange avec Julien, je ferme le ticket en attendant des éventuelles évolutions côtés provider.
