### ISSUE TITLE
Refaire les exports pour tous les mois

### ISSUE THREAD

**Issue by P3rceval** [betagouv/preuve-covoiturage#1414]
Blocked by [233](https://github.com/betagouv/preuve-covoiturage/issues/233)

- [x] Implémenter une commande qui permet de générer et pousser les exports sur le s3 en réutilisant la logique de [1410](https://github.com/betagouv/preuve-covoiturage/issues/1410)
- [x] Les exports doivent être repoussé avec la dernière version du format (Blocked by [1411](https://github.com/betagouv/preuve-covoiturage/issues/1411)
- [x] Vérifier l'intégrité des données (présence de trip_id et journey_id)
- [x] Archiver le changelog
- [ ] Supprimer les anciens exports opendata

**Comment by jonathanfallon** [comment]
On peut imaginer une batterie de tests qui tournerait sur le fichier CSV généré pour valider sa qualité avant upload sur le S3.
Pas forcément nécessaire pour les exports utilisateurs, mais peut-être bien pratique pour les exports open-data vers data.gouv.

**Comment by P3rceval** [comment]
> On peut imaginer une batterie de tests qui tournerait sur le fichier CSV généré pour valider sa qualité avant upload sur le S3.
> Pas forcément nécessaire pour les exports utilisateurs, mais peut-être bien pratique pour les exports open-data vers data.gouv.

J'imaginais plutôt des unit tests pour éviter d'avoir à maintenir des tests complexes type e2e
