### ISSUE TITLE
🔥 BUG - Paramètres de dates attestation covoiturage

### ISSUE THREAD

**Issue by AntoineGirard** [betagouv/preuve-covoiturage#1416]
### Sujet

Bonjour,

Les paramètres de dates ne sont pas pris en compte lors de la génération d’attestation de covoiturage.

Merci d’avance pour votre retour,

### Environnement

Environnement (dev, prod...) : DEMO API
Navigateur :
Utilisateur :
URL : https://api.demo.covoiturage.beta.gouv.fr/v2/certificates/pdf

### Etapes pour reproduire

Requête génération : 
```bash
curl --request POST \
  --url https://api.demo.covoiturage.beta.gouv.fr/v2/certificates \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer TOKEN' \
  --header 'Content-Type: application/json' \
  --data '{
	"tz": "Europe/Paris",
	"identity": {
		"phone_trunc": "+336000000",
		"operator_user_id": "UUID"
	},
	"start_at": "2017-01-01T00:00:00Z",
  "end_at": "2021-12-31T23:59:59Z"
}'
```

Réponse génération : 
```JSON
{
  "uuid": "UUID",
  "created_at": "2021-06-22T15:55:52.965Z",
  "meta": {
    "tz": "Europe/Paris",
    "rows": [],
    "total_km": 0,
    "total_rm": 0,
    "total_tr": 0,
    "total_point": 0
  }
}
```

Requête téléchargement

```
curl --request POST \
  --url https://api.demo.covoiturage.beta.gouv.fr/v2/certificates/pdf \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer TOKEN' \
  --header 'Content-Type: application/json' \
  --data '{
    "uuid": "UUID fourni lors de la génération",
    "meta": {
        "operator": {
            "content": "Attestation"
        },
        "identity": {
            "name": "Un covoit",
            "content": "Je suis un covoit"
        },
        "notes": "Notes"
    }
}
'
```

Réponse

![image](https://user-images.githubusercontent.com/12141434/122960796-123c0800-d384-11eb-9a6d-4a1ed52f7277.png)

### Comportement attendu

Période allant de "start_at": "2017-01-01T00:00:00Z" à "end_at": "2021-12-31T23:59:59Z".

### Comportement actuel

Voir screen

**Comment by hugobarthelemy** [comment]
Bonsoir @jonathanfallon & @P3rceval ,

Suite au fix et aux problèmes de performances, on a regardé le code et il semblerait qu'il n'y ait pas d'index sur le `driver_id` et le `passenger_id` de `trip.list` ce qui pourrait expliquer les problèmes de performance de la requête dans `CarpoolPgRepositoryProvider`. 

Pourriez-vous regarder cette piste svp ?

Cordialement,

Hugo

**Comment by ccyrille** [comment]
@P3rceval @charlesimone pourriez-vous nous confirmer qu'un fix a été poussé concernant les soucis de performances à la génération des attestations et si c'est le cas, nous dire si il est disponible en pré-production / en production ? Merci

**Comment by P3rceval** [comment]
Bonjour, 

Nous avons effectivement déployé la suggestion sur les index en demo et prod ([ici](https://github.com/betagouv/preuve-covoiturage/pull/1443))

**Comment by ccyrille** [comment]
@P3rceval Ok, merci de ton retour et pour ce fix ! 

On relance le projet d'intégration chez Klaxit. On vous tient informé de l'avancement.
