### ISSUE TITLE
Documentation - erreur 404 liens directs

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1417]
### Sujet

_Les liens de la documentation tech.covoiturage.gouv.fr pour se rendre directement dans une section renvoient des erreurs 404.

### Environnement

Environnement (dev, prod...) : prod
URL : https://tech.covoiturage.beta.gouv.fr/partners/preuves/schema.html

### Etapes pour reproduire

1. _Je clique sur tech.covoiturage.beta.gouv.fr
2. _Je vais dans Partners, je clique sur une section. Je fais actualiser ou copier / coller l'url
![image](https://user-images.githubusercontent.com/15428433/123052839-8e296500-d403-11eb-9d99-5ba0c9492a2e.png)

**Comment by jonathanfallon** [comment]
La doc a été mise à jour et /partners/ est maintenant /operateurs/
https://tech.covoiturage.beta.gouv.fr/operateurs/preuves/schema.html
