### ISSUE TITLE
Non remontée des informations DPO / Responsable traitement, etc

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1420]
### Sujet

Bug non bloquant mais chiant à mon sens et peut être symptomatique de problèmes plus profonds
_En tant que territoire, dans mon onglet administration je dois pouvoir voir les informations liées aux responsables traitement, DPO, responsable traitement. 

Dans l'exemple suivant les informations sont bien complétées sur l'interface super admin mais pas dans l'interface territoire. 

### Environnement

Environnement : dev
Navigateur : chrome
Utilisateur : territoire
URL : https://app.dev.covoiturage.beta.gouv.fr/admin/territory

### Etapes pour reproduire

1. _Je clique administration puis territoire

Je n'ai pas d'informations : 
![image](https://user-images.githubusercontent.com/15428433/123095057-ec6b3d80-d42d-11eb-9f04-0a973b7c1ea3.png)
Pourtant côté superadmin je confirme que les informations sont bien là.
![image](https://user-images.githubusercontent.com/15428433/123095121-ff7e0d80-d42d-11eb-94c2-71dcbb8a8845.png)

**Comment by jonathanfallon** [comment]
Pas reproduit sur Brave avec le territoire IDFM. Regarder du côté du store territory.
Proposition de faire un refacto de cette page pour la simplifier et ne pas utiliser le store. Faire des requêtes d'API en direct qui seront plus simples et plus robustes.

**Comment by P3rceval** [comment]
@margot-sanchez Peux-tu confirmer qu'un territoire avec le role admin peut également modifier ces informations ?

**Comment by margot-sanchez** [comment]
Testé le 12/07/2021 sur dev 👍 
![image](https://user-images.githubusercontent.com/15428433/125313664-bc7ccf00-e335-11eb-93e0-78e1b410a21a.png)
