### ISSUE TITLE
Ajout de `operator_journey_id` dans l'export des opérateurs

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1421]
Objectif : permettre aux opérateurs de faire le lien entre les preuves envoyées et celles exportées du Registre par le `operator_journey_id`.

:warning: `operator_journey_id` est appelé `journey_id` dans le payload d'acquisition !

**TODO**

- [x] ajouter la colonne dans la table `trip.list`
- [ ] mettre à jour les données existantes / flasher la table (très long)
- [ ] documenter l'export

DOC : https://hackmd.io/b_axgKveQHGcGoQUWAMwtQ

**Comment by P3rceval** [comment]
J'ai finalement ajouté les 3 champs (`operator_driver_id`, `operator_passenger_id`, `operator_journey_id`) pour tous les groupes (registre, operateur et territoire). 
L'export pour les territoires sert notamment pour les appels de fonds. Il est au final transmis aux operateurs pour justifier des montants (donc autant l'ajouter pour les territoires)

**Comment by P3rceval** [comment]
Testé sur dev :heavy_check_mark:
