### ISSUE TITLE
Fixer la génération de données dans les règles globales de campagnes

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1427]
Retour CodeQL
https://github.com/betagouv/preuve-covoiturage/security/code-scanning/178?query=ref%3Arefs%2Fpull%2F1398%2Fhead

**Comment by jonathanfallon** [comment]
Voir https://github.com/betagouv/preuve-covoiturage/pull/1428

**Comment by margot-sanchez** [comment]
Vous me disiez par le passé que mes tickets n'étaient pas clairs. Mais là pour une fois que je peux vous dire la même chose. Du coup je ne sais pas quoi tester.

**Comment by nmrgt** [comment]
On peut fermer, c'était un ticket pour enlever l'alerte du CodeQL.
