### ISSUE TITLE
🔥 Disparition des données - chiffres clefs

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1432]
### Sujet

_Les chiffres clefs sur la prod (peu importe l'utilisateur) ont disparu. Nb : la liste détaillée semble fonctionner. 

### Environnement

Environnement : prod
Navigateur : chrome
Utilisateur : super admin + territoire + opérateur
URL :  https://app.covoiturage.beta.gouv.fr/trip/stats

### Etapes pour reproduire

1. _Je clique sur "Trajets" puis "Chiffres clefs"

![image](https://user-images.githubusercontent.com/15428433/124560818-8626e780-de3d-11eb-815f-794a28af3e11.png)

**Comment by margot-sanchez** [comment]
C'est revenu à la normale au bout de quelques minutes. Investiguer pourquoi le worker tombe.

**Comment by nmrgt** [comment]
À priori le problème vient d'un bug sur le driver postgres: https://github.com/brianc/node-postgres/issues/1860

Le problème est qu'on ne peut pas mettre des variables d'environnement différente sur le worker chez scalingo pour enlever le timeout sur le worker comme c'est le cas en démo ou en dev.

J'ai fait une PR qui j'espère permettra de résoudre le problème. Elle n'est pas testable sans merge sur la prod du au limitations de l'hébergeur malheureusement.  #1438

**Comment by P3rceval** [comment]
@margot-sanchez je ne reproduis pas sur la prod en super-admin. Est-ce toujours le cas ?

**Comment by nmrgt** [comment]
@nicolas-viennot-beta on peut fermer ?

**Comment by nicolas-viennot-beta** [comment]
oui vu que pas de reproduction. Je clos
