### ISSUE TITLE
🔥 Plus d'envoi de mails transactionnels 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1433]
### Sujet

_Blocage de l'envoi des mails transactionnels (invitation, export, etc.) 

### Environnement

Environnement : prod
Navigateur : chrome
Utilisateur : tous

### Etapes pour reproduire

1. _Je réalise un export OU je fais une invitation pour un nouvel utilisateur.

**Comment by P3rceval** [comment]
Bug sur le worker. 
Lié à https://github.com/betagouv/preuve-covoiturage/issues/1432
Si @nmrgt ou @jonathanfallon vous avez une explication à ce qu'il s'est passé ?

**Comment by margot-sanchez** [comment]
Je réouvre cf mails.

**Comment by P3rceval** [comment]
Problème sur l'envoi d'emails pour des comptes avec des emails en majuscules (Réglé via support pour le moment), à corriger avec  https://github.com/betagouv/preuve-covoiturage/issues/1405
Bug sur la génération des exports réglé via https://github.com/betagouv/preuve-covoiturage/pull/1447

**Comment by P3rceval** [comment]
@margot-sanchez j'te laisse close si tout est OK
