### ISSUE TITLE
🔥 Non prise en compte des n° étranger

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1437]
### Sujet

_Les trajets réalisés par un utilisateur (passager, conducteur ou les 2) possédant un numéro de téléphone étranger ne passent pas dans le moteur de calcul d'incitation. 

### Environnement

Environnement : prod

### Comportement attendu

1. _Seuls les trajets caractérisés comme incohérents / frauduleux ne devraient pas passer dans le moteur.

**Comment by nmrgt** [comment]
Vérifier les trajets exclus de la campagne IDFM
