### ISSUE TITLE
Mise à jour graphique des trajets incités 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1440]
### Sujet

_Les trajets incités ne remontent pas comme incités (bleu foncé) automatiquement.
Ce problème est régulier. 

### Environnement

Environnement : prod
Navigateur : chrome
Utilisateur : super admin & territoire
URL : https://app.covoiturage.beta.gouv.fr/trip/stats

### Etapes pour reproduire

Plusieurs campagnes sont en cours et les trajets sur Juin incités devraient être plus important. Le mois dernier il avait fallu faire une manipulation pour mettre à jour.
![image](https://user-images.githubusercontent.com/15428433/124777084-3c72f580-df40-11eb-992f-61c6adb99105.png)
Il faut investiguer pourquoi il y a besoin d'une action manuelle.

**Comment by margot-sanchez** [comment]
![image](https://user-images.githubusercontent.com/15428433/125310827-3790b600-e333-11eb-9a8f-1b4f38f605cb.png)
Je réouvre car j'ai toujours le même problème. En super admin ou même avec des comptes de territoire par exemple sur Nantes Métropole (or il y a la campagne Pays de la Loire) : 
![image](https://user-images.githubusercontent.com/15428433/125310890-470fff00-e333-11eb-86e3-eb7a4948a27b.png)

**Comment by P3rceval** [comment]
Maybe problème lié aux acquisitions => https://github.com/betagouv/preuve-covoiturage/issues/1448
