### ISSUE TITLE
Ajout app.covoiturage.beta.gouv.fr sur dashlord

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1468]
### Sujet
Un dashLord est un tableau de bord. Il permet de situer sa Startup d'État ou de Territoires par rapport aux standards de qualité des services beta.gouv.fr : accessibilité, sécurité et RGPD.
La documentation est disponible [ici](https://dashlord.incubateur.net/#/intro)

**Comment by jonathanfallon** [comment]
https://github.com/betagouv/dashlord/pull/27
