### ISSUE TITLE
Problème d'affichage des données dans les graphes de la page statistique

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1470]
### Sujet

Les données "Trajets incités" ne semblent pas remontés dans le graphique principal de la page statistique.

### Environnement

Environnement (dev, prod...) : Prod
Navigateur : Safari
Utilisateur : Tous
URL : https://app.covoiturage.beta.gouv.fr/stats

### Etapes pour reproduire

1. _Je clique sur Filtres 
2. _Je rentre la valeur Mai 2021 à aujourd'hui puis valide
3. _Les données trajets remontent mais pas les trajets incités.
Pourtant les stats IDFM affichent 400K€ d'incitations.
<img width="809" alt="Capture d’écran 2021-09-01 à 14 33 19" src="https://user-images.githubusercontent.com/89770924/131672358-077ef73a-eaf3-40c5-a559-a5cc4e92666b.png">
<img width="1420" alt="Capture d’écran 2021-09-01 à 14 38 15" src="https://user-images.githubusercontent.com/89770924/131672436-fddeb57a-8c1f-48fb-bee2-2f0f109657d8.png">

_Ajouter des captures d'écran si nécessaire (Impr. écran et Ctrl-V directement ici)_
_Préciser les valeurs utilisées dans les formulaires_
_Répéter la procédure avec la Console ouverte (F12) et copier-coller le contenu ou faire une capture d'écran_

### Comportement attendu

1. _Je clique sur ... -> ouverture de la fenêtre_
2. ...

### Comportement actuel

1. _Je clique sur ... -> ouverture de la fenêtre_
2. ...

**Comment by P3rceval** [comment]
https://github.com/betagouv/preuve-covoiturage/pull/1472

**Comment by P3rceval** [comment]
Test failed
