### ISSUE TITLE
Erreur moteur d'incitation si règle stateful + restriction

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#1478]
Si un couple est exclu d'un calcul mais que celui-ci fait partie d'une voiture éligible alors les plafonds applicable sur ces incitations ne seront pas appliquées sur le couple exclu initialement.

lié à #1481

**Comment by nmrgt** [comment]
@nicolas-viennot-beta On peut fermer le ticket?

**Comment by nicolas-viennot-beta** [comment]
Si c'est ok pour toi oui.
Je ne sais pas comment le tester/

**Comment by nmrgt** [comment]
Ok je ferme via #1481
