### ISSUE TITLE
Vérifier les trajets bloqués en file d'attente

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#1488]
1. Lister les type d'erreurs en file d'attente
2. Identifier le/les providers impliqués
3. Patcher le code si besoin
4. Relancer les trajets

**Comment by jonathanfallon** [comment]
Beaucoup d'erreurs `positionToInsee`. Il semble y avoir des soucis sur les contours géographiques...

par exemple Monaco : 
![image](https://user-images.githubusercontent.com/1656255/133461500-98825ff0-2bd7-4338-9592-ea108d1eaaa4.png)

**Comment by jonathanfallon** [comment]
Les territoires limitrophes ont des contours simplifiés qui empiètent sur les contours plus précis des communes.
- Belgique
- Luxembourg
- Allemagne
- Suisse
- Italie
- Espagne
- Monaco
- Andorre

Contours manquants :
- Gap (base locale) **à vérifier**
- La Hollande
- Le Royaume-uni
- Somalie

**Comment by jonathanfallon** [comment]
**create the temporary table**
```sql
create table ttimport (name text, geo geography);
```

**Import geojson files to the temporary table**
```shell
wget https://geo.s3.fr-par.scw.cloud/monaco.geojson
wget https://geo.s3.fr-par.scw.cloud/spain.geojson
wget https://geo.s3.fr-par.scw.cloud/andorra.geojson
wget https://geo.s3.fr-par.scw.cloud/italy.geojson
wget https://geo.s3.fr-par.scw.cloud/switzerland.geojson
wget https://geo.s3.fr-par.scw.cloud/luxembourg.geojson
wget https://geo.s3.fr-par.scw.cloud/germany.geojson
wget https://geo.s3.fr-par.scw.cloud/belgium.geojson

ogr2ogr -f "PostgreSQL" PG:"dbname=<dbname> user=<user>" "monaco.geojson" -nln ttimport -append
ogr2ogr -f "PostgreSQL" PG:"dbname=<dbname> user=<user>" "spain.geojson" -nln ttimport -append
ogr2ogr -f "PostgreSQL" PG:"dbname=<dbname> user=<user>" "andorra.geojson" -nln ttimport -append
ogr2ogr -f "PostgreSQL" PG:"dbname=<dbname> user=<user>" "italy.geojson" -nln ttimport -append
ogr2ogr -f "PostgreSQL" PG:"dbname=<dbname> user=<user>" "switzerland.geojson" -nln ttimport -append
ogr2ogr -f "PostgreSQL" PG:"dbname=<dbname> user=<user>" "luxembourg.geojson" -nln ttimport -append
ogr2ogr -f "PostgreSQL" PG:"dbname=<dbname> user=<user>" "germany.geojson" -nln ttimport -append
ogr2ogr -f "PostgreSQL" PG:"dbname=<dbname> user=<user>" "belgium.geojson" -nln ttimport -append
```

**update the territories table with imported shapes matching names**
```sql
update territory.territories tt set geo = ttimport.geo from test where lower(ttc.name) = lower(ttimport.name);
```

## Contours

Contours extraites de OSM via https://osm-boundaries.com/ + nettoyage dans QGIS pour ne garder que le contour du pays.
Pas de simplification du contour.

**Comment by jonathanfallon** [comment]
:warning: fix de Gap à faire (INSEE 05061)

**Comment by jonathanfallon** [comment]
Gap est fixé en prod et les pays limitrophes aussi.

**Comment by jonathanfallon** [comment]
Réglé en prod
