### ISSUE TITLE
Création AOM à la main

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1495]
### Sujet

étudier avec Jo comment permettre création des aggégats de territoire par les bizdev.

### Environnement

Environnement (dev, prod...) :
Navigateur :
Utilisateur :
URL :

### Etapes pour reproduire / vérifier la bonne implémentation de l'amélioration

1. _Je clique sur ..._
2. _Je rentre la valeur ... dans ..._

_Ajouter des captures d'écran si nécessaire (Impr. écran et Ctrl-V directement ici)_

### Comportement attendu

1. _Je clique sur ... -> ouverture de la fenêtre_
2. ...

### Comportement actuel

1. _Je clique sur ... -> ouverture de la fenêtre_
2. ...

**Comment by P3rceval** [comment]
Il faudrait simplement rajouter le territoire parent (généralement un département) dans le formulaire actuel de création de territoire.
C'est cette action qui est faite manuellement qui empêche la création des AOM par les Bizdev.
