### ISSUE TITLE
Intégration de la nouvelle page Mes Statistiques du RPC

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1496]
Objectif : Intégrer une nouvelle page statistique du RPC.

EN AMONT : isoler sur une bdd dédiée ?

METABASE pour la BI : 
Il a été convenu que l'on essai au maximum de tirer les données de Metabase AINSI QUE d'en intégrer les View afin de rendre l'intégration de cette page loins chronophage et plus facile à maintenir.

DETAIL DES INDICATEURS : 
Reprendre les indicateurs mentionnés sur le documents Figma : [suivre lien ](https://www.figma.com/file/J8LeDKQBeHTHGhm4Ys7Q0X/Chantier-Statistiques?node-id=860%3A2)
<img width="886" alt="Capture d’écran 2022-01-21 à 15 26 06" src="https://user-images.githubusercontent.com/89770924/150544551-3b588c0d-5484-44f3-a9a5-67cbd11ad779.png">
--> la carte existe déjà en tant qu'indicateur sur le site Vitrine/ Territoires, cf : https://covoiturage.beta.gouv.fr/territoires/
--> les 3 données sur la droite avec les nombres d'AOM... ne sont pas dynamiques dans un 1er temps

<img width="948" alt="Capture d’écran 2022-01-21 à 15 26 45" src="https://user-images.githubusercontent.com/89770924/150544976-457b0a85-78d9-422b-83b6-a60da372a15a.png">
--> le nombre d'opérateur actif peut être récupéré via carpool.carpools en faisant la somme des opérateurs ayant   cc.datetime >= (NOW() - '6 months'::interval) AND  cc.status = 'fraudcheck_error' **OU status=ok**
--> le nombre de process de normalisation n'est pas dynamique
--> l'indicateur audit sera a masquer pour démarrer

<img width="907" alt="Capture d’écran 2022-01-21 à 15 27 03" src="https://user-images.githubusercontent.com/89770924/150548287-b63af30a-692c-4e1f-bd82-546a30294966.png">
--> pour le graphique, il faut voir si metabase permet de faire de l'affichage dynamique en fonction du filtre période

<img width="896" alt="Capture d’écran 2022-01-21 à 15 27 13" src="https://user-images.githubusercontent.com/89770924/150548449-b2ee59ce-7817-4bb9-81b0-d2f5efd547d4.png">
-> pour tous les autres indicateurs, seuls les indicateurs Primo-conducteur et primo-passagers n'existent pas encore. Il faut voir avec @Datayama38 pour voir comment le mettre en place, il en aura aussi besoin pour l'observatoire. (On assume pour cela d'avoir un biais de surestimation dû aux users multi-opérateur mais on mettra un * pour l'expliquer --> Reprendre la stat Covoitureurs (cf. stat actuelle https://app.covoiturage.beta.gouv.fr/statset et distinguer conducteurs et voyageurs)

**Comment by nicolas-viennot-beta** [comment]
hello @P3rceval : dans le point prio d'aujourd'hui : 
- vous avez évoqué avec Jon le souhait de retravailler les stats du dashboard collectivités sur la base d'une BDD dédiée aux stat sur Metabase, exact ?
- si oui, est-ce que la BDD dédiée aux stats a été traitée avec ce ticket ? cf. la question au début du ticket ci-dessus ("EN AMONT : isoler sur une bdd dédiée ?") ?

**Comment by P3rceval** [comment]
> vous avez évoqué avec Jon le souhait de retravailler les stats du dashboard collectivités sur la base d'une BDD dédiée aux stat sur Metabase, exact ?

Oui c'est vrai !

> si oui, est-ce que la BDD dédiée aux stats a été traitée avec ce ticket ? cf. la question au début du ticket ci-dessus ("EN AMONT : isoler sur une bdd dédiée ?") ?

Mon point de vue suite à la création du dashboard de stats => je pense qu'on peut se contenter d'avoir des **vues matérialisées** que l'on rafraîchit toutes les 24H plutôt que d'avoir une BDD séparée. Ça nous évitera de la maintenance et des coups d'infra supplémentaires. 
Dans le cadre de la page publique nous n'avons pas besoin d'avoir des données en temps réel.
Si on choisit de faire une DB répliquée, dédiée pour les stats, ça sera en dehors de ce scope.

Sinon pour l'ajout des filtres sur le chart => Compliqué car Metabase récupère directement des données projetées par mois pour des soucis de performances. Donc pas possible d'avoir des filtres pertinents ... (Et une BDD dédiée ne résoudrait pas le problème, il y aurai quand même des timeouts coté Metabase)

**Comment by jonathanfallon** [comment]
Scalingo a une nouvelle fonctionnalité de cronjob en utilisant un fichier `cron.json` qui peut permettre de lancer des commandes de `REFRESH MATERIALIZED VIEW` en background job toutes les nuits.
On peut créer 3 actions par exemple :
- `yarn run cron:daily`
- `yarn run cron:weekly`
- `yarn run cron:monthly`

PS : à voir si on garde notre système de scheduling interne ou si on le migre sur des cronjobs que je trouve plus lisibles (et centralisés dans un fichier).

**Comment by nicolas-viennot-beta** [comment]
@P3rceval, sur ce ticket, il faut : 

1. intégrer la stat "xxx attestations opérateur"
<img width="1096" alt="Capture d’écran 2022-03-23 à 12 06 23" src="https://user-images.githubusercontent.com/89770924/159686283-71931407-a083-4c9e-8047-496c1b7d5a94.png">


2. modifier le tableau de l'évolution des trajets en distinguant les "trajets non incités", "les trajets incités hors RPC" et enfin "les trajets incités via RPC"
<img width="1057" alt="Capture d’écran 2022-03-23 à 12 06 41" src="https://user-images.githubusercontent.com/89770924/159686843-3b3f58fa-b503-44e8-b199-05695ee6be4a.png">


3. Warning : les données ne paraissent pas bonnes dans le graphique d'évolution du nbre de trajets., voir différence importante avec le tableau [DGEC](https://stats.covoiturage.beta.gouv.fr/dashboard/10-dgec)


2. modifier le tableau de l'évolution des trajets en distinguant les "trajets non incités", "les trajets incités hors RPC" et enfin "les trajets incités via RPC"
<img width="1057" alt="Capture d’écran 2022-03-23 à 12 06 41" src="https://user-images.githubusercontent.com/89770924/159686843-3b3f58fa-b503-44e8-b199-05695ee6be4a.png">

**Comment by P3rceval** [comment]
@nicolas-viennot-beta j'ai process tout tes retours normalement, j'te laisse checker et clore si c'est bon pour toi :)
