### ISSUE TITLE
Problème de génération d'attestations en pré-prod

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1509]
### Sujet

Problème remonté par Klaxit (message email collé ci-dessous): 

Nous rencontrons un problème pour générer les attestations sur votre environnement de pré-production (cela fonctionne en production). Voici un exemple :

# Utilisateur
operator_user_id : d63f3973-024e-409a-842c-1750b110b849

# Preuve envoyée
journey_id : 479fd964-e5c1-4b5f-9724-6a1bf9435c73
Envoyée le vendredi 01 octobre 2021 à 10:22

Voici la payload lors de notre appel à /v2/certificates : 
```
{
  "tz":"Europe/Paris",
  "identity": {
    "phone_trunc":"+336253645",
    "operator_user_id":"d63f3973-024e-409a-842c-1750b110b849"
  },
  "start_at":"2020-10-01T00:00:00",
  "end_at":"2021-09-30T23:59:59"
}
```

Et voici votre réponse :
```
404:
{
  "id":1,
  "error": {
    "data":"Cannot find UUID for this person",
    "code":-32504,
    "message":"Not found"
  },
  "jsonrpc":"2.0"
}
```

**Comment by jonathanfallon** [comment]
Résolu par #1510
