### ISSUE TITLE
Erreur d'encodage du fichier d'export open-data

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1522]
Il semble y avoir une erreur d'encoding dans les fichiers sur https://www.data.gouv.fr/fr/datasets/trajets-realises-en-covoiturage-registre-de-preuve-de-covoiturage/ pour les trajets du mois de septembre.
Ce n'est ni de l'utf8, ni de l'iso-8859-1 valide. Si vous cliquez sur l'icone de preview du fichier dans data gouv, vous aurez l'erreur "Error: Error parsing CSV: 'utf-8' codec can't decode byte 0xcc in position 2659: invalid continuation byte"

**Comment by P3rceval** [comment]
Fixed
