### ISSUE TITLE
Faire un export de données pour l'AOM Pôle Métropolitain Genevois

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1538]
L'AOM Pôle Métropolitain Genevois a besoin de connaitre le volume de trajet de l'opérateur Karos sur son territoire pour la période d'octobre 2020 à octobre 2021.

-> Leur faire un export

**Comment by P3rceval** [comment]
Done, en attente des retours de jo si il en a

**Comment by nicolas-viennot-beta** [comment]
oui tout à fait. ticket créé avant la mise en production de la feature Visibilité. (Karos n'était pas visible sur ce territoire).
