### ISSUE TITLE
Supprimer la visibilité opérateur de la doc technique

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1544]
https://tech.covoiturage.beta.gouv.fr/operateurs/visibilite-du-nom-de-loperateur.html

**Comment by nicolas-viennot-beta** [comment]
Suite à l'évolution apportée sur la feature visibilité opérateur, les opérateurs n'ont plus la main sur leur visibilité. Il faut donc supprimer l'onglet visibilité de la documentation technique https://tech.covoiturage.beta.gouv.fr/operateurs/visibilite-du-nom-de-loperateur.html
