### ISSUE TITLE
Export de données sur le service Fraude

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1562]
**Besoin
J'aimerai connaitre : 
- Nbre de trajets total exclus par notre micro service "Fraude" par mois (sur au moins les 6 derniers mois)
- Nbre de trajets incités exclus par notre micro service "Fraude" (sur au moins les 6 derniers mois)
- Si possible avoir le motif/quelle règle a été appliquée

**Souhait 
Avoir un export Excel des trajets exclus par le service fraude (au moins sur les 6 derniers mois) avec les informations suivantes : date du trajet, Incité ou non, motif ou règle, opérateur.

**Comment by nicolas-viennot-beta** [comment]
@nmrgt : n'hésite pas à me dire si pas clair.

**Comment by nmrgt** [comment]
On peut fermer le ticket ?

**Comment by nicolas-viennot-beta** [comment]
yes
