### ISSUE TITLE
Documentation du Nouveau Service Policy

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1563]
### Documentation du Nouveau Service Policy

_ Le service Policy a évolué, il est important qu'il soit bien documenté, d'autant plus que la connaissance est principalement détenue par Nico sur ce sujet.
_ Afin d'avoir une documentation la plus accessible aux non initiés, celle-ci pourrait être rédigée par Jon ou Julien sous le regard bienveillant de Nico dans un esprit de fraternité, de jovialité et de... bref ca va être un moment formidable.

https://hackmd.io/8zSDpIzXR5modSgbms_VJw?edit

Documenter les évolutions #1789

**Comment by nmrgt** [comment]
- Documenter le processus de création / test de campagne.
- Documenter les actions possibles sur les campagnes :
  - (re) jouer les campagne
  - contrôle des appels de fonds
