### ISSUE TITLE
Analyse des évolutions front suite au chantier territoire

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1571]
### Impact Chantier Territoire Analyse des évolutions front 

_Analyse notamment des différents Endroits à faire évoluer.

**Comment by P3rceval** [comment]
Mhhh, déjà documenté je dirai :thinking:

**Comment by P3rceval** [comment]
@nicolas-viennot-beta t'es OK pour qu'on ferme ce ticket vu que c'est déjà fait ? J'propose de pas mettre les analyses techniques sur ce board, ça l'alourdit et ça ne suit pas le même workflow qu'une tâche... :thinking:

**Comment by nicolas-viennot-beta** [comment]
oui tout à fait, je clos
