### ISSUE TITLE
MAJ endpoint en anticipation du chantier territoire

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1572]
### MAJ des endpoints suite au chantier territoire.

Endpoints à usages interne uniquement. 
Pas de documentation public à mettre à jour.

**Comment by P3rceval** [comment]
Tests à effectuer à minima : 
- [ ] Création de campagne avec exclusion de trajet (commune à commune) (via user territoire)
- [ ] Création de territoires (via user admin)
- [ ] Modification de territoires (via un user admin et un user territoire)
- [ ] Filtre sur la zone géographique sur la page statistiques

**Comment by nicolas-viennot-beta** [comment]
Tests effectués sur Mac / Safari /Envir Dev / Compte Territoire IDFM

 - [ ] Filtre sur la zone géographique sur la page statistiques
- pas de message d'erreur lors d'une mauvaise saisie dans le champ territoire (ex : 87§§è!§)
- pas de saisie possible d'un département (ex: Yvelines), alors que cela est possible avec un compte Admin.
- pas de saisie possible par n°Insee (ex n°Insee de cergy : 95127)
-

**Comment by nicolas-viennot-beta** [comment]
Tests effectués sur Mac / Safari /Envir Dev / Compte Territoire IDFM

Fonctionnalité Testée : Filtre sur la zone géographique sur la page statistiques (Champ : Ville)
👉
- pas de message d'erreur lors d'une mauvaise saisie dans le champ territoire (ex : 87§§è!§) ❌
- pas de saisie possible d'un département (ex: Yvelines), alors que cela est possible avec un compte Admin. ❓
- pas de saisie possible par n°Insee (ex n°Insee de cergy : 95127) ❓
- pas de saisie possible par EPCI (ex Communauté d'agglomération - Étampois Sud-Essonne) ❌

**Comment by P3rceval** [comment]
- Test2 =>  fixé ici https://github.com/betagouv/preuve-covoiturage/pull/1595
- Test3 => Oui on ne peut plus consulter les insees pour un territoire, mais c'est pas tellement problématique car;
1. Les territoires sont exclusivement créés et modifiés par nous. 
2. Y'a pas de raison majeure pour qu'on ai à modifier cette donnée.
3. Cette donnée n'est actuellement pas visible par l'AOM
4. Le formulaire va encore évoluer après le refacto (C'est pas tellement worth de perde plus de temps à maintenir ce champ) 
- Tests filtre zone géographie => 
1 "pas de message d'erreur" -> ISO avec avant
2 "pas de saisie possible des Yveline" -> je pense que t'étais connecté avec un territoire qui n'englobe pas les Yveline, je n'ai pas reproduit sur dev :thinking: 
3 "pas de saisie d'insee" -> ISO avec avant
4 j'ai testé avec le compte admin et il est possible de saisir une EPCI. La Communauté d'agglomération - Étampois Sud-Essonne ne semble pas être dans notre BDD sur dev

**Comment by P3rceval** [comment]
@nicolas-viennot-beta T'es OK avec mes retours ou tu veux qu'on en discute ?

**Comment by nicolas-viennot-beta** [comment]
Tout est très clair sauf le point 
2."pas de saisie possible des Yveline" -> je pense que t'étais connecté avec un territoire qui n'englobe pas les Yveline, je n'ai pas reproduit sur dev 🤔

=> en fait, c'est peut-être dû à une règle fonctionnelle. Je pensais que la mise en place du chantier territoire permettrait de créer des règles d'exclusion OU autorisation de trajet sur des zones qui pouvait être une commune, une AOM, un département et pas seulement des communes. Exemple : exclure les trajets au départ du département X à destination de l'AOM Y.

cc @P3rceval

**Comment by P3rceval** [comment]
Comme vu avec toi en call, le refacto réalisé ici est à périmètre fonctionnel constant. 
Mais ce pourrait être une évolution possible une fois la migration complète réalisée !
