### ISSUE TITLE
Documentation du chantier Attestation

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1573]
### Documentation du chantier Attestation

1.Décrire sur la documentation technique : 
- les règles fonctionnelles
- les données transmises
2. Mettre sur la doc technique les captures écrans des attestations

**Comment by jonathanfallon** [comment]
Exemple d'attestation en 2 pages

![attestation](https://user-images.githubusercontent.com/1656255/155167201-8b76d443-7409-467b-8886-336dc6a6e34e.png)
![attestation-p2](https://user-images.githubusercontent.com/1656255/155167404-94b6d411-08e0-4d06-8ca1-9cc364c6f85b.png)

**Comment by jonathanfallon** [comment]
Exemple ajouté à la [page de la doc](https://doc.covoiturage.beta.gouv.fr/employeurs-et-employes-developper-du-forfait-mobilite-durables/telecharger-les-attestations-operateurs)

**Comment by nicolas-viennot-beta** [comment]
pas finalisé
