### ISSUE TITLE
Intégration d'un Jeu de données sur l'env. de Dev et Demo

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1575]
### Intégration Jeu de données en dev

Objectif : Pouvoir effectuer des tests sur l'env. de dev et demo avec des jeux de données consistants (nbre de trajets suffisant, trajets incités...)

Solution : réintégration Jeux de données de Prod des 6 derniers mois sur l’env. de dev. et démo.

Question à résoudre en amont : Faut-il anonymizes les données ?

**Comment by nmrgt** [comment]
Actuellement, on a un début de jeu de données dans providers/seed.
Idéalement, ce serait bien de concentrer les efforts des jeux de données :
1. supprimer le legacy des tests d'intégration qui sont dans providers/test/dbTestMacro (les fixtures dans dans fixtures) pour utiliser le providers/test/dbMacro à la place (qui utilise providers/seed)
2. compléter le providers/seed avec les données manquantes pour une couverture de tests complète
3. utiliser un cron pour remettre ces données tous les jours sur dev et demo
