### ISSUE TITLE
Modification de la campagne Lannion 

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1587]
Il y a 2 coquilles dans le paramétrage de la campagne qu'il faut corriger comme suit : 

_Dans le paramétrage « Rétribution », il faut saisir "De 20 à 40km : 0.1 euro par trajet par km par passager gratuit pour le(s) passager(s)" AU LIEU DE "à partir de 20km....."
_Dans le paramétrage « Distance », il faut saisir "A partir de 2km" AU LIEU DE "De 2 à 40km"

**Comment by P3rceval** [comment]
@nicolas-viennot-beta Peut-on fermer ce ticket ?

**Comment by nicolas-viennot-beta** [comment]
Une demande "sauvage" avait été faite en dehors de ce ticket pour modifier également les classes acceptées.

Il faut supprimer la classe A des classes éligibles et donc n'avoir sur cette campagne que les classes B et C.
<img width="587" alt="Capture d’écran 2021-12-22 à 14 03 57" src="https://user-images.githubusercontent.com/89770924/147097210-b7ef000e-4e2e-4dc7-8b18-06edccc93ffb.png">

Merci

**Comment by nmrgt** [comment]
C'est fait en prod, je fermer @nicolas-viennot-beta
