### ISSUE TITLE
Problème de calcul du montant de campagne dépensé

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1591]
### Sujet

_on suspecte une erreur dans le calcul du montant de campagne dépensé.

exemple : 

- Prenons le cas de la campagne IDFM, le 25/11, l'interface affichait un montant dépensé de 985.957€ dépensé.
<img width="636" alt="image" src="https://user-images.githubusercontent.com/89770924/143907981-ef56ddce-9f5b-4e72-8ae2-98897ea8c542.png">

- Jo a recalculé de son coté, cf. le lien vers fichier google sheet,  et arrive à un montant de 803.389€.

https://docs.google.com/spreadsheets/d/1NyEgrsnUHSf0vdQUX6hYtZsInWD1p5Q2C5c9IV1EOJQ/edit#gid=0

### A faire 
_ voir si problème est réel et fixer si besoin

**Comment by P3rceval** [comment]
Les appels de fonds ne prennent pas en compte le mois en cours. 
La rétribution totale ici est une estimation de l'enveloppe consommée en prenant en compte le mois en cours.

- Soit on modifie le wording ici en mettant que c'est une estimation
- Soit on met ce qui correspond au appel de fond effectivement envoyé (et cela ne prendra pas en compte le mois en cours)

**Comment by Jonathankurtz131** [comment]
Super intéressant. Du coup ce serait intéressant d'ajouter le wording estimation de la rétribution totale ? Est ce utile d'ajouter un autre indicateur avec le montant réellement consommé entre début de la campagne et M-1 mois en cours ? Ou c'est trop lourd et ça brouille le message ?

**Comment by jonathanfallon** [comment]
Est-ce possible de séparer la partie des incitations validées avec une couleur et celle estimée avec une autre ?

**Comment by P3rceval** [comment]
Oaui on pourrait superposer les 2 mais ça implique de changer l'UI. ( Genre agrandir le camembert ). Ou alors on sépare l'info en 2 chartes distincts comme propose jo.

**Comment by nicolas-viennot-beta** [comment]
J'ai l'impression que les AOM on un suivi comptable mensuel et non pas temps réel. Auquel cas, restons simple et on met ce qui correspond aux appels de fonds effectivement envoyés (et cela ne prendra pas en compte le mois en cours) en le précisant de façon clair.
Je vais appeler IDFM pour validation si ca vous va.

**Comment by P3rceval** [comment]
@nicolas-viennot-beta Ce ticket est-il toujours d'actualité ? On change l'enveloppe affichée en mettant le montant correspondant aux APDF envoyés ?

**Comment by nicolas-viennot-beta** [comment]
hello @P3rceval.
IDFM préfère la vision comptable du mois précédent MAIS nous intégrerons cette évolution dans un epic complet sur l'interface Collectivité.

* Quick fix à faire en attendant : 
REMPLACER "Rétribution totale" PAR "Estimation de la rétribution totale"

merci
