### ISSUE TITLE
Modification du texte dans bandeau bleu page d'accueil

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1596]
Remplacer 
*Le covoiturage au quotidien concerne principalement des trajets de moins de 80 km. 
PAR
*Le covoiturage au quotidien concerne principalement des trajets de moins de 80 km. Ici l'observatoire se concentre uniquement sur les données réelles enregistrées par les opérateurs du covoiturage partenaires du Registre de Preuve de Covoiturage.
<img width="1200" alt="Capture d’écran 2021-12-01 à 12 41 32" src="https://user-images.githubusercontent.com/89770924/144446400-dbe93762-76cd-425f-ac78-91b8954c844f.png">

**Comment by Datayama38** [comment]
ça serait pas mieux de mettre "Dans un premier temps," au lieu de "Ici" ? Parce qu'à terme on aura pas forcément que des données RPC.
