### ISSUE TITLE
Carroyage - Départ/Arrivée 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#160]
## Contexte
Des collectivités souhaiteraient avoir une précision plus fine sur les origines destinations. Le code INSEE, code postal et nom de commune ne leur suffit pas. 
Il s'agit de combiner une solution permettant à la fois d'avoir une bonne granulométrie et également évitant les possibilités de ré-identification des covoitureurs.

## Contexte
Nous récupérons actuellement en Degré Décimal 5 chiffes après la virgule donc précision à environ 7 mètres sur Paris. 

## Solutions

1) Si on enlève les trois derniers chiffres donc on tronque à la minute, on aurait des "carreaux" de 1,5 km². 
2) On pourrait aussi couper en deux la précision minute. C'est possible ça ? 

![image](https://user-images.githubusercontent.com/15428433/57525696-aa550f80-732b-11e9-8242-8ab9cecabaea.png)

**Comment by jonathanfallon** [comment]
Si on reste dans le système décimal que nous utilisons, ça donne quelque chose comme ça : 

| ^ | précision | mètres |
| - | --------- | ------:|
| 0 | 1 degré   | 78850  |
| 1 | 0.1       | 7885   |
| 2 | 0.01      | 786    |
| 3 | 0.001     | 79     |
| 4 | 0.0001    | 8      |

L'option **^3** me parait être le bon compromis pour les zones denses. En zone peu dense, il faudrait du **^2**. Ça nécessite de qualifier les différentes zones avec leur contours géographiques, sachant que cette donnée n'est pas normalisée.
Pour certaines AOM concernées seulement pas des zones dense, on peut prévoir d'utiliser **^3** sur tout le territoire.

**Comment by margot-sanchez** [comment]
Bizarrement c'est beaucoup plus clair quand c'est toi qui l'explique. 

79 mètres * 79 mètres c'est quand même trop précis selon moi... 
Mais après c'est vrai qu'on peut faire la distinction entre zone dense et peu dense.

**Comment by margot-sanchez** [comment]
Une fois #17 finalisée, partir sur  : 

1. 2 décimales pour territoire dense. 
2. 2 décimales pour territoire peu dense.

**Comment by jonathanfallon** [comment]
Fait dans la PR #637 (mergée)

**Comment by nmrgt** [comment]
1/2/3 = 2 virgules
4 = 3 virgules

**Comment by jonathanfallon** [comment]
fixé par la #710

**Comment by margot-sanchez** [comment]
A tester dès que la PR est passée. Me pinger.

**Comment by margot-sanchez** [comment]
Non cela n'a pas marché. Je suis bien sur le staging et j'ai bien vidé mon cache
![image](https://user-images.githubusercontent.com/15428433/70648260-fb730c00-1c4a-11ea-929b-5e4ab1d1023f.png)

**Comment by margot-sanchez** [comment]
Testé syr dev & staging ==> pas de changement. Cela ne fonctionne pas.

**Comment by margot-sanchez** [comment]
Il y a un problème sur le carroyage. 

Exemple : Malakoff est clairement dans une zone à densité très élevée.
![image](https://user-images.githubusercontent.com/15428433/70791059-96c4c800-1d96-11ea-8af8-a2641e18af93.png)
Pourtant il y a que 2 décimales.
![image](https://user-images.githubusercontent.com/15428433/70791085-a93f0180-1d96-11ea-83b4-b3227f4ed1ec.png)

Pour Réau cela fonctionne bien pourtant. 
![image](https://user-images.githubusercontent.com/15428433/70791218-f4f1ab00-1d96-11ea-9a56-32afbcb323bf.png)

**Comment by margot-sanchez** [comment]
Le bellay en vexin est peu dense donc normalement 2 décimales et pourtant ![image](https://user-images.githubusercontent.com/15428433/70791392-544fbb00-1d97-11ea-9eb8-4c44e83d128f.png)
![image](https://user-images.githubusercontent.com/15428433/70791448-6d586c00-1d97-11ea-9287-bf5e6b7ae128.png)

**Comment by jonathanfallon** [comment]
Problème de spec :
On avait : 1/2/3 = 2 décimales, 4 = 3 décimales
Il nous faut : 1 = 3 décimales, > 1 = 2 décimales

**Comment by jonathanfallon** [comment]
Postgres :champagne: 
```
 un | deux | trois | quatre 
----+------+-------+--------
  3 |    2 |     2 |      2
```
