### ISSUE TITLE
Analyse charge d'une évolution des règles de campagne

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1604]
Une AOM demande s'il est possible d'appliquer la restriction suivante : 
"XX passagers maximum incités par conducteur par trajets".

Coté front cela se traduirait ainsi : 
<img width="1114" alt="Capture d’écran 2021-12-07 à 09 09 30" src="https://user-images.githubusercontent.com/89770924/144991434-9c7881ce-0aa2-46af-ac7c-38dfb816daac.png">

👉 Coté back, je n'arrive pas à mesurer les répercutions. Pourrais-tu me dire les implications risque /temps passés pour apporter ce paramétrage au moteur de campagne ?

**Comment by nmrgt** [comment]
Comme on ne gère plus les voitures, la seule choses qu'on peut faire c'est de mettre un filtre par siège max. Sans le front, je pense qu'il y en a pour une demi journée au max.

**Comment by nicolas-viennot-beta** [comment]
@nmrgt en fait je doute ;)  quand tu évoques un filtre par siège max. c'est sur l'ensemble des couples d'un même Journey_ID ?

**Comment by nmrgt** [comment]
ah ah tu fais bien de poser la question mais comme je le disais, on ne gère plus les voitures donc c'est le nombre de siège réservé sur un couple où on peut mettre un max à 3

**Comment by nicolas-viennot-beta** [comment]
aie je suis buté.
TU veux dire que 
SI un conducteur A a 1 couple passager avec 4 siège réservé : il sera incité uniquement sur 3 sièges maximum
MAIS 
SI un conducteur A a 1 couple passager A avec 2 sièges et un couple passager B avec 2 siège, alors il sera incité pour 4 sièges
MAIS
SI un conducteur A a 1 couple passager A avec 4 sièges et un couple passager B avec 2 siège, alors il sera incité pour 5 sièges

exact ?

**Comment by nicolas-viennot-beta** [comment]
Hello @nmrgt, il nous faut aller vers la solution 2 pour respecter la restriction souhaitée ;(
 (rappel : Pour un trip_id donné, il ne peut y avoir plus de 3 passenger_id bénéficiant d'une aide de la collectivité).

**Comment by nmrgt** [comment]
Ok je reprends le ticket alors :)
