### ISSUE TITLE
faire une modification de texte sur les statistiques territoires pour éviter toute confusion

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1610]
le problème : aujourd'hui les collectivités ne comprennent pas la donnée "trajet incité" sur leur tableau de bord. Elle s'attendent légitimement à ce que les trajets incités lors de campagne hors Rpc y figurent. 

**Solution rapide :** 

1. modifier l'intitulé "Trajet incité" dans l'onglet "Chiffres clés"
REMPLACER "Trajet incité" PAR "Trajets incités via une campagne paramétrée sur le RPC"

<img width="1335" alt="Capture d’écran 2021-12-15 à 10 43 42" src="https://user-images.githubusercontent.com/89770924/146163683-85c7faa1-b71a-4583-9fdb-ff27bd66b4c4.png">

2. masquer la colonne "incitation" dans le tableau de l'onglet "Liste détaillée" (masquer le temps de la mise en place d'une évolution interface à suivre avec intégration des incitations envoyées par les opérateurs)
<img width="1337" alt="Capture d’écran 2021-12-15 à 10 44 51" src="https://user-images.githubusercontent.com/89770924/146165225-36e9c569-efd8-4764-9217-8ffbe1f76314.png">

Solution complète dans une priorisation ultérieure : 
un autre ticket va être créé pour que nous puissions intégrer la donnée "Trajets incités HORS RPC" dans le graphique et le tableau.

**Comment by jonathanfallon** [comment]
Ticket #1603 pour l'affichage des incitations hors RPC

**Comment by nicolas-viennot-beta** [comment]
yes parfait. ok pour toi pour prise en compte de la demande de modification wording MEP d'ici mardi ? (Klaxit prétend que la terminologie "trajets incités" nuit aux partenariats actuels qu'ils entretiennent hors rPc

**Comment by nicolas-viennot-beta** [comment]
@jonathanfallon la modification de wording apportée ne suffit pas. Pourras-tu intégrer aussi la modification de wording suivant : 
Remplacer "Tous les trajets réalisés" PAR "Tous les trajets réalisés (incités et non incités)"

Cf. l'emplacement sur la capture écran ci-dessous.
<img width="849" alt="Capture d’écran 2022-01-04 à 16 44 21" src="https://user-images.githubusercontent.com/89770924/148085633-f9fe618d-9676-4243-8ed4-9dfe0f643bcb.png">

**Comment by nicolas-viennot-beta** [comment]
hello @jonathanfallon : quand cette évolution pourra t-elle passer en production ?
