### ISSUE TITLE
Tables de stats

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1612]
Pour optimiser les perfs de Metabase : 

- Faire des vues materialisées dans le schema `stats`
- Faire un Action CRON dans l'api pour faire des refresh toutes les nuits via des workers
- Utiliser `table stats.<tablename>` dans Metabase pour récupérer les données
- Donner accès uniquement au schema `stats` au user `metabase`

https://hackmd.io/ItJZyMaVRUK7JVen1Mg1yg?view

**Comment by P3rceval** [comment]
Est-ce qu'on utiliserai pas une extension Postgresql type [pg_cron](https://blog.capdata.fr/index.php/postgresql-planifier-une-tache-avec-pg_cron/) ?

**Comment by jonathanfallon** [comment]
Elle ne sembe pas dispo sur scalingo : https://doc.scalingo.com/databases/postgresql/extensions

**Comment by P3rceval** [comment]
- #1738

**Comment by P3rceval** [comment]
@jonathanfallon On peut fermer ce ticket ?

**Comment by jonathanfallon** [comment]
Yes
