### ISSUE TITLE
Ajout de l'information "trajet incité" dans le jeu d'export de données

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1625]
### Objectif : intégrer l'information "trajet incité" dans le jeu d'export de données

- Pour chaque Journey_ID, ajouter un champ "trajet incité" qui indique si oui ou non une incitation a été associée au trajet.
- Un trajet est considéré comme non incité si les champs "passenger_incentive_1_amount", "passenger_incentive_rpc_1_amount" et "driver_incentive_1_amount", "driver_incentive_rpc_1_name" sont égales à 0
- Un trajet est considéré comme incité dès lors que les champs ci-dessus sont > à 0.

**Comment by P3rceval** [comment]
@nicolas-viennot-beta est-ce qu'il faut que ça soit rétroactif ?

**Comment by nicolas-viennot-beta** [comment]
@P3rceval : effectivement bene question. Ce serait l'idéal pour avoir une antériorité pour l'analyse.
y a t-il une complexité? tes de calcul??

**Comment by nicolas-viennot-beta** [comment]
Hello @P3rceval : il faudrait également ajouter dans les exports des trajets du RPC les colonnes "journey_start_aom" "journey_end_aom" afin d'en simplifier l'analyse. Est-ce que c'est un travail à mener en même temps que l'ajout "trajet incité" dans l'export open data ? (auquel cas, je ne fais pas de ticket supplémentaire)

**Comment by P3rceval** [comment]
> @P3rceval : effectivement bene question. Ce serait l'idéal pour avoir une antériorité pour l'analyse. y a t-il une complexité? tes de calcul??

Non pas du tout, j'ai rajouté un bout de code qui met à jour les export opendata existant [ici](https://github.com/betagouv/preuve-covoiturage/pull/1649) ça m'a pris moins d'une demi journée.




> Hello @P3rceval : il faudrait également ajouter dans les exports des trajets du RPC les colonnes "journey_start_aom" "journey_end_aom" afin d'en simplifier l'analyse. Est-ce que c'est un travail à mener en même temps que l'ajout "trajet incité" dans l'export open data ? (auquel cas, je ne fais pas de ticket supplémentaire)

J'pense que ça serait bien un ticket à part. Car on a pas le référentiel complet des AOMs actuellement et ce tant que le chantier territoire n'est pas finalisé.
Et de le faire avec le model actuel des territoires ça peut être lourd

**Comment by P3rceval** [comment]
Voir si #1d44fad9ce75de6f6413de1afba8ad9b3afc2693 fait bien l'ajout OUI / NON
