### ISSUE TITLE
Pouvoir modifier les contacts d'un territoire en tant qu'admin

### ISSUE THREAD

**Issue by P3rceval** [betagouv/preuve-covoiturage#1627]
Lors de la modification d'un territoire en tant qu'Admin, les codes insees ne sont pas remontés ce qui empêche la validation des formulaires et la modification des contatcts . (Pas de pb pour les AOMs à priori)

**Comment by nicolas-viennot-beta** [comment]
Je ne vois pas l'évolution par rapport au ticket.
Désormais, les codes INSEE doivent-ils remonter ? Si c'est le cas, ils ne remontent toujours pas.

**Comment by P3rceval** [comment]
Réponse courte => Non, ils ne doivent pas remonter.

Le demande initiale était de pouvoir modifier les contacts en tant qu'admin. Bug remonté par Victor.
J'étais initialement parti la modification entière du territoire avec les codes INSEE, ce qui aurait résolu le problème. 
Et en fait je suis revenu sur une solution plus courte qui consiste à simplement modifier la partie contacts.

**Comment by nicolas-viennot-beta** [comment]
ok je ne savais pas ce qu'il fallait tester.

C'est tout bon donc. Tests sur modification des contacts ok 👏
