### ISSUE TITLE
Evolution graphique du PDF Attestation Opérateurs

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1628]
### Ajouter sur la 1ère page du pdf "Attestation Opérateur" les éléments suivants : 

1. Remplacer la Marianne actuelle par le logo sous titrée de "Ministère chargé des Transports" comme précisé dans la charte : https://www.gouvernement.fr/charte/charte-graphique-les-applications/ministeres-secretariats-d-etat-services-deconcentres-ou-a-l
Voici le logo du Ministère Chargé des Transports en bonne qualité ici : https://drive.google.com/drive/folders/1fNgxBeNwMLocRoNIYoJ953__BgJe2jrp?usp=sharing

2. Intégrer bloc mentions de prévention fraude que Thomas Menant va nous transmettre sous la mention "Un problème? Une question?...." 

La présente attestation est fournie par le Registre de preuve de covoiturage réalisé par le ministère des Transports.  Cette attestation est réalisée grâce aux informations transmises par les opérateurs de covoiturage participant au Registre. Le ministère des Transports ne saurait être tenue responsable des informations transmises les opérateurs.
Ce document est personnel. Toute personne le modifiant ou procédant à une fausse déclaration s’expose aux sanctions prévues à l’article 441-1 du code pénal, prévoyant des peines pouvant aller jusqu’à trois ans d’emprisonnement et 45 000 euros d’amende.

<img width="546" alt="Capture d’écran 2022-01-06 à 10 42 21" src="https://user-images.githubusercontent.com/89770924/148363154-c43c30ea-a1c5-49d5-8005-2e62b9cb6577.png">

**Comment by nicolas-viennot-beta** [comment]
Tu trouveras le logo du Ministère Chargé des Transports en bonne qualité ici : https://drive.google.com/drive/folders/1fNgxBeNwMLocRoNIYoJ953__BgJe2jrp?usp=sharing

**Comment by nicolas-viennot-beta** [comment]
Hello @jonathanfallon : j'ai édité le ticket ci-dessus en intégrant la mention de Thomas (je viens juste de découvrir qu'il te l'avais envoyé à la suite de notre échange;). On fait donc sauter le bloc commentaire pour intégrer la mention. Merci

**Comment by nicolas-viennot-beta** [comment]
hello @jonathanfallon : j'ai édité le commentaire au dessus et rajouter une coquille sur l'adresse email contact à corriger.

**Comment by jonathanfallon** [comment]
- [x] mise à jour du logo
- [x] ajout des mentions légales
- [x] repositionnement des informations  

[covoiturage-c58c7b03-5ed6-4130-8764-0880ff791c3b.pdf](https://github.com/betagouv/preuve-covoiturage/files/8117247/covoiturage-c58c7b03-5ed6-4130-8764-0880ff791c3b.pdf)
