### ISSUE TITLE
Problème d'affichage des statistiques avec en filtrant sur les trajets incités

### ISSUE THREAD

**Issue by P3rceval** [betagouv/preuve-covoiturage#1635]
Lorsqu'on applique un filtre par campagne, certain trajet non incité remontent quand même
![image](https://user-images.githubusercontent.com/6213517/148756718-1f7e3334-4dc1-4d1a-8cd1-f7099bfb94e1.png)

- [x] Fix de l'action de stat
- [x] Fix aussi le dropdown par campagne 

Ne remonter que les trajets qui ont une incitation > 0

**Comment by nicolas-viennot-beta** [comment]
@P3rceval : on est d'accord que ce n'est pas en prod. si oui, j'ai donc tester en dev sur IDFM et ok pour moi.
