### ISSUE TITLE
Problème Dashboard Trajet sur les interfaces collectivité/opérateur/

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1642]
### J'ai pu observer 2 bugs sur le Dashboard.

1. Problème d'affichage des données en fonction de la date de début de la période sélectionnée. 2 exemples :

_Au niveau Territoire national, SI dans le filtre la date de début de période sélectionnée est < au "04 février 2020", les valeurs du graphique et les indicateurs ne se mettent plus à jour et affichent les mêmes résultats que la requête précédente. Il semble que la requête soit KO sans que cela n'affiche aucun message d'erreur. 
<img width="1650" alt="Capture d’écran 2022-02-03 à 12 54 14" src="https://user-images.githubusercontent.com/89770924/152338139-795ab42c-bfd3-4a22-8772-0e22e77f8734.png">

_Au niveau Territoire=Finistère, SI dans le filtre la date de début de période sélectionnée est < au "04 février 2020", les valeurs du graphique et les indicateurs ne se mettent plus à jour et affichent les mêmes résultats que la requête précédente. Il semble que la requête soit KO sans que cela n'affiche aucun message d'erreur. 

_Au niveau Territoire=Occitanie, SI dans le filtre la date de début de période sélectionnée est < au "21 février 2020", les valeurs du graphique et les indicateurs ne se mettent plus à jour et affichent les mêmes résultats que la requête précédente. Il semble que la requête soit KO sans que cela n'affiche aucun message d'erreur. 

2. Problème de rafraîchissement des données indicateurs dès lors qu'on a rencontré le Bug 1 (cf. ci-dessus)
_Lorsque je fais une recherche en rencontrant un des problèmes ci-dessus, (dans cet exemple, le bug dans la requête Occitane),  ENSUITE peu importe la nouvelle période saisie, les valeurs du graphique évoluent bien MAIS les valeurs des indicateurs affichés dans les tuiles sous le graphique n'évoluent pas.

<img width="1133" alt="Capture d’écran 2022-01-20 à 15 43 47" src="https://user-images.githubusercontent.com/89770924/150361661-0aef690f-2f24-4cc9-b933-dcaa5f037c65.png">

<img width="1211" alt="Capture d’écran 2022-01-20 à 15 45 02" src="https://user-images.githubusercontent.com/89770924/150361673-05157b10-9493-469c-b1ab-19c32d6f89bc.png">

### Environnement

Environnement (dev, prod...) : PROD
Navigateur : SAFARI
Utilisateur : compte territoire Occitanie (nviennot+occitanie@gmail.com) ET compte super Admin
URL : https://app.covoiturage.beta.gouv.fr/trip/stats

**Comment by nicolas-viennot-beta** [comment]
@jonathanfallon : j'ai fais une MAJ du ticket bug ci-dessus.

**Comment by jonathanfallon** [comment]
Vérifier la date butoir dans le backend. S'assurer que c'est pris en compte dans le frontend
Vérifier que les requêtes sont relancées à la modif des paramètres.

**Comment by nicolas-viennot-beta** [comment]
@P3rceval : Comme le fix a été testé en prod, je peux clore, right ?
