### ISSUE TITLE
Simulation d'une campagne

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#165]
# **1) Simulation semaines précédentes (territoire pour information) ~5 jours**
Je suis une AOM et je souhaite lancer une campagne d'incitation au covoiturage. J'ai déjà acté cette volonté et on m'a ouvert un accès au registre.
Je me connecte pour simuler deux politiques incitatives que j'ai en tête car j’hésite par exemple entre inciter le conducteur 2€ ou bien le passager à 1€. Je préfigure deux politiques et je constate que sur le mois dernier si j'avais lancé la politique 1 j'aurais eu 1400€ de dépenses VS 1200€ pour la politique 2.

- [x] Front
- [X] Back

Je vais choisir la politique 2.  Je peux exporter le résumé pour l’insérer directement dans ma proposition de délibération.

**Comment by margot-sanchez** [comment]
Cf maquette de Jérémie. Au lieu de lancer une campagne, enregistrer en brouillon avec une simulation. 
Endpoint Simulation en cours de construction.

**Comment by margot-sanchez** [comment]
Front volet 1)
![image](https://user-images.githubusercontent.com/15428433/96890829-53dc8200-1488-11eb-850f-658d050057b5.png)


Mettre un dropdown de selection de 1 2 3 mois. 
Uniquement valable sur les campagnes en brouillon et visible sur les pages récapitulatives.

**Comment by gillesboisson** [comment]
@margot-sanchez on intègre l'écran de simu dans la page de confirmation et dans le récap quand une campagne et en brouillon

**Comment by jonathanfallon** [comment]
J'ai des bugs sur l'environnement de `dev` avec le territoire 329 (IDFM).

![image](https://user-images.githubusercontent.com/1656255/100615332-c0fcf600-3317-11eb-9d92-968fe7bf4693.png)

Fichier `.har` avec la requête et la réponse : [request.zip](https://github.com/betagouv/preuve-covoiturage/files/5616119/request.zip)

**Comment by margot-sanchez** [comment]
Testé sur dev le 04/12/2020

Simulation sur 1 mois 👍 
Simulation sur 2 mois 👍 
Simulation sur 3 mois 👎  Sur deux mois et trois mois la simulation ne change pas. 
![image](https://user-images.githubusercontent.com/15428433/101144350-7b427500-3618-11eb-9930-25c64addb018.png)
![image](https://user-images.githubusercontent.com/15428433/101144388-8b5a5480-3618-11eb-9671-8c3d2ffa275f.png)

⚠️ **convertir la somme en €, actuellement ce sont des cts !**
