### ISSUE TITLE
Informer les opérateurs des AOM inscrites sur le registre. 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#166]
Reflexion pour savoir comment informer les opérateurs des AOMs inscrites sur le registre.

## Idées
1. Mettre à jour la page covoiturage.beta.gouv.fr ==> la plus simple
2. Avoir une notification sur l'interface opérateur "une nouvelle AOM est connectée au registre"
3. Pouvoir distinguer sur le module AOM des opérateurs de manière différenciée les AOMs connectées ou pas.

**Comment by margot-sanchez** [comment]
1) Ok +Information dans la newsletter.
2) Non retenue
3) Cf maquette de Jérémie & Margot pour avoir une carto.

**Comment by jonathanfallon** [comment]
Aujourd'hui le suivi est fait à la main et ça fonctionne très bien
