### ISSUE TITLE
Analyse des trajets Mobicoop en erreur

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1666]
Suite échange avec Mobicoop analyse des trajets en erreur, notamment ceux pour lesquels les motifs sont  : 

- DatetimeIdentityCollisionCheck : Nombre de trajet effectué par la même personne au même moment
- theoricalDistanceAndDurationCheck : Ratio entre la distance annoncée (dsa) et distance théorique(dst) + durée annoncée (dra) et durée théorique (drt)
- EndLatitudeCollisionCheck :Delta entre la latitude d'arrivée du conducteur et du passager

**Comment by nmrgt** [comment]
Après analyse, il s'agit d'une omission par l'opérateur de la clé de regroupement par véhicule. Ainsi, ces trajets ont été détecté comme étant suspicieux. Il FAUT que l'opérateur donne la clé de regroupement si les personnes sont dans le même véhicule.

**Comment by P3rceval** [comment]
J'ai transmis les éléments à Mobicoop
