### ISSUE TITLE
Calcul du montant à afficher

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1667]
| :warning: En cours de spécification          |
|:---------------------------|

### Problématique

Les attestations de covoiturage doivent refléter les dépenses (passagers) ou les recettes (conducteur) réelles du trajet. Dans le schema d'acquisition, le montant envoyé par l'opérateur est la valeur de la transaction réalisée. Le coût du trajet, supérieur à la transaction sur un trajet subventionné est reconstruit en interne par le RPC en faisant la somme du montant de la transaction (passenger_contribution ou driver_revenue) et des subventions (incentives).

Le montant de la transaction ne correspond pas forcément à coût résiduel supporté par le passager car on a plusieurs cas d'usage :

#### 1. L'opérateur calcule le montant des incitations

Il nous envoie le montant de la transaction et la liste des incitations calculées. La transaction correspond au montant final payé par le passager.

Le montant sur l'attestation correspond au montant de la transaction.

TODO : gérer le cas d'un résultat différent pour le calcul de l'incitation entre l'opérateur et le RPC. En comparant par n° de SIRET, on peut savoir pour quelle entité l'incitation a été calculée (AOM, opérateur, autre...) et comparer les valeurs. Le RPC calcule les incitations pour les AOM uniquement si la campagne est configurée et activée.

#### 2. L'opérateur ne calcule pas le montant des incitations

Le montant de la transaction envoyé correspond au coût du trajet. La liste des incitations est vide. Le RPC calcule les incitations et les applique pour avoir le montant payé par le passager.

Le montant sur l'attestation sera transaction - somme des incitations calculées par le RPC

**Comment by jonathanfallon** [comment]
Holiday-fix déployé en utilisant le paiement.

**Comment by nicolas-viennot-beta** [comment]
hello @jonathanfallon,peut-on fermer ce ticket ?

**Comment by jonathanfallon** [comment]
Pour le moment on affiche le montant du paiement envoyé dans la preuve sans y appliquer de recalcul. Dans l'API V3, les calculs seront faits côté opérateur donc ça réglera le problème.
