### ISSUE TITLE
Problème sur l'application : Erreur 503

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1685]
### Sujet

*Depuis 1 semaine, nous tombons de façon régulière sur une erreur 503 en naviguant sur l'app.

*Difficulté à reproduire l'erreur, il semble que le cas se présente à la suite d'un chargement de page trop long (Timeout)
Exemple de reproduction : 

- via mon compte admin, je lance une recherche de trajet sur la Guadeloupe ces 3 derniers mois.
- une fois le graphique chargé, je vais sur l'onglet "liste détaillée" et je clique sur la pagination "suivant" pour afficher la page n°2 de la liste
- Puis je clique à nouveau "suivant" dans la pagination pour voir la page°3. 
- => ET LA, le loader tourne trop longtemps avant d'afficher la page 503.

<img width="1620" alt="Capture d’écran 2022-03-09 à 14 15 56" src="https://user-images.githubusercontent.com/89770924/157449281-1901b0c7-1764-4ffd-a3e9-6b354d8a59a6.png">
<img width="1353" alt="Capture d’écran 2022-03-08 à 12 35 04" src="https://user-images.githubusercontent.com/89770924/157449291-3a5160f1-b431-40d9-b549-98ce253d7864.png">

Difficulté à reproduire l'erreur, il semble que le cas se présente à la suite d'un chargement de page trop long (Timeout)
### Environnement

Environnement (dev, prod...) :
Navigateur :
Utilisateur :
URL :

### Etapes pour reproduire / vérifier la bonne implémentation de l'amélioration

1. _Je clique sur ..._
2. _Je rentre la valeur ... dans ..._

_Ajouter des captures d'écran si nécessaire (Impr. écran et Ctrl-V directement ici)_

### Comportement attendu

1. _Je clique sur ... -> ouverture de la fenêtre_
2. ...

### Comportement actuel

1. _Je clique sur ... -> ouverture de la fenêtre_
2. ...

**Comment by jonathanfallon** [comment]
Quand un appel au backend (même en XHR) renvoie une erreur comme un timeout, toute l'interface passe en mode 503 ce qui n'est pas top pour l'expérience utilisateur.
L'idée de base était d'avoir une page 503 quand le backend est en erreur ou ne répond pas mais il faudrait pouvoir filtrer entre les affichages de pages et les appels XHR.

**Comment by P3rceval** [comment]
Je pense que c'est juste qu'on gère pas les erreurs 502 renvoyées par Express lorsque le timeout du socket ( configuré à 30s actuellement) est atteinte : 
![image](https://user-images.githubusercontent.com/6213517/172179484-5f36c34a-8f23-4ae2-8360-9a6a4dc1411d.png)
https://github.com/betagouv/preuve-covoiturage/blob/c7597bc638ed621f599e27e80f67271070f6dabf/dashboard/src/app/core/interceptor/http.interceptor.ts#L55
```
          case 0: // Unknown error
          case 503: // Maintenance mode
            if (this.can503(req)) this.router.navigate(['/503']);
            break;

```
