### ISSUE TITLE
Créer un tableau Metabase pour la DGEC

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1694]
### La DGEC dans le cadre de la réflexion sur les CEE nous demande les données suivantes : 

Fournir des graph de l'évolution **mensuelle** (en abscisse)
- du nombre de trajets; (en ordonnée)
- du nombre de km moyen et nbre de km médian des trajets (en ordonnée)
- du taux de remplissage moyen et taux de remplissage médian (en ordonnée)

Donner dans un camembert : 
- la répartition du nombre de trajets par classe avec le %

**Comment by jonathanfallon** [comment]
Stats ajoutées sur https://stats.covoiturage.beta.gouv.fr/dashboard/10-dgec
J'ai fait un histogramme avec des valeurs empilées pour la répartition des classes car ça permet de voir leur évolution dans le temps.
Calcul à affiner sur le nb de covoitureur-es par véhicule avec @Datayama38.
PS : calculer un tx de remplissage n'est pas possible car on ne connait pas la capacité de chaque véhicule.

**Comment by nicolas-viennot-beta** [comment]
hello @jonathanfallon : pour finir sur le tableau DGEC, peux-tu : 

- regarder pourquoi il y a une diff. du tx d'occupation avec l'observatoire

-ajouter une stat de la répartition en % des distance par tranche.

> Reprendre l'exemple ci-dessous mais avec  les lignes : 

> - Distance (km) pour les tranches : 0-3; 3-5; 5-10; 10-15; 15-20; 20-40; 40-60; 60-80; <80

> - Nbre de trajet

> - %


<img width="703" alt="Capture d’écran 2022-03-24 à 09 19 59" src="https://user-images.githubusercontent.com/89770924/159872698-c03c86f7-215c-4830-a698-66def3fe5082.png">
