### ISSUE TITLE
Amélioration de la précision des statistiques

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#17]
Améliorer les statistiques Bilan CO2 et Bilan Energie en fonction des éléments proposés [ici](https://registre-preuve-de-covoiturage.gitbook.io/produit/boite-a-outils/statistiques).

Bilan CO2
+20% en milieu dense urbain, portant la moyenne à 234 g CO2 équivalent par véhicule-kilomètre.
-10% sur les trajets extra-urbain, portant la moyenne à 175 g CO2 équivalent par véhicule-kilomètre.

Bilan énergie
0, 0564 kep / km / véhicule particulier, en milieu dense urbain.
0,0442 kep / km / véhicule particulier sur les trajets extra-urbain.

Pour ce faire la complexité est de définir une liste des CODES INSEE avec appartenance à milieu dense urbain/extra urbain. 

Se baser sur ceci : https://www.observatoire-des-territoires.gouv.fr/outils/cartographie-interactive/#bbox=-293810,6170362,1367404,769774&c=indicator&i=insee_rp_hist_1968.dens_pop&s=2016&view=map26

**Comment by jonathanfallon** [comment]
Export des AOM

**Comment by margot-sanchez** [comment]
@jonathanfallon je ne me souviens plus si tu m'as fait l'export ou pas. 
#amnésie

**Comment by margot-sanchez** [comment]
@jonathanfallon  UP

**Comment by margot-sanchez** [comment]
@jonathanfallon je te l'ai mis dans ce sprint comme vu ensemble, quitte à faire un truc propre sur la couverture du territoire autant intégrer ça. 

Attention : il y a un onglet tableau dans le lien communiqué à l'origine ! Se baser sur le tableau.

Je propose : 
0,0 à 104,8 ==> Territoire peu dense
104,9 à 31 731,0 ==> Territoire dense


Une fois réalisé, (moi) mettre la documentation à jour.

**Comment by margot-sanchez** [comment]
A voir avec @jonathanfallon !

**Comment by margot-sanchez** [comment]
Fait sur le back. A mettre à jour sur le front

**Comment by margot-sanchez** [comment]
Indiquer dans la documentation que finalement cela ne sera pas fait. Raison : complexité lorsque les trajets sont avec une OD sur des typologies différentes.

**Comment by margot-sanchez** [comment]
Documentation mise à jour
