### ISSUE TITLE
Migration PROD de scalingo vers scaleway

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1706]
Prérequis : Gestion Log, config Alert Manager (à minima archivage des log. et quelques alertes clés. )
Estimation : 2 sem.

Doc de spec global : https://hackmd.io/ZgdGjcK5TMi0NxyrQJCgKA?edit

**Comment by jonathanfallon** [comment]
En cours. voir les tickets infra
