### ISSUE TITLE
Fraude inter-opérateur : nouvelle analyse sur la répartition des fraudeurs 

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1717]
Peut-on mesurer si la fraude inter opérateur est principalement réalisée sur des trajets dont les passagers bénéficient de la gratuité du trajet car ils ont un pass navigo. 

- on peut voir cela si la passager_contribution=0, non ?

**Comment by P3rceval** [comment]
@nicolas-viennot-beta on peut clore celui-ci peut-être ?
