### ISSUE TITLE
Ajout de 2 indicateurs dans le Dashboard DGEC de Metabase

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1726]
### Ajout de 2 indicateurs dans le Dashboard DGEC de Metabase : 

- Kilométrage moyen&médian par trajet  par opérateur sur les 12 derniers mois (période glissante)
- Nbre de trajets moyen/médian par conducteur  par opérateur sur les 12 derniers mois (période glissante)
<img width="751" alt="Capture d’écran 2022-05-11 à 17 21 08" src="https://user-images.githubusercontent.com/89770924/167886994-bc6dd4f6-73f3-4be4-bd1f-2480c1cd9741.png">

**Comment by P3rceval** [comment]
Done, j'attends tes retours :)
