### ISSUE TITLE
:fire: Migration le paramétrage des campagnes existantes qui utilisent `insee_whitelist_filter` or `insee_blacklist_filter`

### ISSUE THREAD

**Issue by P3rceval** [betagouv/preuve-covoiturage#1743]
https://mattermost.incubateur.net/betagouv/pl/g496rf8a3bf4m8cx6br5r45ino

Script de migration SQL

Campagnes impactées : 
- IDFM
- PDLL
- NM

**Comment by nmrgt** [comment]
Ça concerne aussi les règles "territory filter" et je pense qu'il faut migrer toutes les campagnes (y compris celle en brouillon) pour éviter les erreurs par la suite.

**Comment by P3rceval** [comment]
J'préfère qu'on perde pas trop de temps sur les campagnes en brouillons sachant que c'est nous qui allons faire le paramétrage des nouvelles campagnes dorénavant.

**Comment by P3rceval** [comment]
Rajouter [ici](https://hackmd.io/Qas-d_1lQOeg3HaDM3JKLw?view#2-Migration-r%C3%A8gle-param%C3%A9trage-d%E2%80%99exlusions--inclusions-de)
