### ISSUE TITLE
Demande fonctionnelle : inclure dans l'export opérateur les trajets non "ok"

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#1747]
Demande d'un opérateur : afin de pouvoir debugger les trajets sans passer par l'API, il est demandé que l'export des trajets côté opérateur inclut l'ensemble des trajets envoyés - y compris ceux ayant été mis de côté par le service de détection d'anomalie.

cc @nicolas-viennot-beta

**Comment by nicolas-viennot-beta** [comment]
ok parfait. tu saurais me dire quel opérateur a fait la demande?

**Comment by P3rceval** [comment]
@nicolas-viennot-beta toujours d'actualité ?

**Comment by nicolas-viennot-beta** [comment]
oui mais je vais la repasser dans backlog car moins prioritaire.

**Comment by P3rceval** [comment]
J'ai ajouté la colonne status et les trajets != 'ok' pour le registre et les opérateurs
