### ISSUE TITLE
E-03 / US "Sélection des Filtres"

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1753]
<img width="1203" alt="Capture d’écran 2022-06-21 à 17 03 16" src="https://user-images.githubusercontent.com/89770924/174832948-6258fc34-81ff-4a39-9b30-3849882776bf.png">

### Résumé de l'us

>  **"En tant qu'utilisateurs, j'applique des filtres afin d'effectuer une analyse rapide des trajets sur mon tableau de bord"**

>  **Utilisateurs concernés par l'us :**
> - Administrateur : ✅
> - Collectivité (compte complet): ✅
> - Opérateur: ✅

> URL concernée : https://app.covoiturage.beta.gouv.fr/trip/stats

> Epic concernée : E03 - Suivi résumé des trajets
--------------
### Filtres à supprimer pour tous les utilisateurs

- Filtre "jours de la semaine"
- Filtre "Km min et Km max"
- Filtre Classes
- Filtre Statut

### Récapitulatif des Filtres à conserver en fonction des utilisateurs

| Colonne 1 | User Admin | User Territoire | User Opérateur |
|-----------|-----------|-----------|-----------|
| Filtre "Dates" | x | x | x |
| Filtre "Territoire" | x | x | x |
| Filtre "Campagne" | x |  |  |
| Filtre "Opérateur "| x | x |  |

<img width="654" alt="Capture d’écran 2022-06-23 à 16 36 20" src="https://user-images.githubusercontent.com/89770924/175325802-b181bacf-f4c5-417b-a088-c00d9d74b0fe.png">

### Fonctionnement des filtres

**_Dates :** 
- Utilisateurs : 
  - Administrateur ✅; Collectivité (compte complet) ✅; Opérateur: ✅
- Intitulé : 
  - Titre du champ : Remplacer "Dates et Horaire" par "Dates"
  - Placeholder : pas de changement
- Fonctionnement : 
  - limiter la sélection aux dates postérieures aux 12 derniers mois.
  - par défaut les champs "début" et "fin" sont renseignés sur la période la plus large. Début=(J-5)-12mois; Fin=J-5
  - --> En résumé, reprendre les mêmes comportements & règles que les champs date de la fonction Export

**_Territoires :** 
- Utilisateurs : 
  - Administrateur ✅; Collectivité (compte complet) ✅; Opérateur: ✅
- Intitulé : 
  - Titre du champ : mettre "Zone géographique"
  - Placeholder : mettre "Commune, EPCI, AOM..."
- Fonctionnement : 
  - possibilité de saisir des communes, EPCI, AOM 
    - Administrateur & Opérateur : Saisie de tous les communes, EPCI, AOM 
    - Collectivité : Saisie uniquement des communes et EPCI appartenant à l'AOM en question
  - la liste de suggestion complétion doit être plus large afin de rendre visible l'entièreté du territoire
<img width="308" alt="Capture d’écran 2022-06-24 à 13 53 38" src="https://user-images.githubusercontent.com/89770924/175529308-5ab7722f-999b-44d8-9972-eabe8db26482.png">
  - Question: pourquoi ne pas mutualiser la feature de complétion avec Observatoire ? pas les mêmes résultats.
  - --> Reprendre les mêmes comportements & règles que les champs date de la fonction Export

**_Campagne :** 
- Utilisateurs : 
  - Administrateur ✅; Collectivité (compte complet) 🛑; Opérateur: 🛑
- Intitulé : 
  - Titre du champ : Campagne
  - Placeholder : Campagne
- Fonctionnement : 
  - identique à l'actuel.
 
**_Opérateurs :** 
- Utilisateurs : 
  - Administrateur ✅; Collectivité (compte complet) ✅; Opérateur: 🛑
- Intitulé : 
  - Titre du champ : Opérateurs
  - Placeholder : Opérateurs
- Fonctionnement : 
  - identique à l'actuel.

**Comment by jonathanfallon** [comment]
Les filtres et la liste des trajets a été supprimée. US à réécrire pour la nouvelle interface
