### ISSUE TITLE
Ne pas déployer le front sur la prod lors d'un merge d'une PR sur l'infra

### ISSUE THREAD

**Issue by P3rceval** [betagouv/preuve-covoiturage#1757]

**Comment by nmrgt** [comment]
@P3rceval In fine je viens de regarder et le trigger c'est la création d'une release donc je suis pas certain qu'on puisse faire beaucoup mieux sauf à intégrer le front dans le container du back (cf discussion qu'on a eu à ce sujet). Je ferme?
