### ISSUE TITLE
E-05 / US "Consulter les APDF"

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1761]
<img width="530" alt="Capture d’écran 2022-06-27 à 10 54 41" src="https://user-images.githubusercontent.com/89770924/175900451-cc740716-5dc2-4cf7-90ba-519bb8acc6cd.png">

### Résumé de l'us

>  **"En tant qu'utilisateurs, je souhaite consulter les APDF recalculés par le RPC à des fins de confirmations"**

>  **Utilisateurs concernés par l'us :**
> - Administrateur : ✅
> - Collectivité (compte complet): ✅
> - Opérateur: ✅

> URL concernée : https://app.covoiturage.beta.gouv.fr/campaign/xxxx

> Épic concernée : E05 - Suivi de la campagne

--------------
### Spec du bloc APDF à ajouter sous le résumé du paramétrage de la campagne

- Principe général : 
  - Le tableau récapitulatif affiche le résumé des APDFs des 12 derniers mois : 
  - Tous les 6 du mois, on ajoute les APDFs du mois précédent. 

- Intitulé du bloc : "Appels de fonds - Récapitulatif des 12 derniers mois"
- Intitulé et contenu des colonnes : 
  - Colonne 1 : 
    - Intitulé : "Mois" 
    - Contenu : mois de l'appel de fond
 - Colonne 2 : 
   - Intitulé : "Opérateur" 
   - Contenu : Nom de l'opérateur concerné par le calcul des appels de fond
 - Colonne 3 (uniquement accessible pour les super Admin) : 
   - Intitulé : "Trajets" 
   - Contenu : Nombre total de trajets éligibles sur la période pour un opérateur donné
 - Colonne 3bis : 
   - Intitulé : "Trajets incités" 
   - Contenu : Nombre total de trajets incités sur la période pour un opérateur donné
 - Colonne 4 : 
   - Intitulé : "Montant d'indemnisation (€)" 
   - Contenu : Montant Total des indemnisations versés sur la période pour un opérateur donné
 - Colonne 5 : 
   - Intitulé : "Rapport complet" 
   - Contenu : Bouton de téléchargement du fichier. (spécification du fichier ci-dessous)

### Vues

- opérateur : ne montrer que les APDF de cet opérateur pour la campagne concernée.
- territoire : montrer les APDF de chaque opérateur partenaire de la campagne concernée.
- admin : idem territoire

### Spécification fichier Excel
- création d'un fichier similaire à celui créé par Julien aujourd'hui.
- modification automatique de certains intitulés de colonne
- série de test automatique sur les fichiers ? (controle des calculs de tranche ?)

### Bloc de Contenu
Sous le bloc APDF, intégrer un bloc de contenu ---> Voir ticket : E-04 / US "Consulter le bloc de contenu"

**Comment by P3rceval** [comment]
@nicolas-viennot-beta , est-ce que c'est OK selon toi de remplacer l'actuel tableau croisé dynamique pour les tranches par un tableau simple, en dur ? ( Pas d’interaction avec les données sources, pas de filtre ect ...) ?

**Comment by nicolas-viennot-beta** [comment]
@P3rceval : est-ce une grosse surcharge d'augmenter la période d'archivage de 3 mois à 6mois ?

**Comment by P3rceval** [comment]
Non ça prend 0 temps en plus

**Comment by nicolas-viennot-beta** [comment]
Hello Julien, 

oui, ajoutons l'info bulle.

**Comment by jonathanfallon** [comment]
déployé en v2.9.1 (avec des fonctionnalités de base)

**Comment by jonathanfallon** [comment]
**Refacto**

- déplacer les actions export et list des APDF dans le service Policy
- Utiliser un provider de nom de fichier d'APDF pour les centraliser et les normaliser
- Utiliser l'id de la campagne et non celle du territoire
- renommer en `funding requests` ce qui est un traduction plus correcte ;)

**Comment by nicolas-viennot-beta** [comment]
Ne pas oublier de classer les mois du bloc appel de fond par ordre anti-chronologique.

**Comment by jonathanfallon** [comment]
**TODO**

- [ ] terminer le refacto pour déplacer l'export dans le service `policy`

**Comment by nicolas-viennot-beta** [comment]
@jonathanfallon : Normalement, on affiche les APDFs que des 12 derniers mois. Il faudra : 
- modifier le texte "Appels de fonds - Récapitulatif des 6 derniers mois" et le remplacer par "Appels de fonds - Récapitulatif des 12 derniers mois"
- appliquer la règle car elle n'est pas en place (cf. IDFM)
<img width="993" alt="Capture d’écran 2023-03-09 à 13 22 04" src="https://user-images.githubusercontent.com/89770924/224021707-e6bb8352-1cf6-496d-9ccf-14b2de3301ae.png">
