### ISSUE TITLE
E-05 / US "Consultation de la liste des campagnes"

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1770]
<img width="697" alt="Capture d’écran 2022-07-04 à 15 12 05" src="https://user-images.githubusercontent.com/89770924/177162028-b6440702-eacc-4db1-8b1b-1de0c358c119.png">

### Résumé de l'us

>  **"En tant qu'utilisateurs (Admin, collectivités ou opérateurs), j'affiche la liste des campagnes qui me concerne afin de consulter une synthèse des campagnes en cours, en brouillon et terminée et de sélectionner la campagne de mon choix."**

>  **Utilisateurs concernés par l'us :**
> - Administrateur : ✅
> - Collectivité (compte complet): ✅
> - Opérateur: ✅

> URL concernée : https://app.covoiturage.beta.gouv.fr/campaign/list

> Épic concernée : E05 - Suivi de la campagne
--------------
### Spec de la liste 

- Titre H1 différent en fonction de l'utilisateur
  - Administrateur : Liste des campagnes sur tous les territoires
  - Collectivité : Toutes vos campagnes paramétrées sur le RPC
  - Opérateur : Toutes vos campagnes paramétrées sur le RPC

- Titre H2 : Campagnes

- Fonctionnement général : 
  - reprendre pour les 3 typologies d'utilisateur l'UX de l'actuelle liste utilisateur "Admin" 
  - y ajouter une colonne "Consommation estimée" (cf. détail ci-dessous)

- Spec du tableau : 
  -  Colonne 1 
     - Intitulé : Statut
     - Fonctionnement : selon le statut de la campagne affichée de son statut matérialisée par son pictogramme et au roll over son info bulle : "En cours", "Brouillon" ou "Terminée" 
     - **WARNING :  L'utilisateur Opérateur ne voit que les campagnes en statut "En cours", ET "Terminée".**
  - Colonne 2
    - intitulé : Début
    - Fonctionnement : date de début de la campagne au format jj/mm/aaaa
  - Colonne 3
    - intitulé : Fin
    - Fonctionnement : date de fin de la campagne au format jj/mm/aaaa
  - Colonne 3
    - intitulé : Nom de la campagne
    - Fonctionnement : 
      - affichage du nom dont la nomenclature conseillée est "#n°campagne_NomTerritoire_Annee&MoisDebut" , exemple : "#1_LAVALAGGLO_2022_01"
      - au clic sur le nom de la campagne, ouverture de la page détail correspondante : https://app.covoiturage.beta.gouv.fr/campaign/xxxx
  - Colonne 4
    - intitulé : Territoire
    - Fonctionnement : affichage du nom de l'aom
  - Colonne 5
    - intitulé : Budget
    - Fonctionnement : affichage du montant de la campagne
  - Colonne 6
    - intitulé : Consommation estimée
    - Fonctionnement : affichage du montant de la consommation estimée

**Comment by nicolas-viennot-beta** [comment]
Intégration de la Colonne 6 dans un 2ème temps

**Comment by jonathanfallon** [comment]
- Ajouter le bouton campagnes dans le menu à côté de trajets
- Ordonner par statut
- Ajouter la colonne de budget

**Comment by P3rceval** [comment]
https://github.com/betagouv/preuve-covoiturage/pull/1865

**Comment by jonathanfallon** [comment]
#1865 mergée. Il reste :
-  Ajouter Colonne consommation estimée (fait dans un second temps après que le cache soit mis en place)

Avec un calcul quotidien de l'estimation dans un champ de la table `policy.policies` (`estimate` ?)
Ça permettra de mettre la valeur en "cache" pour la journée, de l'afficher dans la liste des campagnes et dans la page instantanément (aujourd'hui, on a une requête un peu lourde à chaque affichage de page).

**Comment by P3rceval** [comment]
https://github.com/betagouv/preuve-covoiturage/pull/1870
