### ISSUE TITLE
Problème affichage statistique Metabase

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1776]
##Sujet : Problème d'affichage d'un indicateur sur Metabase

--> Tableau de bord Ministère : https://stats.covoiturage.beta.gouv.fr/dashboard/7-ministere
--> Indicateur "Trajets par semaine"
<img width="1361" alt="Capture d’écran 2022-07-12 à 15 31 41" src="https://user-images.githubusercontent.com/89770924/178502045-26b86369-8d35-4e9b-a664-f8c8aea77049.png">

###Problème identifié : 

-> cet indicateur doit fournir des données hebdomadaires mais il ne prend pas en compte les 3 dernières semaines écoulées. 
exemple au 12 juillet, la dernière semaine affichée est celle du 20 au 26 juin alors que nous aurions pu avoir les semaines 27juin au 3 juilllet et 4 au 10 juillet.

est-ce un bug ou est-ce la requête qui n'affiche que les semaines du mois en cours ?

**Comment by P3rceval** [comment]
@nicolas-viennot-beta j'ai fix la requête j'te laisse me dire si c'est bon

**Comment by nicolas-viennot-beta** [comment]
tu gères. 👌
