### ISSUE TITLE
Problème de la fonctionnalité d'export pour les régions

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1780]
### Problème#1 : pas de distinction avec l'auto complète des région et des AOM.
exemple dans capture écran avec le territoire "occitanie"
<img width="1064" alt="Capture d’écran 2022-07-13 à 15 48 18" src="https://user-images.githubusercontent.com/89770924/178749630-f41f3777-4a46-46e2-aea4-cfe6a84505c1.png">

### Problème#2 : fichier vide dès lors qu'on sélectionne la région ou l'AOM (l'un des 2)
--> cf. fichier csv vide
[covoiturage-ee1379d5-ae21-4a42-911d-dffd735404e0.csv](https://github.com/betagouv/preuve-covoiturage/files/9102784/covoiturage-ee1379d5-ae21-4a42-911d-dffd735404e0.csv)

**Comment by P3rceval** [comment]
Je fais celui la maintenant pour PDLL

**Comment by P3rceval** [comment]
#1791

**Comment by nicolas-viennot-beta** [comment]
@P3rceval : pour rappel, le 2ème point du ticket reste à traiter
