### ISSUE TITLE
Problème d'affichage de graphique - Pays des écrins

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1783]
### Problème d'affichage de graphique - Pays des écrins

Envir : PROD
Navigateur : Opéra, Safari

Le graphique de la page https://app.covoiturage.beta.gouv.fr/trip/stats ne s'affiche pas lorsqu'on est sur une connexion Territoire : 
<img width="1050" alt="Capture d’écran 2022-07-18 à 11 43 43" src="https://user-images.githubusercontent.com/89770924/179485793-7753011a-9fd3-47e5-88e4-4f26d2d992fb.png">

On a essayé de restreindre le filtre période mais cela ne change rien.

EN REVANCHE, le graphique s'affiche lorsqu'on est connecté en tant qu'Admin.

**Comment by P3rceval** [comment]
@nicolas-viennot-beta ce problème semble résolu sans qu'on soit intervenu... 
J'te laisse clore le ticket si c'est aussi OK pour toi

**Comment by nicolas-viennot-beta** [comment]
exact. étrange. je clos
