### ISSUE TITLE
Rejouer jeu de données open data

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1785]
### Rejouer jeu de donnée open data

Nouveau jeu doit comprendre : 
- le correctif évoqué par Julien lors du point équipe et que je n'ai pas noté ;)
- le correctif sur les zones frontalières que @Datayama38 doit apporter

**Comment by P3rceval** [comment]
Les transfrontaliers sont OK. Je regarde le problème https://github.com/betagouv/preuve-covoiturage/issues/1809 et je rejoue pour Juin/Juillet.
