### ISSUE TITLE
Régression sur fonctionnalité d'export à J+1 des opérateurs (ce n'est pas un bug)

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1790]
###  Régression sur fonctionnalité d'export à J+1 des opérateurs

Besoin : permettre aux utilisateurs "opérateurs" de pouvoir faire des exports à J+1
<img width="1142" alt="Capture d’écran 2022-07-21 à 17 13 06" src="https://user-images.githubusercontent.com/89770924/180254062-e056780b-82de-4adf-b2f0-569bd3eea1ca.png">

**Comment by P3rceval** [comment]
@nicolas-viennot-beta c'est fixé en prod, j'te laisse tester

**Comment by nicolas-viennot-beta** [comment]
@P3rceval, là on peut télécharger les trajets du jour même, à savoir J+0 et non J+1. c'est normal? on n'avait pas une contrainte ?
