### ISSUE TITLE
Automatisation des APDFs - Tests à appliquer

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1792]
Suite échange avec Vic et Jo, liste des tests qui pourraient être mis en place pour vérifier les APDFs

**Besoin #1 : Tests que réalisaient Vic et Jo avant envoi des APDFs :** 

- calcul rapide pour vérifier les volumes et montants par tranche minimum et maximum (Attention :  cas marginal de PMGF qui nécessiterait que cette vérification se fasse avant la consolidation des 2cas de campagne))
- vérifier que les incitations=0 ne soient pas comptabilisées dans le nbre de trajets incités.
- vérifier que le plafond n’est pas dépassé lors de l’envoi des APDF 
- vérifier l’écriture de la formule des tranches et veiller à ce qu’aucune erreur ne modifie le TDC
- vérification de l’application des paramètres : 

	- ex : territoires exclus dans le fichier

Construction du CSV : ne pas agréger plusieurs campagnes dans une seule colonne (exemple : campagne 1 dans incitation_rpc_1_amount; campagne 2 dans incitation_rpc_2_amount) 

**Besoin #2 : Création d'indicateurs d'alerte visant à prévenir d'un risque d'erreur ur les APDFs** 

Mesure : 
- écart de volume de trajet incités entre mois m-1 et mois m : 
- écart entre la tendance d’évolution des incitations du territoire sur le mois m vs tendance d’évolution nationale
- écart au sein d’une campagne multi d’un entre la tendance d’évolution d’un opérateur vs les autres (à n’appliquer que sur BBCD, Klaxit et Karos) 
- écart entre les volumes de trajets incités vs les volume de trajets globaux 

Process : si 1 des indicateurs est positif, alors l'APDF n'est pas affiché et les développeurs sont prévenus avec priorisation sur la vérification et validation des APDFs.

**Comment by nicolas-viennot-beta** [comment]
@P3rceval : Ticket à évoquer ensemble d'ici la fin de semaine.

**Comment by P3rceval** [comment]
Mes remarques : 

- calcul rapide pour vérifier les volumes et montants par tranche minimum et maximum (Attention : cas marginal de PMGF qui nécessiterait que cette vérification se fasse avant la consolidation des 2cas de campagne))
On parle de simplement multiplier le nombre de trajets par un montant d'incitation fixe ? Exemple IDFM nbtrajets * 1.5 ?
:heavy_check_mark: 

- vérifier que les incitations=0 ne soient pas comptabilisées dans le nbre de trajets incités.
Je ne sais pas si ce check sera pertinent une fois le calcul des tranches automatisé

- vérifier que le plafond n’est pas dépassé lors de l’envoi des APDF
:heavy_check_mark: 

- vérifier l’écriture de la formule des tranches et veiller à ce qu’aucune erreur ne modifie le TDC
Plus de formule excel une fois que la génération automatisée

- vérification de l’application des paramètres :
  ex : territoires exclus dans le fichier
:heavy_check_mark: 

- Construction du CSV : ne pas agréger plusieurs campagnes dans une seule colonne (exemple : campagne 1 dans incitation_rpc_1_amount; campagne 2 dans incitation_rpc_2_amount)
Plus ce problème là une fois les tranches automatisées

J'pense que mettre en place les indicateurs sera beaucoup plus simple et rapide que les checks du besoin 1.

**Comment by nicolas-viennot-beta** [comment]
ok avec ton retour
