### ISSUE TITLE
APDF JUIN PMGF BBCD : Delta soulevé par S.Wodehouse

### ISSUE THREAD

**Issue by victorstefanini** [betagouv/preuve-covoiturage#1795]
###Sujet : APDF JUIN PMGF BBCD : Delta soulevé par S.Wodehouse

### Problème :** 
Blablacar a remonté un delta dans les trajets qu'ils comptabilisent et notre export de Juin sur PMGF : 

Ils enregistrent une différence de plus de 1000 trajets, en plus des 1480 communiqués. Ces trajets sont répartis un peu partout sur le territoire du PMGF. 

En pièce jointe, ils nous ont fournit des exemples de trajets qu'ils ne retrouvent pas dans nos données. 
[extract_PGMF_missing_trips_rpc_20220728.csv](https://github.com/betagouv/preuve-covoiturage/files/9210849/extract_PGMF_missing_trips_rpc_20220728.csv)

**Comment by victorstefanini** [comment]
@P3rceval 
@nicolas-viennot-beta

**Comment by nicolas-viennot-beta** [comment]
@P3rceval : ticket à ne pas traiter pour l'instant. En attente de précisions coté BlaBlacar D.

**Comment by nicolas-viennot-beta** [comment]
@P3rceval : hello Julien, j'ai modifié le ticket et ajouté un Excel avec les ID des trajets que Blabla ne trouve pas .Si on peut prioriser dessus lundi pour être sur qu'on a pas un souci sur les APDFs.

**Comment by nicolas-viennot-beta** [comment]
rappel règle campagne : `

**Comment by P3rceval** [comment]
Constat : surtout sur des trajets du Genevoie. 
->  en attente du fix sur les trajets transfrontaliers pour voir si le nombre de trajets incités augmente

**Comment by P3rceval** [comment]
Suite investigation : 
Des trajets envoyés comprenaient des incitations avec un numéro de siret vide ("siret": ""), retour 400 BAD_REQUEST du RPC et n'ont donc pas été process.
