### ISSUE TITLE
Spécifications de la route GET /journeys/:journey_id

### ISSUE THREAD

**Issue by stephdz** [betagouv/preuve-covoiturage#1807]
Nous utilisons la route `GET /journeys/:journey_id` pour récupérer le statut des trajets envoyés. Pendant nos développements, nous nous sommes aperçus que la spec présente [ici](https://tech.covoiturage.beta.gouv.fr/operateurs/api-v2.html) ne correspond pas du tout à ce qui est renvoyé par la route en question.

En fouillant un peu, je suis tombé sur #783 qui semble correspondre au développement de cette route.

J'ai donc plusieurs questions :
- L'issue #783 peut-elle actuellement être utilisée comme spec sans partir dans une mauvaise direction ? Par exemple, j'ai remarqué que le statut des trajets avaient changé (par exemple `fraud_error` devient `fraudcheck_error`).
- Est-ce bien ce qui est déployé en préprod et en prod ?
- Pouvez-vous mettre à jour la spec de l'API afin que tout le monde ait les bonnes informations ?

**Comment by nmrgt** [comment]
Hello @stephdz 
Merci pour ton ticket. 

Effectivement il y a une route GET /journeys/:journey_id qui permet de récupérer le statut du trajet. L'API v3 est en cours de spécification, n'hésite pas à y faire des remarques si besoin #1663 

Si jamais tu as besoin d'aide, tu peux écrire au support technique du registre.
Bonne journée
