### ISSUE TITLE
Problème application zoom sur carte densité

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1810]
### Sujet

Le zoom ne s'applique pas sur la Carte "densité de trajet"

### Environnement

Environnement (dev, prod...) : demo
Navigateur :Safari

<img width="1426" alt="Capture d’écran 2022-08-22 à 16 51 33" src="https://user-images.githubusercontent.com/89770924/185951935-5f70fe59-5a57-4191-8450-9ca19100e2bc.png">

**Comment by Datayama38** [comment]
Le zoom fonctionne correctement. Dans ton exemple, il doit y avoir un trajet très longue distance qui empêche la bounding box d'être centrée sur Rennes métropole.

**Comment by nicolas-viennot-beta** [comment]
J'ai cru répliqué ce comportement plusieurs fois. je re-check

**Comment by nicolas-viennot-beta** [comment]
ok right.
