### ISSUE TITLE
Problème d'ancre au clic sur un 1 lien hypertexte du glossaire

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1812]
### Sujet

Lorsqu'on clic sur un terme expliqué sur le glossaire, la page du glossaire s'ouvre bien mais, l'ancre n'est pas activée dans la page. Il faut donc scroller pour retrouver la définition.

### Environnement

Environnement (dev, prod...) : démo
Navigateur : safari et chrome
<img width="1649" alt="Capture d’écran 2022-08-22 à 17 09 22" src="https://user-images.githubusercontent.com/89770924/185956095-b41e0621-db8b-4576-8957-383260bdf965.png">

<img width="1351" alt="Capture d’écran 2022-08-22 à 17 09 06" src="https://user-images.githubusercontent.com/89770924/185956120-5bc07bd7-a1f2-4505-8159-a3f6a54362cc.png">

**Comment by Datayama38** [comment]
done
