### ISSUE TITLE
Problème de zoom lorsqu'on Edit un territoire avec un Reset

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1813]
### Sujet

Lorsqu'on sélectionne un territoire PUIS que l'on clic sur le bouton FERMER (croix), cela ré-affiche par défaut la France MAIS en dé-zoomant pour avoir également de DOMTOM

A faire : limiter le dé zoom à la france métropolitaine.

### Environnement

Environnement (dev, prod...) : Démo
Navigateur : Safari et Chrome

<img width="1597" alt="Capture d’écran 2022-08-22 à 17 15 16" src="https://user-images.githubusercontent.com/89770924/185957870-448bb82c-3f58-48de-866a-adf1b28c92b4.png">

<img width="1544" alt="Capture d’écran 2022-08-22 à 17 16 26" src="https://user-images.githubusercontent.com/89770924/185957908-df141c11-cec4-48e0-bed1-59c46219593e.png">

**Comment by Datayama38** [comment]
done
