### ISSUE TITLE
Résolution investigation écarts de trajets RPC vs Klaxit 

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1820]
### Sujet

Suite des échanges emails " "

### Environnement

Faire requête pour calculer : 
- volume de trajets Klaxit mis en erreur sur tous le territoire pour les mois de mai, juin et  juillet 
- volume de trajets Klaxit mis en erreur sur IDFM uniquement  pour les mois de mai, juin et  juillet + Préciser dans une colonne 
- Volume de trajets Klaxit mis en erreur sur IDFM ayant pour motif "datetimeIdentityCollisionCheck"
- Volume de trajets Klaxit mis en erreur sur IDFM ayant pour motif ""A/R aux mêmes horaires""

exemple tableau : 

  | Mai | Juin | Juillet
-- | -- | -- | --
Volume Total des Trajets KLAXIT en fraude check error sur tout le territoire |   |   |  
Volume Total des Trajets KLAXIT en fraude check error sur IDFM uniquement |   |   |  
Volume Trajets KLAXIT en fraude check error ayant pour motif "datetimeIdentityCollisionCheck" |   |   |  
Volume Trajets KLAXIT en fraude check error ayant pour motif "A/R aux mêmes horaires" |   |   |

**Comment by jonathanfallon** [comment]
https://github.com/betagouv/preuve-covoiturage/security/advisories/GHSA-6fx3-8643-3hw5
