### ISSUE TITLE
Amélioration de la fonctionnalité de monitoring des dates sur la carte ""Densité de trajets....."

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1822]
### Sujet

sur la carte ""Densité de trajets.....", il y a la possibilité d'affiner la plage temporelle de visualisation. 

*Pourras-tu me rappeler pourquoi cette feature ne concerne que cette carte?*

Afin d'en simplifier l'usage, ne serait-il pas pertinent de : 
- limiter la sélection des dates au mois sélectionné dans le bandeau bleu ?
- ne pas permettre à la date de fin d'être antérieure à la date de début

<img width="1639" alt="Capture d’écran 2022-08-30 à 18 16 42" src="https://user-images.githubusercontent.com/89770924/187501731-1a80f71b-d24f-4c2a-ac59-a07878e04a83.png">

**Comment by Datayama38** [comment]
Je peux changer la transparence. ça sera un peu mieux pour les zones denses mais moins bien pour les zones peu denses.
Pour la date. Au début j'avais limité à la période du mois mais on perd la possibilité de voir ce qui se passe sur un ou plusieurs jours.
Je peux peut être mimité le choix au mois en cours et ne pas permettre à la date de fin d'être antérieure à la date de début

**Comment by nicolas-viennot-beta** [comment]
@Datayama38 : ok si tu veux on peut se faire un rapide échange demain sur ce ticket. Dis moi quel créneau t'arrange ?
