### ISSUE TITLE
Analyse Fraude inter opérateur

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1834]
### Rappel

Julien avait en Janvier fait une analyse de volumétrie des trajets que le RPC détectait comme de la fraude inter opérateur.
Pour cela, il faisait une requête pour identifier les collisions entre des trajets ayant les mêmes : 
numéros de tel tronqués pour le conducteur et le passager + me^me horaire de départ (à 10mn près) + même Origine du trajet (à distance de xxxxm près).

Voir son travail sur le hackMd => https://hackmd.io/X4noOFYFRxSGH1Y2wjh9RA?view

En résumé, on avait conclu qu'il y avait à peu près 4% de trajets en cloison pour IDFM.

### Besoin

BlaBlacar Daily nous demande aujourd'hui de recommencer cette analyse sur les derniers mois et de faire l'exercice en modifiant les critères "horaire de départ" et "Origine du trajet)

Il faut donc refaire une analyse dont la restitution serait le tableau ci-dessous.
Attention, il faudra s'accorder en amont sur la variabilité des paramètres.

  | Nbre de trajets IDFM | Nbre de trajets IDFM en collision avec Paramètres de Julien | Nbre de trajets IDFM en collision avec Paramètre Horaire départ 30mn | Nbre de trajets IDFM en collision avec Paramètre Origine trajets 500m | Nbre de trajets IDFM en collision avec Paramètre xxxxxxxxx
-- | -- | -- | -- | -- | --
mars-22 |   |   |   |   |  
avr-22 |   |   |   |   |  
mai-22 |   |   |   |   |  
juin-22 |   |   |   |   |  
juil-22 |   |   |   |   |  
août-22 |   |   |   |   |

**Comment by jonathanfallon** [comment]
Vu en interne

**Comment by nmrgt** [comment]
En cours, nécessite d'optimiser les algo
