### ISSUE TITLE
republier les jeux de données open data qui conrtiennent la données incitation sans cette donnée.

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1854]
### republier les jeux de données open data qui contiennent la données incitation sans cette donnée.

Pour info : nous l'afficherons dès lors que cette donnée est complète. ce n'est pas le cas aujourd'hui.

**Comment by P3rceval** [comment]
@nicolas-viennot-beta Je ne suis pas sur d'avoir compris ce ticket. J'veux bien un exemple ^^

**Comment by nicolas-viennot-beta** [comment]
:) pas clair du tout. 

Contexte : Depuis quelques mois, on affiche dans le set open data, la donnée "trajets incité = OUI/NON".
MAIS on s'est rendu compte qu'elle n'était pas complète. On a alors demandé aux opérateurs de travailler dessus, ce qu'ils font actuellement. 

Besoin : Afin que cette information partielle ne soit à l'origine de biais d'analyse par des tiers, on souhaite qu'elle soit retirée des derniers set open data et qu'on ne l'ajoute que lorsque les opérateurs seront prêt (donnée exhaustive).

**Comment by P3rceval** [comment]
Tous les mois avaient été republiés avec cette colonne en plus...
J'pense le plus simple pour nous c'est de mettre un warning sur la description du dataset en indiquant que la donnée de cette colonne n'est pas précise. Sinon ça fait beaucoup de manutention de données pour pas grand chose non ?

**Comment by nicolas-viennot-beta** [comment]
oui je valide.
