### ISSUE TITLE
Ouverture nouvelle fenêtre pour le détail des statistiques 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#187]
Je suis une AOM. Quand je suis connectée à mon interface et que je vais sur l'onglet Statistiques, je peux cliquer sur un lien explicitant les modalités de calcul des incitations. Je veux que ce lien s'ouvre dans un nouvel onglet afin de ne pas perdre le fil de où j'en étais.

**Comment by margot-sanchez** [comment]
![image](https://user-images.githubusercontent.com/15428433/59101828-7f5ddb80-892a-11e9-92a4-b7546ef9dbdc.png)

**Comment by jonathanfallon** [comment]
Le `target="_blank"` est dans le code
