### ISSUE TITLE
Ajouter des fichiers d'algo pour les campagnes terminées

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1871]
La release 2.9.6 liste les différents types de campagne et vérifie que leurs informations sont affichables, c'est à dire qu'elles peuvent être récupérées dans le fichier d'algo (`api/services/policy/src/engine/policies/`).
Lorsque le fichier est manquant, cliquer sur le lien retourne une erreur.

Les campagnes en cours ont été migrées mais pas celles terminées. Ce serait bien de reprendre le titre et la description dans un fichier spécifique à chaque campagne terminée pour que la page s'affiche.
Pas besoin de coder l'algo de calcul des incitations mais on pourrait coller en commentaire le contenu des `rules` et `global_rules` de la base pour les garder (on va sûrement supprimer ces champs dans une migration future).

**Comment by P3rceval** [comment]
J'pense qu'on peut s'abstenir d'écrire les algos pour des campagnes terminées.
J'suis pas sur non plus de l'intérêt de garder une trace des règles des anciennes campagnes ...
