### ISSUE TITLE
Mettre en place un fallback sur un échec de géolocalisation

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#1877]
Lorsqu'on standardise les données géographiques pour indiquer le code insee de départ/d'arrivée, il arrive que : 
- le point soit en dehors de tout périmètre ;
- le point se situe sur le périmètre "france" (contour eurostat) mais pas sur un code insee ;

Dans le cas où on a un point en dehors de tout périmètre, il faudrait attribuer le périmètre le plus proche dans un rayon de 1km. Dans le second cas, il faut affecter le pays le plus proche dans un rayon de 1km. Si aucun résultat n'est trouvé, une erreur est levée.

```sql
CREATE OR REPLACE FUNCTION geo.get_closest_country(lon float, lat float, year smallint) returns table (
  year smallint,
  l_arr varchar,
  arr varchar,
  l_com varchar,
  com varchar,
  l_epci varchar,
  epci varchar,
  l_dep varchar,
  dep varchar,
  l_reg varchar,
  reg varchar,
  l_country varchar,
  country varchar,
  l_aom varchar,
  aom varchar,
  l_reseau varchar,
  reseau int,
  pop int,
  surface real 
) as $$
  SELECT
    year,
    l_arr,
    arr,
    l_com,
    com,
    l_epci,
    epci,
    l_dep,
    dep,
    l_reg,
    reg,
    l_country,
    country,
    l_aom,
    aom,
    l_reseau,
    reseau,
    pop,
    surface
  FROM geo.perimeters
  WHERE
    geom IS NOT NULL
    AND country <> 'XXXXX'
    AND year = $3 
    AND
    ST_Intersects(ST_Buffer(ST_Transform(ST_SetSRID(ST_Point($1, $2),'4326'),2154),1000),ST_Transform(geom,2154))
  ORDER BY year DESC
  LIMIT 1
$$ language sql stable;
```

**Comment by jonathanfallon** [comment]
Fait et déployé. Utilisé en fallback de `get_latest_by_point` dans le provider geo local.
