### ISSUE TITLE
Ajouter un champ acronyme AOM 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#19]
Servira plus tard pour par exemple les attestations et éviter la lecture trop fastidieuse des noms de ComCom.

Exemple : Communauté Agglomération Privas Centre Ardèche = CAPCA

**Comment by jonathanfallon** [comment]
Exporter au format Excel pour Margot

**Comment by margot-sanchez** [comment]
Liste complète ici : https://docs.google.com/spreadsheets/d/10xy5YxwQreS2hG5UMYPnlTBN4WEtLq_gTchMC7iUlm8/edit#gid=48397468
