### ISSUE TITLE
Service User

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#190]
## Feature
- [x] Déplacer "forgotten password" dans une action : envoie un mail avec un token pour reset le mot de passe
- [x] Déplacer "change password" dans une action : permet de changer le mot de passe pour utilisateur loggué
- [x] Ajouter "reset password" dans une action: permet de mettre en place un mot de passe avec un token (éventuellement, on peut fusionner avec change password)
- [x] Ajouter une action "change email" : envoie un mail pour confirmer le mail avec un token
- [x] Ajouter une action "confirm email" : met à jour le statut du mail avec le token
- [x] Ajouter une action "verify password" : renvoie un boolean (comparaison de mot de passe)
- [x] Ajouter de la doc (à minima, une phrase par méthode éventuellement une phase pour les middleware)
- [x] Filtrer partout les propriétés à ne pas envoyer (genre mot de passe)
- [ ] Optimisation des requêtes (notamment pagination via $facet)

## Fix
- [x] Lint
- [x] Nettoyer les interfaces :)
- [x] Virer les console log qui traine
- [x] Normaliser les noms de classes (exemple: NewUserInterface > CreateUserParamsInterface)
- [x] Déplacer les interfaces (ou autre) dans le bon répertoire
- [x] Déplacer notification service => notification provider (Nicolas)
- [x] Mettre à jour tous les schémas (Jonathan)

## Test
- [x] Ajouter des tests unitaires sur les actions
- [x] Ajouter des test unitaires sur le middleware
- [x] Eventuellement, réduire la voilure des test d'intégration (pas urgent si les tests passent)

**Comment by samueleyre** [comment]
* Ajouter une action "verify password" : renvoie un boolean (comparaison de mot de passe) -- Géré dans le cryptoProvider

**Comment by nmrgt** [comment]
Il faut que tu fasses une action qui check le mot de passe et renvoie l'user si c'est bon (ou lance une exception si ca passe pas). Dans cette action tu peux utiliser le crypto provider
