### ISSUE TITLE
Problème sur les référentiels territoire PDDL 

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1911]
### Problème sur les référentiels territoire PDDL 

<img width="334" alt="Capture d’écran 2022-11-17 à 09 34 13" src="https://user-images.githubusercontent.com/89770924/203346674-28bade27-f33b-42a6-a1d1-e24785f2bf5e.png">

_Dans le champ de saisi des territoires, en tapant Pays de La Loire, on a 3 options : 

- 2 propositions PDLL AOM
- 1 proposition PDLL Région

Les 2 propositions PDLL correspondent à des périmètres géographiques différents.

Ludovic a regardé de son coté mais ne trouve pas de doublon côté chantier territoire pour pays de la Loire. Cela doit venir du champ d'auto-complétion, non ?

**Comment by P3rceval** [comment]
Vu avec Ludo : 
Le problème vient bien du référentiel géo.
En attente de cette [PR](https://github.com/betagouv/evolution_perimetres_geo/pull/63) qui devra également être déployé sur le RPC pour faire une pierre 2 coups

**Comment by nicolas-viennot-beta** [comment]
@Datayama38 : Le ticket "https://github.com/betagouv/preuve-covoiturage/issues/1908" a été clos mais je vois toujours le doublon PDLL sur l'interface de l'app. La mise en prod a t'elle eu lieu ?

**Comment by Datayama38** [comment]
Le fix a été fait au niveau du code mais il faut rejouer le millésime 2022 de la table des périmètres geo pour résoudre le bug en prod. On attendait simplement une review de nico sur evolution_perimetres_geo pour faire passer dans le même temps l'ajout d'une fonction permettant de détecter le pays le plus proche d'un point et éviter de rejouer 2 fois les migrations en prod

**Comment by nmrgt** [comment]
@Datayama38 c'est quelles migrations qu'il faut forcer du coup ?

**Comment by Datayama38** [comment]
Il n'y a que cerema_aom_2022 à forcer. la table des centroides n'a encore jamais été joué.

**Comment by P3rceval** [comment]
mettre à jour le paquet géo dans le rpc
rejouer les migrations geo sur la prod
rejouer la campagne Touraine pour les questions geo (voir le point précédent)
