### ISSUE TITLE
Mettre un accès pour les régions. en tant qu'AOM

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#192]
Aujourd'hui nous avons 338 AOM pouvant prétendre à avoir un compte dans le registre. Il s'agit uniquement des CC ayant la compétence transports. Or une région est par définition une AOM. 
Reprendre les données de transport.data.gouv pour recréer les contours des régions avec les codes INSEE associés. 

---

TODO
- [x] Récupération des contours des régions (18)
- [x] simplification des contours ?
- [x] Trouver les infos (INSEE, statut, SIRET...)

**Comment by jonathanfallon** [comment]
On peut migrer AOM vers territories dans notre code/db pour être plus agnostiques sur la logique du territoire concerné.
On pourra ensuite ajouter un type de territoire comme 'aom', 'region', etc... pour les qualifier.

**Comment by margot-sanchez** [comment]
Effectivement on avait parlé de ça pour élargir à des territoires. Je prends ma casquette juridique (en l'absence de Thomas ) : "aujourd'hui les CGU (convention d'adhésion au service) sont rédigées pour des AOM et non des territoires. En revanche des régions sont des AOMs, donc on pourrait faire un accès pour des régions".  On peut ensuite qualifier l'AOM soit de CC (Communauté de Communes) soit de région.

**Comment by margot-sanchez** [comment]
Ajouter ces régions https://docs.google.com/spreadsheets/d/10xy5YxwQreS2hG5UMYPnlTBN4WEtLq_gTchMC7iUlm8/edit#gid=171247736

**Comment by margot-sanchez** [comment]
<3 Inch'allah Enfin 👍
