### ISSUE TITLE
Nouvelle statistique - Nombre de covoitureurs

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#194]
1 numéro de téléphone = 1 covoitureur différent 
Mettre cette statistique sur la plage stats publique et également spécifique aux AOMs

**Comment by margot-sanchez** [comment]
Done sur le Front par @samueleyre 
A tester au retour de congés de @jonathanfallon une fois branché au back.

**Comment by nmrgt** [comment]
Nombre de personne différentes qui ont fait du covoiturage

**Comment by margot-sanchez** [comment]
Si impossible à faire rapidement alors masquer la stat qui est fausse.

**Comment by nmrgt** [comment]
On ne peut pas l'implémenter tant que la méthode d'identification des personnes n'a pas été mise à jour (cf numéro tronqué)

**Comment by margot-sanchez** [comment]
Devrait fonctionner maintenant que le recoupement simple fonctionne.
