### ISSUE TITLE
Enregistrement d'une demande CEE impossible

### ISSUE THREAD

**Issue by MilioPeralta** [betagouv/preuve-covoiturage#1944]
### Sujet

Nous venons de faire une session de test sur le nouveau flow CEE dans l'application BlaBlaCar Daily et nous rencontrons un problème lors de l'enregistrement d'une demande CEE.

### Environnement

Environnement (dev, prod...) : prod
Navigateur : -
Utilisateur : BLABLACAR
URL : https://api.covoiturage.beta.gouv.fr/v3/policies/cee

### Etapes pour reproduire

Lors de l'appel au endpoint: POST https://api.covoiturage.beta.gouv.fr/v3/policies/cee, nous reçevons en retour un code HTTP 400, avec le message suivant : "Date should be before 7 days from now".
Le trajet en question est un trajet validé ce matin : 2c3360a8-6cf8-42c5-9002-54caa2509b0a_2023-01-02

Il est bien connu de vos systèmes car nous sommes en mesure de le récupérer via un appel au endpoint : GET https://api.covoiturage.beta.gouv.fr/v2/journeys/2c3360a8-6cf8-42c5-9002-54caa2509b0a_2023-01-02

**Comment by nmrgt** [comment]
Merci @MilioPeralta pour le ticket.

C'est des règles métiers qui font que le trajet ne peut être mobilisé que 7 jours après pour que l'ensemble des opérateurs ait remonté les trajets.

Je laisse @nicolas-viennot-beta compléter.

**Comment by MilioPeralta** [comment]
Bonjour @nmrgt, merci pour ce retour !
Nous n'étions pas au courant de cette règle de notre côté.
Je vais re-boucler en interne et si Nicolas a plus d'info je suis preneur également.

**Comment by nmrgt** [comment]
La limite de 7 jours a été supprimé sur l'env de démo. Je ferme le ticket que tu peux réouvrir au besoin
