### ISSUE TITLE
Nouvelle statistique : nombre d'occupant du véhicule moyen (par covoiturage)

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#195]
Nb : le nombre de couple / le nombre de journey id regroupé

Pour la page stats globale et spécifique AOM

**Comment by margot-sanchez** [comment]
Done sur le Front par @samueleyre
A tester au retour de congés de @jonathanfallon une fois branché au back.

**Comment by margot-sanchez** [comment]
Suite sondage Slack, il est préférable d'utiliser la dénomination "personnes par véhicule"

**Comment by nmrgt** [comment]
je pense qu'on peut fermer l'issue
@margot-sanchez

**Comment by nmrgt** [comment]
so ?
