### ISSUE TITLE
Masquer APDF de Décembre coté opérateurs et collectivités

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1951]
### Sujet

Afin que bizdev/produit puissent faire les tests des APDFs de décembre avant la mise à disposition des collectivités et opérateurs, il faut leur masquer l'affichage des APDFs de décembre qui doit avoir lieu demain matin à 6h...

**Comment by jonathanfallon** [comment]
Fait et déployé
