### ISSUE TITLE
Metabase - Créer un dashboard CEE

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1956]
### Sujet

Sur metabase, créer un dashboard CEE, avec un tableau d'évolution stats" Global" et "par opérateur" (ou via filtre) de
- Evolution par semaine du nombre de demande d'enregistrement de dossier (policies/cee)
- Evolution par semaine du nombre d'enregistrement positif des dossiers, exemple via le nbre de token : "signature.......)" créé

**Comment by jonathanfallon** [comment]
https://stats.covoiturage.beta.gouv.fr/collection/20-cee

C'est difficilement lisible par semaine donc j'ai fait : 
1. Graph par semaine sur 1 an - courte distance
2. Graph par mois sur tout - courte distance
3. Graph par moi sur tout - longue distance

**Comment by nicolas-viennot-beta** [comment]
@jonathanfallon : A compléter avec la répartition par opérateur sur le même principe que les tableaux trajets, 

exemple : 
![image](https://user-images.githubusercontent.com/89770924/211372583-11c2f998-9a68-4e23-912e-8feeb2deab89.png)
