### ISSUE TITLE
Dates minimales d'enregistrement CEE au format UTC (au lieu de Europe/Paris)

### ISSUE THREAD

**Issue by adrienhellec** [betagouv/preuve-covoiturage#1971]
### Sujet

La date minimale pour une demande d'enregistrement CEE est en UTC au lieu d'être à l'heure de Paris.

### Environnement

Environnement (dev, prod...) : prod
URL : `POST /policies/cee`

### Etapes pour reproduire

Lors d'un appel sur l'endpoint `POST /policies/cee` avec une date de trajet à minuit le 1er janvier 2023 (`2022-12-31T23:00:00Z`), une erreur nous est renvoyée indiquant que la date devrait être au minimum à `2023-01-01T00:00:00Z`

### Comportement attendu

Les demandes CEE sont censées être acceptées au 1er janvier 2023 à minuit, donc à l'heure UTC `2022-12-31T23:00:00Z`.
Les heures UTC devraient être interprétées sur la zone "Europe/Paris".

### Comportement actuel

```
"Date should be before between 2023-01-01T00:00:00.000Z and 2024-01-01T00:00:00.000Z"
```

**Comment by samuelmasuebbc** [comment]
Bonjour @nmrgt,

Est-ce que vous avez un avancement à nous partager sur le sujet? 
Merci

**Comment by BastienLelargeBlaBlaCar** [comment]
Bonjour @nmrgt,
Cela ne semble pas résolu, les limites sont encore plus restrictives, voici le message d'erreur que nous recevons:
```
Date should be before between 2023-01-01T23:00:00.000Z and 2023-12-31T23:00:00.000Z
```
Il y a un jour d'écart pour la date de début

**Comment by nmrgt** [comment]
Merci pour le retour @BastienLelargeBlaBlaCar 
Le problème est toujours d'actualité ?
On a des demandes dans ce range qui date d'hier (et qui ont été accepté)...

**Comment by BastienLelargeBlaBlaCar** [comment]
Bonjour,
Oui effectivement, je vois que les demandes qui étaient bloqués hier ont été débloqués.
Merci 🙂
