### ISSUE TITLE
Forbidden Error sur trip:stats

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#1972]
Il y a de nombreux jobs failed sur le redis sur la file "trip", notamment sur l'action "trip:stats". Il s'agit probablement d'une mauvaise construction du payload dans `TripCacheWarmCron`, lorsque l'appel se fait pour un territoire. Je pense que l'appel est bloqué par `ScopeToGroupMiddleware`.

**Comment by P3rceval** [comment]
https://github.com/betagouv/preuve-covoiturage/pull/1975
