### ISSUE TITLE
Fix l'automatisation des calculs stats dans MetaBase

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1978]
### Sujet

A date, il faut relancer manuellement le calcul des stats dans Metabase.

Objectif : Automatiser cette commande / ou fix / ou peut être déjà prévu et en attente dans un PR ;)

**Comment by jonathanfallon** [comment]
ça marche bien mais c'est un peu long. Fixé depuis le 23/01
