### ISSUE TITLE
Evolution de l'éditeur d'attestation sur l'honneur.

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#1979]
### Tâches

- [x] 1. ajouter les nouveaux décrets
- [x] 2. modifier les options dans le formulaire secteur public
- [x] 3. modifier le PDF secteur public
- [x] 4. modifier le PDF de l'attestation téléchargeable et les textes sur la doc publique (Gitbook)
- [x] 5. modifier la doc au besoin
- [x] 6. mise à jour technique (Angular)

**### 4 évolutions à apporter à l'éditeur d'attestation sur l'honneur :** 

## 1. Ajouter les redirections vers les nouveaux décrets sur la page [/je-suis-employeur](https://attestation.covoiturage.beta.gouv.fr/je-suis-employeur)

Ajouter à la liste de lien suivant au dessus du lien "Loi n°2019......" (cf. flèche rouge ci-dessous)
<img width="607" alt="Capture d’écran 2023-01-24 à 14 37 07" src="https://user-images.githubusercontent.com/89770924/214309187-39f65bd2-41e4-4c33-a1b5-aa0bcf7044f5.png">

[Décret n° 2022-1562 du 13 décembre 2022 modifiant le décret n° 2020-543 du 9 mai 2020 relatif au versement du « forfait mobilités durables » dans la fonction publique de l'État](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000046733824) ;
[Arrêté du 13 décembre 2022 modifiant l'arrêté du 9 mai 2020 pris pour l'application du décret n° 2020-543 du 9 mai 2020 relatif au versement du « forfait mobilités durables » dans la fonction publique de l'État](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000046733848) ;
[Décret n° 2022-1557 du 13 décembre 2022 modifiant le décret n° 2020-1547 du 9 décembre 2020 relatif au versement du « forfait mobilités durables » dans la fonction publique territoriale](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000046733396) ;
[Décret n° 2022-1560 du 13 décembre 2022 modifiant le décret n° 2020-1554 du 9 décembre 2020 relatif au versement du « forfait mobilités durables » dans les établissements publics de santé, sociaux et médico-sociaux](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000046733697) ;

## 2. Supprimer dans le formulaire [salarié-secteur-public](https://attestation.covoiturage.beta.gouv.fr/salarie-secteur-public) les 3 options suivantes : 

- Je ne bénéficie pas d’abonnement de transport public de personne ; 
- Je ne bénéficie pas d’un abonnement de service public de location de vélo ; 
- Je ne perçois pas d’indemnités représentatives de frais pour mes déplacements entre ma résidence habituelle et mon lieu de travail ;
<img width="609" alt="Capture d’écran 2023-01-24 à 14 39 40" src="https://user-images.githubusercontent.com/89770924/214309829-cebbc8a3-4347-4bda-a9f8-2f7b8144267e.png">

## 3. Modifier le contenu de l'attestation générée à partir du formulaire comme suit (cf. les suggestions faites sur le document) : 
https://docs.google.com/document/d/1SwvUE5SmC5wHTq3zKP114JnLys9gGTT2bt-eZbQcWEc/edit?usp=sharing

## 4. Modifier le contenu de l'attestation téléchargeable https://1138683681-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MT_tG-fSUdzs0cvXC5K%2Fuploads%2FVY5qqrvUZ2SAAOkABDFE%2Fattestation-sur-honneur-covoiturage_public.pdf?alt=media&token=b9a64ea4-34b5-4bde-9825-dde4e05ee0bd comme suit (cf. cap écran) : 
supprimer les 3 optin suivantes ET l'exemple: 
- Je ne bénéficie pas d’abonnement de transport public de personne ; 
- Je ne bénéficie pas d’un abonnement de service public de location de vélo ; 
- Je ne perçois pas d’indemnités représentatives de frais pour mes déplacements entre ma résidence habituelle et mon lieu de travail ;
---> exemple doc modifié : https://docs.google.com/document/d/16_7Oqsv7zQExzsCFzFOyTTPGJPkeVUFC/edit?usp=sharing&ouid=115294686582841067997&rtpof=true&sd=true

**Comment by jonathanfallon** [comment]
@nicolas-viennot-beta on a pas traité le cas de l'attestation pour le secteur privé ([drive](https://drive.google.com/drive/folders/144XER2wOsP4_ltmwQEgSUaAw4NdyRrHW))
