### ISSUE TITLE
Mise à jour des dépendances

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1988]
- [ ] `yarn outdated`
- [ ] supprimer les dépendances déclarées dans des workspaces quand elles peuvent être disponibles à la racine `yarn add -W` (principalement les _devDependencies_) (ex. `date-fns-tz`)
- [ ] garder `ava@4`
- [ ] garder `bullmq@1`
- [ ] tester les majors des autres dépendances

**Comment by nmrgt** [comment]
@P3rceval tu es toujours dessus ?

**Comment by JulienPathtech** [comment]
Je me suis assigné le ticket mais j'ai rien de vraiment commencé !

**Comment by jonathanfallon** [comment]
On est passé à `npm` depuis et je pense qu'on a fait une partie du boulot.
C'est bien de passer dessus chaque semaine de toute façon
