### ISSUE TITLE
Processus constat fraude multiopérateur

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#200]
## Méthodologie
On exclut de notre base le second trajet (pour garder le premier dans l'observatoire avec un label permettant d'identifier qu'il y avait eu une fraude), on exclut de la campagne incitative les deux trajets, on informe les deux opérateurs.

## Impératifs
- [ ] - S'assurer de bien loguer les trajets (en cas de contrôle).
- [ ] - S'assurer de bien loguer nos envois (qu'on puisse montrer qu'on a bien envoyé l'info sur une fraude à telle date, telle heure). 

## Solution d'information aux opérateurs
Mettre en évidence dans l'interface opérateur avec un TAG spécifique.

Réflexions : Ne devrait-on pas créer un référentiel de code de fraude. Exemple Code 02 (fraude multi-opérateur), Code 01 (trajet incohérent), etc. ?

**Comment by nmrgt** [comment]
Ce traitement nécessite d'avoir un recollement d'identité inter opérateur fiable
