### ISSUE TITLE
Mettre à jour la fiche beta

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#2010]
Suite à la demande de Benjamin il faudrait mettre à jour la fiche de la SE sur le github de beta.

https://github.com/betagouv/beta.gouv.fr/blob/master/content/_startups/preuve-de-covoiturage.md

> On aimerait fusionner le ppt que vous remplissez chaque année avec la fiche produit. Ainsi, le nouveau format de la fiche produit serait :
> Un résumé (2 min de lecture)
> Le problème : en une phrase précise
> La solution : une phase précise qui résume votre proposition de valeur et un paragraphe qui la développe un peu + un lien vers votre mvp
> L’impact : un paragraphe avec vos résultats (chiffre KPI) et votre objectif chiffré et daté (« xxx fin 2023 »)+ un lien vers votre page stat
> Ca sera aussi l’occasion pour vous et nous de bien vérifier que vous avez une page stat à jour et claire

**Comment by nicolas-viennot-beta** [comment]
ohhh fichtre, je fais cela cette semaine
