### ISSUE TITLE
API CEE - Mise en place d'un fallback sur la donnée "Distance" 

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2053]
### Contexte

La donnée distance est obligatoire pour qu'un trajet soit éligible à un enregistrement sur l'API CEE.
Certains opérateurs ne la transmette pas car elle est à date optionnelle

### Besoin

Mettre en place un fallback sur la distance calculée afin qu'à l'avenir les demandes des opérateurs soient complètes et donc éligibles.

**Comment by nmrgt** [comment]
fait via #2055

**Comment by jonathanfallon** [comment]
Est-ce qu'on applique le même système pour carpool ? Ça permettrait d'appliquer les tranches d'incitation pour ces opérateurs.
