### ISSUE TITLE
Statistiques CEE - Ajouter dans matermost les données "Demandes refusées"

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2057]
### Besoin : 

Visualiser l'évolution hebdomadaire du volume de demandes refusées en dissociant les motifs Refus "Pas éligible" ET Refus "Collision (dédoublonnement historique ou PC)"

### ToDo : 

Ajouter dans Matermost
- un graphique pour la **courte Distance** représentant l'évolution hebdomadaire des trajets refusés ( avec une couleur distincte pour les 2 motifs de refus)
- un graphique pour la **Longue Distance** représentant l'évolution hebdomadaire des trajets refusés ( avec une couleur distincte pour les 2 motifs de refus)

**Comment by jonathanfallon** [comment]
https://stats.covoiturage.beta.gouv.fr/collection/20-cee
