### ISSUE TITLE
Améliorer la configuration des travel_pass et payments

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#207]
- Utiliser la configuration pour tester les valeurs autorisées en travel_pass et payments
- Ajouter cette intro dans le README
- Ajouter des TU

```md
## Contribution à la liste des cartes de transport et des Titres-Mobilité

Les listes des cartes de transport et des Titres-Mobilité autorisés sont disponibles dans la configuration. Il est possible de soumettre des _Pull Requests_ pour en ajouter.

- [Cartes de transport](api/config/travel-pass.yml)
- [Titres-Mobilité](api/config/mobility-pass.yml)

> Merci d'utiliser le modèle de _Pull Request_ quand vous soumettez des modifications.

Merci pour votre contribution !
```

**Comment by margot-sanchez** [comment]
Pour info j'ai un peu complété le gitbook sur ce sujet : https://registre-preuve-de-covoiturage.gitbook.io/produit/api/schema-json#donnees-sur-lidentite-de-loccupant

**Comment by margot-sanchez** [comment]
@jonathanfallon mettre à jour ce ticket avec la V2

**Comment by jonathanfallon** [comment]
On verra au cas par cas avec les territoires et les opérateurs.
