### ISSUE TITLE
Test incohérent : j'ai alimenté le compte de OuiHop avec un CSV comprenant clairement Karos comme opérateur en colonne B. 👎

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#21]
Test incohérent : j'ai alimenté le compte de OuiHop avec un CSV comprenant clairement Karos comme opérateur en colonne B. 👎

_Originally posted by @margot-sanchez in https://github.com/betagouv/preuve-covoiturage-dashboard/issues/33#issuecomment-477637260_

**Comment by margot-sanchez** [comment]
-[ ] Améliorer l'import CSV en bloquant l'import lorsque le nom d'un autre opérateur est présent dans le fichier.
