### ISSUE TITLE
Création environnement d’exécution pour Jupyter Notebook

### ISSUE THREAD

**Issue by P3rceval** [betagouv/preuve-covoiturage#2107]
**Contexte**
Utilisation d'outils data dans le cadre de la lutte contre la fraude. 

Les notebooks sont versionnés et présents sur cette branche -> https://github.com/betagouv/preuve-covoiturage/pull/2156/files

**Besoins**
- Pouvoir exécuter les notebooks périodiquement (environnement python) sur la BDD de prod (Lecture + Ecriture)
- Pouvoir mettre à jour les fichiers Jupyter notebooks

**Technique**

- Création d'une image papermill versionnée qui embarque les notebooks
- Exemple d’exécution de l'image en local : 
`docker run --network=preuve-covoiturage_back  preuve-covoiturage_notebook:latest ./scripts/production/interoperators-fraud.ipynb -k python3 -p connection_string postgresql://postgres:postgres@postgres:5432/local -p aom_insee 76 -p start_date '2022-02-28 23:59:59' -p end_date '2023-04-01 00:00:00' -p policy_id '841' -p update_carpool_status 'False'`
- Pas besoin d'avoir la sortie du notebook

**Comment by P3rceval** [comment]
#2099

**Comment by nmrgt** [comment]
Peut-on remplacer les paramètres start_date et end_date par :
- un délai avant NOW() => on travaille avec Xheures de décalage (actuellement 5 jours)
- une plage en nombre d'heure => on étudie une plage de X heures
Comme ça le script run en faisant
end_date = NOW() - '{delay} hours'::interval
start_date = NOW() - '{delay} hours'::interval - '{range} hours'::interval
?

**Comment by nmrgt** [comment]
J'en profite : peut-on passer par une varenv pour la connectionString ?

**Comment by nmrgt** [comment]
besoin de précisions sur : 
- quel besoin en termes de 
  -  cpu / mémoire
  - disque (écriture ?)
- quel est le temps de traitement max (après on kill la tache) ?

**Comment by P3rceval** [comment]
@nmrgt Aucun idée.
On a qu'à partir sur 2Go de Ram
1 CPU ultra vener et très peu de disque (10Go)

Temps de traitement max => 1h pour l'instant

**Comment by nmrgt** [comment]
J'ai une erreur lors du run :
`NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres`

**Comment by P3rceval** [comment]
Il faut passer `postgresql://` et non pas `postgres://...` en connection_string

**Comment by nmrgt** [comment]
ok pour la connection string je vais tester :)
pour la passer on utilise un paramètre du cli et pas une variable d'environnement ce qui fait que ça se retrouve dans les logs (ce qui est pas génial)

**Comment by P3rceval** [comment]
Ah yes, je fais la modification

**Comment by P3rceval** [comment]
https://github.com/betagouv/preuve-covoiturage/pull/2174/files

Nom de la variable DATABASE_URL
