### ISSUE TITLE
OpenData - qualité donnée géographique

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#213]
## Problème 

Les données sont en WGS84, c'est bien mais l'intégration automatique dans les logiciels type Kepler, Mapbox, etc. ne fonctionne pas.

## Idées de l'origine du problème
Les formats de données 64 bit, 32 bits.
Virgules, points

S'inspirer que ce qu'a fait DVF

**Comment by jonathanfallon** [comment]
@margot-sanchez Toujours d'actualité ?

**Comment by margot-sanchez** [comment]
Oui :)
