### ISSUE TITLE
Périmètre géo manquant

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#2145]
Coordonnées manquantes
-1.51, 48.62

lié au support `1303`

**Comment by nmrgt** [comment]
@Datayama38 any update ?

Pour rappel, il faudrait utiliser un fallback vers la zone la plus proche en france (dans un rayon de X) si le point n'est pas trouvé avant de tester les pays.

Ce qui donne : 
- recherche du point dans une zone exacte en France
- recherche du point à proximité d'une zone en France
- recherche du point à proximité ou dans une zone hors France

**Comment by nicolas-viennot-beta** [comment]
@Datayama38 : peut-on clore ce ticket ?

**Comment by nicolas-viennot-beta** [comment]
patch correctif déployé. Nous appliquons dorénavant un buffer d'un kilomètre autour des points pour trouver la commune la plus proche lorsque les coordonnées transmises sont en dehors d'un périmètre connu.
