### ISSUE TITLE
Interface Graff Collectivité = problème règle d'affichage

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2147]
### Sujet

1. Je me connecte sur le compte CONCES FRANC CONST EXPL TUNNEL MONT BLANC
2. Je clique sur trajets puis Affiner les résultats et je sélectionne dans campagne : ATMB_2023_053. 

<img width="1158" alt="Capture d’écran 2023-05-26 à 10 25 19" src="https://github.com/betagouv/preuve-covoiturage/assets/89770924/c2e80916-1816-4a10-b945-dafa7fa1cb92">

<img width="548" alt="Capture d’écran 2023-05-26 à 10 16 38" src="https://github.com/betagouv/preuve-covoiturage/assets/89770924/9284d1af-1c73-48d9-a7c4-39975fac4067">

=> Je constate que tous les trajets sont incités. En tant que collectivité, je peux comprendre que TOUS les trajets sont donc incités par MA campagne.

OR ici les trajets sont incités aux 3/4 par une autre campagne.

Conclusion : 
- Lors de l'utilisation du "critère:Campagne" pour affiner un Graff, La règle semble être : 
  - nbre de trajet = tous les trajets éligibles de la campagne ✅
  - nbre de trajets incités = tous les trajets ayant une incitation, peu importe l'incitateur🔴
ALORS que on devrait avoir pour les trajets incités :
  - nbre de trajets incités = SEULEMENT les trajets ayant une incitation liée à la campagne
  
  Besoin : 
Faire une modification de la règle d'affichage.

**Comment by nicolas-viennot-beta** [comment]
pas prio

**Comment by nicolas-viennot-beta** [comment]
Suite échange, 
- le Graff doit bien affiché uniquement les trajets éligibles ET incités
- ajouter cette précision avec un astérisque et la référence "* Ne seront affichés que les trajets éligibles et incités dans le cadre de cette campagne"

<img width="1680" alt="Capture d’écran 2023-07-05 à 17 37 17" src="https://github.com/betagouv/preuve-covoiturage/assets/89770924/197dc8ed-e2e3-4835-a892-d3a6deceeab4">

**Comment by P3rceval** [comment]
@nicolas-viennot-beta C'est en prod, tu me dire si c'est ok pour toi ?

**Comment by nicolas-viennot-beta** [comment]
@P3rceval : j'ai un doute sur le fait que ca fonctionne, j'ai l'impression qu'on a que la données trajets incités dans le Graff mais pas la données trajet éligible. On peut s'appeler quand tu veux
