### ISSUE TITLE
CEE: rendre la réponse 409 iso avec la 201

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#2164]
Contexte : lorsqu'un opérateur envoie une demande CEE sur laquelle il y a déjà eu un enregistrement fait par lui, il reçoit uuid de la demande mais pas le journey_id (ni la signature). Or, il peut arriver que l'application timeout sur certain enregistrement et que l'opérateur, bien que n'ayant pas eu de réponse, ait bien sa demande enregistrée.

Évolutions : 
- ajouter le journey_id au retour 409 dans les mêmes conditions que l'uuid
- quid des autres champs (signature) ?

**Comment by hervouinc** [comment]
Bonjour, @nmrgt , @revolunet , @tut-tuuut ,
Avez-vous des nouvelles à partager concernant ce bug ?
C'est un problème majeur pour BlaBlaCar Daily car nous avons un grand nombre d'utilisateur se retrouvant bloqués dans cette situation. Sans le `journey_id` il nous est impossible de pouvoir les exporter à notre partenaire de CEE, ils ne peuvent donc pas bénéficier du bonus covoiturage, comme cela leur a été promis.
Merci pour votre aide.
Bonne journée.

**Comment by nmrgt** [comment]
Bonjour @hervouinc

Les modifications ont été intégrées dans l'API. Je ferme le ticket mais si vous avez un problème n'hésitez pas à le réouvrir (ou en faire un nouveau!).

Bonne journée

**Comment by maxxfly** [comment]
Bonjour, j'ai vu que le ticket est passé en "merged" mais si je retente sur un call qui me renvoit un 409 en production, je recupere toujours que l'attribut `uuid` et `datetime`
je n'ai toujours pas le `journey_id` en production

**Comment by nmrgt** [comment]
Il n'y a pas de journey_id sur la longue distance. Est-ce que le retour était bien sur de la courte distance ?

**Comment by maxxfly** [comment]
c'etait sur la courte distance

**Comment by nmrgt** [comment]
C'est très étrange parce que je viens de tester sur la demo (qui a la même version que la prod) et j'ai bien un retour qui contient le journey_id. Le plus simple serait d'ouvrir un ticket de support sur technique avec un payload d'exemple que l'on puisse regarder en détail. Merci
