### ISSUE TITLE
CEE: ajouter identity_key dans le endpoint simulate

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#2171]

**Comment by MilioPeralta** [comment]
Bonjour, 
Par rapport au retro-planning partagé : _Covoit.gouv : passage du champ clé d'identité en obligatoire sur l'API CEE --> 30/06/2023_, avez-vous une date pour la release de l'ajout de l'`identity_key` dans l'endpoint `/simulate` ?
Merci d'avance

**Comment by MilioPeralta** [comment]
up :)

**Comment by nmrgt** [comment]
Hello @MilioPeralta 

Je le met en haut de la pile avec une cible au milieu de la semaine prochaine.

**Comment by MilioPeralta** [comment]
Parfait, merci !

**Comment by adrienhellec** [comment]
Bonjour,
Est-ce que l'API est désormais à jour avec ce nouveau champ `identity_key` sur l'endpoint `/simulate`?
Je reçois une réponse `"data must NOT have additional properties"` si je tente de l'ajouter.
Merci !

**Comment by P3rceval** [comment]
Bonjour @adrienhellec 

Cela devrait être bon. Peux-tu réessayer stp ?

**Comment by adrienhellec** [comment]
Ça fonctionne merci !

**Comment by maxxfly** [comment]
Bonjour, je voulais savoir pourquoi on a une difference entre la prod et la demo sur ce point?
la prod gere bien ce parametre, mais la demo continue de nous envoyer un `data must NOT have additional properties`

**Comment by nmrgt** [comment]
@maxxfly la demo est iso avec la prod mais il peut y avoir parfois un décalage de version. Tout a été redéployé donc le problème ne devrait pas persister.
