### ISSUE TITLE
Endpoint /v3/policies/cee/import/identity non fonctionnel ?

### ISSUE THREAD

**Issue by Fenkiou** [betagouv/preuve-covoiturage#2178]
### Sujet

L'endpoint permettant d'importer les clefs d'identité (identity_key) ne semble rien faire..

### Environnement

Environnement (dev, prod...) : preprod
URL: https://api.demo.covoiturage.beta.gouv.fr

### Etapes pour reproduire

- Je crée un trajet (j'omet le payload parce que trop lourd) via `/v3/journeys`
- J'enregistre une demande de prime via `/v3/policies/cee` avec le payload suivant (donc sans le champ identity_key):
```json
{
	"journey_type": "short",
	"last_name_trunc": "BLY",
	"driving_license": "00AA00000",
	"operator_journey_id": "some-id",
	"application_timestamp": "2023-06-20T06:01:26Z"
}
```
- J'import l'identity_key via `/v3/policies/cee/import/identity` avec le payload suivant

```json
[
	{
		"cee_application_type": "standardized",
		"cee_application_uuid": "1a768fd6-0904-4e99-9d87-23a542b0944e",
		"identity_key": "stringstringstringstringstringstringstringstringstringstringstri",
		"journey_type": "short",
		"last_name_trunc": "BLY",
		"phone_trunc": "+336010203",
		"datetime": "2023-06-20T06:01:26Z"
	}
]
```

Je ne sais pas si l'import de la clef d'identité fonctionne ou non..
### Comportement attendu
L'API renvoit:
```json
{
	"imported": 1,
	"failed": 0,
	"failed_details": []
}
```

ou

L'API renvoit:
```json
{
	"imported": 0,
	"failed": 1,
	"failed_details": [des erreurs]
}
```
### Comportement actuel
L'API renvoit:
```json
{
	"imported": 0,
	"failed": 0,
	"failed_details": []
}

**Comment by Fenkiou** [comment]
Also, there is an error in the documentation of the API for the `cee_application_type`.

The doc says the value can be `specific` or `standartized`.

While the code expects `standardized`.

**Comment by nmrgt** [comment]
Merci pour le reporting
Le fix a été fait et déployé.
