### ISSUE TITLE
Application - problème sur Interface collectivité/opérateur en "statut : consultation"

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2182]
## Reproduire le problème : 
_Je me connecte à mon espace avec mon compte utilisateur "opérateur avec un statut "consultation" (et non admin)
_Je me rends sur l'onglet campagne
_Dans la liste des campagnes d'incitation, je clic sur le Nom d'une campagne pour afficher la page de détail de celle-ci
--> Problème : un message  "Campagne non trouvée" s'affiche

<img width="1057" alt="Capture d’écran 2023-06-23 à 12 02 07" src="https://github.com/betagouv/preuve-covoiturage/assets/89770924/992bc129-c16c-4b55-9efa-00b247959e0d">

## Remarque : 
on ne rencontre pas ce problème avec un compte utilisateur ayant le statut : Administrateur

**Comment by P3rceval** [comment]
https://github.com/betagouv/preuve-covoiturage/pull/2220

**Comment by P3rceval** [comment]
C'est en prod
