### ISSUE TITLE
OOM sur exécution manuel du notebook sur des quantités importantes de données sur le cluster

### ISSUE THREAD

**Issue by P3rceval** [betagouv/preuve-covoiturage#2186]
Le notebook prend autant de mémoire que nécessaire lors de l’exécution des cellules et va chercher sur le swap. Sauf qu'il y a pas de swap sur le pod kube et  le process se fait kill par le OOM killer.

![Kernel-died-OOM](https://github.com/betagouv/preuve-covoiturage/assets/6213517/588e1431-7a32-41f1-ba9b-f4c3ec0914da)

Ticket similaire https://github.com/nteract/papermill/issues/476

J'ai tenté d'augmenter la RAM limit à 1Gi mais ça n'a rien changé.

Voix possibles : 

- Ajouter de la SWAP sur le pod (mais j'ai l'impression que c'est pas reco)
- S'assurer que le process ne prendra jamais plus que x RAM.

**Comment by P3rceval** [comment]
@nmrgt J'ai plus d'OOM et le conteneur tourne autour de ces valeurs d'utilisation RAM / CPU avec une exécution mois par mois: 
```
kubectl --namespace pdc-production top pod pdc-fraudcheck-debug                                                                                      jparmentier: Tue Jul  4 09:55:54 2023

NAME                   CPU(cores)   MEMORY(bytes)
pdc-fraudcheck-debug   1001m        776Mi
```

Du coup je monterai bien les limites à 1Go de core et 1Go de RAM ? Est-ce que ça te semble pertinent ?

**Comment by nmrgt** [comment]
quelque chose comme : 
request
  cpu => 500m
  memory > 512Mi
limit 
  cpu => 1000m
  memomry > 1024Mi

?

**Comment by P3rceval** [comment]
Résolu avec l’exécution d'un script avec start + end et augmentation des specs de ressource du one-off de fraud manuel :  
```
"limits": {
            "cpu": "2000m",
            "memory": "2.5Gi"
          },
```
