### ISSUE TITLE
Fraude Inter opérateurs - Elargissement au national

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2197]
### Elargissement de l'algo au national et non pas seulement aux territoires avec campagnes multi sur le RPC

1. Vérifier que tous les opérateurs nous envoient une `identity_key` à partir du 1 Juillet.
2. Remplacer le `phone_trunc` par `identity_key` pour trouver les chevauchements de trajets
3. Faire une itération sur IDFM et checker si y'a des différences

**Comment by P3rceval** [comment]
Effectif depuis le 3 Aout 2023
