### ISSUE TITLE
Erreur invalidation d'un trajet envoyé

### ISSUE THREAD

**Issue by bricevrs** [betagouv/preuve-covoiturage#2207]
### Route concernée : DELETE / journeys / {journey_id} (V2)

La documentation concernant la route mentionnée semble incorrecte. 
L'erreur renvoyée après soumission de la requête (en suivant les instructions de la documentation) indique qu'un **operator_journey_id** et un **code** sont requis

**Comment by bricevrs** [comment]
Petite précision @nmrgt , j'ai constaté le problème en testant avec l'API **V2**

**Comment by jonathanfallon** [comment]
Bonjour @bricevrs l'API V2 est en cours de décommissionnement et sera arrêtée très bientôt. As-tu testé l'API V3 ?

**Comment by bricevrs** [comment]
Bonjour @jonathanfallon, voici ce que j'ai avec l'API V3. (Avec des données tests).

<img width="1009" alt="Screenshot 2023-07-24 at 09 38 57" src="https://github.com/betagouv/preuve-covoiturage/assets/39555351/200442e5-92f4-4415-b9df-a9890b7923fb">
