### ISSUE TITLE
site vitrine - Mise en ligne sur une URL temporaire

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2242]
Afin de pouvoir faire la recette du site vitrine avant sa mise en prod, il faudrait le rendre accessible sur une url temporaire.

TODO
- [x] Déployer le CMS sur https://cms.covoiturage.beta.gouv.fr
- [x] Créer le bucket covoiturage.beta.gouv.fr (https://covoiturage.beta.gouv.fr.s3-website.fr-par.scw.cloud/)
- [x] Créer l'action `deploy-frontends-public.yml` pour déployer NextJs dans le bucket
- [x] Configurer et Activer le _Flow_ Directus pour lancer le déploiement Github
- [x] Activer l'action d'analyse sur le dossier `public`

**Comment by nicolas-viennot-beta** [comment]
@Datayama38 ; je te laisse compléter le ticket

**Comment by nicolas-viennot-beta** [comment]
@Datayama38 il est finti ce ticket, non ?

**Comment by Datayama38** [comment]
@nicolas-viennot-beta Non pas complétement. Il reste à déployer l'ETL pour les données des aires de covoiturage
