### ISSUE TITLE
Problème affichage des images sur l'app en Prod et en Demo

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2251]
Problème affichage des images sur l'app en Prod et en Demo

<img width="1260" alt="Capture d’écran 2023-09-04 à 11 49 48" src="https://github.com/betagouv/preuve-covoiturage/assets/89770924/4e610d14-7f40-4dcc-bd73-5ce9949c3f91">

<img width="1261" alt="Capture d’écran 2023-09-04 à 11 50 06" src="https://github.com/betagouv/preuve-covoiturage/assets/89770924/a649fdec-f71e-43de-8c94-7963e9b4d5b0">

**Comment by jonathanfallon** [comment]
C'est lié aux polices de caractères qui ont peut-être sauté suite à la désactivation de `git lfs`.
TODO : remettre les fichiers de police et s'assurer qu'ils ne sont pas corrompus.
