### ISSUE TITLE
Front Appli - Amélioration de la liste d'affichage des campagnes d'appel de fonds

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2279]
### Front Appli - Amélioration de la liste d'affichage des campagnes d'appel de fonds
_Je me connecte à mon compte RPC
_je me rends sur l'onglet "Campagnes" pour consulter la liste de mes campagnes en cours
<img width="1334" alt="Capture d’écran 2023-09-21 à 15 03 14" src="https://github.com/betagouv/preuve-covoiturage/assets/89770924/61a92668-353c-4710-822e-49b1a706727c">

Problème1 (en rouge sur la capture écran) : actuellement la liste n'est pas triée par statut 
Besoin1 : Trier la liste des campagnes par statut dans l'ordre "En Cours", "En pause", "Terminée"

Problème 2 (en orange) : On a un manque d'identification du stade de la campagne
Besoin2 : Appliquer un code couleur aux statuts et élargir les statuts : 
- Statut "En cours" : campagne en cours d'avancement -- > <img width="57" alt="Capture d’écran 2023-09-21 à 15 10 30" src="https://github.com/betagouv/preuve-covoiturage/assets/89770924/6eb7ffcd-c393-4e3b-bd21-c2d58904bca9"> ; couleur vert

- Statut " En pause" : campagne en cours Mais qui a atteint son plafond et donc dont on arrête de calculer les appels de fond. -->  <img width="57" alt="Capture d’écran 2023-09-21 à 15 10 30" src="https://github.com/betagouv/preuve-covoiturage/assets/89770924/6eb7ffcd-c393-4e3b-bd21-c2d58904bca9">; couleur Orange

- Statut " Brouillon" : campagne qui serait créé dans le cadre d'une simulation très spécifique via le back mais qui reste en draft. --> Mettre un pictogramme "Edition" (ex : stylo) ; couleur rouge

- Statut " Terminé" : campagne dont la période d'activation est terminée. --> <img width="59" alt="Capture d’écran 2023-09-21 à 15 10 53" src="https://github.com/betagouv/preuve-covoiturage/assets/89770924/374ba309-c923-4261-868d-6b1b2d99d0c1"> ; couleur rouge

**Comment by P3rceval** [comment]
@nicolas-viennot-beta 

C'est en prod, dis-moi si c'est OK pour toi

**Comment by nicolas-viennot-beta** [comment]
Hello @P3rceval : 
Problème1 : le tri n'est pas appliqué comme suit : "En cours" "En pause", "En brouillon", "Terminé" 

Problème 2 : pourquoi faire cohabité les picots vert et orange soir "en cours" donc vert, soit "en pause" donc orange

<img width="165" alt="Capture d’écran 2023-09-27 à 14 39 37" src="https://github.com/betagouv/preuve-covoiturage/assets/89770924/35171c8f-c4e6-4e33-b0ba-044189a925ce">

**Comment by P3rceval** [comment]
J'ai pas fait le tri effectivement ! 

Le bug sur "en cours" / "en pause" vient d'être corrigé. 
Ton navigateur doit avoir une ancienne version de l'application. 

J'te re ping quand j'ai fait le tri

**Comment by P3rceval** [comment]
@nicolas-viennot-beta C'est fix
