### ISSUE TITLE
Erreur normalization_error sur les trajets

### ISSUE THREAD

**Issue by bricevrs** [betagouv/preuve-covoiturage#2285]
### Sujet

Après avoir envoyé mon trajet avec des données fictives, j'ai constamment le statut **normalization_error** qui est attribué au trajet. Pourquoi ? 

### Environnement

Environnement (dev, prod...) : API Demo Covoiturage
Navigateur : Postman
Utilisateur :
URL : https://api.demo.covoiturage.beta.gouv.fr/v3/journeys

### Etapes pour reproduire

Voici le body fourni pour la requête (données fictives) :

```json
{
    "incentive_counterparts": [],
    "operator_journey_id": "077f4b4d-584b-5ac6-8cac-214f8cf57bd8",
    "operator_trip_id": "c237cb64-9b2d-4be7-b6e3-9fb8f9dd254b",
    "operator_class": "C",
    "incentives": [],
    "start": {
        "datetime": "2023-08-25T04:00:00Z",
        "lat": -20.9643873,
        "lon": 55.3310478
    },
    "end": {
        "datetime": "2023-08-25T05:17:00Z",
        "lat": -21.3380965,
        "lon": 55.4761052
    },
    "distance": 66000,
    "driver": {
        "identity": {
            "identity_key": "ca28fa78c4699d34f081517452d98e346640da38f92503cc494f0ad2000f9a74",
            "operator_user_id": "32897a26-7368-45c9-8539-8e85763988ef"
        },
        "revenue": 100
    },
    "passenger": {
        "identity": {
            "identity_key": "ca28fa78c4699d34f081517452d98e346640da38f92503cc494f0ad2000f9a75",
            "operator_user_id": "b9c0f469-8de2-4db6-af4e-aa52de324977"
        },
        "contribution": 100,
        "seats": 1
    }
}
```
### Comportement attendu

J'attends à ce que le statut soit normalement **ok**

### Comportement actuel

Cependant le statut est **normalization_error**.

**Comment by jonathanfallon** [comment]
Tu peux contacter technique@covoiturage.beta.gouv.fr pour ce type de demandes, ce qui évitera un échange de d'informations en public.

Il me semble qu'il y ai un bug sur la gestion de l'unicité des `operator_journey_id` qui provoque une collision dans la chaîne de traitement alors que le payload que tu envoies est correct.

Je corrige ça et reviens vers toi quand c'est fait. Merci pour le retour.

**Comment by jonathanfallon** [comment]
C'est corrigé en démo. Je t'invites à re-tester. Merci

**Comment by bricevrs** [comment]
Merci beaucoup @jonathanfallon  !

**Comment by bricevrs** [comment]
Quand est-ce que cela sera corrigé pour la prod ?

**Comment by jonathanfallon** [comment]
C'est corrigé en prod
