### ISSUE TITLE
Export .csv - Investigation SIRET

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2307]
**Problème d'affichage des SÌRET dans les colonnes "passenger_incentive_1_siret" et "driver_incentive_1_siret"**

**reproduction Problème**
- je me connecte en tant que collectivité, ou admin
- j'utilise la fonction d'export
- les colonnes AL (passenger_incentive_1_siret) et BH (driver_incentive_1_siret) sont vides alors même qu'elles étaient renseignées auparavant. 

=> Cela concerne tous les opérateurs donc ce doit être de notre coté. Est-ce que c'est depuis le déploiement de l'API V3 ?

**Comment by P3rceval** [comment]
Depuis l'API V3
Les colonnes de `passenger_incentive_rpc_raw`  et `driver_incentive_rpc_raw` sont vides dans trip.list. 
Probablement un problème avec la définition de `list_view`

**Comment by jonathanfallon** [comment]
La requête de `trip.list_view` utilise `meta->payments` alors que l'on utilise `incentive_counterparts` maintenant.
