### ISSUE TITLE
Délai d'alimentation du registre

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#232]
La théorie en ce qui concerne l'API : 
![image](https://user-images.githubusercontent.com/15428433/62778135-de1d0e00-baaf-11e9-9dc4-a8f393ef79d2.png)

Or un opérateur a pu alimenter le registre avec des trajets dont la date était passée depuis plus de 15 jours.

**Comment by jonathanfallon** [comment]
@margot-sanchez On met en place une première période de notification lors de l'envoi de trajets trop anciens avant de les refuser ?
