### ISSUE TITLE
OpenData - Si nombre trajets <=5 par maille géographique ne pas exposer.

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#233]
Blocked by https://github.com/betagouv/preuve-covoiturage/issues/1410

Exemple :

si 3 trajets en partance de 38730 alors ne pas exposer en Open Data.
si 6 trajets en partance de 34730 alors exposer en Open Data.

Spécifications : https://hackmd.io/w7WGuqtLQLyhzbFZcaE_vA#Chantier-open-data

**Comment by nmrgt** [comment]
lié à #115

**Comment by nmrgt** [comment]
Est-ce qu'on le n'expose pas ou est-ce qu'on omet le code insee concerné ?

**Comment by margot-sanchez** [comment]
Solution aujourd'hui : on n'expose pas.
A voir en fonction des retours suite à notre premier test d'ouverture de données.

**Comment by P3rceval** [comment]
Ce traitement sera à faire uniquement pour les exports open data dans un premier temps

**Comment by P3rceval** [comment]
https://github.com/betagouv/preuve-covoiturage/pull/1467
