### ISSUE TITLE
E-05 / US "Consulter un fichier Excel d'APDF"

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2347]
### Résumé de l'us

>  **"En tant qu'utilisateurs, je souhaite lire un fichier Excel APDF."**

>  **Utilisateurs concernés par l'us :**
> - Administrateur : ✅
> - Collectivité (compte complet): ✅
> - Opérateur: ✅  (⛔️certaines données ne sont pas à afficher dans le fichier)

> URL concernée : https://app.covoiturage.beta.gouv.fr/campaign/xxxx

> Épic concernée : E05 - Suivi de la campagne

--------------
### Spec du fichier APDF

- Principe général : 
  - tous les mois un fichier Excel récapitulant le calcul des incitations d'une campagne suivie par le RPC est généré et mis à disposition des différents utilisateurs dans leur interface dédié.

- Specification onglet 1 : 
  - Nom onglet : Synthèse par tranche ✅
  - Contenu de l'onglet : 
    - 2 tableaux l'un au dessus de l'autre : 
      - tableau 1 :  ✅
        - intitulé du tableau : Tranche "période normale"
        - spécificité du tableau : ne prend en compte que les incitations labellisées "période normale"
      - tableau 2 :  ✅
        - intitulé du tableau : Tranche "période booster"
        - composition : voir onglet ci-dessous MAIS ne prend en compte que les incitations labellisées "période booster"
        - ~~SI la campagne d'incitation n'a pas de règle d'incitation booster, alors on masque ce tableau~~
      - composition :  ✅
        - colonne 1 "Tranche "xxxxx" : synthétise les différentes tranches tarifaire /km de la campagne. 
        - colonne 2 "Incitations RPC " : comptabilise le montant d'incitation RPC calculé par tranche tarifaire. 
        - colonne 3 "Tous les trajets " : comptabilise le volume de trajets éligibles* par tranche tarifaire. 
        - colonne 4 "Trajets incités " : comptabilise le volume de trajets incités* par tranche tarifaire. 
      - exemple : 
<img width="600" alt="Capture d’écran 2023-12-18 à 15 17 45" src="https://github.com/betagouv/preuve-covoiturage/assets/89770924/171bbb2c-cc6a-4907-a379-88cc8c73d9e3">

- Specification onglet 2 : 
  - Nom onglet : Trajets  ✅
  - Contenu de l'onglet : 
    - Ensemble des trajets éligibles réalisés par un opérateur donné sur un mois donné. les trajets "éligibles" sont les trajets qui correspondent au périmètre géographique de la campagne. ✅
    - champs :  ✅

> Nom des champs | Commentaire
> -- | -- 
> journey_id |   
> trip_id |   
> operator_trip_id | Il vaut mieux remplacer ce champ par "operator_journey_id" qui sera plus utile aux opérateurs pour la lecture des APDFs  
> start_datetime |   
> end_datetime |   
> start_location |   
> start_epci_name|  
> start_insee |  
> end_location |   
> end_epci_name | 
> end_insee |   
> duration |   
> distance |   
> operator |  
> operator_class |   
> operator_driver_id |   
> operator_passenger_id |   
> rpc_incentive |   
> incentive_type |  

- Specification onglet 3 :  ✅ (dans l'onglet 1 finalement)
  - Nom onglet : Règle du fichier APDF
  - Contenu à faire figurer : 
    - Ce fichier est un récapitulatif des incitations financières calculées par le RPC à la demande des collectivités souhaitant un suivi mensuel des incitations versées. 
    Le RPC applique alors le montant d'incitation prévu aux trajets respectant les critères d'acceptation RPC (status "ok" et "cancel") et les règles de la campagne d'incitation résumées dans la "fiche descriptive de campagne" transmise par le RPC et validée par la collectivité et les opérateurs partenaires. 
    - Présentation des onglets : 
      - onglet "Synthèse par tranche" : présente une synthèse des montants d'incitations financières en fonction des différentes tranches tarifaires de la campagnes d'incitation. Un second tableau "Tranche "période booster" viendra compléter le premier pour les campagnes appliquant ponctuellement des règles de campagne différentes.
      - onglet "Trajets" : présente l'ensemble des trajets éligibles réalisés par un opérateur donné sur un mois donné. Voir définition de chacun des champs [dans notre documentation publique](https://doc.covoiturage.beta.gouv.fr/nos-services/le-registre-de-preuve-de-covoiturage/comment-lutiliser/export-and-donnees)

**Comment by nicolas-viennot-beta** [comment]
@jonathanfallon : 
Point d'attention le calcul des incitations **doit s'appliquer sur les trajets en statut "Ok" ET "Cancel"**.
En revanche, ils ne doivent pas prendre en compte les trajets en statut "fraudcheck_error" et "anomalie_error"

**Comment by nicolas-viennot-beta** [comment]
@jonathanfallon Pour finir le travail sur la MAJ du fichier APDFs, peux-tu, cf. la spec : 
- modifier l'intitulé du 1er onglet "tranche" par "synthèse par tranche"
- pas de nécessité de prévoir une agrégation des tableaux "période normale" et "période booster". c'est un cas qui sera marginal.
- modifier l'ordre des colonnes et NE CONSERVER que celles dans la spec ci-dessus. (Attention à bien modifier le champ "operator_trip_Id" par "Operator_journey_Id qui a plus de sens".
- intégrer un 3ème onglet avec le bloc texte, cf. spec.

merci

**Comment by jonathanfallon** [comment]
J'ai modifié quelques champs pour que les noms matchent avec la spec de l'API V3 et que ce soit plus clair : `operator_journey_id`, `operator_trip_id`, `trip_id`  reprennent les définitions énoncées ici : https://tech.covoiturage.beta.gouv.fr/operateurs/api-v3.html

![image](https://github.com/betagouv/preuve-covoiturage/assets/1656255/097bb93e-a8f6-4cfb-993c-53de84e3ef17)
