### ISSUE TITLE
Evolution du moteur de campagne d'incitation : ajout donnée incentive_rules

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2348]
Besoin : les collectivités ont besoin de dissocier dans leur fichier d'APdf les incitations qui sont calculées sur la base des règles de "période normale" et de "période booster", cas des campagnes IDFM et PDLL actuellement.

Evolution souhaitée : labelliser les incitations calculées par le RPC en fonction de la période à laquelle s'appliquent les règles de campagne dites normales et les règles dites ponctuelles ou booster, exemple : 
![image](https://github.com/betagouv/preuve-covoiturage/assets/89770924/e0ee2e10-0f0b-44a3-9cfa-2ca30733e320)

**Comment by nmrgt** [comment]
- ajouter les ranges de dates dans la propriété dynamique de policy "params" pour l'export, exemple : 
```
  params(): PolicyHandlerParamsInterface {
    return {
      slices: this.slices,
      operators: this.operators,
      limits: {
        glob: this.max_amount,
      },
      booster_dates: Date[]
    };
  }
```

**Comment by nmrgt** [comment]
La partie policy est faite sur cette PR https://github.com/betagouv/preuve-covoiturage/pull/2355
Il faut faire la partie "APDF". Il faudrait spécifier ce que tu souhaites exactement @nicolas-viennot-beta. Est-ce que c'est une colonne dans la liste des trajets ou est-ce que c'est une stats en "page de garde" (comme les tranches) ?

**Comment by nicolas-viennot-beta** [comment]
ok bien noté @nmrgt merci.
Concernant la partie APDF, c'est spécifié ici : https://github.com/betagouv/preuve-covoiturage/issues/2347 (on remonte la données à la fois dans les tableaux de tranche et dans la colonne de la liste trajet.

**Comment by nmrgt** [comment]
ok s'il y a un autre ticket je vais fermer celui-là.

@jonathanfallon pour faire le ticket #2347 il y a un propriété "booster_dates" disponible sur les campagnes
