### ISSUE TITLE
Couleur de police des dropdowns

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#2351]
Navigateur : Firefox, Chromium
Thème navigateur : foncé

Les polices sont noires en thème clair (attention il faut recharger la page)
Les polices sont claires en thème foncé mais le fond reste clair.

## Sans cliquer sur le dropdown

![image](https://github.com/betagouv/preuve-covoiturage/assets/1656255/5e0ac754-9b3d-46e1-9d04-9587c3ff2888)

## En cliquant sur le dropdown

![Screenshot from 2023-12-19 17-02-38](https://github.com/betagouv/preuve-covoiturage/assets/1656255/de664fe1-c6b1-409d-b455-fe7f7a24728d)

**Comment by Datayama38** [comment]
Je n'arrive pas à reproduire le bug, tu pourrais me donner plus de contexte ?
