### ISSUE TITLE
Statistiques CEE Longue distance

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2360]
Problème  : BBC nous a indiqué une différence entre leurs statistique et les nôtres.

Hypothèses : lors du ré import de leurs données CEE avec les identity_Key, nous avions reçu des données en doublon que nous avons dû supprimer manuellement par la suite. Ces données ont dû être comptabilisées dans les stats. 

Action : rejouer les données CEE Longue distance https://stats.covoiturage.beta.gouv.fr/dashboard/20-demandes-longue-distance?intervalle_de_dates=&op%25C3%25A9rateur=

**Comment by nicolas-viennot-beta** [comment]
@jonathanfallon : j'ai l'impression que l'on a un pb de stat également sur la Courte distance.
<img width="973" alt="Capture d’écran 2024-01-17 à 15 38 43" src="https://github.com/betagouv/preuve-covoiturage/assets/89770924/74f2bf95-9259-4a5d-813b-5283ba8da3fe">

**Comment by nicolas-viennot-beta** [comment]
Pour compléter le commentaire ci-dessus, l'indicateur CEE courte distance qui n'est pas à jour : https://stats.covoiturage.beta.gouv.fr/question/75-nombre-de-demandes-de-primes-de-100-enregistrees-pour-des-primo-conducteurs-courte-distance-par-semaine-mise-a-jour-tous-les-lundis-de-la-semaine-s-2?operator=&date_range=

**Comment by jonathanfallon** [comment]
C'est un bug de la commande qui fait le refresh des vues matérialisées. Il manque une permission d'écriture sur une vue et ça crash la suite des refresh.
