### ISSUE TITLE
Apis et site https://covoiturage.beta.gouv.fr/ indisponibles

### ISSUE THREAD

**Issue by mat-chartier** [betagouv/preuve-covoiturage#2378]
Bonjour,

Depuis 15h50 (2024-01-19) nous n'arrivons plus à contacter l'api https://api.covoiturage.beta.gouv.fr/v3/journeys permettant de déclarer les covoiturages.

Cela nous impacte fortement car les utilisateurs font des trajets qui ne pourront pas conmpter pour la prime covoiturage.

Merci,
Matthieu - La Roue Verte

**Comment by jonathanfallon** [comment]
Bonjour Matthieu, l'incident est résolu chez notre hébergeur et vous pouvez envoyer tous les trajets concernés qui seront bien pris en compte.

N'hésitez pas à nous contacter à technique@covoiturage.beta.gouv.fr pour les questions non liées au code de l'application.
