### ISSUE TITLE
Problème d'affichage des données sur les pages statistiques

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2497]
Navigateur : Safari, chrome...
Page https://observatoire.covoiturage.gouv.fr/observatoire/territoire/

Constat : Si on modifie le mois de l'année 2024, les données ne se rafraichissent. (uniquement 2024)

Est-ce dû à la migration carpool V2?

**Comment by Datayama38** [comment]
Non, il n'y a pas encore de migration vers carpools V2, je pense plutôt à un problème de requêtes asynchrones car le pb est aléatoire. (Parfois ça marche, parfois non). Je vais regarder.

**Comment by nmrgt** [comment]
@Datayama38 on ferme?
