### ISSUE TITLE
Evolution Export - modifier le format xlsx en .csv

### ISSUE THREAD

**Issue by nicolas-viennot-beta** [betagouv/preuve-covoiturage#2560]
Constat : Le nouveau format d'export en .xlsx est trop lourd et allonge considérablement le temps de réception du fichier.

A faire : Modifier le format en .csv

**Comment by nmrgt** [comment]
Perso je suis pour le csv pour des questions d'interopérabilité mais on peut envisager aussi le zipper le fichier pour réduire sa taille si c'est ça le problème

**Comment by jonathanfallon** [comment]
On a revenir sur du CSV. Zipper un XLSX ne fait pas gagner grand chose

**Comment by nicolas-viennot-beta** [comment]
donc csv zappé.

**Comment by jonathanfallon** [comment]
#2604
