### ISSUE TITLE
DPO, Responsable de traitement, sur AOM ET opérateurs

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#26]
![image](https://user-images.githubusercontent.com/15428433/54745518-02905080-4bca-11e9-8c47-aaab9b975ef2.png)

Finalement suite aux conseils judicieux de Thomas il est préférable de le mettre sur les deux. 

Permettre de ne voir que les utilisateurs du groupe. Par exemple que le CTO de Blablalines ne puisse pas mettre le CTO de Klaxit.

**Comment by jonathanfallon** [comment]
Mettre sur les AOM et sur les Opérateurs

**Comment by margot-sanchez** [comment]
@samueleyre cela ne fonctionne pas partout. 

En tant qu'administrateur souhaitant mettre à jour un opérateur cela charge sans résultats 👎 
![image](https://user-images.githubusercontent.com/15428433/56597507-e893c480-65f2-11e9-9a91-1aca7259618b.png)

En tant qu'administrateur souhaitant mettre à jour une AOM cela marche 👍 

En tant qu'AOM je vois des informations sans savoir de quoi on parle (ce n'est pas mentionné DPO, responsable traitement, etc.)
![image](https://user-images.githubusercontent.com/15428433/56597712-52ac6980-65f3-11e9-8441-e2abf1852c0c.png)
et le bouton modifier ne fonctionne plus... j'ai ouvert #128

**Comment by margot-sanchez** [comment]
@samueleyre 
ce cas ne marche toujours pas...
En tant qu'administrateur souhaitant mettre à jour un opérateur cela charge sans résultats 👎
![image](https://user-images.githubusercontent.com/15428433/56799529-69cca080-6819-11e9-8313-1493705c7127.png)
