### ISSUE TITLE
Configurer l'alerting dans le grafana

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#2655]
Remettre en place le système d'alertes dans le Grafana. Lever une alert dans les cas suivants : 

- [x]   % d'erreur HTTP supérieur à 10%
- [x]   crash des pods. Status failed
- ~~[ ]   failing des jobs.~~ -> Redondant avec le crash des pods 

TODO
- Mettre à jour le cluster avec la dernière version stable du helm chart https://github.com/grafana/k8s-monitoring-helm/blob/v1.6.14/charts/k8s-monitoring/values.yaml

**Comment by nicolas-viennot-beta** [comment]
Cf. échange séminaire : https://www.notion.so/fc82c6075847493e88e5da9c2356ab23?v=e7751e7337394297962bbeae4ec23fba&p=103994bec93180ffb065cad998cf4cd8&pm=s
