### ISSUE TITLE
Bug: patch journey is not working

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#2684]
Sur la route patch journey, il y a une erreur de syntaxe dans la mise à jour des start/end

**Comment by bricevrs** [comment]
Bonjour, je remarque qu'il y a une erreur concernant l'api de patch d'un journey, comme décrit dans cette issue. Ce problème impacte un cas d'usage essentiel dans le cadre de mon projet. Auriez-vous des nouvelles sur le statut de ce bug ou une estimation pour sa résolution ?

**Comment by jonathanfallon** [comment]
C'est en cours de résolution sur la PR #2698
