### ISSUE TITLE
Champs manquants chez un opérateur

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#274]
Chez un opérateur spécifique on a des champs manquants d'origine ou de destination. 
![image](https://user-images.githubusercontent.com/15428433/64696653-3d9b7e80-d49f-11e9-85c1-755bd687fed4.png)

En faisant une extraction on constate que l'information est complètement manquante. 
![image](https://user-images.githubusercontent.com/15428433/64697680-a8e65000-d4a1-11e9-8148-4f86696b8954.png)

**Comment by jonathanfallon** [comment]
On n'a pas la résolution du nom de la ville en Belgique, je pense que c'est lié à ça.

**Comment by nmrgt** [comment]
Je ferme au profit du #290
