### ISSUE TITLE
Ajouter résolution nom de ville des pays limitrophes

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#290]
## Contexte 

Nous avons des trajets transfrontaliers. Dans notre base de données nous affectons un nom de ville à l'origine et la destination du trajet en fonction des coordonnées géographiques. Lorsque le trajet est transfrontalier il manque généralement le nom de la ville sur l'origine ou la destination.

## Solution
Ajouter à la base des données carto des pays transfrontaliers à minima (Belgique, Luxembourg, Allemagne, Suisse, Italie, Monaco ?, Andorre, Espagne).

Bug related #274

**Comment by nmrgt** [comment]
8h
