### ISSUE TITLE
Bug - persistance des données en front après changement de session

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#308]
Quand on se connecte sur un compte et qu'on se déconnecte et qu'on se reconnecte sur un autre compte, l'appel à user:me ne renvois pas les données à jour.

**Comment by nmrgt** [comment]
1h de test

**Comment by nmrgt** [comment]
ref #339

**Comment by margot-sanchez** [comment]
Je suis connectée en tant qu'administrateur sur l'AOM de Bordeaux.
![image](https://user-images.githubusercontent.com/15428433/66909455-163f5080-f00d-11e9-92c4-ed81299f94a3.png)

Je me suis connectée en tant qu'administrateur de l'opérateur Maxi Covoit j'ai exactement les mêmes données... 
![image](https://user-images.githubusercontent.com/15428433/66909656-68807180-f00d-11e9-8148-febf879ee9b4.png)

**Comment by gillesboisson** [comment]
@samueleyre je vais vérifier si ton service est bien relié au service authentification

**Comment by margot-sanchez** [comment]
J'ai refais exactement le même parcours et c'est bon pour moi 👍
