### ISSUE TITLE
Connecter Cypress à CircleCi

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#309]

**Comment by nmrgt** [comment]
@vincentlaine peux-tu nous communiquer l'état du ticket ? Notamment quels sont les points de blocage.

**Comment by vincentlaine** [comment]
Alors j'ai vu avec Beta.gouv pour pouvoir lancer des orbs sur circle-ci pour tenter de lancer cypress automatiquement.

J'y ai passé 2/3h puis j'ai rage quit car c'est assez chiant à tester (obligé de faire des modifs, commit / push). L'orb se lance bien mais ça crashait toujours au moment du npm install ou de recup le dossier node_modules

Si vous voulez tenter de le continuer je me suis appuyé sur ces deux docs :
https://github.com/cypress-io/circleci-orb
https://circleci.com/orbs/registry/orb/cypress-io/cypress

**Comment by jonathanfallon** [comment]
Merci pour le taf @vincentlaine je reprends la main pour la suite.
