### ISSUE TITLE
Move failed jobs to postgres

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#321]
- Move failed jobs to database

8h

**Comment by margot-sanchez** [comment]
Cela serait vraiment bien de le faire <3

**Comment by margot-sanchez** [comment]
A voir avec @gillesboisson

**Comment by gillesboisson** [comment]
Il faut faire cela pour éviter de prendre trop de mémoire de la file d'attente (pour Margot).

**Comment by gillesboisson** [comment]
Regarder ce qu'il reste dan la liste d'attente.

**Comment by jonathanfallon** [comment]
Branché sur Sentry à la place de Postgres
