### ISSUE TITLE
Données manquantes tokens d'accès (application)

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#341]
* le token n'est pas retourné après la création
* date de création du token d'accès n'est pas retourné au front via 'application:list'

**Comment by jonathanfallon** [comment]
Le token est retourné par `application:create` avec le payload suivant :
```json
{
	"token": "ABCD....",
	"application": {
		"_id": "",
		"name": "",
		"operator_id": "",
		"created_at": ""
	}
}
```

`created_at` est maintenant disponible dans les résultats de `application:list`
