### ISSUE TITLE
Création des utilisateurs bloquée

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#345]
Branche: `dev`
Commit: `3eb9f14d`
User: Super Admin (admin@example.com / groupe: registry / role: admin)

Problème:
Le bouton _Créer_ reste inactif même si toutes les informations obligatoires sont remplies lors de la création d'un utilisateur en _Registre_ ou _Opérateur_.
La procédure fonctionne quand on choisit le groupe _Territoire_.

## Registre
![screenshot-20190928141705](https://user-images.githubusercontent.com/1656255/65816351-a94d4d80-e1fa-11e9-9106-c6ceab184ee7.png)

## Territoire
![screenshot-20190928141654](https://user-images.githubusercontent.com/1656255/65816353-a94d4d80-e1fa-11e9-8bd3-d343e5f14469.png)

## Opérateur
![screenshot-20190928141630](https://user-images.githubusercontent.com/1656255/65816354-a9e5e400-e1fa-11e9-847f-7ed9d7090be8.png)

**Comment by samueleyre** [comment]
Je n'ai pas réussi à reproduire

**Comment by nmrgt** [comment]
test à faire: 1h

**Comment by jonathanfallon** [comment]
Tests effectués :
- [ ] Super admin crée un admin registre
- [ ] Super admin crée un user registre
- [ ] Super admin crée un admin opérateur
- [ ] Super admin crée un user opérateur
- [ ] Super admin crée un admin territoire
- [ ] Super admin crée un user territoire
- [ ] Admin opérateur crée un admin opérateur
- [ ] Admin opérateur crée un user opérateur
- [ ] Admin territoire crée un admin territoire
- [ ] Admin territoire crée un user territoire
- [ ] User registre ne peut pas créer de users
- [ ] User opérateur ne peut pas créer de users
- [ ] User territoire ne peut pas créer de users
