### ISSUE TITLE
(Vous) ne fonctionne plus

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#346]
Branche: `dev`
Commit: `3eb9f14d`

L'indicateur _"(Vous)"_ ne fonctionne plus sur la liste des users.
`userService.user` dans `dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.html:7` retourne `null`

**Comment by nmrgt** [comment]
- Se connecter avec un utilisateur quelconque
- Vérifier que son utilisateur est taggé (vous) dans la liste des utilisateurs

**Comment by margot-sanchez** [comment]
Je ne me vois même pas alors que je suis connectée en super admin... 
![image](https://user-images.githubusercontent.com/15428433/66641087-5328d300-ec1a-11e9-9b00-dd46d36de5ce.png)
C'est lié au même problème ou bien c'est autre chose ?

**Comment by jonathanfallon** [comment]
Connecté comme Opérateur Admin ça fonctionne bien.

**Comment by margot-sanchez** [comment]
Est-ce que cela ne serait pas lié à la #373 ?
