### ISSUE TITLE
Mettre à jour la page stat côté opérateur

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#348]
Reste à faire : 

- ajouter message erreur pour dire qu'il y a une erreur de permission

**Comment by nmrgt** [comment]
4h

**Comment by margot-sanchez** [comment]
Je pourrai tester quand j'aurais des données sur le staging.

**Comment by margot-sanchez** [comment]
👍 On a des données sur le staging 🎉 
D'ailleurs je constate en tant que super admin qu'il y a bien des trajets rattachés à MaxiCovoit.
![image](https://user-images.githubusercontent.com/15428433/66910201-666ae280-f00e-11e9-9d02-a4a4d9d4f487.png)

👎 
Je me connecte en connexion normal et en faisaint F5 pour actualiser (sinon persistance des données de la session en tant que super admin) en tant que MaxiCovoit pour voir si les stats fonctionnent. 
Cela mouline depuis 10 minutes...
![image](https://user-images.githubusercontent.com/15428433/66910281-8ef2dc80-f00e-11e9-8532-784da07dece8.png)
Je tente également en connexion privée même problème.

**Comment by margot-sanchez** [comment]
👍
