### ISSUE TITLE
Versioning - Modifier un trajet soumis par l'opérateur

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#35]
**Demande**

Avoir la possibilité de modifier un trajet à posteriori pour apporter de nouveaux éléments d'information afin d'améliorer la détection des anomalies.

**Comment by margot-sanchez** [comment]
Réflexions de @nmrgt ici : https://hackmd.io/rjcEtpPVQ_67UXDerWJx0Q

**Comment by nmrgt** [comment]
Il faudrait faire un choix sur les différentes options histoire qu'on puisse adapter les développements aux contraintes que cette issue va créer.

**Comment by nmrgt** [comment]
fix in #911
