### ISSUE TITLE
Définir les templates des campagnes

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#354]
- [x] faire une liste des templates
- [x] pour chaque template (éventuellement inclure idfm)
  - [x] titre
  - [x] description
  - [x] règles métier

update 6/11/2019 : 

- [x] ajouter les restrictions

update 18/11/2019

- [x] seed des [templates](https://hackmd.io/hPmTiUVHRZaE8TvILAYuFQ?both) ( BACK )
- [x] retester les templates ( FRONT )

**Comment by nmrgt** [comment]
- 4h de specs

**Comment by margot-sanchez** [comment]
Voici une première ébauche : https://docs.google.com/spreadsheets/d/1hLwV91q6gcQ8ajiuTGK8k2FMaJZRjg2PiE5Ajl8EuRs/edit#gid=0

**Comment by margot-sanchez** [comment]
@samueleyre fait le json

**Comment by margot-sanchez** [comment]
2H00

**Comment by samueleyre** [comment]
Les templates au format json : https://hackmd.io/hPmTiUVHRZaE8TvILAYuFQ

**Comment by margot-sanchez** [comment]
Faire une discussion tech rapide - @gillesboisson

**Comment by jonathanfallon** [comment]
Besoin d'un identifiant pour le seeding dans la base seulement si pas déjà fait.

**Comment by margot-sanchez** [comment]
1H00

**Comment by nmrgt** [comment]
On peut fermer ?

**Comment by margot-sanchez** [comment]
Non car je ne vois toujours rien dans dev. 
![image](https://user-images.githubusercontent.com/15428433/72968961-e26e8680-3dc4-11ea-8933-66d2268429e3.png)
