### ISSUE TITLE
Accès aux méthodes trip.list et trip.stat pour les opérateurs

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#355]
* [x] ajouter les permissions operator.trip.list, operator.trip.stat aux admin et users de group 'operators'
* [x] compléter les middlewares aux actions trip.list et trip.stat associés aux permissions operator.trip.list, operator.trip.stat

**Comment by nmrgt** [comment]
In fine on fait des stats pour les opérateurs aussi ? J'avais retenu que c'était pas utile parce qu'ils avaient des outils statistique de leur côté probablement plus adapté. J'ai raté quelque chose ?
cc @margot-sanchez

**Comment by samueleyre** [comment]
Pour répondre pour Margot, on a mis ça dans les maquettes pour des raisons d'inclusivité pour des plus petits acteurs.

**Comment by margot-sanchez** [comment]
Je pourrai tester uniquement quand j'aurais des données sur le staging.

**Comment by margot-sanchez** [comment]
Voir #362

**Comment by margot-sanchez** [comment]
Voir #444

**Comment by margot-sanchez** [comment]
1H00

**Comment by margot-sanchez** [comment]
👍
