### ISSUE TITLE
Documentation des permissions

### ISSUE THREAD

**Issue by gillesboisson** [betagouv/preuve-covoiturage#362]
https://docs.google.com/spreadsheets/d/11lpQvGaUdRMnotO9Oj4kYxi5k5vdhg_wTaomH4i6MEk/

**Comment by gillesboisson** [comment]
4h

**Comment by margot-sanchez** [comment]
A valider https://docs.google.com/spreadsheets/d/11lpQvGaUdRMnotO9Oj4kYxi5k5vdhg_wTaomH4i6MEk/edit#gid=0

**Comment by margot-sanchez** [comment]
Validé tous ensemble le 21/10/2019
