### ISSUE TITLE
Export CSV v2

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#365]
En tant que territoire, je dois pouvoir exporter les données de covoiturage de mon territoire.

- [x] Écrire les specs

**Comment by nmrgt** [comment]
ref #301 #289 #275

**Comment by nmrgt** [comment]
2h

**Comment by margot-sanchez** [comment]
Le fichier CSV idéal est disponible ici : https://docs.google.com/spreadsheets/d/1CTtz14gfgsSKdHvCbgBQcqs1TPQh5mXYy3bLXRMqKG0/edit#gid=0


Il contient deux onglets : 
1) Le fichier idéal d'export CSV d'un territoire sur sa plateforme.
2) Le fichier idéal d'export opendata.

Etant donné qu'1 ligne = 1 couple passager/conducteur c'est donc l'information du passager qui conditionne les informations du trajet. En conclusion dans le cadre d'un export et afin de faciliter la lecture les variables de type passenger.start.lat sont renommées journey.start.lat et les informations sur le driver ne sont pas exportées (ceci allège grandement l'export).

**Comment by margot-sanchez** [comment]
Il est possible de le faire en deux fois : 
1) une première version avec les informations que nous avons déjà.
2) une seconde version avec l'ensemble des informations (exemple : #433 ou #430)

**Comment by margot-sanchez** [comment]
Cela fonctionne donc je ferme mais il reste des : 

- Incohérences : 

1. #396 
2. #688 

- Améliorations
1. #687 
2. #690 
3. #691 
4. #692 
5. #693
