### ISSUE TITLE
Review architecture front

### ISSUE THREAD

**Issue by gillesboisson** [betagouv/preuve-covoiturage#371]
Sur base des problèmes rencontrés sur les sprints précédent, revoir la base du code actuel et des refactos faites sur l'authentification et lien avec l'API 
- Interaction avec l'API
- Organisation des différents service (Sépération store, service)
- Relation page / fonctionnalité permission

**Comment by gillesboisson** [comment]
8 h Gilles
2 h Vincent

**Comment by gillesboisson** [comment]
@vincentlaine, quand serais-tu dispo en début de semaine prochaine pour faire cette review ?

**Comment by vincentlaine** [comment]
Lundi / Mardi je suis pas là.
Mercredi je suis dispo jusqu'à 12h ou sinon de 15h30 à 18h30
