### ISSUE TITLE
Mise à jour des templates de mails

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#372]
Les mails reçus par mailjet ne sont pas à jour ou obsolètes.
Actions
Margot (2H00
[ ] Template mot de passe oublié
[ ] Template invitation par email

Gilles (1H00)
[ ] Mise en oeuvre

**Comment by gillesboisson** [comment]
@margot-sanchez est ce que tu aurais les contenus qu'il faut changer

**Comment by margot-sanchez** [comment]
Voir maquettes Figma : 
[x] Template mot de passe oublié
[x] Template invitation par email
[x] Template changement email compte 1
[x ) Template changement email compte 2

Sources disponibles ici : https://drive.google.com/drive/folders/1RN53ds8b8-ySW5Q8vXaefdXgJO4ycR7G

**Comment by jonathanfallon** [comment]
Les fichiers de template sont ici : `api/services/user/src/templates/`

**Comment by gillesboisson** [comment]
Pour infos @margot-sanchez on peut pas utilisé de font un peu custom dans l'emailing, on pourra donc pas utilisé raleway pour les headers. Je repasse le tout en open sans (commes les textes)

**Comment by margot-sanchez** [comment]
A voir avec @nmrgt :)

**Comment by margot-sanchez** [comment]
Voir aussi le "renvoyer une invitation".

**Comment by margot-sanchez** [comment]
👍
