### ISSUE TITLE
les utilisateurs invités ne s'affichent pas dans le tableau utilisateurs

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#373]
Quand on ajoute un utilisateur dans l'interface admin, il ne s'affiche pas dans l'interface tant que le compte n'est pas activé. 

* back : envoyer ce type d'utilisateur car ce n'est pas le cas actuellement 
* front : ajouter un label 'en cours d'activation' à ce type d'utilisateur dans le tableau des utilisateurs

**Comment by jonathanfallon** [comment]
Le back liste bien les utilisateurs en `pending` et `active`.
Vérifie que tu as fait un `yarn fix-permissions` à la racine du projet (et dans le container Docker) pour t'assurer que tu n'as pas de soucis de ce côté là.

**Comment by jonathanfallon** [comment]
cf. #408

**Comment by margot-sanchez** [comment]
A retester une fois que @gillesboisson a fait ses tickets (gestion utilisateurs, tableau, etc.)

**Comment by gillesboisson** [comment]
lié à #425

**Comment by margot-sanchez** [comment]
👍
