### ISSUE TITLE
UI : Affichage des tokens lors de la création

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#375]
Améliorer l'XP de sélection / copier-coller et affichage.
Supprimer le scroll qui n'apporte rien dans ce cas d'usage.

![screenshot-20191002151350](https://user-images.githubusercontent.com/1656255/66047345-e598ea80-e527-11e9-8588-d47ab580ccbd.png)

**Comment by gillesboisson** [comment]
@jonathanfallon tu as fixé

**Comment by gillesboisson** [comment]
@jonathanfallon tu as fixé ?
