### ISSUE TITLE
Filtrer les trajets par application

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#376]
Pouvoir filtrer les trajets par applications (accès API) afin de permettre à des opérateurs gérant plusieurs services de les dissocier dans l'affichage, l'export, les stats, etc... et éviter d'avoir plusieurs identités (comptes utilisateurs) pour la même personne physique.

> Un utilisateur peut appartenir à un opérateur seulement

**Comment by margot-sanchez** [comment]
Voir #300
