### ISSUE TITLE
Rétrocompatibilité du schema de preuve

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#383]
#### Contexte

Suite à des retours utilisateurs, il est demandé de supporter le schema d'envoi des preuves plus longtemps que le calendrier prévu :
- Tests en staging du 1er au 28 octobre
- Déploiement en production sans rétro-compat le 28 octobre.

#### Objectif

- Assurer le support du schema de données V1 dans la V2 de l'application.
- Créer un schema de validation de la V1
- Assigner des valeurs par défaut aux données manquantes
- Afficher un message de dépréciation rappelant le calendrier sur les appels V1
- Notifier les envois sur les mauvaises URL (V2 sur V1 et inversement)
- Gérer le timeout des requêtes (bench des temps de réponse) avec un code d'erreur permettant aux opérateurs de renvoyer ou non la preuve.
- Retour d'erreur 409 Conflict lors de l'envoi de preuves dupliquées.

#### Proposition de calendrier

- Tests en staging du 1er au 28 octobre
- Déploiement en production possiblement avancé vers le 15 octobre
- Support de la route V1 jusqu'au 31 décembre 2019 (veille de la mise en place prévue du FMD)

#### Ressources

| Version | Schema | Route |
| ------- | ------ | ----- |
| V1      | _V2 et diff ci-dessous_ | `POST /journeys/push` |
| V2      | [Doc](https://hackmd.io/@jonathanfallon/HyXkGqxOH) | `POST /v2/journeys` |

#### Stratégie de données V1 --> V2

| V1  | V2  | stratégie |
| --- | --- | --------- |
| `cost` | - | |
| `incentive` | - | supprimer et utiliser `incentives` |
| `remaining_fee` | - | supprimer et utiliser `contribution` (passager) ou `revenue` (conducteur) |
| - | `contribution` | `v1.cost - v1.incentive` |
| - | `incentives` | Créer une entrée dans `incentives` en réutilisant la valeur pour `amount`. On utilise le SIREN de l'opérateur s'il manque.  | 
| `travel_pass` | `identity.travel_pass` | Déplacer dans `identity` |

Est. 8h

**Comment by margot-sanchez** [comment]
##Questions Margot
_V1 durant 6 mois (~ 5 mai 2020)_ 
On passe de 0 jours de retro-compat à 6 mois. 
 - N'existe-t-il pas un juste milieu ? 
 - A quoi cela nous engage ? Si je comprends bien une fois que le process est mis en place pour assigner des valeurs par défauts cela n'engage pas d'efforts  supplémentaire sur le long terme. Pourrions-nous indiquer plutôt le 31/12/2019 ? En échange nous restons à disposition pour aller aider les opérateurs qui ne comprennent pas et ont besoin d'aide sur ce changement. 
La convention DGITM se finalise au 28/02/2019. Nous avons donc un engagement d'être sur la nouvelle version pour cette date (au delà de nos autres engagements ;) ). 

_supprimer et utiliser expense_
Cette donnée n'est pas à communiquer, elle est de notre côté. Il conviendrait de le spécifier pour ne pas que l'opérateur se dise "oh mais il me parle de "expense" mais je ne le vois pas dans le schéma".

Sinon 👍

**Comment by jonathanfallon** [comment]
OK, j'amende la description avec tes remarques.
L'idée des 6 mois était arbitraire mais c'est intéressant de la faire concorder avec notre calendrier de convention.
