### ISSUE TITLE
OpenAPI

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#39]
Spécification de l'API au format OpenAPI 3.0.2

- Fichier de specs : `back-api/openapi.yaml`
- Editor (local) : http://localhost:8081
- Spécification : https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md
- Documentation : https://api-staging.covoiturage.beta.gouv.fr/openapi/

> Pour éditer dans _l'Editor_, copier-coller le contenu du fichier `openapi.yaml` dans l'éditeur, faire les modifs et faire le chemin inverse. Commiter.

**Comment by margot-sanchez** [comment]
Mise à jour dès la mise en prod de la nouvelle version du Back par @samueleyre sur https://api-staging.covoiturage.beta.gouv.fr/openapi/

**Comment by jonathanfallon** [comment]
Migration vers un format de présentation des données adapté au RPC et non au REST.
