### ISSUE TITLE
Homologation du service par le MTES

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#398]
L’homologation de sécurité est un acte formel par lequel l’autorité responsable d’un système engage sa responsabilité en matière de gestion du risque. 

Réalisation d'un dossier d'homologation formel auprès de l'autorité compétente (DGITM ==> MTES).

Le service étant en phase d'accélération la DINSIC n'est pas notre autorité responsable du système. 

Voir guide 

- https://www.ssi.gouv.fr/uploads/2018/11/guide-securite-numerique-agile-anssi-pa-v1.pdf
- https://github.com/betagouv/beta.gouv.fr/wiki/Homologation

# TODO

- [ ] préparer des schemas pour les flux de données.
- [x] envoyer la release [2.1.0](https://github.com/betagouv/preuve-covoiturage/releases) pour installation locale avec dump db.

**Comment by margot-sanchez** [comment]
Dossier envoyé au SNUM. En attente retours.

**Comment by jonathanfallon** [comment]
En cours

**Comment by margot-sanchez** [comment]
To Do Margot - relancer

**Comment by margot-sanchez** [comment]
Relancé le 26/02/2021

**Comment by margot-sanchez** [comment]
@charlesimone est sur le coup
