### ISSUE TITLE
Données onglets administrations - persistance des données des autres onglets 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#405]
Contexte : Staging

Je suis super admin, je me connecte sur mon interface pour gérer les profils utilisateurs. Je clique sur modifier un utilisateur opérateur et je bouge sur un autre onglet (exemple : registre).
Je vois toujours la modification du profil utilisateur opérateur et de ce fait cela enlève des informations sur les autres profils utilisateurs du registre. Voir ci-dessous. Par exemple : mon nom Margot Sanchez devrait apparaître. 
![image](https://user-images.githubusercontent.com/15428433/66459839-0f956400-ea76-11e9-88a8-ebef7a99a0b7.png)

**Comment by gillesboisson** [comment]
@margot-sanchez, je peux faire un quick fix qui cache le formulaire si on change d'onglet. Nous avons fait une passe sur cet Ecran avec Jeremie, il serait question qu'on place le formulaire dans un écran séparé, car c'est pas très pratique quand on a des listes à ralonge.
On en parle plus au prochain daily ou sprint review

**Comment by margot-sanchez** [comment]
Yes go pour cacher le formulaire quand on change d'onglet ! Merci

**Comment by margot-sanchez** [comment]
A tester

**Comment by margot-sanchez** [comment]
👍
