### ISSUE TITLE
Impossibilité de créer un nouvel utilisateur

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#407]
Contexte : staging V2

Je suis super admin, je me connecte à mon interface, je vais dans les onglets administrations, je clique sur "ajouter un nouvel utilisateur" le bouton disparaît et rien ne se passe.

**Comment by margot-sanchez** [comment]
MAJ : quand on change d'onglet et qu'on revient les champs de création sont apparus.

**Comment by margot-sanchez** [comment]
MAJ : Lorsque je veux créer un nouveau territoire, dans la liste déroulante les noms des AOM s'affichent mais quand je clique dessus il n'est pas sélectionné.

**Comment by margot-sanchez** [comment]
MAJ : Pour la sélection des opérateurs cela marche. Mais quand on clique sur le bouton créer rien ne se passe.

**Comment by jonathanfallon** [comment]
branche : `staging`
Je réouvre pour les raisons suivantes :

La sélection des territoires ou des opérateurs est impossible quand on est super admin. (pas de matching, ni dropdown)

Quand on est admin territoire : 
- impossible de créer un utilisateur, (il y a `group: 'operators'` à la place de `group: 'territories'` dans le payload.

Quand on est admin opérateur : 
- Création d'un utilisateur : OK
- Création d'un admin : OK

**Comment by jonathanfallon** [comment]
Fixed by #413

**Comment by margot-sanchez** [comment]
Moi je réouvre pour la même raison que @jonathanfallon 
La sélection des territoires ou des opérateurs est impossible quand on est super admin. (pas de matching, ni dropdown)

**Comment by gillesboisson** [comment]
@margot-sanchez tu fait une manip particulière avant, tu est sur quelle navigateur ? J'arrive pas à recréer le bug

**Comment by margot-sanchez** [comment]
https://drive.google.com/file/d/1GtLYO06kJC0m-If8RUDO6vM2FL0Pkztj/view?usp=drivesdk

**Comment by margot-sanchez** [comment]
Le tout premier bug est de retour.

Par contre j'ai trouvé un truc comme quoi si tu vas sélectionner dans la liste cela ne bug pas. C'est la sélection quand on complète le champs qui bug.

**Comment by margot-sanchez** [comment]
A tester par @margot-sanchez

**Comment by margot-sanchez** [comment]
@gillesboisson 

Contexte : staging suite sprint 8 
👍 La sélection des territoires même avec mon pad fonctionne.
👎 Quand je clique sur créer rien ne se passe
![image](https://user-images.githubusercontent.com/15428433/66911192-53f1a880-f010-11e9-8523-a1031ced14e8.png)
