### ISSUE TITLE
Tests de validation des trajets

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#41]
Estimation : 16h

Ecriture du cahier de tests.
https://docs.google.com/spreadsheets/d/1qc0gFqNST42L6BLSednDo5MI56bjvIbIFM90g7hgsZg/edit#gid=658626478

**Comment by nmrgt** [comment]
2h @margot-sanchez

**Comment by margot-sanchez** [comment]
@jonathanfallon j'ai ajouté pas mal d'idées dans "service acquisition"

**Comment by margot-sanchez** [comment]
4H00 @jonathanfallon
