### ISSUE TITLE
Améliorer les retours d'erreur JSON Schema

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#418]
Améliorer le payload des erreurs JSON RPC liées à la validation des JSON Schema pour que le frontend puisse faire des retours pertinents aux utilisateurs de façon générale ou particulière (formulaires).

Back: 

- utiliser l'objet `data` de `RPCErrorType` pour retourner un tableau d'erreurs complet.
- utiliser `message` pour retourner un message intelligible.

https://github.com/epoberezkin/ajv#validation-errors

**Comment by gillesboisson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Petites Feature Back end](https://trello.com/c/8HyQpfcl/3-petites-feature-back-end)
