### ISSUE TITLE
Log Management

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#419]
- [x] Récupération et test clé GPG DINSIC
- [ ] Chiffrement des logs avec clé DINSIC
- [ ] Script de logrotate avec zip, gpg, upload
- [ ] Crontab

**Comment by margot-sanchez** [comment]
Prêt pour la prod.

**Comment by nmrgt** [comment]
lié à #1035

**Comment by margot-sanchez** [comment]
Au 15/06/2021 je n'ai toujours pas compris ce qu'était ce ticket. J'abandonne.
