### ISSUE TITLE
Récupérer le nombre total de trajets (actuellement c'est juste la somme en front )

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#426]
Le problème actuel est que le nombre total de trajets affichés est la somme de ce qui est renvoyé par l'API. 

**BACK** 

Retourner en meta le nombre total de trajets. méthode : "trip.list"

**FRONT**

Adapter ce changement.

**Comment by margot-sanchez** [comment]
Back : 3
Front : 1

**Comment by margot-sanchez** [comment]
En attendant de résoudre le problème est-ce qu'on peut au moins cacher le "50 résultats" ?

**Comment by nmrgt** [comment]
C'est fait en back
