### ISSUE TITLE
Le patch(édition) des "rules" d'une campagne est plus permissif au patch qu'à la création

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#427]
La validation sur le format des "rules" d'une campagne n'est pas effectué lors d'un patch. ( Alors qu'à la création on reçoit bien des erreurs de validation ) 

methode : campaign:patch

**Comment by nmrgt** [comment]
Tu as des datas pour reproduire ? - je demande parce qu'ils ont tous les deux le middleware de validation des rules

**Comment by samueleyre** [comment]
Exemple : je créé une campagne avec le filtre global sur les classe :  A,B,C. Si je fais un patch en remplaçant C par le chiffre 1, je n'ai pas de message d'erreur. La modification est bien effectué car je récupère les classes A, B, 1 dans la campagnes modifiés renvoyé par le list.
