### ISSUE TITLE
Rattachement des origines / destinations à des EPCI

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#433]
En tant que ré utilisateur lambda des données accessibles sur le registre (territoire, opérateur, super admin ou opendata), je souhaites pouvoir rapidement identifier les données OD (Origine/Destination) par EPCI.

Les AOM sont des EPCI mais les EPCI ne sont pas toujours des AOM.

**Comment by jonathanfallon** [comment]
_« Les AOM sont des EPCI mais les EPCI ne sont pas toujours des AOM »_
On a une liste officielle des EPCI ?
