### ISSUE TITLE
Stats du mois en cours non affichées

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#443]
Contexte : staging suite sprint 8

Ci-dessous on voit comme dernier mois d'affiché le mois de septembre avec 35k trajets. Nous sommes le 16/10 et il y a eu des trajets en octobre. 
![image](https://user-images.githubusercontent.com/15428433/66895714-bdaf8980-eff3-11e9-9e3c-85ecc39bc66a.png)
D'ailleurs quand on clique sur vue "jour" on voit bien qu'il y a des trajets en Octobre.
![image](https://user-images.githubusercontent.com/15428433/66895824-f0598200-eff3-11e9-835f-ca2d4e57c7ca.png)

**Comment by samueleyre** [comment]
Tu es sûr qu'il y a des trajets le 15 octobre ?

**Comment by margot-sanchez** [comment]
2H00

**Comment by margot-sanchez** [comment]
👍 sur l'ensemble des interfaces
