### ISSUE TITLE
Mise à jour et documentation des tests sur Cypress

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#446]
* Mettre à jour par rapport aux tests existants
* Définir ensemble les premiers parcours utilisateurs à tester

**Comment by margot-sanchez** [comment]
2H00 pour sam
1H00 pour gilles et margot

**Comment by margot-sanchez** [comment]
https://docs.google.com/spreadsheets/d/1FpBGeSKsfPKSpzshhiOwcjdOeWnbnpN6ZntEVZ7XILw/edit#gid=741779346
