### ISSUE TITLE
Possibilité d'éditer uniquement certains profils

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#448]
Contexte : staging suite sprint 8

Je suis super admin et je me connecte à mon interface. Je vais dans la partie administration pour gérer les utilisateurs et éditer des profils.

Certains profils sont éditables et d'autres sont bloqués (exemple Mark et Franck)

Voir vidéo : https://drive.google.com/file/d/1qR1mgAuCmq7BAVET4amVM6BCjN9GruSQ/view?usp=drivesdk

NB  Tests identiques (les mêmes profils sont bloqués) sur Firefox et Chrome

**Comment by margot-sanchez** [comment]
Sur la prod au 07/11/2019 le problème est de nouveau là !

**Comment by gillesboisson** [comment]
@margot-sanchez sera corrigé lors du déploiement postgres

**Comment by margot-sanchez** [comment]
@jonathanfallon sur dev et staging manuellement dans le DB mettre un nom de famille bidon aux deux profils qui posent problème. Ensuite je pourrai éditer et mettre des vraies informations. Puisque désormais l'ajout de profil sans nom de famille est bloqué, cela ne se reproduira pas.
