### ISSUE TITLE
Filtrage sur les statistiques et les trajets

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#460]
Certains filtres ne fonctionnent pas en LOCAL et en DEV : 

* les horaires de départs
* les statuts ( vérifier la normalisation avec le Front ) 
* les villes
* les dates

**Comment by margot-sanchez** [comment]
C'est la partie Back pour résoudre les tickets #441 et #442 apparemment d'après @samueleyre

**Comment by samueleyre** [comment]
Exemple de payload : 
[
  {
    "id": 1571387205171,
    "method": "trip:list",
    "jsonrpc": "2.0",
    "params": {
      "campaign_id": [
        "5da87dfc2bf5ac0034504186"
      ],
      "date": {
        "start": "2019-10-18T22:00:00.000Z",
        "end": "2020-01-17T23:00:00.000Z"
      },
      "hour": {
        "start": 18,
        "end": 22
      },
      "days": [
        0,
        1
      ],
      "towns": [
        "Lyon"
      ],
      "distance": {
        "min": 80,
        "max": 123
      },
      "ranks": [
        "A",
        "B"
      ],
      "status": "pending",
      "operator_id": [
        "5c803f3eb1b2ad0018adca63"
      ],
      "skip": 0,
      "limit": 50,
      "territory_id": [
        "5c66d89760e6ee004a6cab1f"
      ]
    }
  }
]

**Comment by margot-sanchez** [comment]
Sur trajets cela ne fonctionne pas : 
![image](https://user-images.githubusercontent.com/15428433/67101783-935ff680-f1c2-11e9-9cef-0d956e646de5.png)

**Comment by margot-sanchez** [comment]
Toujours des problèmes sur les distances.
