### ISSUE TITLE
Accessibilité à la liste des campagnes pour les utilisateurs du registre & opérateur

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#467]
Le problème: Les utilisateurs de type registre & opérateur n'ont pas accès aux données des campagnes utiles pour les auto-completes pour filtrer. 

Solution : créer une route dédié pour cette liste avec l'id et le nom des campagnes car l'information des opérateurs sélectionné pour la campagne par le territoire ne doivent pas être public. 
Mettre à jour le commondata-service dans le front.

**Comment by jonathanfallon** [comment]
Ajouter un droit d'accès à la liste des campagnes pour les utilisateurs concernés :
- opérateurs
- registre
