### ISSUE TITLE
Indicateur nombre d'opérateurs actifs

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#471]
Unité : opérateur(s)

Un opérateur désigne une personne morale opérant un service de covoiturage pour mettre en relation les covoitureurs. Le nombre d'opérateur correspond à la somme des services de covoiturage différents actifs. Un service est considéré comme actif à partir du moment où un trajet a été remonté. A titre d'exemple sur le période du 1 au 15 juin 2020, si l'opérateur A fait remonter 5 trajets, que l'opérateur B fait remonter 1 trajet et que l'opérateur C a fait remonter 0 trajet, alors l'indicateur sera de "2 opérateur(s)".

#818 dépend du chantier stats pour être implémenté

**Comment by margot-sanchez** [comment]
Vérifier que les opérateurs récupérés quand on est connecté côté territoire sont bien filtrés par rapport aux opérateurs actifs sur le territoire.

**Comment by samueleyre** [comment]
Ce n'est pas le cas actuellement.

**Comment by nmrgt** [comment]
Pour être sûr de bien comprendre le besoin, le nombre d'opérateur dans les stats correspond au nombre d'opérateur actif vis à vis des filtres. Si je met un filtre par date, je n'ai que les opérateurs qui ont des trajets sur ces dates, quelque soit sont statuts vis à vis de la collectivité. C'est ça ?

**Comment by nmrgt** [comment]
C'est fait en back

**Comment by samueleyre** [comment]
Actuellement le calcul statistique du nombre d'opérateurs est faite avec un count sur une journée ce qui ne donne pas le compte global.

**Comment by jonathanfallon** [comment]
@margot-sanchez c'est testé ?

**Comment by margot-sanchez** [comment]
C'est fait en back mais pas en front cela va arriver dans le prochain chantier stat de gilles. Donc je mets à nouveau gilles dessus
