### ISSUE TITLE
Partager les interfaces entre front et back

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#483]
Le problème : Les interfaces sont dupliqués en front et en back. 

Objects : Rendre disponible les interfaces en les plaçant à la racine du projet.

**Comment by nmrgt** [comment]
Je propose qu'on ne fasse pas de paquet mais des imports avec alias

**Comment by margot-sanchez** [comment]
A faire - dans le front aller chercher les éléments du Back.

**Comment by margot-sanchez** [comment]
Grosse passe avec le Front
