### ISSUE TITLE
Placeholder du n° de téléphone

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#488]
Dans le formulaire d'édition du profile d'un utilisateur (admin) territoire. Utiliser _Numéro de téléphone_ ou _Téléphone_ pour que ce soit plus clair de quel numéro il s'agit.

![screenshot-20191022143727](https://user-images.githubusercontent.com/1656255/67286482-c0215000-f4d9-11e9-9c6a-89c7647d520e.png)

**Comment by margot-sanchez** [comment]
@samueleyre c'est tout petit à faire je pense :)
