### ISSUE TITLE
Message d'erreur RNA absent

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#489]
![screenshot-20191022144444](https://user-images.githubusercontent.com/1656255/67287004-9a487b00-f4da-11e9-8afe-a23e08ddb23b.png)

Pas de message d'erreur pour le champ RNA quand le format n'est pas bon

**Comment by gillesboisson** [comment]
Plus besoin de check, c'est délégué à l'API company
