### ISSUE TITLE
Le bouton "Mettre à jour mes infos" n'est pas sélectionnable dans Territoires & Opérateurs

### ISSUE THREAD

**Issue by Jonathankurtz131** [betagouv/preuve-covoiturage#497]
Contexte : staging #492 

Je suis super admin, je me suis connecté à mon interface et j'ai essayé de modifier les infos dans les onglets Territoires et des opérateurs en veillant à bien remplir les cases obligatoires (celles avec des * ) mais le bouton "Mettre à jour mes infos" reste non sélectionnable. Je fais alors le test de fermer la page pour voir si les infos que j'ai ajoutées dans les cases restent enregistrées mais ce n'est pas le cas. 

Voir images ci-dessous du bug pour tous les territoires : 
![Capture d’écran 2019-10-22 à 18 08 29](https://user-images.githubusercontent.com/54620644/67308809-13f06100-f4fb-11e9-9975-7a1e2889db20.png)
![Capture d’écran 2019-10-22 à 18 08 38](https://user-images.githubusercontent.com/54620644/67308829-19e64200-f4fb-11e9-9a10-7f2ef4f6fca0.png)

![Capture d’écran 2019-10-22 à 18 32 06](https://user-images.githubusercontent.com/54620644/67308403-56656e00-f4fa-11e9-8945-b52e51be9e04.png)

Voir images ci-dessous du bug pour tous les opérateurs : (sauf le Révérend Olive)
![Capture d’écran 2019-10-22 à 18 23 24](https://user-images.githubusercontent.com/54620644/67308312-2f0ea100-f4fa-11e9-81e0-a6e625cd1319.png)
![Capture d’écran 2019-10-22 à 18 23 38](https://user-images.githubusercontent.com/54620644/67308313-2fa73780-f4fa-11e9-8672-57ef2cee53d1.png)
![Capture d’écran 2019-10-22 à 18 32 06](https://user-images.githubusercontent.com/54620644/67308416-5c5b4f00-f4fa-11e9-9cfa-cf58382fb78d.png)

**Comment by samueleyre** [comment]
Je n'ai pas réussi à reproduire ce bug.

**Comment by Jonathankurtz131** [comment]
Hello Sam, 

Lorsque tu remplis les cases obligatoires dans les formulaires, le bouton "Mettre à jour mes infos" est sélectionnable pour toi ?

**Comment by Jonathankurtz131** [comment]
Nous avons fait un test avec Sam, si la case du SIRET est entrée avec un SIRET valide alors le formulaire peut être validé avec le bouton "Mettre à jour mes infos"
