### ISSUE TITLE
Email : création de l'action d'envoi d'email d'invitation

### ISSUE THREAD

**Issue by gillesboisson** [betagouv/preuve-covoiturage#500]
- Possibilité d'envoyer l'email d'invitation depuis la liste d'utilisateurs (Admin / Users)

**Comment by margot-sanchez** [comment]
Je me suis connectée en tant que super admin. J'ai fais renvoyer l'invitation pour le compte de registretoulouse@yopmail.com 
Aucune action ne s'effectue. Mon message dans la console est : "main-es2015.19bcc1cd8390e4b3e097.js:1 ERROR D {headers: d, status: 405, statusText: "OK", url: "https://pdc-api-dev.scalingo.io/rpc?methods=user:sendInvitationEmail", ok: false, …}".
