### ISSUE TITLE
Problème d'affichage des graphiques cumulé et par jour

### ISSUE THREAD

**Issue by Jonathankurtz131** [betagouv/preuve-covoiturage#515]
Contexte : staging #492 

Je suis super admin, je me suis connecté à mon interface et j'ai mis un le filtre de date du 02/10/19 au 09/10/19 et

1. le graphique des trajets cumulés s'affiche sur la période 01/10/19 au 08/10/19. Quand je change les dates le bug persiste. Les abscisses des trajets cumulés s'affichent entre date de début - 1 jour et date de fin - 1 jour. (voir image 1 & 2 ci-dessous)

![Capture d’écran 2019-10-28 à 18 51 30](https://user-images.githubusercontent.com/54620644/67704343-33810100-f9b5-11e9-97eb-20753c63976c.png)
![Capture d’écran 2019-10-28 à 18 51 42](https://user-images.githubusercontent.com/54620644/67704345-34199780-f9b5-11e9-9419-d1b2a6a24bd9.png)

2. le graphique des trajets par jour ne s'affichent pas et il y a un message d'erreur "Aucun trajet n'a été réalisé la semaine dernière avec vos critères de recherches" qui ne correspond pas à la semaine précédente. (voir image 3 ci dessous)

![Capture d’écran 2019-10-28 à 18 54 47](https://user-images.githubusercontent.com/54620644/67704429-675c2680-f9b5-11e9-8bfd-4742f204595e.png)

**Comment by margot-sanchez** [comment]
Pour compléter 
![image](https://user-images.githubusercontent.com/15428433/67844010-4999d900-fafd-11e9-885e-8fa2a76b9735.png)

**Comment by margot-sanchez** [comment]
Ok sur le premier problème. On ferra une passe complète sur les stats pour le second problème.
