### ISSUE TITLE
Possibilité d'exclure les jours fériés des campagnes d'incitation

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#525]
Retour utilisateur : 

Je suis un territoire, lorsque je sélectionne uniquement du lundi au vendredi est-ce que les jours fériés sont exclus ?
A voir si on permet ce genre de disposition ou est-ce qu'on oriente le territoire sur le fait de ne pas indiquer ce type de restriction dans sa délibération.

**Comment by nmrgt** [comment]
- [ ] Création d'un filtre "exclure les jours fériés" en backend
  - [ ] Trouver un service qui fournit ces jours
  - [ ] Implémenter le pont avec ce service
  - [ ] Implémenter la règle
- [ ] Mise à jour du front

**Comment by margot-sanchez** [comment]
Finalement on va pas le faire :)
