### ISSUE TITLE
Company service

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#551]
Objectif : Centraliser les données des entreprises (_companies_) et les synchroniser avec l'API Entreprise (base SIRENE).

- [x] création du service `company`
- [x] migration du schema `company`
- [x] migration de la table `companies`
- [ ] création de la vue `common.companies`
- [x] action `company:fetch`
- [ ] modifications des actions `update`, `create`, etc... dans les services `operator` et `territory`
- [x] détecter un changement de SIRET lors d'une mise à jour d'opérateur ou territoire pour récupérer les infos de l'entreprise

### Action `company:fetch`

Récupération des données de l'entreprise à partir du `SIRET`

URL : https://entreprise.data.gouv.fr/api/sirene/v3/etablissements/<SIRET>

Mapping des données :

| API SIRENE | Schema SQL | Commentaires |
| ---------- | ---------- | ------------ |
| etablissement.siret | siret | |
| etablissement.geo_l4 | street | _en majuscules_ |
| etablissement.code_postal | postcode | |
| etablissement.libelle_commune | city | |
| etablissement.code_cedex | cedex | _concat de cedex_ |
| etablissement.libelle_cedex | cedex | _concat de cedex_ |
| etablissement.libelle_pays_etranger \|\| 'France' | country | |
| etablissement.activite_principale | naf | |
| etablissement.unite_legale.denomination | legal_name | |
| etablissement.etat_administratif | is_active | A (actif) ou F (fermé) -> true / false |

**Comment by gillesboisson** [comment]
@nmrgt @jonathanfallon tout est bon chez nous il reste plus que 2 3 implementation chez vous

**Comment by jonathanfallon** [comment]
Voir #604 et régler tout en mm temps.

**Comment by nmrgt** [comment]
- [ ] Ajouter un notify vers company:fetch sur [operator.create, operator.update, territory.create, territory.update]
- [ ] Ajouter un call vers company:find sur [operator.find, territory.find]
