### ISSUE TITLE
Campagne - modification des campagnes en cours

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#552]
# Sélection des opérateurs
Aujourd'hui la sélection des opérateurs se fait au niveau de l'étape 2 du moteur de création de campagne. 
Retours de la part d'une AOM : c'est problématique car nous allons utiliser le moteur pour orienter notre délibération :
1) il est obligatoire de sélectionner un opérateur pour passer à l'étape 3 et son nom est mentionné dans le texte à copier coller dans la délibération (pourtant au moment de la délib nous ne savons pas qui seront les opérateurs volontaires)
2) si nous lançons une campagne et qu'un opérateur s'ajoute, nous sommes bloqués car nous ne pouvons modifier une campagne

Propositions : 
- sortir la sélection des opérateurs au moment du lancement de la campagne. 
- ajouter une date d'activation de l'opérateur si ajout en cours de route (exemple : 3 opérateurs du 1 au 31 octobre, ajout d'un nouvel opérateur au 1 novembre).

# Modification des dates

# Modification de l'enveloppe

A réfléchir avec l'équipe.

**Comment by nmrgt** [comment]
Lié à la modification de campagne en cours de campagne

**Comment by margot-sanchez** [comment]
@margot-sanchez à spécifier !
