### ISSUE TITLE
Super admin pouvant supprimer un opérateur

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#566]
Contexte : staging

En tant que super admin aujourd'hui je ne peux pas supprimer de compte opérateur de tests. Voir ci-dessous, il y uniquement possible d'éditer le compte mais pas de le supprimer. 
![image](https://user-images.githubusercontent.com/15428433/68661908-0cd9d300-053c-11ea-8c03-b68eb0d38db0.png)

**Comment by gillesboisson** [comment]
@margot-sanchez en attente car pas implémenté dans l'API, j'ai assigné à @jonathanfallon

**Comment by margot-sanchez** [comment]
👍
