### ISSUE TITLE
Déconnecter l'exploration de la vue front

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#579]
Quand on clique sur documenter, afficher un message : 'Pas encore implémenté'.

**Comment by jonathanfallon** [comment]
Du contexte ?

**Comment by margot-sanchez** [comment]
@samueleyre c'est où ça ? Tu peux mettre une copie d'écran ?

**Comment by margot-sanchez** [comment]
Testé sur dev 👍
