### ISSUE TITLE
Statistiques & filtres distance calcule sur le théorique si réelle null

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#580]
Contexte : prod

Aujourd'hui le calcul de la distance totale se fait uniquement sur les distances réelles communiquées. Si la distance communiquée = null, nous calculons un distance théorique. Prendre en compte cette distance dans le calcul. Mettre une condition pour le if distance réelle = null, prendre distance théorique.

**Comment by margot-sanchez** [comment]
Ceci est aussi valable pour les filtres.

**Comment by margot-sanchez** [comment]
Est-ce qu'on pourrait pas faire un truc du style :
distance.calculated==> OSRM
distance.communicated ==> celle communiquée
distance=if(distance.communicated=null; distance.calculated; distance.communicated)
Et que du coup l'ensemble des stats et des recherches soit basée sur la dernière variable au lieu chaque fois de faire une requête à deux étage (je sais pas si je suis claire). Mais en gros créer une nouvelle variable.

**Comment by margot-sanchez** [comment]
UP !

**Comment by gillesboisson** [comment]
Problème de nettoyage distance = 0 > null : @jonathanfallon @gillesboisson

**Comment by margot-sanchez** [comment]
A tester une fois la PR passée ! Me pinger !

**Comment by margot-sanchez** [comment]
@jonathanfallon non cela ne marche pas... parce que 5 km c'est clairement pas possible.
![image](https://user-images.githubusercontent.com/15428433/70647974-6a039a00-1c4a-11ea-9049-46b51e931cff.png)
