### ISSUE TITLE
l'API company:find donnée manquante

### ISSUE THREAD

**Issue by gillesboisson** [betagouv/preuve-covoiturage#585]
l'action company retourne pas toute les donnée, test avec le siret '53996626700012' (dotify):
- vat_intra = null
- pas de cas avec des numéro RNA

**Comment by nmrgt** [comment]
- vat_infra n'est pas traité actuellement (en fait, l'API ne le renvoie que sur un call sur le siren et non le siret, j'ai considéré que cette donnée n'était pas prioritaire donc c'est pas implémenté).
- j'ai pas compris ton point sur les numéro RNA :)

**Comment by gillesboisson** [comment]
j'ai pas trouvé de siret de d'assoce valide pour tester, et avec les territoires que j'ai testé ça me retourne rien. Est ce que tu as un exemple de siret avec RNA qui match @nmrgt

**Comment by nmrgt** [comment]
78422809000105 ?

**Comment by jonathanfallon** [comment]
Le num de TVA intra c'est simple à calculer :
```js
`FR${(12 + 3 * (parseInt(siret.substr(0,9), 10) % 97)) % 97}${siret.substr(0,9)}`
```

_Source : https://fr.wikipedia.org/wiki/Code_Insee#Num%C3%A9ro_de_TVA_intracommunautaire_
