### ISSUE TITLE
Prendre en compte les cartes de transport

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#59]
### Objectif
Donner la possibilité aux opérateurs quand les AOM ont besoin de l'information pour l'application de leur politique d'incitation, d'envoyer des informations relatives aux cartes de transport (ex: Navigo pour IDFM).

### Questions :
- Quel format ?
  1. Nom de la carte + possession (oui/non)
  2. Infos sur la carte (nom de la carte, ID)
- Ajouter une variable pour la configuration de la politique d'incitation
  1. `boolean`

**Comment by margot-sanchez** [comment]
En fonction de la délibération exacte de IDFM (17/04) on y verra un peu plus clair. 
👍 pour le boolean dans la configuration : paramètre ou filtre, j'aurais tendance à dire paramètre dans le cas présent. 
Je me demande s'il est pertinent de faire remonter le numéro de la carte ou pas.

**Comment by margot-sanchez** [comment]
Lié à #72

**Comment by margot-sanchez** [comment]
## Questions : 
Comment déterminé s'il s'agit d'un pass annuel ou mensuel ? 
Conditionné à la délibération.

**Comment by margot-sanchez** [comment]
Conclusion suite au RDV IDFM. 
Phase 1 : On rajoute un champs dans le schéma JSON et CSV pour faire remonter le N° du pass. Attention le faire le plus générique possible (pas de masque) pour l'envisager sur d'autres AOM. Ensuite on remonte du binaire (0 n'a pas de pass, 1, a un pass). 
Phase 2 : Fin 2019 ouverture de l'API IDF M pour requeter si c'est un pass annuel, mensuel, non validé, etc.

**Comment by jonathanfallon** [comment]
On va collecter les numéros et les types de cartes

Done : 
- [x] Documentation JSON
- [x] Documentation CSV
- [x] Schema JSON
- [x] Schema CSV

**Comment by jonathanfallon** [comment]
On va collecter les numéros et les types de cartes

Done : 
- [x] Documentation JSON
- [x] Documentation CSV
- [x] Schema JSON
- [x] Schema CSV

**Comment by margot-sanchez** [comment]
@jonathanfallon je reopen avec une proposition d'un opérateur : 

"card" -> "transit_pass"
"number" -> "id"
Et plutôt que "name" soit un champ libre, faire un énumération  qui liste tous les pass possibles. 

[ ] Faire une page wiki qui détaille les specs pour chaque type de pass. 
[ ] Prendre en compte les cartes spéciales (Exemple, les cartes anonymes, ou encore celles pour des policiers)

**Comment by jonathanfallon** [comment]
J'aurais tendance à favoriser l'orthographe de nos amis britanniques :wink: 
```
  "travel_pass": "nom normalisé du pass, cf. doc",
  "id": "id de la carte",
```
