### ISSUE TITLE
Filtrer les données des incitations   

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#601]
Concerne la méthode trip:list

* Filtrer les données des incitations renvoyer vers le fronts qui ne concernent pas des campagnes d'incitations.

* Filter les incitations par rapport aux campagnes qui sont sur le territoire ( pour le dashboard des territoires )

**Comment by nmrgt** [comment]
Est-ce que tu peux préciser ? Je ne comprends pas la demande.

**Comment by margot-sanchez** [comment]
En gros ne pas afficher les opertor.incentives qui ne concernent pas les campagnes.

**Comment by margot-sanchez** [comment]
![image](https://user-images.githubusercontent.com/15428433/70614600-1a51ae00-1c0b-11ea-9adb-b6251cb85be4.png)

**Comment by margot-sanchez** [comment]
Ticket obsolète puisque sur la nouvelle prod cela disparait
