### ISSUE TITLE
Stats - Seuil minimum sur les dates

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#607]
Contexte : dev

Je suis super admin, sur l'interface le graphique est illisible. Pourquoi ? Car il y a une donnée en 1970... 

1° ceci doit être bloquée à l'acquisition (back)
2° mettre un historique de maximum 1 an (front)
![image](https://user-images.githubusercontent.com/15428433/69262082-178f0a80-0bc3-11ea-9f22-67b49be4f3a6.png)

**Comment by samueleyre** [comment]
Ne concerne pas le front, on va appliquer avec un date de 1 an en arrière au max de base.
