### ISSUE TITLE
Pieds de mail - DINSIC ==> DINUM 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#609]
Dans le service d'emailing changer les signatures en remplaçant DINSIC par DINUM. 

Un service fourni grâce au soutien financier de l'ADEME, puis de la DGITM et à l’appui stratégique et opérationnel de la DINUM.

En théorie, à faire avant le 31/12/2019.

**Comment by gillesboisson** [comment]
@margot-sanchez c'est fait tu peux double check. Il y a eu des changements :
- dans les pieds d'email
- dans le mentions légal de la license de la plateforme
- le gitbook

**Comment by jonathanfallon** [comment]
Fait dans les emails (je suis passé dessus et ça me piquait les :eyes:)

**Comment by margot-sanchez** [comment]
Ok j'ai double check
 - [X] Pieds de mail
