### ISSUE TITLE
Réparer vue trajets, mettre à jour les données renvoyé par la méthode trip.list

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#612]
Mettre à jour les champs à renvoyer.

- Enlever is_driver, ajouter incentives.
- Normaliser la date ( datetime est renvoyé par l'api, mais l'interface LightTripInterface définit start_datetime ) 

`
campaigns_id ( array )
start_datetime
end_town
operator_class
operator_id
start_town
status
trip_id
incentives
`

**Comment by jonathanfallon** [comment]
#611

**Comment by nmrgt** [comment]
faut dans fix/back_trip

**Comment by margot-sanchez** [comment]
Ok c'est bon pour moi sur dev 👍
