### ISSUE TITLE
Pas de message d’erreur pour l’email dupliqué quand changement d’email sur son profile

### ISSUE THREAD

**Issue by gillesboisson** [betagouv/preuve-covoiturage#654]
duplicate key value violates unique constraint “users_email_idx”

**Comment by margot-sanchez** [comment]
@gillesboisson je n'ai toujours pas de message d'erreur de mon côté !

**Comment by margot-sanchez** [comment]
Test réalisé 👎 
Je suis super admin
Je vais créer un utilisateur avec l'adresse margotchiô@yopmail.com
Je valide son compte.
Je vais ensuite créer un nouvel utilisateur avec l'adresse margotchipo@yopmail.com
Je valide l'envoi du formulaire mais rien ne se passe.
Je tente avec margotchiô2@yopmail.com et là ça fait quelque chose.

**Comment by margot-sanchez** [comment]
En revanche 👍 lorsque je vais changé l'email de margotchipo2@yopmail.com pour margotchipo@yopmail.com là j'ai bien un message !

**Comment by margot-sanchez** [comment]
En conclusion :
