### ISSUE TITLE
Bug suppression utilisateurs

### ISSUE THREAD

**Issue by gillesboisson** [betagouv/preuve-covoiturage#656]
La liste des utilisateurs n'est pas raffraichi quand un utilisateur est supprimé

**Comment by margot-sanchez** [comment]
Test 👍 
Se connecter en tant qu’utilisateur admin (registre, operateur, territoire)
supprimer un utilisateur
vérifier qu’il y a un message de confirmation, que la liste se met bien à jour (sans l’utilisateur supprimé)
