### ISSUE TITLE
bug : affichage données profil

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#659]
Context :  je me connecte à mon espace et je vais dans la section profil

Problème : Aucun donnée rempli dans le formulaire

Console : "ERROR Error: Must supply a value for form control with name: 'phone'"

**Comment by margot-sanchez** [comment]
Test 👍 
se connecter en tant qu’utilisateur qui n’a pas de numéro de tel
vérifier que dans le profil, les informations sont bien présentes
sauver
raffaichir la page et vérifier que les données de profile sont bien à jour
