### ISSUE TITLE
Gestion de classes multiples pour le conducteur dans le trip

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#66]
Parent : #60

Lors de la reconstruction du trip, si les classes des couples sont différentes, appliquer la plus élevée sur le conducteur.

**Comment by margot-sanchez** [comment]
A+A=A
B+A=B
A+B=B
B+B=C

**Comment by nmrgt** [comment]
Précision concernant le moteur d'incitation : à l'heure actuelle, il n'y a pas de "classe de trajet" : chaque personne au sein du trajet a une classe correspondant à ce qui a été envoyé par l'opérateur.
