### ISSUE TITLE
Pas les bonnes permissions pour les méthode trip.list & trip.stats en tant que consultant du registre

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#661]
* mettre à jour les permissions d'un utilisateur consultant pour accéder aux données des statistiques & trat. 

Problème : 403 sur les routes trip.list & trip.stats avec un utilisateur du groupe registre & en consultation. 

Solution : Mettre à jour les bonnes permissions à la création d'un utilisateur qui a des droits de consultation

**Comment by margot-sanchez** [comment]
👍
