### ISSUE TITLE
Renvoie de l'email d'invitation

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#669]
branche : dev

Problème: en cliquant sur 'renvoyer l'invitation' une erreur 400 est retourné : "No schema provided for this type"

**Comment by gillesboisson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs du moment](https://trello.com/c/giXXA0aK/1-bugs-du-moment)

**Comment by gillesboisson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BO bug de chauffe](https://trello.com/c/QiPJqP82/2-bo-bug-de-chauffe)

**Comment by margot-sanchez** [comment]
Test 👍 
Aller en tant qu’utilisateur registre dans la gestion des utilisateurs
Cliquer sur le bouton réenvoyer l’invitation
vérifier que le message de confirmation s’affiche
