### ISSUE TITLE
start et end en Array

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#67]
Pour les positions `start` et `end` du conducteur ou du passager, utiliser un tableau afin de stocker plusieurs valeurs.

**Comment by jonathanfallon** [comment]
Utilisation de `calc_duration` et `calc_distance` pour les données calculées par OSRM. Pas de flag à ajouter.

**Comment by margot-sanchez** [comment]
Duration et distance sont basées sur carpool.id target passenger donc désormais obsolète et possible de fait !
