### ISSUE TITLE
Bug filtre trajets aucun opérateur n'est visible

### ISSUE THREAD

**Issue by gillesboisson** [betagouv/preuve-covoiturage#670]
Bug filtre trajets aucun opérateur n'est visible

**Comment by gillesboisson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#](https://trello.com/c/giXXA0aK/1-untitled)

**Comment by gillesboisson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BO bug de chauffe](https://trello.com/c/QiPJqP82/2-bo-bug-de-chauffe)

**Comment by jonathanfallon** [comment]
Fonctionne correctement sur app-dev. Peut-être un soucis de DB en local.

**Comment by margot-sanchez** [comment]
@jonathanfallon moi cela ne marche pas sur dev non plus
![image](https://user-images.githubusercontent.com/15428433/70429454-d9299480-1a78-11ea-83aa-cb59d92690c8.png)

**Comment by margot-sanchez** [comment]
En fait c'était juste puisque que c'est du opt-in on avait aucun opérateur qui avait sélectionné le territoire.
