### ISSUE TITLE
Amélioration campagne récapitulatif - conditions particulieres

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#684]
Contexte : dev (09/12/2019)

Je suis connectée en tant que territoire. Je vais configurer une campagne d'incitation pour laquelle j'ai défini des conditions particulières sur les trajets au niveau de l'étape 2. Pour autant au moment du récapitulatif ces conditions particulières ne sont plus présentes (cf : ci-dessous)

![image](https://user-images.githubusercontent.com/15428433/70440260-16e6e700-1a92-11ea-9b48-ea4d626d294d.png)

**Comment by samueleyre** [comment]
@margot-sanchez ça correspond à quoi plus exactement ? Tu pourrais reproduire ce bug ?

**Comment by margot-sanchez** [comment]
En fait c'est fait :)
