### ISSUE TITLE
🔥 Lat / Long bug sur la précision 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#688]
Contexte : dev

Aujourd'hui lors de l'export de données CSV la précision sur lat/long bug complet (47, 48 au lieu de 47.654 et 48.987) on se retrouve avec des précisions allant de la France à la Pologne limite.

**Comment by nmrgt** [comment]
C'est lié au truncate qui est peut-être un peu fort :)
Actuellement, on a (en fonction de la densité) entre 0 et 3 chiffres après la virgule.
On peut paramétrer ça comme tu le souhaites sachant qu'on a une densité entre 1 et 4

**Comment by margot-sanchez** [comment]
Oui voir la #160

**Comment by margot-sanchez** [comment]
Je propose 
densité 1,2 et 3 - 3 décimales
densité 4 - 2 décimales

**Comment by margot-sanchez** [comment]
A tester par margot quand la PR sera faite

**Comment by margot-sanchez** [comment]
La PR est passée et pourtant aucun changement de mon côté. Je viens de faire l'export à 19H00. 
![image](https://user-images.githubusercontent.com/15428433/70647785-0a0cf380-1c4a-11ea-9a1c-dbce33f957a0.png)
