### ISSUE TITLE
Permettre de ne pas envoyer d'identité dans un couple

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#69]
Parent : #60 

Si l'opérateur a les infos du couple mais que l'occupant ne veut pas transmettre ses coordonnées personnelles, permettre de passer :
`identity: null` dans `driver` ou `passenger`

**Comment by margot-sanchez** [comment]
C'est bon sur le service acquisition. Mettre à jour le cross-check et normalization @nmrgt !
