### ISSUE TITLE
Permettre de n'envoyer qu'une partie de la preuve

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#70]
Parent : #60

Permettre d'envoyer `driver: null` ou `passenger: null` si l'opérateur n'a pas toute la preuve.

La reconstruction du trip doit échouer ou ne pas avoir lieu tant que suffisamment de parties ne sont pas récupérées.

? Gestion du délai maximal de modification du trip (ajout des infos des couples au fur et à mesure de leur arrivée)

**Comment by margot-sanchez** [comment]
Voir #69
