### ISSUE TITLE
Adapter la norme pour les jours de la semaine

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#704]
Cf : [hackmd](https://hackmd.io/Fp150fhtRr-g4gIvTgsCqA)

Norme : Dimanche : 0 ... Samedi : 6

Faire les modifications : 
- [x] sur les filtres ( trajets & stats )  
- [x] sur les campagnes & incitations

**Comment by margot-sanchez** [comment]
@samueleyre mettre à jour partout !
