### ISSUE TITLE
Tester les outils Etalab pour la publication du schema de données

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#705]
Cf. base des lieux de covoiturage de l'équipe transport.data.gouv.fr

https://doc.transport.data.gouv.fr/producteurs/points-de-rencontre-de-covoiturage
https://schema.data.gouv.fr/etalab/schema-lieux-covoiturage/latest.html
https://transport.data.gouv.fr/datasets/base-nationale-consolidee-des-lieux-de-covoiturage/
https://csv-gg.etalab.studio/

Idées : Publier le schema, orienter les utilisateurs vers le validateur

**Comment by margot-sanchez** [comment]
Allez je vais tenter de le faire sur la partie référencement par sur l'utilisation du validateur.
