### ISSUE TITLE
Chantier fuseau horaire

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#706]
Aujourd'hui les fuseaux horaires 1) ne sont pas demandés 2) ne sont pas recalculés 3) ne sont pas stockés de toute manière. 

Ceci engendre quelques problématiques que nous n'avions pas encore considérées. 
Exemple : je suis un territoire à Nouméa, j'ai des trajets au Canada, je retrouve des trajets du 19 mai sur la date du 18 mai, etc. 

A voir comment on fait ça proprement. Au choix 1) demander 2) calculer en fonction de lat/long ?

Spec / Doc : https://hackmd.io/Olb-3ZADSJeXMx7SDoxTyg

**Comment by margot-sanchez** [comment]
A tester avec des trajets qui chevauchent des changements d'heure :)

**Comment by jonathanfallon** [comment]
La PR #1099 est fusionnée dans le code.
On a enlevé le filtre par heure qui posait un gros problème de performances sur la liste des trajets.
Les stats sont en UTC mais ce n'est pas vraiment génant car ce sont des données grosse maille.
L'export de données est converti dans le fuseau horaire de l'utilisateur avec le bon format de dates. Les changements d'heure sont bien visibles (+0100 ou +0200 en fonction de la date).
L'application de la règle de plage horaire pour les campagnes est effective. Le fuseau horaire est envoyé avec la campagne.

Le fonctionnement en résumé c'est :
- la base de données stocke toutes les dates en UTC (pas de changement d'heure)
- les dates sont envoyées au backend en UTC (conversion par le front)
- un fuseau horaire (timezone) au format texte (ex. Europe/Paris) est envoyé à l'API au cas par cas. Il est détecté automatiquement par l'API native `Intl` dans le navigateur de l'utilisateur. Le backend s'assure que le nom envoyé est supporté par la base de données.
- Dans ces cas, les dates et heures sont converties par l'API et leur format affiche le décalage du fuseau horaire au format ISO.
