### ISSUE TITLE
Problème API géo si point de départ ou arrivée à l'étranger

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#712]
Aujourd'hui l'API plante quand le départ ou arrivée est à l'étranger car cela fait appel à l'API Géo.

**Comment by margot-sanchez** [comment]
@nmrgt tu m'avais dit que c'était bon non ça ? Je vois pas la référence de la PR dans le ticket.

**Comment by nmrgt** [comment]
fait dans https://github.com/betagouv/preuve-covoiturage/commit/dfb9b3f6e6cf3e547a3766da76419ba2c4056626

**Comment by margot-sanchez** [comment]
🍒 pick
