### ISSUE TITLE
Nouvelle règle sur le passenger.seat 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#713]
Le passenger.seat doit affecter le résultat du calcul de l'incitation. 

- [x] Back : 2H00
- [x] Front : 2H00

**Comment by samueleyre** [comment]
@margot-sanchez Il faut voir si ont choisit une valeur par défault pour les passenger seats ou si on met l'option dans le formulaire de création des campagnes. 

Je serais pour dire qu'on prend en compte les sièges des passagers par défaut et de mettre cette information dans la documentation.

**Comment by margot-sanchez** [comment]
C'est bien la deuxième option @samueleyre
