### ISSUE TITLE
Amélioration du texte de compréhension module sélection de la visibilité des opérateurs

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#723]
Contexte : dev (2019/12/12)

Aujourd'hui un opérateur (admin) ne comprend pas ce qu'il doit faire sur ce module (cf photo)
![image](https://user-images.githubusercontent.com/15428433/70728548-e73e1600-1d01-11ea-8c16-7a261b59679b.png)

Ajouter les textes qui sont sur les maquettes.
![image](https://user-images.githubusercontent.com/15428433/70728199-40f21080-1d01-11ea-9d7d-384ca2c3ed52.png)
![image](https://user-images.githubusercontent.com/15428433/70728593-fe7d0380-1d01-11ea-9831-d6f58621ff72.png)

**Comment by samueleyre** [comment]
@margot-sanchez Pour la partie territoires sélectionnés, c'est un peu lourd quand on sélectionne tout. 
![image](https://user-images.githubusercontent.com/11545031/71814916-2c920100-307e-11ea-96fe-6b400f393e48.png)

J'ai opté pour afficher le nombre de territoires sélectionnés.
