### ISSUE TITLE
Chantier "se connecter en tant que"

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#729]
En tant que super admin je souhaiterais pouvoir avoir une fonctionnalité me permettant de "se connecter en tant que" ou imiter la vue d'autres utilisateurs (consultation/admin/opérateur/registre/territoire). Ceci afin de pouvoir faire du support mais aussi faire des démonstrations facilement et enfin tester plus rapidement.

- jongler avec les cookies de session pour passer d'une session à l'autre.
- ajouter un bouton pour quitter le mode _impersonate_

Exemple : admin de Gitlab

**Comment by jonathanfallon** [comment]
TODO : faire un proto pour valider le modèle avec les cookies de session

**Comment by margot-sanchez** [comment]
On ferme ce ticket car un environnement démo à été fait.
