### ISSUE TITLE
Impossibilité de créer un nouvel opérateur si le formulaire est 100% complété

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#737]
Contexte ; staging 13/12/2019

Je suis super admin et je souhaite créer un nouvel opérateur. Par chance j'ai quasiment l'ensemble des informations donc je peux remplir la quasi intégralité du formulaire.
![image](https://user-images.githubusercontent.com/15428433/70805129-86254980-1db8-11ea-8e9c-0347630582cd.png)
![image](https://user-images.githubusercontent.com/15428433/70805268-d13f5c80-1db8-11ea-9cd2-5930465d13ac.png)
![image](https://user-images.githubusercontent.com/15428433/70805304-e4eac300-1db8-11ea-9689-6de0fd333fe8.png)

Je peux cliquer sur le bouton me permettant de créer le nouvel opérateur mais cela me fait une erreur. 
POST https://api-staging.covoiturage.beta.gouv.fr/rpc?methods=operator:create 400
`[{id: 1576244781166, error: {,…}, jsonrpc: "2.0"}]
0: {id: 1576244781166, error: {,…}, jsonrpc: "2.0"}
error: {,…}
code: -32602
data: "[{"keyword":"required","dataPath":".bank","schemaPath":"#/properties/bank/required","params":{"missingProperty":"bank_name"},"message":"should have required property 'bank_name'","schema":{"bank_name":{"macro":"varchar"},"client_name":{"macro":"varchar"},"iban":{"macro":"iban"},"bic":{"macro":"bic"}},"parentSchema":{"type":"object","required":["bank_name","client_name","iban","bic"],"additionalProperties":false,"properties":{"bank_name":{"macro":"varchar"},"client_name":{"macro":"varchar"},"iban":{"macro":"iban"},"bic":{"macro":"bic"}}},"data":{}},{"keyword":"required","dataPath":".bank","schemaPath":"#/properties/bank/required","params":{"missingProperty":"client_name"},"message":"should have required property 'client_name'","schema":{"bank_name":{"macro":"varchar"},"client_name":{"macro":"varchar"},"iban":{"macro":"iban"},"bic":{"macro":"bic"}},"parentSchema":{"type":"object","required":["bank_name","client_name","iban","bic"],"additionalProperties":false,"properties":{"bank_name":{"macro":"varchar"},"client_name":{"macro":"varchar"},"iban":{"macro":"iban"},"bic":{"macro":"bic"}}},"data":{}},{"keyword":"required","dataPath":".bank","schemaPath":"#/properties/bank/required","params":{"missingProperty":"iban"},"message":"should have required property 'iban'","schema":{"bank_name":{"macro":"varchar"},"client_name":{"macro":"varchar"},"iban":{"macro":"iban"},"bic":{"macro":"bic"}},"parentSchema":{"type":"object","required":["bank_name","client_name","iban","bic"],"additionalProperties":false,"properties":{"bank_name":{"macro":"varchar"},"client_name":{"macro":"varchar"},"iban":{"macro":"iban"},"bic":{"macro":"bic"}}},"data":{}},{"keyword":"required","dataPath":".bank","schemaPath":"#/properties/bank/required","params":{"missingProperty":"bic"},"message":"should have required property 'bic'","schema":{"bank_name":{"macro":"varchar"},"client_name":{"macro":"varchar"},"iban":{"macro":"iban"},"bic":{"macro":"bic"}},"parentSchema":{"type":"object","required":["bank_name","client_name","iban","bic"],"additionalProperties":false,"properties":{"bank_name":{"macro":"varchar"},"client_name":{"macro":"varchar"},"iban":{"macro":"iban"},"bic":{"macro":"bic"}}},"data":{}}]"
message: "Invalid params"
id: 1576244781166
jsonrpc: "2.0"`

**A noter que lorsque j'ai enlevé les informations non obligatoires j'ai pu créer l'opérateur !**

**Comment by margot-sanchez** [comment]
Pour le Payload

**Comment by margot-sanchez** [comment]
Je viens de retester cela vient des informations bancaires !

**Comment by margot-sanchez** [comment]
Le code BIC est : TRZOFR21XXX
On accepte pas les codes BIC étrangers ?

**Comment by jonathanfallon** [comment]
TREEZOR est une banque française ;)
