### ISSUE TITLE
Plafond maximum (2 trajets par jour) de gratuité pour les passagers

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#74]
#72 
Ceci signifie que le montant du coût du trajet pour les passagers (qui peut être par nature variable) doit être automatiquement ajouté au montant de subvention de l'AOM à destination de l'opérateur. 
Ce n'est donc pas une règle sur un montant mais de dire 
- si trajet passager aller travail = 2€ alors subvention 2€ 
- si trajet passager  retour travail = 3€ alors subvention 3€
- si trajet passager pour aller faire les courses = 1€ alors subvention = 0€

Donc dans la formule il faut plafonner avec comme sortie le montant d'incitation = passenger.cost

**Comment by margot-sanchez** [comment]
#59 
Une condition serait d'avoir un pass navigo.

**Comment by margot-sanchez** [comment]
@nmrgt en fait il faudrait pouvoir mettre une variable en sortie au lieu d'un chiffre.

**Comment by nmrgt** [comment]
rattaché à #354 
A tester
