### ISSUE TITLE
Possibilité de plafonner l'aide pour ne pas avoir un reste à charge <0 ==> bénéfice

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#75]
Une AOM souhaite mettre en oeuvre une politique très incitative pour le conducteur en fonction du nombre de passagers en partant du principe que dans la majorité des cas, la voiture n'est pas remplie à 100%. 
Donc en gros : 
- si 1 passager l'incitation conducteur est importante par exemple 3€ pour 5 km. 
- si 2 passagers l'incitation conducteur devrait être de 2*3€ mais les frais restants à charge avant incitation AOM étaient de 5€ donc plafonner l'incitation à 5€.

**Comment by margot-sanchez** [comment]
Voici la méthodologie :
Etape 1 : nous collectons 3 informations auprès des opérateurs :
passenger.seats : Nombre de sièges réservés par l'occupant passager. Défault : 1
passenger.contribution : Coût total du service pour l’occupant passager en fonction du nombre de sièges réservés après une possible incitation opérateur (subventions, promotions, etc).
driver.revenue : La somme perçue par le conducteur, comprenant les contributions des passagers, après une possible incitation opérateur (subventions, promotions, etc) et prise de commission de l’opérateur.
Etape 2 : nous capitalisons les informations paramétrées par l’AOM dans son module de gestion de politique incitative sur le registre :
driver.incentive : Incitation donnée par l'AOM au conducteur.
passenger.incentive : Incitation donnée par l'AOM au passager.
Etape 3 : le registre procède ensuite aux calculs suivants :
driver.expense : Frais engagés par le conducteur selon le barème kilométrique (0,558 euros / km). Seuls les kilomètres covoiturés sont pris en compte.
driver.cost : driver.expense - driver.revenue : Coût pour le conducteur basé sur les frais engagés après avoir perçu les contributions des passagers, une possible incitation opérateur (subventions, promotions, etc) et prise de commission de l’opérateur.
passenger.cost : passenger.contribution / passenger.seats : Coût pour un passager unique.
driver.remaining_fee : driver.cost - driver.incentive : Somme restante à charge du conducteur après incitation de l'AOM.
passenger.remaining_fee : passenger.cost - passenger.incentive : Somme restante à charge du passager après incitation de l'AOM.

**Comment by margot-sanchez** [comment]
![image](https://user-images.githubusercontent.com/15428433/56601660-09ace300-65fc-11e9-9940-b958c2ee331e.png)
Illustration pour comprendre.

**Comment by nmrgt** [comment]
voir le gitbook

**Comment by nmrgt** [comment]
référence à #366

**Comment by nmrgt** [comment]
8h

**Comment by jonathanfallon** [comment]
à mettre dans la détection de fraudes et lancer une alerte.

**Comment by margot-sanchez** [comment]
1) a mettre dans le calcul

**Comment by margot-sanchez** [comment]
J'ai rajouté dans le document rapido à la fin : https://docs.google.com/spreadsheets/d/1qc0gFqNST42L6BLSednDo5MI56bjvIbIFM90g7hgsZg/edit#gid=155989203

**Comment by margot-sanchez** [comment]
En attente des décrets finalisés.
