### ISSUE TITLE
Limiter le montant maximum par opérateur

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#76]
Limitation du montant maximum par opérateur

**Comment by margot-sanchez** [comment]
#72

**Comment by jonathanfallon** [comment]
### Problématique

Effectuer une simulation du coût de l'incitation lors de la constitution du _trip_ afin d'avoir un prévisionnel des dépenses engagées par la future campagne.
Ce prévisionnel sera modifié lors de l'application des incitations, idéalement dans le sens d'une économie.

### Questions

Eclaircir les actions à effectuer lors de l'approche ou du dépassement du seuil fixé pour chaque opérateur.

### Pistes

Afficher la consommation de l'enveloppe sur le dashboard opérateur et AOM.

**Comment by margot-sanchez** [comment]
On verra si on a vraiment besoin de la faire en 2020.

**Comment by margot-sanchez** [comment]
@margot-sanchez regarder la nouvelle convention
