### ISSUE TITLE
Problème de MAJ du cache 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#767]
Contexte : dev 19/12/2019

Attention lorsque je me connecte les stats ressemblent à ça.
![image](https://user-images.githubusercontent.com/15428433/71178665-f592b180-226e-11ea-8de5-9e16964924c6.png)
Lorsque je mets un filtre, cela se corrige automatiquement. Cependant, lorsque réinitialise 0 revient.

**Comment by nmrgt** [comment]
réglé sur la prod
