### ISSUE TITLE
Exclure les trajets Paris Intra Muros

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#77]
#72

**Comment by margot-sanchez** [comment]
Ceci signifie exclure dans la formule de versement de l'incitation les trajets si point A et B sont dans Paris intramuros.

To Do:
Définir avec IDFM les codes INSEE de Paris IntraMuros.

**Comment by jonathanfallon** [comment]
Paris (entier) : 75056
Paris 1 : 75101
...
Paris 20 : 75120

**Comment by margot-sanchez** [comment]
👍
