### ISSUE TITLE
Prendre des trajets si point A et/ou B dans le périmètre de l'AOM

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#78]
Appliquer les politiques incitatives uniquement sur les trajet avec départ et/ou arrivée dans le territoire d'une AOM (exemple : IDF M)
Ca c'est bon normalement.

**Comment by margot-sanchez** [comment]
#72

**Comment by jonathanfallon** [comment]
Les trajets listés pour IDFM auront forcément cette caractéristique car ce sont les critères d'appartenance à une AOM que nous utilisons.

Je ferme ce ticket à la faveur de #77 qui vise à exclure les trajets intra-muros.
