### ISSUE TITLE
🔥 Différence front / back / export nombre de trajets 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#786]
Contexte : prod 8/01/2020

Sur le front, un super admin peut voir 460 000 trajets pour un opérateur alors que sur le back c'est 500 000 trajets. L'export est fait sur les données reçues en front. En conséquence il y a un delta entre les calculs faits en étant basés sur l'export et ceux en étant directement faits dans la base.

**Comment by jonathanfallon** [comment]
Le problème vient de l'invalidation du cache des statistiques qui conservait les anciens résultats.
L'export ne se base pas sur le cache et exporte le bon nombre de trajets.
