### ISSUE TITLE
Bug affichage page campagne 

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage#787]
Branche _dev_

![image](https://user-images.githubusercontent.com/11545031/71984956-1d4fb680-322a-11ea-8c6d-82ad323b1c01.png)

Quand la campagne est terminée, l'affichage du cercle n'est pas bon.

**Comment by margot-sanchez** [comment]
![image](https://user-images.githubusercontent.com/15428433/72795783-7c57f700-3c3e-11ea-8582-b7e8e42b7489.png)
👍
