### ISSUE TITLE
Pas de nom d'opérateur si export côté territoire ==> ajouter mention "non visible"

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#799]
Contexte : dev et prod au 15/01/2020

Je suis un territoire et je réalise un export des données sur mon territoire. Le nom de l'opérateur n'est plus visible. Cette colonne est devenue vide alors que j'ai des exports d'avant les vacances où elle était bien complétée. 

UPDATE : en fait ajouter la mention "non visible" dans l'export pour faciliter la compréhension.

**Comment by gillesboisson** [comment]
@margot-sanchez il y a peut être souci car c'est lié à la visibilité opérateur territoire est ce que ces opérateurs sont bien visible par ton territoire.

**Comment by margot-sanchez** [comment]
Tu as tout à fait raison @gillesboisson ! Du coup je vais modifier le ticket pour que dans l'export dans ce cas là au lieu de mettre "    " mettre "non visible" aussi ;)

**Comment by margot-sanchez** [comment]
Contexte staging 09/09/2020. Je suis un territoire et j'ai à nouveau réalisé l'export et cette fois-ci la colonne opérateur a disparu.

**Comment by jonathanfallon** [comment]
**Test 1**

1. Se connecter comme territoire
2. Faire un export et vérifier la présence de la colonne opérateur

**Test 2**

- 1 compte opérateur sur admin > visibilité
- 1 compte territoire sur trajets > export

1. Sur la page de visibilité opérateur : **activer** le territoire
2. Faire un export avec le compte territoire -> vérifier que le nom de l'opérateur apparait dans la colonne `operator`
3. Sur la page de visibilité opérateur : **désactiver** le territoire
4. Faire un export avec le compte territoire -> vérifier que le nom de l'opérateur apparait comme **NC** dans la colonne `operator`

**Comment by margot-sanchez** [comment]
Cela marche <3
