### ISSUE TITLE
Automatisation export données personnelles - application du RGPD

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#806]
15/01/2020 nous avons eu notre première demande d'extraction de données personnelles de la part d'un utilisateur. 
Ce type de demande devrait se reproduire. Comment mettre en oeuvre une automatisation de l'export de données personneles. Quel processus : qui répond, dans quel délai, comment sécuriser l'envoi des données ?

Je propose de faire un atelier dans l'équipe pour réfléchir à ce point et spécifier la fonctionnalité. 

Référence : https://www.cnil.fr/fr/professionnels-comment-repondre-une-demande-de-droit-dacces

**Comment by jonathanfallon** [comment]
A voir le jour où on a besoin de scaler.
