### ISSUE TITLE
Affichage des histogrammes des statistiques spécifiques AOM 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#81]
J'ai l'impression qu'il y a un bug sur les histogrammes des stats spécifiques AOM 
exemple ci dessous, stats Grand Lyon. 
![image](https://user-images.githubusercontent.com/15428433/56047045-dee1a580-5d44-11e9-91a0-bbf6401b1878.png)

Alors que sur les stats globales cela semble être lisse. 
![image](https://user-images.githubusercontent.com/15428433/56047272-59122a00-5d45-11e9-8c8a-db719bb030ab.png)

Je peux me tromper.

**Comment by margot-sanchez** [comment]
En vrai mettre des histo plutôt qu'une courbe

**Comment by margot-sanchez** [comment]
@margot-sanchez doit faire un dessin

**Comment by margot-sanchez** [comment]
Le format courbe c'est moche et peu lisible. 
![image](https://user-images.githubusercontent.com/15428433/57123172-288c4180-6d81-11e9-9299-f6cb06dba9ef.png)

Proposition numéro 1) 
![image](https://user-images.githubusercontent.com/15428433/57132799-fdb1e580-6da0-11e9-9ea5-f1cf8bddd7ac.png)

Proposition numéro 2 (dans un second temps - ajouter une vue par mois)
![image](https://user-images.githubusercontent.com/15428433/57132823-0b676b00-6da1-11e9-82af-5e9a4720429c.png)

**Comment by jonathanfallon** [comment]
J'ai fait une vue par mois (qui est par défaut) avec un switch un peu plus sympa pour passer en cumulatif.

![screenshot-20190521172029](https://user-images.githubusercontent.com/1656255/58108826-d191c380-7bec-11e9-964b-6dbcc24588e1.png)

La nouvelle version est ici :
![screenshot-20190521171927](https://user-images.githubusercontent.com/1656255/58108852-da829500-7bec-11e9-8e66-ec768289368a.png)

**Comment by margot-sanchez** [comment]
Ok. On fera une nouvelle issue pour mettre par jour plus tard. Je pense que c'est bien pour les personnes qui voudront voir que les mardi sont les jours les plus forts etc.
