### ISSUE TITLE
Récap de campagne ne fonctionnant pas. 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#811]
Contexte : prod 21/01/2020

Je suis connectée en tant que territoire et j'ai dans mes brouillons des campagnes. 
![image](https://user-images.githubusercontent.com/15428433/72790194-6e51a880-3c35-11ea-8f90-a5e6e40a7b9b.png)
Je me connecte en tant que Super Admin et je ne vois aucune campagne en brouillon dans le récap. 
![image](https://user-images.githubusercontent.com/15428433/72746835-6e10c900-3bb3-11ea-80fa-22bae4a03a36.png)

**Comment by samueleyre** [comment]
Le problème vient du cas de la campagne d'IDFM généré dans le back qui n'a pas les données ui_status utiles pour l'affichage dans le front. 

Il faudrait faire un point spec FRONT / BACK concernant ui_status pour s'assurer d'avoir les données nécessaires à l'affichage côté front.

**Comment by margot-sanchez** [comment]
👍
