### ISSUE TITLE
Chantier territoire

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#816]
- [x] Mise en place de la base de données
- [x] Migration des données existantes
- [x] Modification, édition, création Front/Back
- [x] Application normalisation carpool

Spec / Notes : https://hackmd.io/d0gCY7S8Qku8bUmXrAataw

**Comment by nmrgt** [comment]
Je viens d'avoir Gilles à ce sujet. C'est plutôt un gros changement, avec des migrations de données et des impacts sur : 
- les permissions
- la visualisation des trajets
- les campagnes

En conséquence, je pense qu'il faut poser des specs fonctionnelles (à quel besoin cette modification répond-elle) puis programmer les évolutions du code. En tout état de cause, je ne pense pas que ça puisse être fait dans ce sprint.

**Comment by margot-sanchez** [comment]
Voir synthèse des échanges ici : https://hackmd.io/d0gCY7S8Qku8bUmXrAataw
