### ISSUE TITLE
Chantier statistiques 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#818]
📒[Spécifications](https://hackmd.io/w7WGuqtLQLyhzbFZcaE_vA?edit) : 
🦄Voir [les maquettes](https://www.figma.com/file/J8LeDKQBeHTHGhm4Ys7Q0X/Chantier-Statistiques?node-id=0%3A1)

- Voir #471

**Comment by jonathanfallon** [comment]
Publier le budget sur la page des statistiques ? voir #1076

**Comment by jonathanfallon** [comment]
J'aime bien le graph avec le cumul des demandes par périodes et leurs statuts chez Data Pass (anciennement Signup).
https://datapass.api.gouv.fr/stats

Est-ce intéressant de publier le nombre de campagnes créées / lancées / en cours... par mois / trimestre ?

**Comment by margot-sanchez** [comment]
Etat des lieux le 14/01/2020

**Comment by margot-sanchez** [comment]
Etat des lieux 28/01/2020
