### ISSUE TITLE
Statistiques par classe - erreur

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#82]
Dans la base staging il y a 2 trajets en classe A datant du 29 mars, donc ils ont forcement été processé 
![image](https://user-images.githubusercontent.com/15428433/56047597-0dac4b80-5d46-11e9-993e-50e21c6ae499.png)

Or sur les stats staging on voit que du B & C
![image](https://user-images.githubusercontent.com/15428433/56047688-464c2500-5d46-11e9-83e6-83c32ee3e9dc.png)

**Comment by samueleyre** [comment]
Ce n'est pas assez significatif pour s'afficher ;)

**Comment by margot-sanchez** [comment]
@samueleyre en % c'est à partir de quoi le significatif ?
