### ISSUE TITLE
SAV technique du registre - réflexions sur une interface/méthode

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#821]
Nous recevons régulièrement des mails de la part d'opérateur souhaitant avoir un retour sur les trajets qu'ils envoient et si nous rencontrons des problèmes de notre côté.
Aujourd'hui, ce type de réponses ne peut être apporté que par @nmrgt et @jonathanfallon qui sont les seuls a avoir les logs. 
Je peux tout à fait leur répondre et assurer le suivi mais il m'est impossible de savoir quoi que ce soit. Par exemple : je ne peux pas savoir quel type d'erreur nous avons au niveau du service acquisition, normalisation, etc. 

Il serait pertinent de réfléchir à une manière d'avoir un backoffice pouvant être utilisé également en mode SAV pour moi ou une autre personne de l'équipe. 

Attention : le fonctionnement actuel permet tout de même de limiter les fuites de données (nb : seuls Nico et John ont accès à l'intégralité des données). A voir comment conserver cette sécurité tout en permettant d'améliorer notre "SAV."

**Comment by jonathanfallon** [comment]
Fait en back pour avoir le statut d'un trajet. Besoin d'avoir une interface front pour les admins ? @margot-sanchez

**Comment by jonathanfallon** [comment]
![SAV](https://cdn-media.rtl.fr/cache/pPezkkziwGszZCQrZfvgsQ/880v587-0/online/image/2012/0206/7743205584_omar-et-fred-en-pleine-seance-de-sav-des-emissions-sur-canal.jpg)
