### ISSUE TITLE
Comment indiquer que le paiement s'est fait en dehors de la plateforme

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#822]
Aujourd'hui les opérateurs ne gérant pas le paiement dans leur plateforme doivent rentrer une valeur nulle. Réfléchir à une manière d'indiquer que le paiement n'est pas nul, mais géré directement de mains à mains.

**Comment by jonathanfallon** [comment]
L'opérateur doit envoyer la valeur de la transaction et s'assurer qu'elle est réalisée.
