### ISSUE TITLE
Localisation du territoire - fiche récap campagne.

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#832]
Je suis un territoire et je vais configurer une campagne. Dans la vision récapitulative de la campagne, il y avait un "pin point" pour situer le territoire. Ce pin point était ensuite récupéré dans le module "inspiration". Aujourd'hui cette fonction a disparu. Etudier comment la remettre et si c'est pertinent. 

Besoin : ceci est inutile pour un territoire qui sait forcement où il se trouve. En revanche, dans une logique où un territoire pourrait aller voir un exemple de campagne (inspiration)
![image](https://user-images.githubusercontent.com/15428433/74221646-e3535380-4cb2-11ea-826a-134e721e4f44.png)

**Comment by margot-sanchez** [comment]
![Uploading image.png…]()

**Comment by margot-sanchez** [comment]
A spécifier quel est le problème exactement ? De mémoire l'adresse sur API entreprise n'est pas formatable pour pinpointer. Ne pourrait-on pas simplement prendre le code INSEE ou postal ?

**Comment by jonathanfallon** [comment]
Cette fonctionnalité a été supprimée pour les raisons suivantes : 
- les données géographiques du territoire n'étaient pas assez cohérentes pour afficher une carte qui ai du sens
- je ne crois pas que l'on ai vraiment réfléchi et spécifié ce besoin
- le ratio complexité technique / valeur ajoutée était défavorable
- la fonctionnalité était bugguée et affichait des infos incohérentes (voir points précédents)

Je propose que l'on profite d'avoir Ludo dans notre équipe pour réfléchir à la valeur que peut ajouter une cartographie sur cette page (ou d'autres).
