### ISSUE TITLE
Mise à jour CGU & mentions légales

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#838]
Mise à jour des CGU + mentions légales.

⚠️ aux annexes des CGU et documentation.

**Comment by margot-sanchez** [comment]
Mettre aussi une documentation sur le processus idéal de 1) je suis un opérateur je récupère mes données dans l'interface 2) je fais une facture auprès du territoire

Réfléchir avec IDFM aux données qui doivent être présentes pour justifier une facture.

**Comment by nicolas-viennot-beta** [comment]
@charlesimone : est-ce que ce ticket a été traité dans ta MAJ des CGU ?

**Comment by charlesimone** [comment]
Oui j'ai mis à jour les CGU mais il faudra le refaire bientôt avec l'arrivée de l'ademe et d'idfm de toute manière
