### ISSUE TITLE
Ajouter colonne - campagne applicable 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#841]
Je suis un territoire. Je réalise un export de mes données. Je souhaiterais qu'une colonne campagne applicable soit présente dans l'export. Ceci afin de pouvoir filtrer sur les trajets spécifiques à une campagne (voir #692 )

Je suis un opérateur. Je réalise un export de mes données en vue de pouvoir envoyer une facture auprès du territoire incitateur (voir #169 )

Je suis un super admin et je souhaites avoir une vision globale des campagnes dans mon export.

**Comment by margot-sanchez** [comment]
Non

**Comment by margot-sanchez** [comment]
A réflechir sur comment l'intégrer dans le CSV idéal. https://docs.google.com/spreadsheets/d/1CTtz14gfgsSKdHvCbgBQcqs1TPQh5mXYy3bLXRMqKG0/edit#gid=0

**Comment by nmrgt** [comment]
Les campagnes appliquées sont dans l'export (à tester).

**Comment by margot-sanchez** [comment]
@nmrgt sur demo je retrouve que amout, siret. 
Je n'ai pas de campagne

**Comment by margot-sanchez** [comment]
👍
