### ISSUE TITLE
Créer une campagne en tant que super admin

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#845]
Aujourd'hui, seuls les territoires ont la possibilité de créer une campagne d'incitation. Pour faciliter l'accompagnement, il serait intéressant d'avoir la possibilité de créer des campagnes d'incitation en tant que super admin.

Besoins :
- Sélectionner le territoire cible (passé en `territory_id`)
- Ajouter la vérification de la permission dans le middleware de `CreateCampaignAction.ts`

**Comment by margot-sanchez** [comment]
Le registre de preuve de covoiturage est un outil pouvant faciliter le contrôle et suivi de fiches standardisées CEE. Un rapide scénario d’utilisation envisagé serait le suivant : 

1. Un administrateur du registre pourrait créer une fiche CEE dans le registre en utilisant la brique campagne. 
2. Cette fiche pourrait être enregistrée dans la rubrique inspiration (nb : rubrique dans laquelle se situe des exemples de campagnes). 
3. Ainsi un opérateur de covoiturage en accord avec son “éligible” pourrait activer une fiche sur son périmètre (nb : les utilisateurs de sa plateforme).  
4. Dans son interface l’opérateur peut visualiser les trajets éligibles à cette fiche et réaliser un export. 
5. Cet export peut être remis à son éligible pour justifier les CEE.

Remarque : des fonctionnalités sont à développer et améliorer pour couvrir ce scénario mais une partie des briques sont déjà existantes.

**Comment by nmrgt** [comment]
@margot-sanchez ca a l'air cool mais peux-tu détailler ? Je ne suis pas sûr de comprendre ce que tu veux faire.

**Comment by margot-sanchez** [comment]
La fonctionnalité pour l'instant est uniquement : la possibilité pour un super admin de créer une campagne et de l'affecter à un (des) territoire(s) et un (des) opérateur(s)
