### ISSUE TITLE
Ajout d'un filtre "opérateur" dans l'export territoire

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#850]
Problème : Aujourd'hui l'export se fait uniquement par sélection de plage de dates.
Or des territoires nous demandent de pouvoir sélectionner un export par opérateur.

**Solution**
En tant qu'admin d'un territoire, je peux télécharger un jeu de données en filtrant par date (✅ ) et par opérateur.

Nb : il est aussi facile pour le territoire de filtrer dans un tableur par opérateur... sauf pour IDFM et les supers admins.

**Comment by jonathanfallon** [comment]
On peut faire un petit tuto pour expliquer comment filtrer par colonne dans Excel / LibreOffice, ça prendra moins de temps que de le développer.

**Comment by margot-sanchez** [comment]
Non mais c'est relou par exemple pour IDFM. Je suis d'accord sur le fait qu'il faut faire par opérateur.

**Comment by margot-sanchez** [comment]
C'est bon côté back d'après moi. Juste à mettre côté front.

**Comment by margot-sanchez** [comment]
J'ai téléchargé deux jeux de données avec les mêmes dates mais pas les mêmes opérateurs et j'ai bien des nombres différents 👍
