### ISSUE TITLE
Opérateur sans n° SIRET

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#851]
Contexte : partout

Aujourd'hui, un super admin ne peut ouvrir des comptes qu'au opérateur ayant un numéro SIRET (nb : mettre 00000000000000 ne fonctionne pas). Résultat des opérateurs non français et n'ayant pas créé une entreprise en france ne peuvent avoir de compte.

*Doit-on permettre l'ouverture de compte pour des opérateurs sans numéro SIRET ?* 
- [ ] Oui
- [ ] Non

*Si oui, doit-on faire une amélioration pour gérer des identifiants autres que le SIRET ? Mettre une case, opérateur n'ayant pas de SIRET ?"
Peut-on sur l'environnement de staging créer des comptes avec un numéro de SIRET aléatoirement tiré ? (#usurpationd'identité) ? Il n'existe pas un numéro de SIRET générique que tout le monde utilise ? Genre un John Doe du SIRET ? 

Est-ce que le plus simple ne serait pas de dire aux opérateurs : il est obligatoire d'avoir un numéro SIRET et puis c'est tout ? 

Note : attention à ne pas tomber dans la dérive du registre européen géré par des français. Trouver une manière de collaborer tout en gardant notre mission en tête "faciliter la distribution d'incitation sur le territoire français".

**Comment by margot-sanchez** [comment]
Afin de travailler avec des entreprises en dehors de France et/ou de l'Europe, il serait intéressant d'avoir un numéro d'identification plus large et universel que le SIRET français.

En l'état actuel, le SIRET est intéressant comme identifiant car il n'est pas limité aux entreprises et identifie également les entités administratives.

Pistes :

Numéro de TVA intra-communautaire (Europe seule, pas la Suisse par exemple)
DUNS - Data Universal Numbering System
EasyNumber
European Business Register

**Comment by margot-sanchez** [comment]
Retours de Thomas 

- [ ] Solution 1 - Inscription à la main en demandant la preuve de l’existence juridique de l’entreprise (genre l’équivalent du Kbis allemand, etc) ; la difficulté : régime dérogatoire, instruction manuelle polyglotte ;
- [ ] Solution 2 : utiliser le numéro de TVA intra communautaire : 
           - Inconvénients : structures différentes selon les Etats membres : http://ec.europa.eu/taxation_customs/vies/faqvies.do#item_11 
             - L’avantage c’est qu’une société peut demander à en obtenir un “rapidement” :https://ec.europa.eu/taxation_customs/business/vat/telecommunications-broadcasting-electronic-services/content/guide-vat-mini-one-stop-shop-moss#infosel 
- [ ] Solution 1 : utiliser le numéro de douanes (EORI), il n’est nécessaire que pour l’import/export, donc bon : https://ec.europa.eu/taxation_customs/business/customs-procedures/general-overview/economic-operators-registration-identification-number-eori_en
Version incomplète : https://e-justice.europa.eu/content_find_a_company-489-en.do 

Retour d'expérience : chez etalab, beta.gouv quand on a rencontré le problème, les équipes se sont orientées vers la TVA intracomm.

**Comment by nmrgt** [comment]
Pourquoi pas la TVA intra... Mais quid des personnes morales non assujettis à la TVA (association non lucrative par ex.), elles peuvent en avoir un aussi ?

**Comment by jonathanfallon** [comment]
Aujourd'hui toute la partie _company_ et _payments_ repose sur le numéro de SIRET. Gros chantier à prévoir pour faire une modification.
