### ISSUE TITLE
Bug Affichage de la date dans Campagne/Eligibilité

### ISSUE THREAD

**Issue by Jonathankurtz131** [betagouv/preuve-covoiturage#852]
Je suis un territoire et je souhaite créer une campagne sur app-staging.covoiturage. Je clique sur "Définir un modèle personnalisé". Ensuite, dans "Définissez les conditions d'éligibilité", je souhaite sélectionner les jours relatifs à ma campagne. Je sélectionne "Mardi" et "Mercredi" s'affiche. 

Voir image ci-dessous. 

![Capture d’écran 2020-02-17 à 15 48 24](https://user-images.githubusercontent.com/54620644/74664717-88cc6280-519e-11ea-91f0-960654643651.png)

**Comment by margot-sanchez** [comment]
Nb : c'est sur le staging.

**Comment by margot-sanchez** [comment]
Done :)
