### ISSUE TITLE
🧹🧴🧽🧼😷 Nettoyage de printemps

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#853]
- [x] supprimer les références à mongo @nmrgt 
- [x] supprimer les commandes inutiles (migration mongo par ex.) @nmrgt 
- [ ] de manière générale, supprimer le code mort
- [ ] mettre à jour la documentation
- [ ] rétablir les tests
- [x] migrer les champs "varchar" en integer dans le cas de relation @jonathanfallon 
- [x] passer les `peerDependencies` en `dependencies` pour pouvoir utiliser `lerna --sort` @jonathanfallon 
- [x] faire remonter le répertoire "shared" au même niveau que api et dashboard @nmrgt 
- [x] enlever config et env de l'appli @jonathanfallon 
- [ ] ~~ajouter `"shared/*": ["../../../shared/*"]` dans les `paths` de tous les `tsconfig.ts` et nettoyer les imports~~
- [ ] configurer les `package.json` pour ava avec `src/` et `tests/`
- [x] supprimer le script `test:integration` et tout regrouper dans `test`
- [ ] nettoyer le coverage

**Comment by nmrgt** [comment]
- [ ] migrer les champs "varchar" en integer dans le cas de relation

**Comment by margot-sanchez** [comment]
A voir avec @jonathanfallon . Du côté de @nmrgt 👍
