### ISSUE TITLE
Ajouter un échelonnement des incitations (€/points) selon la classe de confiance

### ISSUE THREAD

**Issue by Jonathankurtz131** [betagouv/preuve-covoiturage#874]
Dans "Définissez les rétributions"/"rétributions", ajouter un mode échelonné par classe de confiance, en plus du mode échelonné par km. (cf. photo ci-dessous)

![Capture d’écran 2020-03-04 à 15 57 00](https://user-images.githubusercontent.com/54620644/75891975-dd274180-5e30-11ea-877f-e003f72562c3.png)

**Comment by margot-sanchez** [comment]
Usine à gaz
