### ISSUE TITLE
Correctifs textes récapitulatif de campagne

### ISSUE THREAD

**Issue by gillesboisson** [betagouv/preuve-covoiturage#883]
- [x] Correction majuscule limitée à lundi, mercredi, vendredi, samedi, dimanche **d**e 10h00 à 12h00
- [x] Date de départ affichée en double
- [x] Texte limitation de trajets **Cette campagne est limitée** à 10 000 points.
- [x] Citer les opérateurs lorsqu'on limite la campagne à certain opérateurs
- [x] Pour les trajets ignorés corrigée le wording : Les axes suivant**s** sont **ne sont pas incités** :
- [x] Vérifier que dans le cas des passagers majeurs uniquement, c'est spécifié dans le texte  ex *Les conducteurs et passagers **(majeurs uniquement)** effectuant un trajet d’au moins 14 km sont incités selon les règles suivantes :**
- [x] Pour les rétributions placer les échelons de km en début de phrase : ex. **de 14 à 30 km :** 2 € par trajet par km par passager pour le conducteur, 5 € par trajet par km pour le(s) passager(s) .
- [x] Lorsque tous les opérateurs sont sélectionnés remplacer limités par ouvert à ex. La campagne est **ouverte** à tous les opérateurs présents sur le territoire, proposant des preuves de classe A ou C.
- [x] Pour les trajets inclusifs changer la formulation : Les trajets **incités** doivent être sur les axes suivants :

Ref : Doc https://hackmd.io/cCad8uKhSu6lJbn138fpCw?sync=&type=

**Comment by gillesboisson** [comment]
@margot-sanchez voici la todo liste

**Comment by margot-sanchez** [comment]
Attention La campagne est ouverte à tous les opérateurs présents sur le territoire, proposant des preuves de classe A ou B ou C.

Ne pas mettre de S à la fin de ouverte
