### ISSUE TITLE
Acquisition BETON : Tooling interne

### ISSUE THREAD

**Issue by gillesboisson** [betagouv/preuve-covoiturage#889]
## Tooling interne
- [x] Créer une action pour lister les trajets présent dans acquisition et non dans carpool (left join vers carpool)
- [x] Créer une commande qui lance cette action / relance les jobs (cf ci-dessus)

https://hackmd.io/Klq4rwbER6KsoJfevj8Y8Q?edit

**Comment by jonathanfallon** [comment]
La commande est créé dans `@pdc/service-monitoring` et peut être appelée comme ça :
`yarn workspace @pdc/service-monitoring ilos stats:journeys`

le résultat met un peu de temps à arriver...
