### ISSUE TITLE
Acquisition code B.E.T.O.N

### ISSUE THREAD

**Issue by gillesboisson** [betagouv/preuve-covoiturage#891]
Mise en place d'outils de reporting , retry des acquisition
(https://hackmd.io/Klq4rwbER6KsoJfevj8Y8Q?edit)[DOC]

## Socle commun (avoir l'info)
https://github.com/betagouv/preuve-covoiturage/issues/888

## Tooling interne
https://github.com/betagouv/preuve-covoiturage/issues/889

## Tooling externe
https://github.com/betagouv/preuve-covoiturage/issues/890

**Comment by jonathanfallon** [comment]
Tous les tickets liés ont été fermés.
