### ISSUE TITLE
Identification des entreprises internationales

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#907]
Afin de travailler avec des entreprises en dehors de France et/ou de l'Europe, il serait intéressant d'avoir un numéro d'identification plus large et universel que le SIRET français.

En l'état actuel, le SIRET est intéressant comme identifiant car il n'est pas limité aux entreprises et identifie également les entités administratives.

Pistes : 
- Numéro de TVA intra-communautaire (Europe seule, pas la Suisse par exemple)
- [DUNS - Data Universal Numbering System](https://fr.wikipedia.org/wiki/Data_Universal_Numbering_System)
- [EasyNumber](https://fr.wikipedia.org/wiki/EasyNumber)
- [European Business Register](https://en.wikipedia.org/wiki/European_Business_Register)

**Comment by margot-sanchez** [comment]
Contexte : partout

Aujourd'hui, un super admin ne peut ouvrir des comptes qu'au opérateur ayant un numéro SIRET (nb : mettre 00000000000000 ne fonctionne pas). Résultat des opérateurs non français et n'ayant pas créé une entreprise en france ne peuvent avoir de compte.

Doit-on permettre l'ouverture de compte pour des opérateurs sans numéro SIRET ?

 Oui
 Non
*Si oui, doit-on faire une amélioration pour gérer des identifiants autres que le SIRET ? Mettre une case, opérateur n'ayant pas de SIRET ?"
Peut-on sur l'environnement de staging créer des comptes avec un numéro de SIRET aléatoirement tiré ? (#usurpationd'identité) ? Il n'existe pas un numéro de SIRET générique que tout le monde utilise ? Genre un John Doe du SIRET ?

Est-ce que le plus simple ne serait pas de dire aux opérateurs : il est obligatoire d'avoir un numéro SIRET et puis c'est tout ?

Note : attention à ne pas tomber dans la dérive du registre européen géré par des français. Trouver une manière de collaborer tout en gardant notre mission en tête "faciliter la distribution d'incitation sur le territoire français".
