### ISSUE TITLE
Template campagne - bug si échelonné 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#914]
Contexte : staging

Je suis un territoire et je vais configurer une campagne d'incitation au covoiturage. Je sélectionne un modèle lors de l'étape 1. Par exemple "limiter la pollution".
Dans la partie rétribution je vois ça : 
![image](https://user-images.githubusercontent.com/15428433/77309679-5c57b900-6cfd-11ea-8970-8bcce3279011.png)

Or normalement c'est un mode échelonné et ces rétributions sont à compter de 50 km. Voir spécifications.

**Comment by gillesboisson** [comment]
@margot-sanchez : c'est un souci dans la configuration de la template. ça vient vient pas du mode échelonnée mais de la valeur que tu met dans les distances limites (Eligibilité > distance). 
Est ce que tu peux me donner les valeurs que tu veux dans chaque template.
Ce que j'ai vu par contre c'est que quand tu change les distance limites ça (tu active le mode échelonée, tu reviens en arrière tu change la distance tu reviens) sur le premier échelons la distance min n'est pas changé. Je vais donc fixé ça dans la foulée.

**Comment by margot-sanchez** [comment]
Tu parles de ça ? https://docs.google.com/spreadsheets/d/1hLwV91q6gcQ8ajiuTGK8k2FMaJZRjg2PiE5Ajl8EuRs/edit#gid=0

**Comment by gillesboisson** [comment]
@nmrgt est ce que tu pourrais faire une passe sur les templates : j'ai fais un fix dans templates pour débloquer la situation, mais il semblerais que tu as appliqué ta restructuration de règle sur les templates. 
Voici mon commit de [d1b48072725308a9643d8f6d8d001fc8b9052094](https://github.com/betagouv/preuve-covoiturage/commit/d1b48072725308a9643d8f6d8d001fc8b9052094)

**Comment by margot-sanchez** [comment]
Je ne peux pas tester, les templates ont disparu voir #1017

**Comment by jonathanfallon** [comment]
@jonathanfallon vérifier le payload dans les templates pour s'assurer que les règles ont le bon nom

**Comment by jonathanfallon** [comment]
Mise à jour des campagnes qui utilisent encore l'ancien nom de règles globales.Ajouté à une migration.

```sql
UPDATE policy.policies
SET global_rules = REPLACE(global_rules::text, 'max_trip_per_target_restriction', 'max_trip_restriction')::json
WHERE global_rules::text LIKE '%max_trip_per_target_restriction%';
```

**Comment by margot-sanchez** [comment]
Cela bug toujours.

**Comment by margot-sanchez** [comment]
Cela marche <3

**Comment by margot-sanchez** [comment]
Hum de retour sur demo

**Comment by jonathanfallon** [comment]
Problème de seeding des templates dû au fait que l'on vient de reflasher la base.
Doc mise à jour pour le process de migration

**Comment by margot-sanchez** [comment]
👍
