### ISSUE TITLE
Filtrer les trajets des opérateurs non conventionnés

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#92]
Aggréger les trajets des opérateurs non conventionnés avec l'AOM en cours de consultation.

Les opérateurs ne doivent pas être identifiables.

**Comment by margot-sanchez** [comment]
## Proposition

1) Dans l'interface super admin : 
Un super admin, va dans l'onglet AOM, et peut décocher des opérateurs sur la fiche AOM. L'ensemble des opérateurs sont sélectionnés de base. 
2) Dans l'interface AOM
Un utilisateur peut voir les trajets avec un nom d'opérateur si une convention est signée ou si l'opérateur souhaite quand même apparaître.
Un utilisateur peut voir l'ensemble des trajets avec les opérateurs "fantômes" sous un même nom "opérateur masqué".

**Comment by margot-sanchez** [comment]
Rajouter une info-bulle : cet opérateur n'est pas conventionné ou ne souhaite pas apparaître sur l'interface.

**Comment by jonathanfallon** [comment]
Ajouter une interface pour permettre aux opérateurs de gérer les infos qu'ils affichent aux AOMs.
