### ISSUE TITLE
Adresse territoire - API SIRENE 🧜‍♀️

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#925]
Contexte : prod

Je suis un super admin et je vais mettre à jour les informations contacts RGPD pour un territoire. Lorsque je clique sur le territoire je constate que les informations de type adresse sont manquantes, bien qu'obligatoires. Avec l'API SIRENE et le numéro SIRET de l'entreprise #territoire, on peut retrouver cette information. 
![image](https://user-images.githubusercontent.com/15428433/78045787-a6344500-7376-11ea-8eb6-eefc21d018f5.png)

Je ne sais pas si c'est le Front qui n'expose pas la donnée ou bien la liaison avec l'API SIRENE qui flanche côté back. A mon sens, les territoires en tant qu'entité ont été créés bien avant la liaison avec l'API SIRENE et du coup il n'y a tout simplement pas eu de refresh sur ces informations. 

Problème pour mettre à jour les données RGPD il faut remplir manuellement les informations sur l'adresse.

**Comment by nmrgt** [comment]
C'est un bug qui sera réglé dans le chantier territoire
je ping @gillesboisson pour que ce soit intégré dans les specs ;)

**Comment by gillesboisson** [comment]
@margot-sanchez les infos ne se remplisse car on reçoit des adresse complètes non séparés en adresse / CP / Ville.
On pourrait néanmoins afficher un champs d'infos reprenant l'adresse trouvés

**Comment by margot-sanchez** [comment]
👍
