### ISSUE TITLE
Super admin - indication de l'acceptation des CGU par les territoires

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#926]
# Comportement actuel 15/06/2021
Aujourd'hui côté back l'information "CGU accepted Y/N" est stockée. Pour autant, ce n'est pas actif et encore moins modifiable sur le front.
Côté déploiement, cette information est stockée avec la date d'acceptation et le nom de la personne qui a accepté sur pipedrive.

# Comportement attendu
A spécifier

**Comment by gillesboisson** [comment]
Oui c'est l'idée
