### ISSUE TITLE
Suppression automatique des comptes utilisateur associés à compte opérateur

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#945]
Contexte : prod

Je suis super-admin et un opérateur m'informe mettre fin à ses activités. Je me connecte pour supprimer le compte de cet opérateur puis je dois supprimer les comptes utilisateurs de manière individuelle.
C'est un peu lourd et je pense que cela pourrait être fait automatiquement lorsque l'on supprime le compte "parent". Exemple : je supprime mega.covoit et cela supprime automatiquement les comptes de jean.dupont@megacovoit.fr et michelle.serlin@megacovoit.fr.

**Comment by jonathanfallon** [comment]
L'opérateur est en soft-delete pour des raisons d'intégrité de données mais on peut supprimer les utilisateurs liés.

**Comment by jonathanfallon** [comment]
@margot-sanchez tu peux tester en créant un opérateur, des utilisateurs liés et en supprimant l'opérateur. Même chose pour les territoires.

**Comment by margot-sanchez** [comment]
Suppression des utilisateurs liés à un opérateur 👍 
Suppression des utilisateurs liés à un territoire 👎 (prérequis #1018)

**Comment by margot-sanchez** [comment]
Finalement pas de suppression des comptes territoire
