### ISSUE TITLE
Migration Always Data

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#958]
La migration « Infrastructure logicielle 2020 » doit être effectuée avant le 28 septembre 2020 pour les comptes suivants, appartenant à jonathan.fallon@beta.gouv.fr :

   - covoiturage-beta-gouv

Vous pouvez effectuer cette migration depuis l'interface d'administration (section Avancé > Migrations).
Important : si cette migration n'est pas effectuée avant la date limite, elle s'enclenchera automatiquement. Nous vous invitons vivement à prendre en charge la migration vous-même pour pouvoir la tester et éventuellement apporter des corrections sur votre compte pour éviter tout risque de dysfonctionnement.

Pour avoir plus de détails sur cette migration :
https://help.alwaysdata.com/fr/avanc%C3%A9/migrations/architecture-logicielle-2020/

**Comment by jonathanfallon** [comment]
Toutes les migrations ont été effectuées dont celle intitulée _Infrastructure logicielle 2020_.
