### ISSUE TITLE
Impossible de créer une nouvelle entité AOM

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#97]
![image](https://user-images.githubusercontent.com/15428433/56222825-f4b8d880-606c-11e9-991e-d4ae1f710be2.png)
J'ai pourtant bien mis à jour l'ensemble des codes INSEE. Je souhaitais créer une AOM fictive pour la comcom Grand Paris Seine & Oise et ensuite la supprimer...

**Comment by jonathanfallon** [comment]
Erreur dûe au fait que le contour géographique n'est pas éditable dans le formulaire des AOM.

```
{
   "name":"MongoError",
   "message":"Can't extract geo keys: { _id: ObjectId('5cb8df10ff410d00406d2781'), cgu: { accepted: false }, geometry: { type: \"MultiPolygon\" }, shortname: \"\", acronym: \"TAOM\", insee: [ \"75056\" ], name: \"Test AOM\", company: { siren: \"123456789\", naf_etablissement: null, naf_entreprise: null, nature_juridique: null, cle_nic: null, rna: null, vat_intra: null }, createdAt: new Date(1555619600319), updatedAt: new Date(1555619600319), __v: 0 }  MultiPolygon coordinates must be an array"
}
```

**Comment by margot-sanchez** [comment]
Finalement choix stratégique ne pas laisser la possibilité de créer de nouvelles AOM. On enlève le bouton.
