### ISSUE TITLE
Amélioration de la liste des trajets

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#977]
**Problématique :**

Dans la liste détaillée des trajets, l'affichage est souvent très long et le lazy loading ne semble pas fonctionner correctement.

**Analyse**

La requête de récupération des trips dans `TripRepositoryProvider.ts::search` effectue un comptage de tous les résultats qui correspondent aux filtres envoyés et récupère aussi les _n_ premiers résultats (LIMIT et OFFSET).

La requête est très longue avec beaucoup de résultats (ReqScan pour le `count(*) over()`)

Proposition à tester : 
1. séparer la requête de comptage et celle de recherche
2. le front appelle d'abord la liste de trajets puis le comptage (plus long)
3. les appels pour le _lazy loading_ sont optimisés, on décale l'offset et le comptage n'est plus appelé.

Point de vigilance : vérifier le comportement quand on atteint le nombre max de trajets

**Comment by m-azar** [comment]
Retour terrain Mathieu : 
- Défilement vers le bas : nécessité de remonter un peu puis redescendre (scroll up / scroll down) pour que ça charge les trajets suivants 
- Test sur Evreux : ça bloque au bout de quelques chargements quand on défile vers le bas (test le 17/07 : impossible de remonter plus loin dans le détail des trajets que le 12 juin)
- Une fois descendu, plus de possibilité de remonter vers les trajets plus récents, à moins de recharger la page / réaffiner les résultats

Une barre de défilement est elle par exemple possible, ou un affichage par pages (ex. 50 résultats par "page") ?

**Comment by margot-sanchez** [comment]
🎉
