### ISSUE TITLE
Refactoring AOM --> territories

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#98]
Afin de prendre en compte des territoires qui ne sont pas des AOM mais qui peuvent être concernés par le registre et en auraient une utilité (nous avons déjà des use-cases) il est proposé de renommer `AOM` en `territories`

@nmrgt c'est l'occasion de le faire lors du rewrite Typescript.

**Comment by margot-sanchez** [comment]
Finalement choix stratégique. On reste sur la position d'ouvrir qu'aux AOM ! 
Pour les autres territoires l'open data leur conviendra.
