### ISSUE TITLE
Bug filtre campagne - réinitialisation 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#994]
**Contexte staging (31/08/2020)**

**La réinitialisation du filtre campagne ne fonctionne pas. Cela garde en mémoire le filtre.**

Etape 1 : sans filtre 35k trajets 👍 
![image](https://user-images.githubusercontent.com/15428433/91705213-f65d4080-eb7c-11ea-95d6-6af4c1a944a2.png)

Etape 2 : avec filtre campagne 1487 trajets 👍 
![image](https://user-images.githubusercontent.com/15428433/91705493-53f18d00-eb7d-11ea-8928-ec63aa409d6b.png)

Etape 3 : réinitialisation du filtre toujours 1487 trajets 👎 
![image](https://user-images.githubusercontent.com/15428433/91705565-6d92d480-eb7d-11ea-9f01-ed62a145711f.png)

Etape 4 : application d'un filtre date (avant 2018) le retour des 35k trajets 👍 
![image](https://user-images.githubusercontent.com/15428433/91705664-91eeb100-eb7d-11ea-8e95-f9c0695f19fe.png)

Etape 5 : réinitialisation complète, 1487 trajets... 👎 
![image](https://user-images.githubusercontent.com/15428433/91705761-b21e7000-eb7d-11ea-9122-2ec0dbab3bca.png)

Conclusion le filtre date ne tient pas compte du filtre campagne ce qui permet d'avoir des bonnes données ET le filtre campagne n'est pas réinitiatlisé.

Voir si problème front ou back.

**Comment by nmrgt** [comment]
Problème de requête, il faut envoyer un objet vide sinon la recherche est scopée par défaut sur l'année en cours > front

**Comment by margot-sanchez** [comment]
En partie réglé. Ce qu bug toujours.

Etape 1 : sans filtres il y a 35 919 trajets 👍 
![image](https://user-images.githubusercontent.com/15428433/91992073-feabac00-ed33-11ea-8d87-941dccd9671f.png)

Etape 2 : je mets un filtre sur une campagne, j'ai 1483 trajets 👍 
![image](https://user-images.githubusercontent.com/15428433/91992239-2f8be100-ed34-11ea-8ad5-c85992581a24.png)

Etape 3 : je mets un filtre campagne et date entre janvier 2020 et avril 2020, j'ai 569 résultats 👍 
![image](https://user-images.githubusercontent.com/15428433/91992332-4e8a7300-ed34-11ea-881e-cbf78de639a2.png)

Etape 4 : je supprime le filtre campagne et je garde le filtre date, j'ai toujours 569 résultats 👎 
![image](https://user-images.githubusercontent.com/15428433/91992687-b80a8180-ed34-11ea-9d1c-a61094046170.png)

Etape 5 : je remets le filtre campagne et un filtre date de mai 2019 à aout 2020 j'ai 9 524 résultats. Je ne devrais pas pouvoir voir les trajets de mai 2019 puisque la campagne est en mars 2020. 👎 
![image](https://user-images.githubusercontent.com/15428433/91993218-631b3b00-ed35-11ea-814a-0f5e18f94e8b.png)

Conclusion : le filtre campagne et date ne s'associent pas. Lorsqu'il y a les deux c'est uniquement date qui est appliqué.

**Comment by margot-sanchez** [comment]
la réinitialisation a été corrigée

**Comment by margot-sanchez** [comment]
Il n'y a pas de campagnes qui ont été lancées donc je ne peux pas tester sur la staging. Mais vu que le problème était sur les dates cela devrait être réglée.
