### ISSUE TITLE
Bug filtre kilométrage

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#995]
Contexte : sur staging et sur dev (pas sur prod)

Etape 1 : sans filtre 35k trajets 👍 
![image](https://user-images.githubusercontent.com/15428433/91707218-c95e5d00-eb7f-11ea-871a-925406bda995.png)

Etape 2 : application d'un filtre de 0 à 500 km (ce qui devrait faire 100% donc 35k trajets)
Erreur 👎 
![image](https://user-images.githubusercontent.com/15428433/91707326-ed21a300-eb7f-11ea-8b6b-45c445203ad9.png)

Etape 3 : application d'un filtre 0 à 100 km (ce qui devrait faire du 90% au moins). Mais 1400... 👎 
![image](https://user-images.githubusercontent.com/15428433/91708023-fb23f380-eb80-11ea-81b7-b07e83c75a73.png)

Etape 4 : réinitialisation des filtres 1487 pourquoi ce 1487 !!! 👎 
![image](https://user-images.githubusercontent.com/15428433/91707913-d0399f80-eb80-11ea-8ef2-8024f34c950d.png)

**Comment by nmrgt** [comment]
Problème de requête, il faut envoyer un objet vide sinon la recherche est scopée par défaut sur l'année en cours > front

**Comment by margot-sanchez** [comment]
Toujours le même bug

**Comment by margot-sanchez** [comment]
Je crois avoir eu une révélation ! Pour le bug sur le kilométrage la recherche se fait en mètre en non en km non ? Ceci explique que je trouve si peu de résultats en mettant 0 à 150 km !

**Comment by nmrgt** [comment]
Etape 2 : 
- le maximum accepté par le backend c'est 150km, d'où l'erreur

Etape 3/4 : 
- cf problème sur le scope de date : dès que l'on met un filtre, on applique la recherche sur l'année précédente (ce qui n'est pas le cas sur la requête globale), d'où les écarts de résultat.

**Comment by margot-sanchez** [comment]
Cela fonctionne bien.
