### ISSUE TITLE
Bug des filtres - territoire

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#997]
Contexte staging & dev

Etape 1 : sans filtre 35k trajets
On peut apercevoir un trajet Mulhouse à minima.
![image](https://user-images.githubusercontent.com/15428433/91708805-222ef500-eb82-11ea-994d-b744b98cac65.png)

Etape 2 : application filtre Mulhouse 0 résultats... on devrait au moins en avoir 1 
![image](https://user-images.githubusercontent.com/15428433/91708914-48549500-eb82-11ea-9084-d4ac79c46924.png)

Etape 3 : réinitialisation des filtres 0 résultats.
![image](https://user-images.githubusercontent.com/15428433/91709050-79cd6080-eb82-11ea-8f40-0c8a1739cfb1.png)

Lié avec #994 #995

**Comment by margot-sanchez** [comment]
Cela ne s'améliore pas 
![image](https://user-images.githubusercontent.com/15428433/91998925-1f77ff80-ed3c-11ea-9107-fd6e9f4ad7a8.png)

**Comment by gillesboisson** [comment]
@margot-sanchez : @nmrgt a remarqué que quand on filtre nous appliquons par défaut une date début de d'un ans (aujourd'hui - 1 ans). Ce qui veut dire qu'a partir de maintenant :
- Le champs date de début a une date par défaut d'aujourd'hui - 1 ans.
- Nous ne pouvons pas mettre une date inférieur a cette date ci.
- Le champs requis.

**Comment by margot-sanchez** [comment]
👍 cela fonctionne. Tests réalisés en changeant les dates avant après le filtre des 1 an et en réinitialisant.
