### ISSUE TITLE
Export - colonne pays vide

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#998]
Contexte staging

La colonne pays est vide (sauf pour les pays étrangers et là c'est bien indiqué )

![image](https://user-images.githubusercontent.com/15428433/91726260-3eda2580-eba0-11ea-882f-c73688bea05d.png)

![image](https://user-images.githubusercontent.com/15428433/91726397-73e67800-eba0-11ea-98a8-523903e57455.png)

**Comment by margot-sanchez** [comment]
Problème de migration :)

**Comment by margot-sanchez** [comment]
Insérer un territoire france avec comme enfant les régions !

**Comment by jonathanfallon** [comment]
Insérer un territoire France avec toutes régions dedans dans le script de migration.

**Comment by margot-sanchez** [comment]
![image](https://user-images.githubusercontent.com/15428433/93777730-6bc0ac00-fc25-11ea-94bd-e560e253c830.png)
Toujours vide sur l'environnement de démo
