### ISSUE TITLE
Campagnes passées dans en cours - interface territoire

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#999]
Contexte : staging 31/08/2020

Je suis un territoire, j'ai lancé une campagne qui est terminée depuis avril 2020 et pourtant dans mon interface elle apparait comme dans "en cours"
![image](https://user-images.githubusercontent.com/15428433/91728552-8a420300-eba3-11ea-9ae2-90d30aa46b6b.png)
Surement lié au #937

**Comment by gillesboisson** [comment]
@margot-sanchez : en vérifiant l'implémentation, les campagnes on été séparé en 3 groupes :
- Campagne campagne en attente ou validé : Section : Vos campagnes en cours
- Campagne en brouillon : Section : Vos campagnes en brouillon
- Campagne archivé : Section : Vos campagnes terminées.

L'implémentation ne match pas avec les nom de sections.
Est ce qu'on aligne l'implémentation ou on renomme les sections ?
Je pense que l'implémentation est plus logique, pour campagne en cours / campagne terminée on peut ajouté un petit flag dans la liste

**Comment by gillesboisson** [comment]
en double avec la #937

**Comment by margot-sanchez** [comment]
@gillesboisson je ne suis pas d'accord avec ce qui a été fait. 
Dans en cours on retrouve deux campagnes 
![image](https://user-images.githubusercontent.com/15428433/92586507-9bbb9700-f296-11ea-8697-5b3acff149ad.png)

Alors que l'un d'entre elle est en brouillon 
![image](https://user-images.githubusercontent.com/15428433/92586542-a7a75900-f296-11ea-99a0-51a94c27b5df.png)


**En gros**

1) les campagnes en brouillon (donc non lancées) vont dans _brouillons_ (pas d'importance de la date)
2) les campagnes lancées vont dans _en cours_ si la date de fin n'est pas passée
3) les campagnes lancées vont dans _terminées_ si la date de fin est passée

Désolée si tu n'avais pas compris ma demande hier.

**Comment by margot-sanchez** [comment]
@gillesboisson  prend !
